<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Termeh Shafie and David Schoch">

<title>18&nbsp; Exponential Random Graph Models (ERGMs) – R for Social Network Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../inferential/saom.html" rel="next">
<link href="../inferential/rgm.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3f70bac5631458d474a321d4182f9338.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="18&nbsp; Exponential Random Graph Models (ERGMs) – R for Social Network Analysis">
<meta property="og:description" content="">
<meta property="og:image" content="https://schochastics.io/R4SNA/inferential/img/markov.png">
<meta property="og:site_name" content="R for Social Network Analysis">
<meta property="og:image:height" content="411">
<meta property="og:image:width" content="979">
<meta name="twitter:title" content="18&nbsp; Exponential Random Graph Models (ERGMs) – R for Social Network Analysis">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://schochastics.io/R4SNA/inferential/img/markov.png">
<meta name="twitter:image-height" content="411">
<meta name="twitter:image-width" content="979">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../inferential/introduction.html">Inferential Network Analysis</a></li><li class="breadcrumb-item"><a href="../inferential/ergm.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Exponential Random Graph Models (ERGMs)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">R for Social Network Analysis</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/schochastics/R4SNA" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Welcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../network-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Network Data and Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Descriptive Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/descriptives-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Basic Network Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/centrality-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Centrality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Cohesive Subgroups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/two-mode-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Two-Mode Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/signed-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Signed Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/ego-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Ego Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/netropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Entropy Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Network Visualization</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/ggraph-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Basics of ggraph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/ggraph-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Advanced Layouts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/enhance-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Enhancing Visualizations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/interactive-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Interactive Visualization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Inferential Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/non-parametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Non-Parametric Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/rgm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Random Graph Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/ergm.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Exponential Random Graph Models (ERGMs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/saom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Stochastic Actor Oriented Models (SAOMs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/rem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Relational Event Models (REMs)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Tidy Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/tidygraph-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Basics of tidygraph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/tidygraph-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Descriptive Network Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/ucnets-egor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Creating the UCNets Ego Network Dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/cat-ex-saoms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">A Continuous-Time Markov Chain (Cat Behavior Model)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/rem-frozen-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Creating Relational Event Data for the Frozen Character Network</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#packages-needed-for-this-chapter" id="toc-packages-needed-for-this-chapter" class="nav-link active" data-scroll-target="#packages-needed-for-this-chapter"><span class="header-section-number">18.1</span> Packages Needed for this Chapter</a></li>
  <li><a href="#ergm-modeling-outline" id="toc-ergm-modeling-outline" class="nav-link" data-scroll-target="#ergm-modeling-outline"><span class="header-section-number">18.2</span> ERGM Modeling Outline</a></li>
  <li><a href="#variants-and-extensions-of-ergms" id="toc-variants-and-extensions-of-ergms" class="nav-link" data-scroll-target="#variants-and-extensions-of-ergms"><span class="header-section-number">18.3</span> Variants and Extensions of ERGMs</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">References</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/schochastics/R4SNA/edit/main/inferential/ergm.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/schochastics/R4SNA/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../inferential/introduction.html">Inferential Network Analysis</a></li><li class="breadcrumb-item"><a href="../inferential/ergm.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Exponential Random Graph Models (ERGMs)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-ergm" class="quarto-section-identifier"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Exponential Random Graph Models (ERGMs)</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>So far, the models we’ve considered have treated tie formation as mostly random or locally constrained: ties are formed with fixed probabilities (<span class="math inline">\(G(n, p)\)</span>), rewired at random (small-world), or arranged to match node degrees (configuration model). However, real-world networks are shaped by richer and more structured processes. People do not form ties independently or at random; they are influenced. For example, two people who share a common friend may be more likely to form a tie themselves (triadic closure), or individuals may be more likely to reciprocate a connection that is initiated by someone else. These kinds of dependencies are central to many social theories, and they give rise to complex patterns of self-organization in networks.</p>
<p>To capture these processes, we need a more flexible modeling framework that allows for:</p>
<ul>
<li>Multiple network features to be modeled simultaneously</li>
<li>Direct specification of tie dependencies</li>
<li>Testing of competing social mechanisms</li>
</ul>
<p>This leads us to models that are built around network configurations, i.e., small, interpretable patterns of ties (such as mutual ties, stars, and triangles) that collectively describe the structure of the network. These configurations are often nested, meaning they build on one another hierarchically, and they can represent competing explanations for the observed structure. For instance, both reciprocity and popularity could explain why a node has many incoming ties, but these explanations imply different underlying processes.</p>
<p><strong>Exponential Random Graph Models (ERGMs)</strong> provide a flexible way to model these kinds of patterns. Instead of assuming each edge forms independently, ERGMs allow the probability of a tie to depend on what else is happening in the network. For example, the likelihood of a tie forming between two nodes may increase if they share mutual connections (triadic closure), or decrease if one node is already connected to many others (crowding out).</p>
<p>By explicitly modeling such configurations, we gain not only better empirical fit but also the ability to test theoretical hypotheses about the generative processes that shape real-world networks.</p>
<section id="packages-needed-for-this-chapter" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="packages-needed-for-this-chapter"><span class="header-section-number">18.1</span> Packages Needed for this Chapter</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(statnet)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(intergraph)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(graphlayouts)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(networkdata)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="ergm-modeling-outline" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="ergm-modeling-outline"><span class="header-section-number">18.2</span> ERGM Modeling Outline</h2>
<p>Exponential Random Graph Models (ERGMs) are a powerful family of statistical models for analyzing and simulating social networks. Unlike simpler random graph models, ERGMs are designed to capture the complex dependencies that often characterize real-world networks (such as reciprocity, transitivity, or clustering) by explicitly modeling how the presence of one tie can affect the likelihood of others.</p>
<p>The core idea is as follows. ERGMs specify a probability distribution over the set of all possible networks with a given number of nodes. The probability of observing a particular graph <span class="math inline">\(G\)</span> is defined as:</p>
<p><span class="math display">\[
P(G) = \frac{1}{\kappa} \exp\left( \sum_{k=1}^{K} \theta_k \cdot s_k(G) \right)
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(s_k(G)\)</span> is a network statistic that counts a specific configuration (e.g., number of edges, mutual ties, triangles).</li>
<li><span class="math inline">\(\theta_k\)</span> is the parameter associated with statistic <span class="math inline">\(s_k(G)\)</span>; it tells us how strongly that configuration influences tie formation.</li>
<li><span class="math inline">\(\kappa\)</span> is a normalizing constant ensuring that all possible graphs sum to a probability of 1: <span class="math display">\[
\kappa = \sum_{G'} \exp\left( \sum_{k=1}^{K} \theta_k \cdot s_k(G') \right)
\]</span></li>
</ul>
<p>This formulation makes clear that networks with more of the structures positively weighted by <span class="math inline">\(\theta_k\)</span> are more probable. For instance, a large positive <span class="math inline">\(\theta_{\text{mutual}}\)</span> implies that the observed network contains more reciprocated ties than expected by chance.</p>
<p>In general, we interpret the parameters as follows:</p>
<ul>
<li>A positive <span class="math inline">\(\theta_k\)</span> means that the corresponding configuration (e.g., triangles) is overrepresented in the observed network relative to what is expected by chance.</li>
<li>A negative <span class="math inline">\(\theta_k\)</span> indicates that the configuration is underrepresented relative to what is expected by chance.</li>
<li>A value of <span class="math inline">\(\theta_k = 0\)</span> implies that the configuration occurs at chance levels.</li>
</ul>
<p>The statistics <span class="math inline">\(s_k\)</span> are network configurations. As mentioned, ERGMs rely on small, interpretable network configurations to explain structure. These include:</p>
<ul>
<li><strong>Edges</strong>: baseline tendency for tie formation (controls overall density)</li>
<li><strong>Mutual</strong>: reciprocity in directed networks</li>
<li><strong>Triangles</strong>: clustering or transitivity (friends of friends)</li>
<li><strong>Stars</strong>: centralization or popularity (many ties to a node)</li>
<li><strong>Homophily</strong>: ties between nodes with similar attributes</li>
</ul>
<p>Each of these configurations reflects a hypothesized mechanism that may drive the evolution of network structure. We formalize some of the standard statistics in the following.</p>
<p>In the following section, we will move through four generations of dependence assumptions yielding different ERGM specifications with statistics (network configurations) that are included in the model.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Specifying an ERGM in R
</div>
</div>
<div class="callout-body-container callout-body">
<p>An ERGM is specified using a formula that defines the network structure and any covariates to be included. The <code>ergm()</code> function takes a <code>network</code> object on the left-hand side and a set of model terms on the right-hand side.</p>
<p>Here is an example model including edge density, a node-level covariate, homophily on an attribute, and a structural dependency term (<code>gwesp</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ergm</span>(network_object <span class="sc">~</span> model_terms)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>where <code>model_terms</code> represent structural configurations or covariate effects, e.g., edges, triangles, mutual, etc. For a full list of available statistics in the <code>ergm</code> package you can check.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>?ergmTerm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="model-specification" class="level3" data-number="18.2.1">
<h3 data-number="18.2.1" class="anchored" data-anchor-id="model-specification"><span class="header-section-number">18.2.1</span> Model Specification</h3>
<section id="dyadic-independence-edges-and-homophily" class="level4" data-number="18.2.1.1">
<h4 data-number="18.2.1.1" class="anchored" data-anchor-id="dyadic-independence-edges-and-homophily"><span class="header-section-number">18.2.1.1</span> Dyadic Independence: Edges and Homophily</h4>
<p>To begin working with exponential random graph models (ERGMs), we first need to understand how models are specified and what kinds of network structures they describe. In this section, we introduce the simplest possible ERGM, one that assumes Bernoulli dependence, and show how it connects to the familiar <span class="math inline">\(G(n, p)\)</span> model. This first step lays the foundation for more complex ERGMs that incorporate structural dependencies.</p>
<p>The Bernoulli ERGM assumes that all possible edges form independently of one another. In other words, the probability that a tie exists between nodes <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> is unrelated to whether other ties are present elsewhere in the network. This is a very strong assumption and one that is often unrealistic in practice, but it is useful as a baseline.</p>
<p>Let <span class="math inline">\(Y_{ij}\)</span> be a binary random variable indicating the presence (<span class="math inline">\(1\)</span>) or absence (<span class="math inline">\(0\)</span>) of a tie between nodes <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>. The full graph <span class="math inline">\(G\)</span> can then be represented by its adjacency matrix <span class="math inline">\(Y\)</span>, where <span class="math inline">\(Y_{ij}\)</span> encodes the tie between <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>.</p>
<p>In the general formulation of an exponential random graph model, one could imagine assigning a different parameter <span class="math inline">\(\theta_{ij}\)</span> to every possible tie <span class="math inline">\((i, j)\)</span> in the network. This would allow the model to express highly specific tendencies for each dyad. The probability of observing a network <span class="math inline">\(G\)</span> under this formulation would be:</p>
<p><span class="math display">\[
P(G) = \frac{1}{\kappa} \exp\left( \sum_{i&lt;j} \theta_{ij} y_{ij} \right)
\]</span></p>
<p>However, this model quickly becomes infeasible because it would require estimating a separate parameter for every possible edge, a number that grows quadratically with the number of nodes.</p>
<p>To make the model estimable and interpretable, ERGMs rely on the <strong>homogeneity assumption</strong>: the effect of a given configuration (such as an edge, triangle, or mutual tie) is the same wherever it appears in the network. That is, all instances of the same configuration share a single global parameter. For the Bernoulli ERGM, this means:</p>
<p><span class="math display">\[
\theta_{ij} = \theta \quad \text{for all } (i, j)
\]</span></p>
<p>Applying this assumption simplifies the model considerably:</p>
<p><span class="math display">\[
P(G) = \frac{1}{\kappa} \exp\left( \theta \sum_{i&lt;j} y_{ij} \right) = \frac{1}{\kappa} \exp(\theta \cdot L)
\]</span></p>
<p>Here, <span class="math inline">\(L\)</span> is the total number of edges in the network, <span class="math inline">\(\theta\)</span> is a single parameter that governs the overall probability of tie formation, and <span class="math inline">\(\kappa\)</span> is the normalizing constant ensuring all probabilities sum to 1.</p>
<p>This structure implies that each potential tie forms independently with the same probability, much like in a <span class="math inline">\(G(n, p)\)</span> random graph. Here, the parameter <span class="math inline">\(\theta\)</span> governs the log-odds of a tie between any two nodes. More formally, the relationship between <span class="math inline">\(\theta\)</span> and the tie probability <span class="math inline">\(p\)</span> (i.e., the density of the network) is:</p>
<p><span class="math display">\[
\theta = \log\left( \frac{p}{1 - p} \right) \quad \Leftrightarrow \quad p = \frac{e^\theta}{1 + e^\theta}
\]</span></p>
<p>This means that:</p>
<ul>
<li>When <span class="math inline">\(\theta = 0\)</span>, the expected density is <span class="math inline">\(p = 0.5\)</span></li>
<li>When <span class="math inline">\(\theta &lt; 0\)</span>, the expected density is less than 0.5 (a sparse network)</li>
<li>When <span class="math inline">\(\theta &gt; 0\)</span>, the expected density is greater than 0.5</li>
</ul>
<p>So, the edge parameter directly controls the overall density of the network. In practice, real-world social networks tend to be sparse, so <span class="math inline">\(\theta\)</span> is typically negative. This relationship also means that if you estimate a Bernoulli ERGM and obtain an edge coefficient <span class="math inline">\(\hat{\theta}\)</span>, you can compute the implied expected density using:</p>
<p><span class="math display">\[
\hat{p} = \frac{e^{\hat{\theta}}}{1 + e^{\hat{\theta}}}
\]</span></p>
<p>This makes the edge parameter easy to interpret: it is just the logit-transformed density.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note: <span class="math inline">\(G(n, p)\)</span> as a Special Case of ERGM
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Bernoulli ERGM is structurally identical to the <span class="math inline">\(G(n, p)\)</span> model, with the relationship:</p>
<ul>
<li><span class="math inline">\(\theta = 0\)</span> → expected density <span class="math inline">\(p = 0.5\)</span></li>
<li><span class="math inline">\(\theta &gt; 0\)</span> → expected density <span class="math inline">\(p &gt; 0.5\)</span></li>
<li><span class="math inline">\(\theta &lt; 0\)</span> → expected density <span class="math inline">\(p &lt; 0.5\)</span></li>
</ul>
<p>However, this does not hold in general (if the ERGM contains other statistics).</p>
<p>Put differently, the <span class="math inline">\(G(n, p)\)</span> random graph model is actually a special case of an ERGM. It includes only one term: the number of edges.</p>
</div>
</div>
<p>In ERGMs, a parameter estimate is considered statistically significant (by convention) if the absolute value of the estimate is greater than approximately twice its standard error (i.e., <span class="math inline">\(|\hat{\theta}| &gt; 2 \cdot \text{SE}\)</span>). This rule of thumb suggests that the corresponding network feature (such as homophily or reciprocity) is unlikely to have arisen by chance, and is therefore meaningfully associated with the observed pattern of tie formation.</p>
<section id="example-coleman-friendship" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="example-coleman-friendship">Example: Coleman Friendship</h5>
<p>To demonstrate the Bernoulli ERGM, we fit the model to the Coleman high school friendship network used in <a href="non-parametric.html" class="quarto-xref"><span>Chapter 16</span></a>. However, here we convert the graph object into an adjacency matrix since the <code>ergm</code> response argument needs to be a network object or a matrix that can be coerced to a network object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"coleman"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>coleman_g <span class="ot">&lt;-</span> coleman[[<span class="dv">1</span>]]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to adjacency matrix</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>coleman_mat <span class="ot">&lt;-</span> <span class="fu">as_adjacency_matrix</span>(coleman_g, <span class="at">sparse =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Bernoulli ERGM with only the edge term</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>model_bern <span class="ot">&lt;-</span> <span class="fu">ergm</span>(coleman_mat <span class="sc">~</span> edges)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_bern)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = coleman_mat ~ edges)

Maximum Likelihood Results:

      Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges -3.02673    0.06569      0  -46.08   &lt;1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 7286  on 5256  degrees of freedom
 Residual Deviance: 1969  on 5255  degrees of freedom
 
AIC: 1971  BIC: 1977  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>The output provides the estimated <span class="math inline">\(\theta\)</span> parameter for the edge term. A strongly negative value suggests that the probability of a tie between any two students is low, which is typical of real-world social networks that are sparse.</p>
<p>The estimated edge parameter from the Bernoulli ERGM is: <span class="math display">\[
\hat{\theta}_{\text{edges}} = -3.02673
\]</span></p>
<p>This value reflects the log-odds of a tie forming between any two nodes in the network. To convert this into an expected tie probability (i.e., network density), we apply the inverse logit function:</p>
<p><span class="math display">\[
p = \frac{e^{\hat{\theta}}}{1 + e^{\hat{\theta}}}
\]</span></p>
<p>Substituting the estimated value:</p>
<p><span class="math display">\[
p = \frac{e^{-3.02673}}{1 + e^{-3.02673}} \approx 0.046
\]</span></p>
<p>This result implies that the expected density of the network under this model is approximately 4.6%. This is in fact the density of the observed network which you can verify.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">edge_density</span>(coleman_g)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04623288</code></pre>
</div>
</div>
<p>Another class of network statistics in ERGMs captures <strong>homophily</strong>: the tendency of individuals to form ties with others who are similar to themselves in a particular attribute, such as gender, age, race, or occupation.</p>
<p>Let each node in the network have a categorical attribute, denoted:</p>
<p><span class="math display">\[
v_i \in \{1, \dots, C\}
\]</span></p>
<p>This assigns each actor <span class="math inline">\(i\)</span> to one of <span class="math inline">\(C\)</span> categories. To model homophily, we define a statistic that counts the number of ties between actors who share the same attribute value:</p>
<p><span class="math display">\[
m_v(G) = \sum_{i&lt;j} y_{ij} \cdot \mathbf{1}(v_i = v_j)
\]</span></p>
<p>That is, <span class="math inline">\(m_v(G)\)</span> is the number of edges where both endpoints belong to the same category. Adding this statistic to the ERGM, the model becomes:</p>
<p><span class="math display">\[
P(G) = \frac{1}{\kappa} \exp\left( \theta_1 \cdot L + \theta_2 \cdot m_v(G) \right)
\]</span></p>
<p>We interpret the homophily parameter as follows:</p>
<ul>
<li><span class="math inline">\(\theta_2 &gt; 0\)</span>: Ties between similar nodes are more likely (homophily)</li>
<li><span class="math inline">\(\theta_2 &lt; 0\)</span>: Ties between dissimilar nodes are more likely (heterophily)</li>
<li><span class="math inline">\(\theta_2 = 0\)</span>: No effect of similarity</li>
</ul>
<p>This formulation assumes that the tendency for similarity-based tie formation is uniform across all dyads, consistent with the homogeneity assumption discussed earlier. Moreover, since the statistic depends only on the attributes of the two actors in a dyad and not on any other ties in the network, it also maintains dyadic independence. That is, the presence or absence of one tie does not influence the probability of others, unless additional structural terms (like triangles or mutual ties) are included in the model.</p>
<p>Thus, including a homophily term allows us to model nodal covariate effects; how actor characteristics affect tie formation while keeping the model simple and tractable.</p>
</section>
<section id="example-teenage-friends-and-lifestyle-study-data" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="example-teenage-friends-and-lifestyle-study-data">Example: Teenage Friends and Lifestyle Study data</h5>
<p>For an example including the homophily statistic, we use the “Teenage Friends and Lifestyle Study” data called <code>s50</code> in the <code>networkdata</code> package. The <code>s50</code> dataset is a subset of 50 pupils over a three-year panel study of adolescent friendship networks and health behaviors conducted in a school in the West of Scotland <span class="citation" data-cites="west1996s50">(<a href="#ref-west1996s50" role="doc-biblioref">West and Sweeting 1996</a>)</span>. This excerpt was created for illustrative purposes and includes dynamic friendship data over three waves, capturing changes in social ties alongside attributes like gender, sport participation, and substance use. We will focus on the homophily based on smoking behavior.</p>
<p>We only consider cross-sectional network data here so we only focus on the third wave network (we will in later chapters look at modeling longitudinal network data). Let’s prepare the data for the <code>ergm</code> specification. Note that we here instead convert the graph object into a network one using the package <code>integraph</code> in order to preserve the node attribute of interest</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"s50"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the third wave network</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>s50_g <span class="ot">&lt;-</span> s50[[<span class="dv">3</span>]]</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to network object using intergraph</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>s50_net <span class="ot">&lt;-</span> <span class="fu">asNetwork</span>(s50_g)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># check network object and stored attributes</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>s50_net</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Network attributes:
  vertices = 50 
  directed = FALSE 
  hyper = FALSE 
  loops = FALSE 
  multiple = FALSE 
  bipartite = FALSE 
  total edges= 77 
    missing edges= 0 
    non-missing edges= 77 

 Vertex attribute names: 
    smoke vertex.names 

No edge attributes</code></pre>
</div>
</div>
<p>We now test whether students tend to form friendships with others who have the same smoking behavior. The <code>s50</code> dataset includes a categorical node attribute called <code>smoke</code>, with three levels: non-smoker (1), occasional smoker (2), and regular smoker (3). To test for smoking-based homophily, we fit an ERGM that includes an edge term and a <code>nodematch("smoke")</code> term.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit ERGM with homophily on smoking status</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>model_smoke <span class="ot">&lt;-</span> <span class="fu">ergm</span>(s50_net <span class="sc">~</span> edges <span class="sc">+</span> <span class="fu">nodematch</span>(<span class="st">"smoke"</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_smoke)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = s50_net ~ edges + nodematch("smoke"))

Maximum Likelihood Results:

                Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges            -3.0196     0.1902      0 -15.878   &lt;1e-04 ***
nodematch.smoke   0.5736     0.2425      0   2.365    0.018 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 1698.2  on 1225  degrees of freedom
 Residual Deviance:  569.4  on 1223  degrees of freedom
 
AIC: 573.4  BIC: 583.6  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>The model includes two terms:</p>
<ul>
<li><code>edges</code>: controls for the overall density of the network (should always be included)</li>
<li><code>nodematch("smoke")</code>: counts the number of ties where both nodes have the same smoking status.</li>
</ul>
<p>This specification assumes that the tendency to form ties is homogeneous across dyads, and the homophily term preserves dyadic independence, as it depends only on the attributes of the two individuals involved in each potential tie.</p>
<p>We interpret the output as follows. The <code>edges</code> term gives the baseline log-odds of a tie between two students, regardless of smoking behavior. The <code>nodematch("smoke")</code> term estimates the additional log-odds of a tie when two students share the same smoking status.</p>
<p>Since the coefficient for <code>nodematch("smoke")</code> is positive and significant, we see that students tend to form ties with peers who have similar smoking habits (homophily).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note on <code>nodematch()</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that <code>nodematch("smoke")</code> adds one statistic to the model: the total number of edges connecting nodes that share the same value of the smoke attribute. It does not distinguish between which category is shared, it treats all matches equally. So in our case, it would count:</p>
<ul>
<li>Ties between two non-smokers</li>
<li>Ties between two occasional smokers</li>
<li>Ties between two regular smokers</li>
</ul>
<p>All of those contribute to the same term. It does not tell you whether one group is more homophilous than another. If we want more detail, we can instead use <code>nodemix("smoke")</code> as it can separate estimates for each combination of categories (e.g., smoker-smoker, smoker-non-smoker, etc.), that is you get detailed between-group dynamics.</p>
</div>
</div>
</section>
</section>
<section id="dyadic-dependence-reciprocity" class="level4" data-number="18.2.1.2">
<h4 data-number="18.2.1.2" class="anchored" data-anchor-id="dyadic-dependence-reciprocity"><span class="header-section-number">18.2.1.2</span> Dyadic Dependence: Reciprocity</h4>
<p>In ERGMs, we can explicitly model <strong>dyadic dependence</strong>, that is, the statistical relationship between the presence or absence of ties within pairs of nodes (dyads). This is particularly important in directed networks, where the direction of a tie from node <span class="math inline">\(i\)</span> to node <span class="math inline">\(j\)</span> may be statistically related to the reverse tie from <span class="math inline">\(j\)</span> to <span class="math inline">\(i\)</span>.</p>
<p>To capture this, we include a <strong>reciprocity</strong> term in the model specification. This term counts the number of mutually connected dyads, i.e., pairs where both <span class="math inline">\(y_{ij} = 1\)</span> and <span class="math inline">\(y_{ji} = 1\)</span>. Including this term allows the model to account for the observed tendency in many social networks for actors to reciprocate ties (such as returning a favor, replying to a message, or forming a mutual friendship).</p>
<p>An ERGM with both an edge and a reciprocity statistic is specified as:</p>
<p><span class="math display">\[
P(G) = \frac{1}{\kappa} \exp\left(\theta_1 \cdot L + \theta_2 \cdot R\right)
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(L = \sum_{i \neq j} y_{ij}\)</span> is the total number of directed ties (edges),</li>
<li><span class="math inline">\(R = \sum_{i &lt; j} y_{ij} \cdot y_{ji}\)</span> is the number of reciprocated dyads.</li>
</ul>
<p>A positive value for <span class="math inline">\(\theta_2\)</span> indicates a tendency toward reciprocation, while a negative value suggests an avoidance of mutual ties.</p>
<section id="example-coleman-friendship-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="example-coleman-friendship-1">Example: Coleman Friendship</h5>
<p>We use the <code>coleman</code> data from earlier to specify an ERGM including reciprocity as statistic. The fitted ERGM includes two terms: a baseline <code>edges</code> term and a <code>mutual</code> term that captures reciprocity (i.e., the tendency for ties to be reciprocated).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit ERGM with reciprocity term</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>model_rec <span class="ot">&lt;-</span> <span class="fu">ergm</span>(coleman_mat <span class="sc">~</span> edges <span class="sc">+</span> mutual)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_rec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = coleman_mat ~ edges + mutual)

Monte Carlo Maximum Likelihood Results:

       Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges   -3.7148     0.0926      0  -40.12   &lt;1e-04 ***
mutual   3.7638     0.2127      0   17.70   &lt;1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 7286  on 5256  degrees of freedom
 Residual Deviance: 1713  on 5254  degrees of freedom
 
AIC: 1717  BIC: 1731  (Smaller is better. MC Std. Err. = 1.288)</code></pre>
</div>
</div>
<p>The edge term has a strong negative estimate (<span class="math inline">\(\hat{\theta}_{\text{edges}} = -3.72\)</span>, <span class="math inline">\(p &lt; 0.0001\)</span>), indicating that ties are generally infrequent in the network. This negative coefficient reflects the baseline log-odds of a directed tie existing between two nodes in the absence of any reciprocation or other structural tendencies.</p>
<p>In contrast, the mutual term has a strong positive estimate (<span class="math inline">\(\hat{\theta}_{\text{mutual}} = 3.77\)</span>, <span class="math inline">\(p &lt; 0.0001\)</span>), which suggests a highly significant tendency for reciprocated ties. In other words, when a tie exists from node <span class="math inline">\(i\)</span> to node <span class="math inline">\(j\)</span>, the likelihood that node <span class="math inline">\(j\)</span> also ties back to node <span class="math inline">\(i\)</span> is much greater than would be expected by chance, controlling for overall network sparsity.</p>
<p>This combination of results suggests that while directed ties are rare in general, when ties do form, they are very likely to be mutual; a common feature in social networks. Overall, this ERGM confirms that dyadic dependence in the form of reciprocity is a defining feature of the Coleman data network.</p>
</section>
</section>
<section id="markov-dependence-triangles-and-stars" class="level4" data-number="18.2.1.3">
<h4 data-number="18.2.1.3" class="anchored" data-anchor-id="markov-dependence-triangles-and-stars"><span class="header-section-number">18.2.1.3</span> Markov Dependence: Triangles and Stars</h4>
<p><strong>Markov random graphs</strong> are a foundational class of models in network statistics, based on the idea that the presence or absence of a tie between two nodes <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> depends only on ties that are “locally adjacent”, specifically, those that share a node. This assumption, known as <strong>Markov dependence</strong>, implies that edges are conditionally independent unless they share a common node. In other words, the presence or absence of a tie may influence other ties in the network, but only if those ties are adjacent. This locality of dependence makes the model tractable while capturing meaningful structural effects.</p>
<p>Formally introduced by <span class="citation" data-cites="frank1986markov">Frank and Strauss (<a href="#ref-frank1986markov" role="doc-biblioref">1986</a>)</span>, Markov random graphs were inspired by analogous models in spatial statistics, e.g., Besag’s auto-logistic models which similarly use local dependencies to define global probability distributions <span class="citation" data-cites="besag1972nearest">(<a href="#ref-besag1972nearest" role="doc-biblioref">Besag 1972</a>)</span>. The key insight is that network ties can exhibit local dependencies (like clustering or centralization) that can be modeled using well-defined building blocks.</p>
<p>Under Markov dependence, ERGMs are typically specified using <strong>edges, <span class="math inline">\(k\)</span>-stars, and triangles</strong>, since these configurations reflect dependencies between adjacent ties. Examples of such configurations are shown in <a href="#fig-markov" class="quarto-xref">Figure&nbsp;<span>18.1</span></a>.</p>
<div id="fig-markov" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-markov-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/markov.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-markov-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.1: Common network configurations used in Markov-dependent ERGMs. The top row shows star terms (edges, 2-star, 3-star, etc.) capturing degree centralization, while the triangle term reflects triadic closure.
</figcaption>
</figure>
</div>
<p>A <strong>triangle</strong> occurs when three nodes are all pairwise connected. In undirected networks, this represents a basic unit of <strong>triadic closure</strong>; the idea that “a friend of a friend is likely to become a friend.” In ERGM terms, a triangle statistic is defined as:</p>
<p><span class="math display">\[
T = \sum_{i &lt; j &lt; \ell} y_{ij} \cdot y_{i\ell} \cdot y_{j\ell}
\]</span></p>
<p>Including a triangle term in the model allows us to test for <strong>transitivity</strong>. A positive coefficient on this term suggests a tendency toward forming closed triads, while a <strong>negative</strong> coefficient implies avoidance of such closure.</p>
<p>In <strong>directed networks</strong>, we distinguish between:</p>
<ul>
<li><strong>Transitive triads</strong>: if <span class="math inline">\(i \to j\)</span> and <span class="math inline">\(j \to \ell\)</span>, then <span class="math inline">\(i \to \ell\)</span></li>
<li><strong>Cyclic triads</strong>: if <span class="math inline">\(i \to j\)</span>, <span class="math inline">\(j \to \ell\)</span>, and <span class="math inline">\(\ell \to i\)</span></li>
</ul>
<p>Each type can be specified as a separate statistic in an ERGM to assess different triadic dynamics.</p>
<p><strong>Star configurations</strong> capture the tendency for nodes to have many ties, i.e., to be “popular” or “active” in the network. A <span class="math inline">\(k\)</span>-star is a configuration where a single node is connected to <span class="math inline">\(k\)</span> others. The star statistic of order <span class="math inline">\(k\)</span> is:</p>
<p><span class="math display">\[
S_k = \sum_{i} \sum_{\substack{j_1 &lt; \dots &lt; j_k \\ j_m \neq i}}
y_{i j_1} \cdot \dots \cdot y_{i j_k}
\]</span></p>
<p>where all <span class="math inline">\(j_1,\dots,j_k\)</span> are distinct and different from <span class="math inline">\(i\)</span>. Including star terms allows the model to capture degree heterogeneity, reflecting whether some individuals tend to form many more ties than others. Note that in directed networks, we can specify:</p>
<ul>
<li><strong>Out-stars</strong> (activity): a node sending many ties</li>
<li><strong>In-stars</strong> (popularity): a node receiving many ties</li>
</ul>
<p>A positive parameter on star terms suggests that nodes with many connections are more likely to gain additional ties, a form of preferential attachment or “rich-get-richer” dynamics.</p>
<section id="example-florentine-business-network" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="example-florentine-business-network">Example: Florentine Business Network</h5>
<p>To illustrate the use of Markov-dependent configurations in ERGMs, we fit a model to the Florentine business network, the classic dataset representing marriage and business ties among Renaissance-era families in Florence. While rather small, this undirected network contains important social patterns such as clustering and centralization, making it an ideal candidate for modeling local dependence structures such as edges, stars, and triangles.</p>
<p>The goal of this example is to assess how these network structures contribute to the overall topology of the network using an ERGM based on Markov dependence.</p>
<p>First we visualize the using by loading the data from the <code>networkdata</code> package to obtain it as <code>igraph</code> object and to be able to use <code>ggraph</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"flo_business"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>flob_g <span class="ot">&lt;-</span> flo_business</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>flob_p <span class="ot">&lt;-</span> <span class="fu">ggraph</span>(flob_g, <span class="at">layout =</span> <span class="st">"stress"</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link0</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">edge_color =</span> <span class="st">"#666060"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">edge_width =</span> <span class="fl">0.8</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">edge_alpha =</span> <span class="dv">1</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>(</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"#808080"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"#808080"</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">7</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape =</span> <span class="dv">21</span>,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">stroke =</span> <span class="fl">0.9</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_graph</span>() <span class="sc">+</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Florentine business network"</span>)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>flob_p</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ergm_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="1440"></p>
</figure>
</div>
</div>
</div>
<p>We specify an ERGM including:</p>
<ul>
<li><code>edges</code>: to capture baseline tie propensity (density),</li>
<li><code>kstar(2)</code> and <code>kstar(3)</code>: to model degree centralization (nodes connected to 2 or 3 others),</li>
<li><code>triangle</code>: to capture triadic closure (transitivity).</li>
</ul>
<p>The data is loaded from the <code>ergm</code> package and stored as a <code>network</code> class object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Florentine business network data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(florentine)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The object is a network object representing business ties</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>flob_net <span class="ot">&lt;-</span> flobusiness</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(flob_net) <span class="co"># Confirms it's a 'network' class object</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "network"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit ERGM with Markov dependence terms</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1108</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>model_markov <span class="ot">&lt;-</span> <span class="fu">ergm</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  flob_net <span class="sc">~</span> edges <span class="sc">+</span> <span class="fu">kstar</span>(<span class="dv">2</span>) <span class="sc">+</span> <span class="fu">kstar</span>(<span class="dv">3</span>) <span class="sc">+</span> triangle</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display summary of the model</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_markov)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = flob_net ~ edges + kstar(2) + kstar(3) + triangle)

Monte Carlo Maximum Likelihood Results:

         Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges     -4.1930     1.1897      0  -3.524 0.000424 ***
kstar2     1.0377     0.6613      0   1.569 0.116566    
kstar3    -0.6378     0.4053      0  -1.574 0.115568    
triangle   1.3268     0.6348      0   2.090 0.036605 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 166.36  on 120  degrees of freedom
 Residual Deviance:  79.02  on 116  degrees of freedom
 
AIC: 87.02  BIC: 98.17  (Smaller is better. MC Std. Err. = 0.3806)</code></pre>
</div>
</div>
<p>The model output provides coefficients for each configuration:</p>
<ul>
<li><code>edges</code>: Significantly negative indicating that ties are relatively sparse overall.</li>
<li><code>kstar(2)</code>: Not statistically significant suggesting no strong tendency toward moderate centralization (i.e., nodes connected to two others).</li>
<li><code>kstar(3)</code>: Also not statistically significant meaning the network does not exhibit a clear preference for or against nodes forming many connections (larger stars).</li>
<li><code>triangle</code>: Significantly positive indicating a strong tendency for triadic closure; that is, if two families are both connected to a third, they are more likely to also be connected to each other.</li>
</ul>
<p>This suggests the Florentine business network is locally clustered (triadic), but does not support highly centralized hub-like nodes. The network’s structure reflects a preference for mutual interdependence rather than hierarchical dominance.</p>
<p>The good news is that by including triangle and star terms in an ERGM, we can move beyond modeling just dyadic interactions and begin to account for local clustering, degree distributions, and complex relational tendencies. The bad news is that they don’t always work.</p>
<p>While Markov random graph models offer a powerful way to represent local dependence through structures like edges, stars, and triangles, they come with a significant challenge: <strong>model degeneracy</strong>.</p>
<p>Model degeneracy occurs when an ERGM assigns overwhelming probability to a small set of unrealistic graph configurations, such as the empty graph (no ties) or the complete graph (every possible tie), even though the observed network lies somewhere in between. This typically manifests during estimation as:</p>
<ul>
<li>Extremely poor convergence of the MCMC algorithm,</li>
<li>Implausible simulated networks that look nothing like the observed data,</li>
<li>A breakdown in model fit across key structural statistics (e.g., triad census, degree distribution).</li>
</ul>
<p>For example, when fitting a model to the Florentine business network, a model with edges, stars, and triangles may produce simulated networks that deviate substantially from the observed triad census despite having reasonable parameter estimates. This discrepancy arises because certain parameter combinations (especially involving triangles and high-order stars) can push the model into degenerate territory, where the likelihood surface becomes unstable or flat. Thus, careful diagnostic checks are essential when modeling endogenous network structure implying dyadic dependence. We will cover this in more detail in <a href="#sec-ergmest" class="quarto-xref"><span>Section 18.2.2</span></a>.</p>
<p>The degeneracy problem highlights a key limitation of Markov dependence: <em>not all local dependence assumptions lead to coherent global models</em>. Particularly when clustering is strong, models relying solely on Markov terms (edges, stars, triangles) can become computationally fragile or even mathematically incoherent. In the next section, we will examine how social circuit dependence offers an alternative approach to modeling complex interdependence while mitigating model degeneracy.</p>
</section>
</section>
<section id="social-circuit-dependence-gwesp" class="level4" data-number="18.2.1.4">
<h4 data-number="18.2.1.4" class="anchored" data-anchor-id="social-circuit-dependence-gwesp"><span class="header-section-number">18.2.1.4</span> Social Circuit Dependence: GWESP</h4>
<p>In response to the degeneracy issues inherent in classic Markov ERGMs, researchers have proposed alternative specifications that build more stable dependence structures into the model. One promising approach is based on <strong>social circuit dependence</strong> <span class="citation" data-cites="pattison2002neighborhood">Snijders et al. (<a href="#ref-snijders2006new" role="doc-biblioref">2006</a>)</span>.</p>
<p>Social circuit dependence modifies the way tie dependencies are specified in the model. Instead of assuming that two ties are conditionally dependent simply because they share a node (as in Markov dependence), social circuit dependence restricts dependence to occur only when two ties would complete a <strong>4-cycle</strong> in the network. Under social circuit dependence, network ties are assumed to self-organize through 4-cycles, i.e., closed paths involving four distinct nodes. Two potential ties are considered conditionally dependent only if they would complete a 4-cycle in the network. In other words, the existence of a tie between <span class="math inline">\((i, j)\)</span> is only dependent on a tie between <span class="math inline">\((\ell, m)\)</span> if adding both would close such a circuit.</p>
<p>Examples of configurations based on this dependence assumption are shown in <a href="#fig-soccirc" class="quarto-xref">Figure&nbsp;<span>18.2</span></a>.</p>
<div id="fig-soccirc" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-soccirc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/sc.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-soccirc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.2: Common configurations in social circuit–based ERGM specifications. The top row illustrates <span class="math inline">\(k\)</span>-paths, which capture extended local connectivity through shared paths of increasing length. The bottom row depicts <span class="math inline">\(k\)</span>-triangles, representing increasing levels of triadic closure.
</figcaption>
</figure>
</div>
<p>This more constrained form of local dependence avoids the pitfalls of degeneracy by reducing the likelihood that the model overemphasizes clustering or centralization. It reflects more realistic assumptions about how social ties form: not purely through dyadic exchange or triadic closure, but through broader patterns of interconnection.</p>
<p>The <strong>Geometrically Weighted Edgewise Shared Partner (GWESP)</strong> statistic is a commonly used term in ERGMs to capture triadic closure, the tendency for connected nodes to have shared partners, as shown in <a href="#fig-gwesp" class="quarto-xref">Figure&nbsp;<span>18.3</span></a>. Unlike a simple triangle count, GWESP down-weights the contribution of additional shared partners to help prevent model degeneracy and improve stability.</p>
<div id="fig-gwesp" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gwesp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ergm_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gwesp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.3: Visualization of the GWESP (Geometrically Weighted Edgewise Shared Partner) statistic. The tie between nodes <em>i</em> and <em>j</em> is supported by <em>k</em> shared partners, each contributing diminishing weight to the likelihood of that tie being present.
</figcaption>
</figure>
</div>
<p>To formalize this, we let:</p>
<ul>
<li><span class="math inline">\(y_{ij} = 1\)</span> if there is a tie between nodes <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>,</li>
<li><span class="math inline">\(p_{ij}\)</span> be the number of shared partners between nodes <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>, i.e., <span class="math display">\[
p_{ij} = \sum_{\ell \neq i,j} y_{i\ell} \cdot y_{j\ell},
\]</span></li>
<li><span class="math inline">\(\alpha\)</span> be a decay parameter (usually a small positive number, e.g., 0.25).</li>
</ul>
<p>Then the GWESP statistic is defined as:</p>
<p><span class="math display">\[
\text{GWESP}(G; \alpha) = \sum_{i &lt; j} y_{ij} \cdot \left(1 - (1 - e^{-\alpha})^{p_{ij}} \right)
\]</span></p>
<ul>
<li>This formula sums over all existing ties in the graph.</li>
<li>For each tie <span class="math inline">\((i, j)\)</span>, it calculates a weighted function of the number of their shared partners.</li>
<li>The decay parameter <span class="math inline">\(\alpha\)</span> controls how quickly the contribution of additional shared partners diminishes.</li>
</ul>
<p>When <span class="math inline">\(\alpha\)</span> is close to zero, the statistic approaches a simple count of edges with at least one shared partner. When <span class="math inline">\(\alpha\)</span> is larger, the contribution of each additional shared partner is increasingly discounted.</p>
<p>GWESP provides a smooth and more stable way to model triadic closure in networks. It is often used in place of triangle counts to reduce the risk of model degeneracy; where the model produces unrealistic networks concentrated on extremes (e.g., empty or complete graphs).</p>
<p>In practice, GWESP is typically included in ERGMs with a fixed decay value using the <code>gwesp()</code> term in <code>ergm::ergm()</code>.</p>
<p>A commonly used value for <span class="math inline">\(\alpha\)</span> is <strong>0.693</strong>, which is approximately <span class="math inline">\(\log(2)\)</span>. This choice has a convenient and interpretable consequence: With <span class="math inline">\(\alpha = \log(2)\)</span>, each additional shared partner contributes about half as much as the one before. For example, the first shared partner contributes ~50% of the max possible increment, the second adds ~25%, the third adds ~12.5%, and so on. This exponential discounting reflects a realistic assumption: <em>having one or two mutual friends greatly increases the chance of tie formation, but the influence of additional mutual friends diminishes quickly</em>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note on choice of <span class="math inline">\(\alpha\)</span> in GWESP
</div>
</div>
<div class="callout-body-container callout-body">
<p>In some models, it may be beneficial to fix <span class="math inline">\(\alpha\)</span> to a value based on theory or prior experience (common in applied work), or estimate <span class="math inline">\(\alpha\)</span> directly from the data (<code>fixed = FALSE</code> in <code>gwesp()</code>), though this can lead to convergence issues or overfitting. In practice, using <code>gwesp(0.693, fixed = TRUE)</code> is often a safe and interpretable starting point.</p>
</div>
</div>
<p>Next we demonstrate how to fit an ERGM using GWESP and interpret the results.</p>
<section id="example-lawyers-network---cowork-among-partners" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="example-lawyers-network---cowork-among-partners">Example: Lawyers Network - Cowork Among Partners</h5>
<p>To demonstrate how ERGMs capture social circuit dependence, we will use the same subset of this network as earlier: we want to check whether or not the partners of the firm more frequently work together with other partners having the same practice, whilst also including a statistic related to triadic clustering. We import the data as an <code>igraph</code> object from the <code>networkdata</code> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"law_cowork"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We then create an adjacency matrix from the directed graph for the first 36 lawyers in the network corresponding to the partners of the firm (see attribute ‘status’). Note that we this time create the network object ourselves from the symmetrized adjacency matrix.</p>
<p>This example includes the following statistics:</p>
<ul>
<li><code>edges</code>: baseline tie probability,</li>
<li><code>nodecov("practice")</code>: effect of practice area on tie activity,</li>
<li><code>nodematch("practice")</code>: homophily within practice areas,</li>
<li><code>gwesp(0.693, fixed = TRUE)</code>: transitive closure (triadic clustering).</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note on <code>nodecov("...")</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>nodecov("...")</code> term in an ERGM includes a <strong>node-level covariate effect</strong>, where the probability of forming a tie is modeled as a function of the attribute value for each node. Specifically, for an undirected network, it sums the attribute values of both nodes involved in each dyad. A positive coefficient indicates that nodes with higher values on the given attribute are more active in forming ties (i.e., they tend to have higher degree). If you’re modeling a binary categorical attribute (e.g., practice = 0 or 1), then the statistic tests whether being in group 1 (e.g., corporate practice) increases a lawyer’s general tendency to form ties, regardless of whom they connect with.</p>
</div>
</div>
<p>These reflect both attribute-based processes and structural dependencies consistent with social circuit theory. A positive and significant <code>gwesp</code> coefficient would support the idea of social circuit dependence, where ties are not just formed dyadically or through attributes, but also through embedded collaboration patterns within the firm’s structure.</p>
<p>The code below creates the co-work network object for the 36 partners, adds the practice attribute as a binary variable and fits the ERGM with the above defined statistics.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"law_cowork"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># symmetrize the matrix to create and undirected graph</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>law_mat_cwdir <span class="ot">&lt;-</span> <span class="fu">as_adjacency_matrix</span>(law_cowork, <span class="at">sparse =</span> <span class="cn">FALSE</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>law_mat_cwdir <span class="ot">&lt;-</span> law_mat_cwdir[<span class="dv">1</span><span class="sc">:</span><span class="dv">36</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">36</span>] <span class="co"># only partners</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>law_mat_cw <span class="ot">&lt;-</span> (law_mat_cwdir <span class="sc">==</span> <span class="fu">t</span>(law_mat_cwdir) <span class="sc">&amp;</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  law_mat_cwdir <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="dv">0</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co"># save the binary attribute 'practice'</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># (1 = litigation, 2 = corporate) from the graph object as a vector</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>law_attr.pract <span class="ot">&lt;-</span> <span class="fu">vertex_attr</span>(law_cowork)<span class="sc">$</span>pract[<span class="dv">1</span><span class="sc">:</span><span class="dv">36</span>] <span class="sc">-</span> <span class="fl">1.</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="co"># We create a network object and add the binary node attribute 'practice':</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>law_net <span class="ot">&lt;-</span> <span class="fu">as.network</span>(law_mat_cw, <span class="at">directed =</span> <span class="cn">FALSE</span>)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>law_net <span class="sc">%v%</span> <span class="st">"practice"</span> <span class="ot">&lt;-</span> law_attr.pract</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit ERGM with attribute and structural terms</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1108</span>)</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>model_sc <span class="ot">&lt;-</span> <span class="fu">ergm</span>(</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  law_net <span class="sc">~</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>    edges <span class="sc">+</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">nodecov</span>(<span class="st">"practice"</span>) <span class="sc">+</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">nodematch</span>(<span class="st">"practice"</span>) <span class="sc">+</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">gwesp</span>(<span class="fl">0.693</span>, <span class="at">fixed =</span> <span class="cn">TRUE</span>)</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_sc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = law_net ~ edges + nodecov("practice") + nodematch("practice") + 
    gwesp(0.693, fixed = TRUE))

Monte Carlo Maximum Likelihood Results:

                   Estimate Std. Error MCMC % z value Pr(&gt;|z|)
edges              -4.41134    0.32289      0 -13.662  &lt; 1e-04
nodecov.practice    0.17810    0.07371      0   2.416 0.015678
nodematch.practice  0.60167    0.16668      0   3.610 0.000306
gwesp.fixed.0.693   1.15319    0.15878      0   7.263  &lt; 1e-04
                      
edges              ***
nodecov.practice   *  
nodematch.practice ***
gwesp.fixed.0.693  ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 873.4  on 630  degrees of freedom
 Residual Deviance: 503.8  on 626  degrees of freedom
 
AIC: 511.8  BIC: 529.6  (Smaller is better. MC Std. Err. = 0.4295)</code></pre>
</div>
</div>
<p>Let’s interpret the output: The fitted model includes four terms: <code>edges</code>, <code>nodecov("practice")</code>, <code>nodematch("practice")</code>, and <code>gwesp(0.693, fixed = TRUE)</code>. Each coefficient represents the log-odds change in the probability of a tie associated with that network statistic, controlling for the others. What do these estimates tell us?</p>
<ul>
<li><code>edges</code> (<span class="math inline">\(\hat\theta = -4.41\)</span>, <em>p</em> &lt; 0.001): Ties are rare overall; the network is sparse.</li>
<li><code>nodecov("practice")</code> (<span class="math inline">\(\hat\theta = 0.18\)</span>, <em>p</em> &lt; 0.05): Lawyers from a given practice area (e.g., corporate) are slightly more likely to form ties overall.</li>
<li><code>nodematch("practice")</code> (<span class="math inline">\(\hat\theta = 0.61\)</span>, <em>p</em> &lt; 0.001): Strong evidence of homophily, lawyers are significantly more likely to collaborate within their own practice area.</li>
<li><code>gwesp(0.693)</code> (<span class="math inline">\(\hat\theta = 1.15\)</span>, <em>p</em> &lt; 0.001): High and significant triadic closure effect, indicating a strong tendency for collaboration among those with shared partners consistent with social circuit dependence.</li>
</ul>
<p>Taken together, the results indicate that processes of attribute-related activity, assortative mixing by attribute (homophily), and structural closure (via triadic dependence) operate concurrently in shaping tie formation within the Lazega co-working network.</p>
</section>
</section>
</section>
<section id="sec-ergmest" class="level3" data-number="18.2.2">
<h3 data-number="18.2.2" class="anchored" data-anchor-id="sec-ergmest"><span class="header-section-number">18.2.2</span> Model Estimation</h3>
<p>Estimating the parameters of an Exponential Random Graph Model (ERGM) involves finding the parameter vector <span class="math inline">\(\boldsymbol{\theta}\)</span> that maximizes the likelihood of observing the network <span class="math inline">\(G_{\text{obs}}\)</span>:</p>
<p><span class="math display">\[
\hat{\boldsymbol{\theta}} = \arg\max_{\boldsymbol{\theta}} P(G_{\text{obs}}\mid\boldsymbol{\theta}).
\]</span></p>
<p>Under the ERGM specification, this likelihood is</p>
<p><span class="math display">\[
P(G_{\text{obs}}\mid\boldsymbol{\theta})=
\frac{\exp\left(\boldsymbol{\theta}^{\top}\mathbf{s}(G_{\text{obs}})\right)}
{\kappa(\boldsymbol{\theta})},
\]</span></p>
<p>where <span class="math inline">\(\mathbf{s}(G)\)</span> is a vector of network statistics (e.g., the number of edges, mutual ties, or triangles), and</p>
<p><span class="math display">\[
\kappa(\boldsymbol{\theta})
=
\sum_{G'}
\exp\left(\boldsymbol{\theta}^{\top}\mathbf{s}(G')\right)
\]</span></p>
<p>is a normalizing constant computed over all possible networks with the same set of nodes. Because the number of possible networks grows exponentially with the number of nodes, evaluating this sum exactly is computationally infeasible except for very small networks.</p>
<p>For <strong>dyad-independent</strong> ERGMs (e.g., models containing only nodal covariates such as homophily), estimation is relatively straightforward and does not require full MCMC-based maximum likelihood estimation. In fact, a dyad-independent ERGM is mathematically equivalent to a logistic regression model fit to all possible dyads in the network. Accordingly, the <code>ergm</code> package estimates these models using <strong>maximum pseudo-likelihood estimation (MPLE)</strong>, which is essentially logistic regression under the hood.</p>
<p>Once dyad-dependent structural terms (e.g., triangles, shared partners, or stars) are introduced, however, this simple estimation strategy is no longer valid. Instead, the model must be estimated using <strong>Markov Chain Monte Carlo Maximum Likelihood Estimation (MCMCMLE)</strong>. Because the normalizing constant cannot be computed exactly, the algorithm repeatedly simulates networks from the current model and compares their network statistics with those of the observed network. The parameter estimates are then updated until the simulated and observed network statistics closely agree.</p>
<p>The estimation process implemented in the <code>ergm</code> package proceeds as follows:</p>
<ol type="1">
<li><p><strong>Initial Parameter Values:</strong><br>
Estimation begins from initial parameter values, typically obtained using MPLE. Although MPLE is generally not sufficiently accurate for final inference, it provides a good starting point for the MCMC algorithm.</p></li>
<li><p><strong>MCMC Simulation:</strong><br>
Using the current parameter estimates, the algorithm simulates a <strong>Markov chain</strong> of networks. The chain begins with an initial network (typically the observed network or a simple starting network). At each MCMC iteration, a small change is proposed by selecting a dyad and proposing to either add or remove the edge between those two nodes. The resulting change statistics are computed, and the proposed network is accepted or rejected according to a <strong>Metropolis–Hastings</strong> acceptance probability determined by the current parameter values. This process is repeated thousands of times, producing a sequence of highly related networks. After discarding an initial burn-in period, the remaining networks are treated as samples from the ERGM implied by the current parameter vector.</p></li>
<li><p><strong>Likelihood Approximation and Parameter Updating:</strong><br>
The sampled networks are used to estimate the expected values of the network statistics under the current model. These expected statistics are compared with the statistics of the observed network. At the maximum likelihood estimate, the expected network statistics under the model should equal the observed network statistics: <span class="math display">\[
E_{\hat{\boldsymbol{\theta}}}[\mathbf{s}(G)] = \mathbf{s}(G_{\text{obs}}).
\]</span> If systematic differences remain, for example if the simulated networks consistently contain fewer triangles or more edges than the observed network, the parameter vector <span class="math inline">\(\boldsymbol{\theta}\)</span> is updated to reduce those differences.</p></li>
<li><p><strong>Iteration:</strong><br>
Once the parameters have been updated, an entirely new MCMC simulation is run using the revised parameter values. The process of simulating a Markov chain of networks, comparing simulated and observed statistics, and updating the parameters is repeated until the parameter estimates stabilize and the simulated network statistics closely match those of the observed network.</p></li>
</ol>
<p>Thus, there are two nested iterative processes. Within each MCMC run, the network changes one edge at a time as the Markov chain explores the space of possible networks. Across MCMCMLE iterations, the parameter estimates themselves are updated so that the distribution of simulated networks increasingly resembles the observed network.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note on <strong>Metropolis–Hastings</strong> sampling
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>ergm</code> package uses the <strong>Metropolis–Hastings (MH)</strong> algorithm to generate a Markov chain of networks for a given set of parameter values. Rather than generating completely new networks at each step, the algorithm constructs a sequence of networks in which each network differs only slightly from the previous one. This allows the chain to gradually explore the space of possible network configurations while preserving the probability distribution implied by the current ERGM.</p>
<p>At each iteration, the algorithm performs the following steps:</p>
<ol type="1">
<li><strong>Select a dyad</strong> (a pair of nodes) at random.</li>
<li><strong>Propose a network change</strong> by toggling the edge between those nodes (i.e., adding the edge if it is absent or removing it if it is present).</li>
<li><strong>Compute the change statistics</strong>, that is, determine how the network statistics (e.g., the number of edges, triangles, or shared partners) would change if the proposed edge toggle were accepted. These changes (known as change statistics) summarize the effect of the proposed edge toggle on the sufficient statistics used by the ERGM.</li>
<li><strong>Calculate an acceptance probability</strong> based on how the proposed change affects the probability of the network under the current ERGM.</li>
<li><strong>Accept or reject the proposal</strong> according to this probability. If accepted, the proposed network becomes the next state of the Markov chain; otherwise, the current network is retained.</li>
</ol>
<p>Repeating this procedure thousands of times produces a sequence of networks that, after an initial burn-in period, approximates the ERGM specified by the current parameter values. These sampled networks are then used to estimate the expected network statistics, which in turn are used to update the model parameters during maximum likelihood estimation.</p>
</div>
</div>
<section id="model-diagnostics" class="level4" data-number="18.2.2.1">
<h4 data-number="18.2.2.1" class="anchored" data-anchor-id="model-diagnostics"><span class="header-section-number">18.2.2.1</span> Model Diagnostics</h4>
<p>Because ERGMs rely on MCMC simulation to estimate model parameters, it is essential to verify that the Markov chain has properly <strong>converged</strong> and is <strong>mixing well</strong>. MCMC diagnostics assess whether the chain has explored the space of possible networks sufficiently, whether successive samples have become sufficiently independent, and whether the sampled networks represent the target ERGM distribution. Poor convergence or poor mixing can lead to unreliable parameter estimates and misleading statistical inferences.</p>
<p>Common MCMC diagnostics include:</p>
<ul>
<li><strong>Trace plots</strong>, which assess whether the sampled network statistics fluctuate randomly around a stable value over the course of the simulation.</li>
<li><strong>Autocorrelation plots</strong>, which evaluate the dependence between samples at different lags; rapidly decreasing autocorrelation indicates efficient mixing.</li>
<li><strong>Geweke convergence diagnostics</strong>, which compare the early and late portions of the Markov chain to determine whether it has reached a stationary distribution.</li>
<li><strong>Comparisons between observed and simulated network statistics</strong>, which assess whether the fitted model successfully reproduces the structural features of the observed network.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Running MCMC Diagnostics
</div>
</div>
<div class="callout-body-container callout-body">
<p>After fitting an ERGM, use <code>mcmc.diagnostics()</code> to evaluate whether the MCMC estimation has converged and whether the Markov chain has mixed well. This function provides trace plots, density plots, and numerical summaries for the estimating functions associated with each model term.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MCMC convergence check</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mcmc.diagnostics</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>We now examine the MCMC diagnostics for <code>model_sc</code>, fitted to the lawyers’ co-working network.</p>
<section id="example-lawyers-network---cowork-among-partners-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="example-lawyers-network---cowork-among-partners-1">Example: Lawyers Network - Cowork Among Partners</h5>
<p>The <code>mcmc.diagnostics()</code> function in the <code>ergm</code> package produces trace plots and density plots for each model term, allowing us to evaluate the stability and mixing of the MCMC chain. The diagnostics consist of two parts. The first part is a plot (see <a href="#fig-mcmc" class="quarto-xref">Figure&nbsp;<span>18.4</span></a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcmc.diagnostics</span>(model_sc, <span class="at">which =</span> <span class="st">"plots"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Note: MCMC diagnostics shown here are from the last round
  of simulation, prior to computation of final parameter
  estimates. Because the final estimates are refinements
  of those used for this simulation run, these
  diagnostics may understate model performance. To
  directly assess the performance of the final model on
  in-model statistics, please use the GOF command:
  gof(ergmFitObject, GOF=~model).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-mcmc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mcmc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ergm_files/figure-html/fig-mcmc-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mcmc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.4: MCMC trace (left) and density (right) plots for the fitted ERGM. The differences between simulated and observed network statistics fluctuate around zero, indicating good convergence and mixing of the Markov chain.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The MCMC diagnostic output includes two main types of plots as seen in <a href="#fig-mcmc" class="quarto-xref">Figure&nbsp;<span>18.4</span></a>: <strong>trace plots</strong> and <strong>density plots</strong>, which together help assess whether the Markov chain has properly converged.</p>
<p>The <strong>trace plots</strong> (left panels of <a href="#fig-mcmc" class="quarto-xref">Figure&nbsp;<span>18.4</span></a>) display the differences between the network statistics of the simulated networks and those of the observed network for each model term across the MCMC simulation. In a well-behaved chain, these traces should exhibit irregular but stable fluctuations around zero, without systematic trends, drifts, or prolonged flat segments. Such patterns indicate that the Markov chain has converged and is mixing well, meaning it is effectively exploring the distribution of networks implied by the fitted ERGM rather than becoming trapped in a limited region of the network space.</p>
<p>Because the maximum likelihood estimate for an ERGM is obtained when the expected network statistics under the model equal the observed network statistics, the differences plotted in the trace plots should fluctuate around zero. Persistent deviations from zero, clear trends, or long periods where the chain becomes stuck suggest poor convergence, inadequate mixing, or potential problems with model specification.</p>
<p>In the Lazega model, all four trace plots (for <code>edges</code>, <code>nodecov.practice</code>, <code>nodematch.practice</code>, and <code>gwesp.fixed.0.693</code>) exhibit the expected noisy, stable behavior. There are no signs of poor mixing or convergence issues.</p>
<p>The <strong>density plots</strong> (right panels of <a href="#fig-mcmc" class="quarto-xref">Figure&nbsp;<span>18.4</span></a>) complement the trace plots by summarizing the distribution of the differences between the simulated and observed network statistics for each model term. Approximately symmetric, unimodal density curves centered near zero indicate that the simulated network statistics closely match those of the observed network and that the Markov chain has reached its stationary distribution. In <a href="#fig-mcmc" class="quarto-xref">Figure&nbsp;<span>18.4</span></a>, all four model terms exhibit smooth, bell-shaped densities with means close to zero, providing further evidence of good convergence, adequate mixing, and reliable MCMC-based parameter estimation.</p>
<p>Together, these visual diagnostics indicate that the model has converged appropriately and that the MCMC estimation procedure has produced a stable and interpretable result.</p>
<p>In addition to the trace and density plots, the <code>mcmc.diagnostics()</code> function provides a set of detailed numerical diagnostics that assess both the stability of the simulated statistics and the convergence behavior of the Markov chain. These diagnostics offer a more granular view of the estimation process and help confirm whether the model has been reliably estimated. We’ll interpret the output in the following.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcmc.diagnostics</span>(model_sc, <span class="at">which =</span> <span class="st">"texts"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample statistics summary:

Iterations = 93184:1841152
Thinning interval = 1024 
Number of chains = 1 
Sample size per chain = 1708 

1. Empirical mean and standard deviation for each variable,
   plus standard error of the mean:

                     Mean    SD Naive SE Time-series SE
edges               7.091 27.10   0.6557          1.998
nodecov.practice    5.302 24.89   0.6023          1.633
nodematch.practice  4.230 16.56   0.4008          1.163
gwesp.fixed.0.693  13.519 54.18   1.3109          4.007

2. Quantiles for each variable:

                     2.5%    25%   50%   75% 97.5%
edges              -48.00 -10.00 10.00 26.00  56.0
nodecov.practice   -50.32  -9.00  8.00 22.25  48.0
nodematch.practice -30.00  -7.00  5.00 16.00  35.0
gwesp.fixed.0.693  -96.12 -23.13 16.52 50.73 114.7


Are sample statistics significantly different from observed?
                  edges nodecov.practice nodematch.practice
diff.      7.0907494145       5.30210773        4.230093677
test stat. 3.5487184676       3.24757744        3.636136218
P-val.     0.0003871107       0.00116392        0.000276758
           gwesp.fixed.0.693       (Omni)
diff.           1.351858e+01           NA
test stat.      3.373832e+00 1.903298e+01
P-val.          7.412971e-04 9.111204e-04

Sample statistics cross-correlations:
                       edges nodecov.practice nodematch.practice
edges              1.0000000        0.8264120          0.9319707
nodecov.practice   0.8264120        1.0000000          0.7678457
nodematch.practice 0.9319707        0.7678457          1.0000000
gwesp.fixed.0.693  0.9927742        0.8370170          0.9251511
                   gwesp.fixed.0.693
edges                      0.9927742
nodecov.practice           0.8370170
nodematch.practice         0.9251511
gwesp.fixed.0.693          1.0000000

Sample statistics auto-correlation:
Chain 1 
             edges nodecov.practice nodematch.practice
Lag 0    1.0000000        1.0000000          1.0000000
Lag 1024 0.7812515        0.6669325          0.7428406
Lag 2048 0.6356838        0.4833907          0.6001471
Lag 3072 0.5280292        0.3686701          0.4907969
Lag 4096 0.4260868        0.2842123          0.3962557
Lag 5120 0.3552503        0.2527400          0.3190893
         gwesp.fixed.0.693
Lag 0            1.0000000
Lag 1024         0.7462760
Lag 2048         0.6047712
Lag 3072         0.5022241
Lag 4096         0.4027607
Lag 5120         0.3393722

Sample statistics burn-in diagnostic (Geweke):
Chain 1 

Fraction in 1st window = 0.1
Fraction in 2nd window = 0.5 

             edges   nodecov.practice nodematch.practice 
       -0.13897313         0.98934189         0.04600824 
 gwesp.fixed.0.693 
       -0.01253819 

Individual P-values (lower = worse):
             edges   nodecov.practice nodematch.practice 
         0.8894714          0.3224959          0.9633037 
 gwesp.fixed.0.693 
         0.9899962 
Joint P-value (lower = worse):  0.00691819 

Note: MCMC diagnostics shown here are from the last round
  of simulation, prior to computation of final parameter
  estimates. Because the final estimates are refinements
  of those used for this simulation run, these
  diagnostics may understate model performance. To
  directly assess the performance of the final model on
  in-model statistics, please use the GOF command:
  gof(ergmFitObject, GOF=~model).</code></pre>
</div>
</div>
<p>One key output compares the mean of the simulated statistics to the corresponding observed values. For most terms, including <code>nodecov.practice</code>, <code>nodematch.practice</code>, and the <code>gwesp</code> statistic, there is no significant difference between simulated and observed statistics, indicating a good model fit. The only exception is the <code>edges</code> term, which shows a small but statistically significant deviation (<span class="math inline">\(p\)</span> = 0.0389). This suggests a slight misfit on overall tie density, though the magnitude of the difference is modest and not cause for concern.</p>
<p>The <strong>cross-correlations</strong> summarize the relationships among the differences between the simulated and observed network statistics for the model terms across the MCMC samples. Moderate correlations are expected because several statistics capture related structural features of the network. For example, ties that contribute to homophily (<code>nodematch.practice</code>) also contribute to the overall edge count, resulting in a positive correlation between these terms. Similarly, structural effects such as triangles and shared partners are inherently related. The observed correlations are moderate and well below levels that would suggest excessive collinearity or poor mixing. Consequently, they do not indicate problems with model identifiability, instability, or degeneracy.</p>
<p>Looking at the <strong>autocorrelation diagnostics</strong>, we see that the autocorrelation for each model term decreases steadily as the lag increases. Autocorrelation measures how similar a sampled network statistic is to its value several iterations earlier in the Markov chain. A <strong>lag</strong> refers to the number of MCMC iterations separating two samples; for example, a lag of 10 compares a sampled statistic with the value obtained 10 iterations later. High autocorrelation means that successive samples are very similar and therefore provide little new information. In contrast, autocorrelation that declines rapidly toward zero as the lag increases indicates that the chain is moving efficiently through the space of possible networks and that samples become increasingly independent of one another. The observed pattern therefore suggests that the MCMC sampler is mixing well, producing an efficient sample of networks from the target ERGM distribution.</p>
<p>Finally, the <strong>Geweke convergence diagnostic</strong> compares the mean of the sampled statistics from the early portion of the post-burn-in chain with the mean from a later portion of the chain. The null hypothesis is that these two portions of the chain have the same mean, implying that the Markov chain has converged to its stationary distribution. If this null hypothesis is not rejected, there is no evidence that the chain is still drifting over time. Consequently, large <span class="math inline">\(p\)</span>-values indicate that the early and late portions of the chain are statistically indistinguishable and are consistent with convergence. In this example, all model terms yield comfortably non-significant <span class="math inline">\(p\)</span>-values (ranging from 0.15 to 0.27), suggesting that the chain has converged and reached stationarity. The joint <span class="math inline">\(p\)</span>-value of 0.64 provides additional evidence that the MCMC sampler has stabilized and is producing reliable samples from the target ERGM distribution.</p>
<p>In this example, the diagnostics indicate that the estimation has been successful. In practice, however, MCMC diagnostics do not always look this favorable. Poor convergence or poor mixing may instead reflect model instability, often referred to as <strong>ERGM degeneracy</strong>.</p>
</section>
</section>
<section id="model-instability-and-degeneracy" class="level4" data-number="18.2.2.2">
<h4 data-number="18.2.2.2" class="anchored" data-anchor-id="model-instability-and-degeneracy"><span class="header-section-number">18.2.2.2</span> Model Instability and Degeneracy</h4>
<p>Although MCMC makes it possible to estimate rich dyad-dependent ERGMs, these models can become unstable if they are poorly specified. In such cases, the fitted ERGM may assign nearly all of its probability to a small number of unrealistic networks, typically networks that are almost entirely empty or almost completely connected.</p>
<p>This phenomenon is known as <strong>model degeneracy</strong>. A degenerate ERGM assigns near-zero probability to most networks in the model space, and high probability only to extreme graphs, such as the completely empty or fully connected one. Since real social networks rarely resemble either of these extremes, such a distribution indicates a serious modeling failure.</p>
<p>Signs of degeneracy include:</p>
<ul>
<li>Simulated networks that are always empty or complete, regardless of the observed data.</li>
<li>Poor convergence of MCMC chains, or failure to reach a stable equilibrium (stationary distribution).</li>
<li>Large gaps between observed and simulated statistics, especially for higher-order configurations like triangles.</li>
</ul>
<p>Poor diagnostics may arise for two different reasons. First, the MCMC algorithm may need more tuning, such as a longer burn-in period, a larger post-burn-in sample, or a larger MCMC interval. Second, the model itself may be poorly specified. In the latter case, simply running the chain longer will not solve the problem; the model must be revised.</p>
<p>For a detailed technical treatment of model instability in ERGMs, see <span class="citation" data-cites="schweinberger2011instability">Schweinberger (<a href="#ref-schweinberger2011instability" role="doc-biblioref">2011</a>)</span>. Alternative specification strategies that improve stability are discussed in <span class="citation" data-cites="snijders2006new">Snijders et al. (<a href="#ref-snijders2006new" role="doc-biblioref">2006</a>)</span>, while the formulation and rationale behind the <code>gwesp</code> term, and curved exponential family models more broadly, are addressed in <span class="citation" data-cites="hunter2006inference">Hunter and Handcock (<a href="#ref-hunter2006inference" role="doc-biblioref">2006</a>)</span>.</p>
<p>When poor convergence, high autocorrelation, or other signs of instability are detected, there are several possible remedies. Sometimes the MCMC algorithm simply requires additional tuning, whereas in other cases the model itself must be simplified or respecified. Common strategies include:</p>
<ul>
<li>Increasing <code>MCMC.burnin</code> to allow the Markov chain more time to reach its stationary distribution before samples are retained for estimation.</li>
<li>Increasing <code>MCMC.samplesize</code> to obtain more post-burn-in samples, thereby reducing Monte Carlo error and improving the precision of the parameter estimates.</li>
<li>Increasing <code>MCMC.interval</code> when autocorrelation is high so that recorded samples are farther apart in the chain and therefore less dependent on one another.</li>
<li>Replacing raw triangle or star terms with smoother alternatives, such as <code>gwesp()</code> or <code>gwdsp()</code>, which typically produce more stable models while still capturing clustering and shared-partner effects.</li>
<li>Simplifying the model by removing unnecessary or highly collinear terms if diagnostics indicate poor convergence or degeneracy. A simpler model is often easier to estimate and may provide a better representation of the underlying network-generating process.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note on MCMC control parameters
</div>
</div>
<div class="callout-body-container callout-body">
<p>Control parameters for the MCMC algorithm can be found here <code>help(control.ergm)</code></p>
</div>
</div>
</section>
</section>
<section id="model-fit" class="level3" data-number="18.2.3">
<h3 data-number="18.2.3" class="anchored" data-anchor-id="model-fit"><span class="header-section-number">18.2.3</span> Model Fit</h3>
<p>After confirming that the MCMC estimation has converged, the next step is to assess how well the fitted ERGM reproduces the observed network. MCMC diagnostics evaluate the estimation procedure, whereas <strong>goodness-of-fit (GOF) diagnostics</strong> evaluate the model itself. A model can converge successfully but still fail to capture important structural features of the network.</p>
<p>ERGM model checking therefore involves two complementary questions:</p>
<ol type="1">
<li><p><strong>Did the model reproduce the statistics included in the formula?</strong><br>
This is a property of maximum likelihood estimation: once the algorithm has converged, the expected values of the modeled statistics should match their observed values.</p></li>
<li><p><strong>Does the model reproduce broader structural properties of the network?</strong><br>
This is the more important and revealing test. GOF checks compare simulated networks to the observed one on key network features not explicitly included in the model. These typically include:</p>
<ul>
<li><strong>Degree distribution</strong> (node-level centrality)</li>
<li><strong>Edgewise shared partners (ESP)</strong> (local clustering)</li>
<li><strong>Geodesic distances</strong> (overall reachability)</li>
</ul>
<p>Agreement between the observed and simulated distributions suggests that the model captures structural features beyond those explicitly included in the ERGM formula.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Running Goodness-of-Fit Checks in ERGM
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>ergm</code> package provides the <code>gof()</code> function, which performs a <strong>simulation-based goodness-of-fit assessment</strong>. This function compares the observed network to a distribution of networks simulated from the fitted model, focusing on structural features not directly modeled.</p>
<p>A typical workflow is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run GOF assessment</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>gof_model <span class="ot">&lt;-</span> <span class="fu">gof</span>(model)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View numeric summary</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gof_model)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot GOF results</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gof_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="example-lawyers-network---cowork-among-partners-2" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="example-lawyers-network---cowork-among-partners-2">Example: Lawyers Network - Cowork Among Partners</h5>
<p>We now assess the goodness of fit of the ERGM fitted to Lazega’s co-working network. The model includes the following terms:</p>
<ul>
<li><code>edges</code>: baseline tie probability,</li>
<li><code>nodecov("practice")</code>: effect of practice area on tie activity,</li>
<li><code>nodematch("practice")</code>: homophily within practice areas,</li>
<li><code>gwesp(0.693, fixed = TRUE)</code>: transitive closure (triadic clustering).</li>
</ul>
<p>The goal is to determine whether the fitted model reproduces both the modeled statistics and broader structural features of the observed network.</p>
<div id="fig-gof" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gof-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>gof_sc <span class="ot">&lt;-</span> <span class="fu">gof</span>(model_sc, <span class="at">plotlogodds =</span> <span class="cn">TRUE</span>) <span class="co"># this will produce 4 plots</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># figure orientation with 2 rows and 2 columns</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gof_sc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ergm_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gof-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.5: Goodness-of-fit (GOF) diagnostics for the ERGM fitted to the Lazega lawyers co-working network. The plots compare the observed network to networks simulated from the fitted model. The top-left panel evaluates the modeled statistics, while the remaining panels assess broader structural features such as degree distribution, edgewise shared partners, and geodesic distances.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note on using log-odds instead
</div>
</div>
<div class="callout-body-container callout-body">
<p>Normally, GOF plots show the proportion (e.g., of nodes with a given degree) on the y-axis. Using the following and setting <code>plotlogodds = TRUE</code> transforms those proportions to log-odds:</p>
<p><span class="math display">\[
\text{log-odds}(p) = \log\left(\frac{p}{1 - p}\right)
\]</span> In other words, you instead run <code>gof(model, plotlogodds=TRUE)</code>.</p>
<p>This is useful when you’re interested in small differences in low-probability bins (e.g., rare degrees or long geodesic distances). Values close to 0 (e.g., rare degrees or high distances) are spread out and more visible. Differences between observed and simulated values in the tails become more pronounced. Plots become less intuitive if you’re unfamiliar with log-odds, so interpret with care.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpreting the GOF plots
</div>
</div>
<div class="callout-body-container callout-body">
<p>In GOF plots generated by the <code>ergm</code> package, the meaning of the black line and blue diamond differs slightly depending on the panel.</p>
<ul>
<li>In the <strong>model statistics</strong> panel, the blue diamond represents the observed value, while the black line represents the mean value across simulated networks.</li>
<li>In the remaining panels, the black line represents the observed distribution, while the blue diamonds represent the mean of the simulated distributions.</li>
</ul>
<p>Good fit is indicated when the observed values fall within the range of the simulated distributions and align closely with the simulated means.</p>
</div>
</div>
<p>The panels in <a href="#fig-gof" class="quarto-xref">Figure&nbsp;<span>18.5</span></a> can be interpreted as follows:</p>
<ul>
<li><strong>Model statistics</strong>: the sufficient statistics explicitly specified in the model formula (e.g., <code>edges</code>, <code>nodematch</code>, <code>gwesp</code>). This plot shows whether the model reproduces the statistics it was explicitly fit to match. Each boxplot represents the distribution of simulated values for a modeled term (e.g., <code>edges</code>, <code>nodematch.practice</code>, <code>gwesp</code>), and the blue diamond marks the observed value. Good fit is indicated when the diamond lies near the center of the box.</li>
<li><strong>Degree distribution</strong>: the number of ties per node. The model accurately captures the variability in the number of ties per node if the observed degree frequencies fall within the simulated distribution at most points.</li>
<li><strong>Geodesic distances</strong>: shortest paths between nodes. If the model reflects the observed network’s overall connectivity, the distribution of shortest path lengths should align closely with those from the simulations.</li>
<li><strong>Edgewise shared partners (ESP)</strong>: the number of common neighbors shared by directly connected pairs of nodes. ESP captures local clustering. Because the model already includes <code>gwesp()</code>, this panel is not a fully independent test of fit in this example; rather, it confirms that the fitted model reproduces the clustering pattern it was designed to capture.</li>
</ul>
<p>In addition to the plots shown in <a href="#fig-gof" class="quarto-xref">Figure&nbsp;<span>18.5</span></a>, we can also look at the printed GOF summary.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>gof_sc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Goodness-of-fit for degree 

         obs min mean max MC p-value
degree0    2   0 4.11  14       0.70
degree1    3   0 2.34   8       0.82
degree2    2   0 2.22   9       1.00
degree3    4   0 2.86   9       0.64
degree4    2   0 2.61   7       0.86
degree5    4   0 2.88   8       0.60
degree6    4   0 3.14   7       0.80
degree7    1   0 2.92   9       0.46
degree8    1   0 2.97   8       0.38
degree9    5   0 2.46   6       0.32
degree10   1   0 2.20   6       0.62
degree11   1   0 1.59   7       1.00
degree12   2   0 1.32   7       0.68
degree13   3   0 0.91   4       0.16
degree14   0   0 0.61   4       1.00
degree15   1   0 0.33   2       0.56
degree16   0   0 0.24   3       1.00
degree17   0   0 0.10   1       1.00
degree18   0   0 0.07   1       1.00
degree19   0   0 0.06   1       1.00
degree20   0   0 0.05   1       1.00
degree21   0   0 0.01   1       1.00

Goodness-of-fit for edgewise shared partner 

      obs min  mean max MC p-value
esp0    5   0  4.77  12       0.90
esp1   16   5 16.13  28       1.00
esp2   29   3 25.65  43       0.72
esp3   17   0 24.41  56       0.44
esp4   23   0 18.39  50       0.60
esp5   11   0 10.32  32       0.76
esp6   10   0  4.65  19       0.26
esp7    4   0  2.04  10       0.48
esp8    0   0  0.84   8       1.00
esp9    0   0  0.28   3       1.00
esp10   0   0  0.07   2       1.00
esp11   0   0  0.03   1       1.00
esp12   0   0  0.01   1       1.00

Goodness-of-fit for minimum geodesic distance 

    obs min   mean max MC p-value
1   115  29 107.59 167       0.78
2   275  36 250.34 400       0.80
3   148  19 107.10 182       0.24
4    21   0  18.60  63       0.74
5     2   0   2.43  29       0.60
6     0   0   0.53  19       1.00
7     0   0   0.11   8       1.00
8     0   0   0.02   2       1.00
Inf  69   0 143.28 535       0.70

Goodness-of-fit for model statistics 

                        obs      min     mean      max
edges              115.0000 29.00000 107.5900 167.0000
nodecov.practice   129.0000 21.00000 121.2900 178.0000
nodematch.practice  72.0000 16.00000  67.3200 117.0000
gwesp.fixed.0.693  181.2969 22.49978 167.4399 285.2343
                   MC p-value
edges                    0.78
nodecov.practice         0.88
nodematch.practice       0.84
gwesp.fixed.0.693        0.76</code></pre>
</div>
</div>
<p>The printed GOF summary provides the same comparison numerically, including Monte Carlo <span class="math inline">\(p\)</span>-values for each network statistic. For each statistic, the null hypothesis is that the observed value could reasonably have been generated by the fitted ERGM. In other words, there is no evidence that the observed network differs from the networks simulated under the model with respect to that structural feature. Consequently, large <span class="math inline">\(p\)</span>-values indicate good agreement between the observed and simulated networks, whereas small <span class="math inline">\(p\)</span>-values suggest that the model does not adequately reproduce that aspect of the network.</p>
<p>The numerical output supports the visual interpretation. The degree distribution is well captured across nearly all values, with observed counts generally falling within the range of those generated by the simulations. Most Monte Carlo <span class="math inline">\(p\)</span>-values are comfortably non-significant, indicating no evidence that the observed degree frequencies differ from those expected under the fitted model. Minimum geodesic distances also show good agreement between observed and simulated networks, although the fit is somewhat weaker for geodesic distance 3 (<span class="math inline">\(p = 0.08\)</span>). Finally, the modeled terms (<code>edges</code>, <code>nodecov.practice</code>, <code>nodematch.practice</code>, and <code>gwesp</code>) are all closely reproduced by the simulated networks, confirming that the maximum likelihood estimation successfully matched the sufficient statistics specified in the model.</p>
<p>Together, these diagnostics indicate that the model performs well for this network. It reproduces the modeled terms accurately and also captures broader structural features such as degree variation and path lengths. Since the model has also passed the MCMC convergence diagnostics, we have evidence that the ERGM is both computationally well estimated and substantively adequate for the structural features examined here.</p>
</section>
</section>
</section>
<section id="variants-and-extensions-of-ergms" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="variants-and-extensions-of-ergms"><span class="header-section-number">18.3</span> Variants and Extensions of ERGMs</h2>
<p>The ERGM framework has been extended in several ways to address different types of network data and research questions. While standard ERGMs are typically applied to a single cross-sectional binary network, the following variants expand the framework to model temporal dynamics, multi-mode structures, alternative estimation approaches, and non-binary ties.</p>
<ul>
<li><p><strong>Temporal ERGMs (TERGMs).</strong><br>
TERGMs extend ERGMs to longitudinal network data, modeling network evolution across discrete time steps. They allow researchers to estimate how past network structure influences the probability of ties in subsequent time periods.</p></li>
<li><p><strong>Separable Temporal ERGMs (STERGMs).</strong><br>
STERGMs explicitly separate the processes of tie formation and tie dissolution, allowing these mechanisms to be modeled independently. This is useful when the drivers of tie creation differ from those governing tie persistence.</p></li>
<li><p><strong>Curved ERGMs.</strong><br>
Curved ERGMs introduce nonlinear parameterizations of model terms, allowing complex dependence structures (such as geometrically weighted degree or shared partner statistics) to be modeled with fewer parameters and improved stability.</p></li>
<li><p><strong>ERGM for Two-Mode Networks (ERGM-2mode).</strong><br>
Specialized ERGM formulations allow the modeling of bipartite networks (e.g., actors–events or authors–papers), accounting for structural constraints inherent to two-mode data.</p></li>
<li><p><strong>Valued and Count ERGMs.</strong><br>
Extensions of ERGMs allow modeling valued or weighted ties rather than only binary relationships. These models can represent tie strength, interaction frequency, or counts of interactions between nodes.</p></li>
<li><p><strong>Bayesian ERGMs (BERGMs).</strong><br>
Bayesian ERGMs estimate model parameters using Bayesian inference, combining prior distributions with the likelihood of the observed network. Posterior distributions are typically approximated using Markov chain Monte Carlo (MCMC) methods. This framework allows incorporating prior knowledge and provides full posterior uncertainty estimates for parameters.</p></li>
<li><p><strong>ERGMito.</strong><br>
ERGMito extends the ERGM framework to collections of small independent networks (e.g., multiple ego networks or networks observed across different groups). Because the networks are modeled as independent realizations, the likelihood can often be computed exactly, allowing exact parameter estimation without relying on MCMC-based approximation, which can substantially reduce computational complexity.</p></li>
</ul>
<p>These extensions highlight the flexibility of the ERGM framework and allow researchers to study a broad range of network structures and dynamics beyond a single static binary network.</p>


</section>
<section id="bibliography" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-besag1972nearest" class="csl-entry" role="listitem">
Besag, Julian E. 1972. <span>“Nearest-Neighbour Systems and the Auto-Logistic Model for Binary Data.”</span> <em>Journal of the Royal Statistical Society: Series B (Methodological)</em> 34 (1): 75–83.
</div>
<div id="ref-frank1986markov" class="csl-entry" role="listitem">
Frank, Ove, and David Strauss. 1986. <span>“Markov Graphs.”</span> <em>Journal of the American Statistical Association</em> 81 (395): 832–42.
</div>
<div id="ref-hunter2006inference" class="csl-entry" role="listitem">
Hunter, David R, and Mark S Handcock. 2006. <span>“Inference in Curved Exponential Family Models for Networks.”</span> <em>Journal of Computational and Graphical Statistics</em> 15 (3): 565–83.
</div>
<div id="ref-pattison2002neighborhood" class="csl-entry" role="listitem">
Pattison, Philippa, and Garry Robins. 2002. <span>“Neighborhood–Based Models for Social Networks.”</span> <em>Sociological Methodology</em> 32 (1): 301–37.
</div>
<div id="ref-schweinberger2011instability" class="csl-entry" role="listitem">
Schweinberger, Michael. 2011. <span>“Instability, Sensitivity, and Degeneracy of Discrete Exponential Families.”</span> <em>Journal of the American Statistical Association</em> 106 (496): 1361–70.
</div>
<div id="ref-snijders2006new" class="csl-entry" role="listitem">
Snijders, Tom AB, Philippa E Pattison, Garry L Robins, and Mark S Handcock. 2006. <span>“New Specifications for Exponential Random Graph Models.”</span> <em>Sociological Methodology</em> 36 (1): 99–153.
</div>
<div id="ref-west1996s50" class="csl-entry" role="listitem">
West, P, and H Sweeting. 1996. <span>“Background, Rationale and Design of the West of Scotland 11 to 16 Study.”</span> <em>MRC Medical Sociology Unit Working Paper</em>, no. 52: 1.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/schochastics\.io\/R4SNA");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../inferential/rgm.html" class="pagination-link" aria-label="Random Graph Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Random Graph Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../inferential/saom.html" class="pagination-link" aria-label="Stochastic Actor Oriented Models (SAOMs)">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Stochastic Actor Oriented Models (SAOMs)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>R for Social Network Analysis was written by Termeh Shafie and David Schoch.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/schochastics/R4SNA/edit/main/inferential/ergm.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/schochastics/R4SNA/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>