<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Termeh Shafie and David Schoch">

<title>19&nbsp; Relational Event Models (REMs) – R for Social Network Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../tidy/introduction.html" rel="next">
<link href="../inferential/saom.html" rel="prev">
<link href="../cover.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-36bf55b16c7cb4b1420f41495cb5446a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="19&nbsp; Relational Event Models (REMs) – R for Social Network Analysis">
<meta property="og:description" content="">
<meta property="og:image" content="https://schochastics.io/R4SNA/inferential/rem_files/figure-html/fig-frozen-1.png">
<meta property="og:site_name" content="R for Social Network Analysis">
<meta property="og:image:height" content="1344">
<meta property="og:image:width" content="1344">
<meta name="twitter:title" content="19&nbsp; Relational Event Models (REMs) – R for Social Network Analysis">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://schochastics.io/R4SNA/inferential/rem_files/figure-html/fig-frozen-1.png">
<meta name="twitter:image-height" content="1344">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../inferential/introduction.html">Inferential Network Analysis</a></li><li class="breadcrumb-item"><a href="../inferential/rem.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Relational Event Models (REMs)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">R for Social Network Analysis</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/schochastics/R4SNA" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../network-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Data and Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Descriptive Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/descriptives-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Basic Network Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/centrality-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Centrality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Cohesive Subgroups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/two-mode-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-Mode Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/signed-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Signed Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/ego-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ego Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/netropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Entropy Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Network Visualization</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/ggraph-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Basics of ggraph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/ggraph-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Advanced Layouts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/enhance-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Enhancing Visualizations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/interactive-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Interactive Visualization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Inferential Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/non-parametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Non-Parametric Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/rgm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Random Graph Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/ergm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Exponential Random Graph Models (ERGMs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/saom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Stochastic Actor Oriented Models (SAOMs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/rem.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Relational Event Models (REMs)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Tidy Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/tidygraph-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Basics of tidygraph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/tidygraph-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Descriptive Network Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/ucnets-egor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Constructing the UCNets Ego Network Dataset</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#packages-needed-for-this-chapter" id="toc-packages-needed-for-this-chapter" class="nav-link active" data-scroll-target="#packages-needed-for-this-chapter"><span class="header-section-number">19.1</span> Packages Needed for this Chapter</a></li>
  <li><a href="#model-specification" id="toc-model-specification" class="nav-link" data-scroll-target="#model-specification"><span class="header-section-number">19.2</span> Model Specification</a>
  <ul>
  <li><a href="#formal-specification-of-the-relational-event-model" id="toc-formal-specification-of-the-relational-event-model" class="nav-link" data-scroll-target="#formal-specification-of-the-relational-event-model"><span class="header-section-number">19.2.1</span> Formal Specification of the Relational Event Model</a></li>
  <li><a href="#relational-event-data-structure" id="toc-relational-event-data-structure" class="nav-link" data-scroll-target="#relational-event-data-structure"><span class="header-section-number">19.2.2</span> Relational Event Data Structure</a></li>
  <li><a href="#intuition-competing-events" id="toc-intuition-competing-events" class="nav-link" data-scroll-target="#intuition-competing-events"><span class="header-section-number">19.2.3</span> Intuition: Competing Events</a></li>
  </ul></li>
  <li><a href="#modeling-procedure" id="toc-modeling-procedure" class="nav-link" data-scroll-target="#modeling-procedure"><span class="header-section-number">19.3</span> Modeling Procedure</a>
  <ul>
  <li><a href="#step-1-constructing-the-risk-sets" id="toc-step-1-constructing-the-risk-sets" class="nav-link" data-scroll-target="#step-1-constructing-the-risk-sets">Step 1: Constructing the Risk Sets</a></li>
  <li><a href="#step-2-computing-event-statistics" id="toc-step-2-computing-event-statistics" class="nav-link" data-scroll-target="#step-2-computing-event-statistics">Step 2: Computing Event Statistics</a></li>
  <li><a href="#step-3-estimating-the-model" id="toc-step-3-estimating-the-model" class="nav-link" data-scroll-target="#step-3-estimating-the-model">Step 3: Estimating the Model</a></li>
  <li><a href="#endogenous-statistics" id="toc-endogenous-statistics" class="nav-link" data-scroll-target="#endogenous-statistics"><span class="header-section-number">19.3.1</span> Endogenous Statistics</a>
  <ul>
  <li><a href="#reciprocity" id="toc-reciprocity" class="nav-link" data-scroll-target="#reciprocity">Reciprocity</a></li>
  <li><a href="#repetition" id="toc-repetition" class="nav-link" data-scroll-target="#repetition">Repetition</a></li>
  <li><a href="#past-interaction" id="toc-past-interaction" class="nav-link" data-scroll-target="#past-interaction">Past Interaction</a></li>
  <li><a href="#sender-activity" id="toc-sender-activity" class="nav-link" data-scroll-target="#sender-activity">Sender Activity</a></li>
  <li><a href="#sender-popularity" id="toc-sender-popularity" class="nav-link" data-scroll-target="#sender-popularity">Sender Popularity</a></li>
  <li><a href="#receiver-activity" id="toc-receiver-activity" class="nav-link" data-scroll-target="#receiver-activity">Receiver Activity</a></li>
  <li><a href="#receiver-popularity" id="toc-receiver-popularity" class="nav-link" data-scroll-target="#receiver-popularity">Receiver Popularity</a></li>
  </ul></li>
  <li><a href="#exogenous-covariates" id="toc-exogenous-covariates" class="nav-link" data-scroll-target="#exogenous-covariates"><span class="header-section-number">19.3.2</span> Exogenous Covariates</a></li>
  </ul></li>
  <li><a href="#rems-in-r" id="toc-rems-in-r" class="nav-link" data-scroll-target="#rems-in-r"><span class="header-section-number">19.4</span> REMs in R</a>
  <ul>
  <li><a href="#model-1-reciprocity-and-repetition" id="toc-model-1-reciprocity-and-repetition" class="nav-link" data-scroll-target="#model-1-reciprocity-and-repetition"><span class="header-section-number">19.4.1</span> Model 1: Reciprocity and Repetition</a>
  <ul>
  <li><a href="#reciprocity-rrecsnd" id="toc-reciprocity-rrecsnd" class="nav-link" data-scroll-target="#reciprocity-rrecsnd">Reciprocity (<code>RRecSnd</code>)</a></li>
  <li><a href="#repetition-rsndsnd" id="toc-repetition-rsndsnd" class="nav-link" data-scroll-target="#repetition-rsndsnd">Repetition (<code>RSndSnd</code>)</a></li>
  <li><a href="#interpreting-the-coefficients" id="toc-interpreting-the-coefficients" class="nav-link" data-scroll-target="#interpreting-the-coefficients">Interpreting the Coefficients</a></li>
  </ul></li>
  <li><a href="#model-2-gender-as-an-exogenous-covariate" id="toc-model-2-gender-as-an-exogenous-covariate" class="nav-link" data-scroll-target="#model-2-gender-as-an-exogenous-covariate"><span class="header-section-number">19.4.2</span> Model 2: Gender as an Exogenous Covariate</a>
  <ul>
  <li><a href="#interpreting-the-coefficients-1" id="toc-interpreting-the-coefficients-1" class="nav-link" data-scroll-target="#interpreting-the-coefficients-1">Interpreting the Coefficients</a></li>
  </ul></li>
  <li><a href="#model-3-gender-interaction-effects" id="toc-model-3-gender-interaction-effects" class="nav-link" data-scroll-target="#model-3-gender-interaction-effects"><span class="header-section-number">19.4.3</span> Model 3: Gender Interaction Effects</a>
  <ul>
  <li><a href="#interpreting-the-coefficients-2" id="toc-interpreting-the-coefficients-2" class="nav-link" data-scroll-target="#interpreting-the-coefficients-2">Interpreting the Coefficients</a></li>
  </ul></li>
  <li><a href="#assessing-goodnes-of-fit" id="toc-assessing-goodnes-of-fit" class="nav-link" data-scroll-target="#assessing-goodnes-of-fit"><span class="header-section-number">19.4.4</span> Assessing Goodnes of Fit</a>
  <ul>
  <li><a href="#actual-vs.-predicted" id="toc-actual-vs.-predicted" class="nav-link" data-scroll-target="#actual-vs.-predicted">Actual vs.&nbsp;Predicted</a></li>
  <li><a href="#residual-diagnostics" id="toc-residual-diagnostics" class="nav-link" data-scroll-target="#residual-diagnostics">Residual Diagnostics</a></li>
  <li><a href="#comparing-model-specifications" id="toc-comparing-model-specifications" class="nav-link" data-scroll-target="#comparing-model-specifications">Comparing Model Specifications</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/schochastics/R4SNA/edit/main/inferential/rem.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/schochastics/R4SNA/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../inferential/introduction.html">Inferential Network Analysis</a></li><li class="breadcrumb-item"><a href="../inferential/rem.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Relational Event Models (REMs)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Relational Event Models (REMs)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Imagine you are watching a group of people at a party. At any moment, someone might start a conversation with someone else. The question is: <em>who will start talking to whom next?</em></p>
<p>Many different interactions are possible, but only one actually happens. Understanding why that particular interaction occurs rather than any of the others is the kind of problem that event-based statistical models are designed to address.</p>
<p>One approach to studying such processes is Cox regression, a statistical method used to analyze events that unfold over time. Instead of focusing only on whether something happens, Cox regression models the rate at which events occur, and how different factors make an event more or less likely to happen sooner rather than later. In intuitive terms, it helps us understand which possible events are “more likely to happen next” given the current situation and the characteristics of the actors involved.</p>
<p><strong>Relational Event Models (REMs)</strong> build on this logic to study social interactions as they occur in sequence. Rather than treating relationships as static connections between individuals, REMs conceptualize networks as streams of actions (such as messages, conversations, or interactions) unfolding over time.</p>
<p>Traditional approaches in social network analysis have typically relied on two dominant perspectives. On the one hand, <em>static network models</em>, such as Exponential Random Graph Models (<a href="ergm.html" class="quarto-xref"><span>Chapter 17</span></a>), focus on long-term equilibrium patterns in aggregated networks. On the other hand, <em>longitudinal network models</em>, such as Stochastic Actor Oriented Models (<a href="saom.html" class="quarto-xref"><span>Chapter 18</span></a>), examine how relatively stable ties evolve across discrete time periods. Both approaches emphasize relationships as relatively enduring structures observed over bounded intervals.</p>
<p>In contrast, Relational Event Models shift attention to the fine-grained sequence and timing of discrete behavioral events. Rather than treating ties as fixed or slowly evolving entities, REM conceptualizes networks as streams of interaction. Social structure is not simply observed, it is continuously produced and reproduced through temporally ordered actions.</p>
<p>A key distinction between ERGMs and REM lies in the question each approach seeks to answer. ERGMs ask whether a particular <em>network structure</em> is likely to emerge within a defined time window. REM, by contrast, asks:</p>
<blockquote class="blockquote">
<p>Given the history of prior interactions, how likely is it that actor <em>a</em> will direct an event toward actor <em>b</em> at a specific moment?</p>
</blockquote>
<p>This represents a conceptual shift from modeling cumulative structures to modeling event rates. In REM, the fundamental unit of analysis is not the tie, but the event. Each event is understood as occurring within a dynamic system shaped by prior interactions. The probability (or rate) of a new event depends on the evolving history of the network.</p>
<p>Relational Event Models pursue two central analytic objectives:</p>
<ol type="1">
<li><strong>Prediction</strong>: Accurately predict who will send a message to whom, given the prior sequence of events.</li>
<li><strong>Explanation</strong>: Identify the factors that influence the propensity for interaction between two actors.</li>
</ol>
<p>These factors may include:</p>
<ul>
<li><strong>Node attributes</strong> (e.g., status, role, demographic characteristics)</li>
<li><strong>Dyadic attributes</strong> (e.g., similarity, shared group membership)</li>
<li><strong>Historical patterns of communication</strong> (e.g., reciprocity, repetition, transitive closure)</li>
<li><strong>Environmental or contextual factors</strong> (e.g., time constraints, institutional settings)</li>
</ul>
<p>By incorporating these elements, REM enables researchers to test hypotheses about the mechanisms that generate interaction sequences.</p>
<p>This chapter introduces the theoretical foundations and methodological tools of Relational Event Models. It begins by situating REM within the broader landscape of network analysis and clarifying its event-centered logic. It then develops the core components of the model (event histories, risk sets, and rate functions) before examining how structural, attribute-based, and contextual effects are specified and interpreted.</p>
<p>Through this approach, we will see how REM provides a rigorous and flexible framework for modeling dynamic interaction processes, illuminating the micro-level mechanisms through which social structure emerges over time.</p>
<section id="packages-needed-for-this-chapter" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="packages-needed-for-this-chapter"><span class="header-section-number">19.1</span> Packages Needed for this Chapter</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(relevent)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note on Alternative Software for Relational Event Models
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this chapter we use the <code>relevent</code> package to estimate relational event models. The package implements the framework introduced by <span class="citation" data-cites="butts2008">Butts (<a href="#ref-butts2008" role="doc-biblioref">2008</a>)</span> and provides a straightforward and widely used approach for estimating REMs from sequences of dyadic interactions.</p>
<p>Several alternative implementations are also available. The <code>goldfish</code> package provides a more modern and flexible framework for relational event modeling. In contrast to <code>relevent</code>, which requires users to manually construct event statistics and covariates, <code>goldfish</code> offers a formula-based interface that allows endogenous effects and actor attributes to be specified directly within the model. The package also supports a broader range of structural effects and is designed to scale more efficiently to larger event datasets.</p>
<p>Another option is the <code>rem</code> package, which provides a simplified implementation of relational event models with a more modern interface than <code>relevent</code>. In particular, <code>rem</code> integrates more naturally with tidyverse-style workflows, making it convenient for researchers who prefer a tidy data structure and formula-based model specification. While it supports many core REM features, it is currently less widely used in applied research than <code>relevent</code> or <code>goldfish</code>.</p>
<p>Despite these differences in implementation, the underlying statistical logic remains the same across packages: relational event models estimate the intensity of possible interactions and compare competing events within a risk set. For introductory applications and teaching purposes, <code>relevent</code> remains a convenient and transparent tool, while <code>goldfish</code> or <code>rem</code> may be preferable in more complex or larger-scale analyses.</p>
</div>
</div>
</section>
<section id="model-specification" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="model-specification"><span class="header-section-number">19.2</span> Model Specification</h2>
<p>When relational event data contain information about the <em>order</em> of events (but not their precise timestamps), the modeling problem can be framed in terms of relative event hazards. This situation is mathematically equivalent to estimating a Cox proportional hazards model (or Cox regression) over a sequence of discrete event opportunities <span class="citation" data-cites="butts2008">(<a href="#ref-butts2008" role="doc-biblioref">Butts 2008</a>)</span>. Rather than modeling the exact timing of events, we instead model the relative rate (or intensity) at which a particular interaction occurs next, given the prior history of events.</p>
<section id="formal-specification-of-the-relational-event-model" class="level3" data-number="19.2.1">
<h3 data-number="19.2.1" class="anchored" data-anchor-id="formal-specification-of-the-relational-event-model"><span class="header-section-number">19.2.1</span> Formal Specification of the Relational Event Model</h3>
<p>Following <span class="citation" data-cites="butts2008">Butts (<a href="#ref-butts2008" role="doc-biblioref">2008</a>)</span>, relational event models are formulated in terms of a <strong>conditional event intensity function</strong>, which represents the instantaneous rate at which a specific interaction occurs given the past event history.</p>
<p>Let <span class="math inline">\(\lambda_{ab}(t)\)</span> denote the intensity of an event from actor <span class="math inline">\(a\)</span> to actor <span class="math inline">\(b\)</span> at time <span class="math inline">\(t\)</span>, given the history of past events <span class="math inline">\(H_t\)</span>. The model is specified as</p>
<p><span class="math display">\[
\lambda_{ab}(t \mid H_t) = \lambda_0(t)\exp(\theta^\top s_{ab}(t))
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\lambda_{ab}(t)\)</span> is the <strong>event intensity</strong> for interaction <span class="math inline">\(a \rightarrow b\)</span> at time <span class="math inline">\(t\)</span>,</li>
<li><span class="math inline">\(\lambda_0(t)\)</span> is the <strong>baseline rate</strong> of events,</li>
<li><span class="math inline">\(s_{ab}(t)\)</span> is a vector of <strong>statistics</strong> describing the event (e.g., actor attributes, dyadic covariates, or history-based structural effects),</li>
<li><span class="math inline">\(\theta\)</span> is a vector of <strong>model parameters</strong>.</li>
</ul>
<p>The statistics <span class="math inline">\(s_{ab}(t)\)</span> are typically functions of the event history, meaning they evolve as new interactions occur.</p>
<p>When only the <em>order</em> of events is observed (rather than exact timestamps), inference can proceed using the partial likelihood, which compares the intensity of the observed event with the intensities of all other possible events in the risk set <span class="math inline">\(R_t\)</span>. The probability that a specific event <span class="math inline">\(a \rightarrow b\)</span> occurs next is therefore</p>
<p><span class="math display">\[
P(a \rightarrow b \text{ occurs next}) =
\frac{\exp(\theta^\top s_{ab}(t))}
{\sum_{(i,j)\in R_t}\exp(\theta^\top s_{ij}(t))}
\]</span></p>
<p>where <span class="math inline">\(R_t\)</span> denotes the set of all interactions that could occur at time <span class="math inline">\(t\)</span>.</p>
<p>This formulation shows that relational event models explain which interaction occurs next by comparing the relative intensities of all competing events in the risk set.</p>
<p>Although REMs are typically written using event intensities, estimation for ordered event data relies on the same likelihood logic as Cox proportional hazards models.</p>
</section>
<section id="relational-event-data-structure" class="level3" data-number="19.2.2">
<h3 data-number="19.2.2" class="anchored" data-anchor-id="relational-event-data-structure"><span class="header-section-number">19.2.2</span> Relational Event Data Structure</h3>
<p>To apply the event-based hazard logic to social interactions, we need a specific type of data structure known as relational event data. Rather than representing relationships as static ties between actors, relational event data record individual interactions as they occur over time.</p>
<p>Each observation typically includes:</p>
<ul>
<li>a <strong>sender</strong> (the actor initiating the interaction),</li>
<li>a <strong>receiver</strong> (the actor targeted by the interaction),</li>
<li>and a <strong>time or order</strong> indicating when the interaction occurred.</li>
</ul>
<p>For example, a relational event dataset describing communication might look like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>time</th>
<th>sender</th>
<th>receiver</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Alice</td>
<td>Bob</td>
</tr>
<tr class="even">
<td>2</td>
<td>Bob</td>
<td>Alice</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Carol</td>
<td>Alice</td>
</tr>
</tbody>
</table>
<p>In this format, the network is not represented as a fixed structure but as a chronological sequence of actions. The history of past events becomes crucial, because earlier interactions influence the likelihood of future ones. For instance, a reply may be more likely after receiving a message, or individuals who communicate frequently may continue interacting.</p>
<p>Relational event data therefore allow researchers to study <em>how interaction processes unfold moment by moment</em>, rather than only observing the final network structure.</p>
</section>
<section id="intuition-competing-events" class="level3" data-number="19.2.3">
<h3 data-number="19.2.3" class="anchored" data-anchor-id="intuition-competing-events"><span class="header-section-number">19.2.3</span> Intuition: Competing Events</h3>
<p>One intuitive way to think about Cox regression is as a race. Suppose several runners are lined up at the starting line. Each runner represents a possible event (for example, a person sending a message to another person). Each runner runs at a different speed depending on certain characteristics:</p>
<ul>
<li>Some runners have better shoes (a helpful covariate).</li>
<li>Some runners are tired (a negative covariate).</li>
<li>Some runners have run this race before and know the route (history effects).</li>
</ul>
<p>The runner who reaches the finish line first is the event that occurs. Cox regression does not try to predict the exact finishing time. Instead, it focuses on who is most likely to win the race, given their characteristics.</p>
<p>At the core of Cox regression is the idea of a <strong>hazard</strong>. The hazard represents the instantaneous chance that an event happens right now, given that it has not yet occurred. A helpful analogy is popcorn in a microwave. Imagine many popcorn kernels heating up at the same time. At any moment, each kernel has some chance of popping. Some kernels pop early, others later. Cox regression models what makes certain kernels more likely to pop sooner. In social science terms, we might ask questions such as:</p>
<ul>
<li>Does previous interaction make a new message more likely?</li>
<li>Are people more likely to communicate with similar others?</li>
<li>Does status increase the chance that someone initiates contact?</li>
</ul>
<p>Each of these factors changes the hazard rate, increasing or decreasing the likelihood that a particular event occurs next.</p>
<p>One of the most elegant features of Cox regression is that it does not require specifying the overall timing pattern of events. Events might occur very quickly at the beginning and slow down later, or slowly at first and accelerate over time. Cox regression essentially says:</p>
<blockquote class="blockquote">
<p><em>That’s fine. We will ignore the overall clock and focus on comparing the competitors.</em></p>
</blockquote>
<p>Instead of modeling absolute time, the model compares relative chances:</p>
<blockquote class="blockquote">
<p><em>At this moment, which event is most likely to happen?</em></p>
</blockquote>
<p>This is achieved through the <strong>partial likelihood</strong>, which evaluates the relative hazards of all possible events at each moment in time.</p>
<p>So why does this work so well for social interactions? In many datasets, especially relational event data, the exact timing of events is often less important than the order in which events occur.</p>
<p>Consider the following sequence:</p>
<ol type="1">
<li>Alice messages Bob<br>
</li>
<li>Bob replies to Alice<br>
</li>
<li>Carol messages Alice</li>
</ol>
<p>At step 3, several interactions were possible, including:</p>
<ul>
<li>Alice → Bob<br>
</li>
<li>Alice → Carol<br>
</li>
<li>Bob → Alice<br>
</li>
<li>Bob → Carol<br>
</li>
<li>Carol → Alice<br>
</li>
<li>Carol → Bob</li>
</ul>
<p>This set of possible interactions is called the risk set (which we return to more formally in the next section).</p>
<p>Cox regression allows us to ask:</p>
<blockquote class="blockquote">
<p><em>Given the situation and the history of interactions, why did Carol message Alice rather than another interaction occurring?</em></p>
</blockquote>
<p>The model compares the rate (or intensity) of the observed event with those of all other possible events in the same situation.</p>
</section>
</section>
<section id="modeling-procedure" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="modeling-procedure"><span class="header-section-number">19.3</span> Modeling Procedure</h2>
<p>Estimation of relational event models proceeds in three main steps. These steps transform the sequence of observed interactions into a dataset that can be estimated using a Cox-type likelihood.</p>
<section id="step-1-constructing-the-risk-sets" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-1-constructing-the-risk-sets">Step 1: Constructing the Risk Sets</h4>
<p>At each point in the event sequence, one interaction is observed, but many other interactions were possible and did not occur. All dyads that could potentially interact at that moment form the risk set.</p>
<p>Each event time can therefore be understood as a discrete choice situation, in which one event is selected from among several competing alternatives. The Cox partial likelihood compares the covariates of the observed event with those of all other possible events in the same risk set.</p>
<p>For each observed interaction, we identify all dyads that were eligible to interact at that time. We then augment the dataset by adding all unobserved but possible events corresponding to that risk set. This transforms the event history into a series of choice sets consisting of one observed event and multiple non-events at each step in the sequence.</p>
</section>
<section id="step-2-computing-event-statistics" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-2-computing-event-statistics">Step 2: Computing Event Statistics</h4>
<p>For both observed and unobserved events, we compute a set of statistics that capture factors influencing the likelihood of interaction. These statistics serve as explanatory variables in the relational event model.</p>
<p>The statistics can capture several types of mechanisms, including:</p>
<ul>
<li><strong>Endogenous structural effects</strong>, derived from the history of previous interactions,</li>
<li><strong>Node-level attributes</strong>, describing characteristics of the actors involved,</li>
<li><strong>Dyadic covariates</strong>, capturing properties of the sender–receiver pair,</li>
<li><strong>Contextual variables</strong>, describing features of the environment in which interactions occur.</li>
</ul>
<p>All statistics are evaluated <strong>dynamically</strong>, meaning they are recalculated at each event step to reflect the evolving interaction history.</p>
<p>The specific statistics included in our model are described in the following section.</p>
</section>
<section id="step-3-estimating-the-model" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-3-estimating-the-model">Step 3: Estimating the Model</h4>
<p>Finally, we estimate the relational event model using a Cox proportional hazards framework. Event occurrence is treated as the dependent variable, while the computed statistics serve as explanatory variables.</p>
<p>Estimation relies on the partial likelihood, which compares the intensity of the observed event with the intensities of all other possible events within the same risk set.</p>
</section>
<section id="endogenous-statistics" class="level3" data-number="19.3.1">
<h3 data-number="19.3.1" class="anchored" data-anchor-id="endogenous-statistics"><span class="header-section-number">19.3.1</span> Endogenous Statistics</h3>
<p>Relational event models allow us to incorporate <strong>endogenous statistics</strong>, which capture patterns that arise from the history of interactions itself. These statistics represent mechanisms through which past events influence the likelihood of future events. Some of these endogenous statistics are summarized in the following and in <a href="#tbl-endstats" class="quarto-xref">Table&nbsp;<span>19.1</span></a>.</p>
<p>Let <span class="math inline">\(V=\{1,\dots,n\}\)</span> denote the set of actors. An event at time <span class="math inline">\(t\)</span> is represented as <span class="math inline">\(e_t=(i,j,t)\)</span>, where actor <span class="math inline">\(i\)</span> sends an interaction to actor <span class="math inline">\(j\)</span>. Let <span class="math inline">\(Y_{ij}(t)\)</span> be an indicator variable that equals 1 if the event <span class="math inline">\(i \rightarrow j\)</span> occurs at time <span class="math inline">\(t\)</span> and 0 otherwise. Further, let <span class="math inline">\(N_{ij}(t)\)</span> denote the total number of interactions from <span class="math inline">\(i\)</span> to <span class="math inline">\(j\)</span> that have occurred up to time <span class="math inline">\(t\)</span>.</p>
<section id="reciprocity" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="reciprocity">Reciprocity</h4>
<p>Reciprocity captures the tendency for actors to immediately respond to interactions they have received. If the previous event was <span class="math inline">\(i \rightarrow j\)</span>, the statistic equals 1 when the next event is <span class="math inline">\(j \rightarrow i\)</span>.</p>
<p><span class="math display">\[
s_{\text{reciprocity}}(i,j,t) = Y_{ij}(t-1) \cdot Y_{ji}(t)
\]</span></p>
</section>
<section id="repetition" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="repetition">Repetition</h4>
<p>Repetition captures the continuation of a dyadic interaction, meaning the same sender repeats an interaction with the same receiver.</p>
<p><span class="math display">\[
s_{\text{repetition}}(i,j,t) = Y_{ij}(t-1) \cdot Y_{ij}(t)
\]</span></p>
</section>
<section id="past-interaction" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="past-interaction">Past Interaction</h4>
<p>This statistic measures the strength of the historical relationship between the sender and receiver. It is defined as the proportion of the sender’s previous interactions that were directed toward the receiver.</p>
<p><span class="math display">\[
s_{\text{past}}(i,j,t) =
\frac{N_{ij}(t-1)}
{\sum_{k=1}^{n} N_{ik}(t-1) + \sum_{k=1}^{n} N_{ki}(t-1)}
\]</span></p>
</section>
<section id="sender-activity" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="sender-activity">Sender Activity</h4>
<p>Sender activity captures how frequently the sender has initiated interactions in the past. It is defined as the proportion of all previous events that were sent by the current sender.</p>
<p><span class="math display">\[
s_{\text{sender activity}}(i,j,t) =
\frac{\sum_{k=1}^{n} N_{ik}(t-1)}
{\sum_{p \neq q} N_{pq}(t-1)}
\]</span></p>
</section>
<section id="sender-popularity" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="sender-popularity">Sender Popularity</h4>
<p>Sender popularity measures how often the sender has previously received interactions from others.</p>
<p><span class="math display">\[
s_{\text{sender popularity}}(i,j,t) =
\frac{\sum_{k=1}^{n} N_{ki}(t-1)}
{\sum_{p \neq q} N_{pq}(t-1)}
\]</span></p>
</section>
<section id="receiver-activity" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="receiver-activity">Receiver Activity</h4>
<p>Receiver activity captures how frequently the receiver has initiated interactions in the past.</p>
<p><span class="math display">\[
s_{\text{receiver activity}}(i,j,t) =
\frac{\sum_{k=1}^{n} N_{jk}(t-1)}
{\sum_{p \neq q} N_{pq}(t-1)}
\]</span></p>
</section>
<section id="receiver-popularity" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="receiver-popularity">Receiver Popularity</h4>
<p>Receiver popularity measures how frequently the receiver has previously been the target of interactions.</p>
<p><span class="math display">\[
s_{\text{receiver popularity}}(i,j,t) =
\frac{\sum_{k=1}^{n} N_{kj}(t-1)}
{\sum_{p \neq q} N_{pq}(t-1)}
\]</span></p>
<div id="tbl-endstats" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-endstats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;19.1: Summary of some endogenous statistics used in relational event models.
</figcaption>
<div aria-describedby="tbl-endstats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th>Description</th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reciprocity</td>
<td>Immediate response to previous interaction</td>
<td><span class="math inline">\(Y_{ij}(t-1)Y_{ji}(t)\)</span></td>
</tr>
<tr class="even">
<td>Repetition</td>
<td>Same sender repeats interaction</td>
<td><span class="math inline">\(Y_{ij}(t-1)Y_{ij}(t)\)</span></td>
</tr>
<tr class="odd">
<td>Past interaction</td>
<td>Proportion of sender’s past interactions directed toward receiver</td>
<td><span class="math inline">\(\frac{N_{ij}(t-1)}{\sum_k N_{ik}(t-1)+\sum_k N_{ki}(t-1)}\)</span></td>
</tr>
<tr class="even">
<td>Sender activity</td>
<td>Proportion of past events sent by the sender</td>
<td><span class="math inline">\(\frac{\sum_k N_{ik}(t-1)}{\sum_{p\ne q}N_{pq}(t-1)}\)</span></td>
</tr>
<tr class="odd">
<td>Sender popularity</td>
<td>Proportion of past events received by the sender</td>
<td><span class="math inline">\(\frac{\sum_k N_{ki}(t-1)}{\sum_{p\ne q}N_{pq}(t-1)}\)</span></td>
</tr>
<tr class="even">
<td>Receiver activity</td>
<td>Proportion of past events sent by the receiver</td>
<td><span class="math inline">\(\frac{\sum_k N_{jk}(t-1)}{\sum_{p\ne q}N_{pq}(t-1)}\)</span></td>
</tr>
<tr class="odd">
<td>Receiver popularity</td>
<td>Proportion of past events received by the receiver</td>
<td><span class="math inline">\(\frac{\sum_k N_{kj}(t-1)}{\sum_{p\ne q}N_{pq}(t-1)}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="exogenous-covariates" class="level3" data-number="19.3.2">
<h3 data-number="19.3.2" class="anchored" data-anchor-id="exogenous-covariates"><span class="header-section-number">19.3.2</span> Exogenous Covariates</h3>
<p>In addition to endogenous statistics derived from the event history, relational event models can also incorporate <strong>exogenous covariates</strong>. These variables capture attributes of actors or dyads that may influence the likelihood of interactions but are not themselves determined by the evolving sequence of events.</p>
<p>Exogenous covariates may include <strong>actor-level attributes</strong> (e.g., demographic characteristics, roles, or status), <strong>dyadic attributes</strong> (e.g., similarity or shared group membership), or other contextual variables describing the environment in which interactions occur.</p>
<p>Let <span class="math inline">\(c_k\)</span> denote an attribute associated with actor <span class="math inline">\(k\)</span>. For binary attributes, this can be represented as</p>
<p><span class="math display">\[
c_k =
\begin{cases}
1 &amp; \text{if actor } k \text{ possesses the attribute} \\
0 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>Using this attribute, several covariates can be constructed for a potential event <span class="math inline">\(i \rightarrow j\)</span>. For example:</p>
<ul>
<li><strong>Sender attribute</strong>: indicates whether the sender possesses the attribute<br>
</li>
<li><strong>Receiver attribute</strong>: indicates whether the receiver possesses the attribute<br>
</li>
<li><strong>Sender–receiver interaction</strong>: indicates whether both sender and receiver possess the attribute</li>
</ul>
<p>These covariates allow the model to test whether actor characteristics influence interaction patterns, such as whether certain actors are more likely to initiate communication, receive interactions, or interact preferentially with others sharing the same attribute.</p>
<p>The exogenous covariates included in the model are summarized in <a href="#tbl-exstats" class="quarto-xref">Table&nbsp;<span>19.2</span></a>.</p>
<div id="tbl-exstats" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-exstats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;19.2: Summary of exogenous covariates used in relational event models.
</figcaption>
<div aria-describedby="tbl-exstats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Covariate</th>
<th>Description</th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sender attribute</td>
<td>Indicates whether the sender possesses the attribute</td>
<td><span class="math inline">\(c_i\)</span></td>
</tr>
<tr class="even">
<td>Receiver attribute</td>
<td>Indicates whether the receiver possesses the attribute</td>
<td><span class="math inline">\(c_j\)</span></td>
</tr>
<tr class="odd">
<td>Sender–receiver interaction</td>
<td>Indicates whether both actors possess the attribute</td>
<td><span class="math inline">\(c_i c_j\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="rems-in-r" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="rems-in-r"><span class="header-section-number">19.4</span> REMs in R</h2>
<p>Here we estimate a relational event model for the dialogue interactions among characters in <em>Frozen</em>. In the <code>relevent</code> package, relational event models are estimated using the function <code>rem.dyad()</code>, which fits a dyadic relational event model based on the observed sequence of interactions.</p>
<p>The main arguments of the <code>rem.dyad()</code> function are:</p>
<ul>
<li><strong><code>edgelist</code></strong>: the event sequence, provided as a matrix or data frame containing the time (or order) of each event, the sender, and the receiver.</li>
<li><strong><code>n</code></strong>: the number of actors in the network.</li>
<li><strong><code>effects</code></strong>: a vector specifying the endogenous effects to include in the model (e.g., reciprocity, repetition, or activity effects).</li>
<li><strong><code>covar</code></strong>: a list of covariate matrices corresponding to the exogenous effects specified in <code>effects</code>.</li>
<li><strong><code>ordinal</code></strong>: a logical argument indicating whether the event data are ordinal. Set <code>TRUE</code> if the data only record the order of events (without exact timestamps), and <code>FALSE</code> if precise event times are available.</li>
</ul>
<p>In our case, the dataset consists of a sequence of dialogue interactions between characters in <em>Frozen</em>, where each event records which character speaks to another and the order in which the interaction occurs. Because the data contain only the ordering of events rather than precise timestamps, we specify <code>ordinal = TRUE</code> when estimating the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Edit this code once frozen is in networkdata</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the two files</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>frozenlines <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"frozenlines.csv"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>frozenchars <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"frozenchars.csv"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the structure</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(frozenlines)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   634 obs. of  17 variables:
 $ eventID         : int  1 2 3 4 5 6 7 8 9 10 ...
 $ sceneID         : int  1 1 1 1 1 1 2 3 3 3 ...
 $ speakerID       : int  1 1 2 1 2 1 1 1 1 2 ...
 $ Anna..1.        : int  0 0 1 0 1 0 0 0 0 1 ...
 $ Elsa..2.        : int  1 1 0 1 0 1 1 1 1 0 ...
 $ Olaf..3.        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ King..4.        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Queen..5.       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Kristoff..6.    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Bulda..8.       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Grand.Pabbie..9.: int  0 0 0 0 0 0 0 0 0 0 ...
 $ Kai..10.        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Hans..11.       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Duke..12.       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Oaken..13.      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Gerda..14.      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Marshmallow..15.: int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(frozenchars)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   14 obs. of  4 variables:
 $ characterID   : int  1 2 3 4 5 6 7 8 9 10 ...
 $ character.name: chr  "Anna" "Elsa" "Olaf" "King" ...
 $ charfem       : int  1 1 0 0 1 0 1 0 0 0 ...
 $ nlines        : int  249 69 73 9 2 115 3 8 9 59 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(frozenlines)[<span class="dv">4</span><span class="sc">:</span><span class="fu">ncol</span>(frozenlines)] <span class="ot">&lt;-</span> frozenchars<span class="sc">$</span>characterID</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>receiver_cols <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">:</span><span class="fu">ncol</span>(frozenlines)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>edges <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(frozenlines)) {</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  sender <span class="ot">&lt;-</span> frozenlines<span class="sc">$</span>speakerID[i]</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  event  <span class="ot">&lt;-</span> frozenlines<span class="sc">$</span>eventID[i]</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># find receivers with value 1</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  receivers <span class="ot">&lt;-</span> receiver_cols[frozenlines[i, receiver_cols] <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">length</span>(receivers) <span class="sc">&gt;</span> <span class="dv">0</span>){</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span>(r <span class="cf">in</span> receivers){</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>      edges[[k]] <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">time =</span> event,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">sender =</span> sender,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">receiver =</span> <span class="fu">as.integer</span>(<span class="fu">names</span>(frozenlines)[r])</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>      k <span class="ot">&lt;-</span> k <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all edges</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>edgelist <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, edges)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort by event order</span></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>edgelist <span class="ot">&lt;-</span> edgelist[<span class="fu">order</span>(edgelist<span class="sc">$</span>time), ]</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(edgelist)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  time sender receiver
1    1      1        2
2    2      1        2
3    3      2        1
4    4      1        2
5    5      2        1
6    6      1        2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make sure eachevent is unique (this can be a manual fix from networkdata)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>edgelist <span class="ot">&lt;-</span> edgelist[<span class="fu">order</span>(edgelist<span class="sc">$</span>time), ]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>edgelist<span class="sc">$</span>time <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(edgelist)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>edgelist <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(edgelist)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Network size ----</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>n_actors <span class="ot">&lt;-</span> <span class="fu">nrow</span>(frozenchars)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Before estimating the relational event models, it is helpful to visualize the aggregated dialogue network. Figure <a href="#fig-frozen" class="quarto-xref">Figure&nbsp;<span>19.1</span></a> shows the <em>Frozen</em> character interaction network, with node color indicating gender.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-frozen" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-frozen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="rem_files/figure-html/fig-frozen-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-frozen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19.1: Aggregated dialogue network of Frozen characters. Node colour indicates gender, node size reflects the number of dialogue lines spoken, and edge width reflects interaction frequency.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="model-1-reciprocity-and-repetition" class="level3" data-number="19.4.1">
<h3 data-number="19.4.1" class="anchored" data-anchor-id="model-1-reciprocity-and-repetition"><span class="header-section-number">19.4.1</span> Model 1: Reciprocity and Repetition</h3>
<p>We begin by estimating a relational event model that includes two endogenous structural effects: reciprocity and repetition. These effects capture two basic conversational dynamics: turn-taking behaviour and the persistence of interactions between the same pair of characters. Including these mechanisms allows the model to account for simple structural patterns in the dialogue sequence before introducing additional explanatory variables, such as actor attributes or contextual factors, in later models.</p>
<p>Because the dialogue data record only the order of interactions rather than precise timestamps, the model is estimated with <code>ordinal = TRUE</code>. In this setting, the relational event model compares the intensity of the observed interaction to the intensities of all other possible interactions in the risk set, which consists of all possible sender–receiver pairs at that moment.</p>
<p>Formally, the event intensity for a potential interaction <span class="math inline">\(i \rightarrow j\)</span> at time <span class="math inline">\(t\)</span> is given by</p>
<p><span class="math display">\[
\lambda_{ij}(t \mid H_t) =
\lambda_0(t)\exp\Big(
\theta_1\,\text{Reciprocity}_{ij}(t) +
\theta_2\,\text{Repetition}_{ij}(t)
\Big)
\]</span></p>
<p>where <span class="math inline">\(\lambda_{ij}(t \mid H_t)\)</span> denotes the rate at which actor <span class="math inline">\(i\)</span> directs an interaction to actor <span class="math inline">\(j\)</span> at time <span class="math inline">\(t\)</span>, given the event history <span class="math inline">\(H_t\)</span>. The statistics capture the following mechanisms:</p>
<ul>
<li><span class="math inline">\(\text{Reciprocity}_{ij}(t)\)</span> indicates whether the previous interaction was <span class="math inline">\(j \rightarrow i\)</span>.</li>
<li><span class="math inline">\(\text{Repetition}_{ij}(t)\)</span> indicates whether the previous interaction was <span class="math inline">\(i \rightarrow j\)</span>.</li>
</ul>
<section id="reciprocity-rrecsnd" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="reciprocity-rrecsnd">Reciprocity (<code>RRecSnd</code>)</h4>
<p>This effect captures whether characters tend to respond to someone who has just addressed them. In conversational settings, reciprocity reflects a basic turn-taking mechanism. If the previous interaction was <span class="math inline">\(i \rightarrow j\)</span>, a positive reciprocity effect indicates that the event <span class="math inline">\(j \rightarrow i\)</span> becomes more likely to occur next.</p>
<p>In the context of the <em>Frozen</em> dialogue network, a positive reciprocity coefficient implies that when one character speaks to another, the addressed character is more likely to respond directly.</p>
</section>
<section id="repetition-rsndsnd" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="repetition-rsndsnd">Repetition (<code>RSndSnd</code>)</h4>
<p>This effect captures the tendency for the same sender–receiver interaction to occur repeatedly. If the previous event was <span class="math inline">\(i \rightarrow j\)</span>, this statistic measures whether the same interaction <span class="math inline">\(i \rightarrow j\)</span> occurs again immediately afterward.</p>
<p>In conversational terms, repetition indicates that a speaker may continue addressing the same character across consecutive lines of dialogue.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">rem.dyad</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">edgelist =</span> edgelist,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_actors,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> <span class="fu">c</span>(<span class="st">"RRecSnd"</span>, <span class="st">"RSndSnd"</span>),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ordinal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">hessian =</span> <span class="cn">TRUE</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Prepping edgelist.
Checking/prepping covariates.
Computing preliminary statistics
Fitting model
Obtaining goodness-of-fit statistics</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Relational Event Model (Ordinal Likelihood)

        Estimate Std.Err Z value  Pr(&gt;|z|)    
RRecSnd  3.57036 0.14991  23.816 &lt; 2.2e-16 ***
RSndSnd  2.24439 0.13296  16.881 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Null deviance: 6879.697 on 661 degrees of freedom
Residual deviance: 3995.745 on 659 degrees of freedom
    Chi-square: 2883.952 on 2 degrees of freedom, asymptotic p-value 0 
AIC: 3999.745 AICC: 3999.763 BIC: 4008.732 </code></pre>
</div>
</div>
</section>
<section id="interpreting-the-coefficients" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="interpreting-the-coefficients">Interpreting the Coefficients</h4>
<p>The estimated coefficients reported in <code>summary(model1)</code> represent log-relative rates of events. A positive coefficient indicates that the corresponding interaction pattern increases the likelihood that a given event occurs next, while a negative coefficient indicates that it decreases that likelihood. Because the model uses a log-linear intensity formulation, coefficients can be interpreted multiplicatively: if a coefficient is <span class="math inline">\(\theta\)</span>, the corresponding event rate is multiplied by <span class="math inline">\(e^{\theta}\)</span> when the associated statistic increases by one unit. The argument <code>hessian = TRUE</code> instructs the model to compute the Hessian matrix, allowing standard errors and statistical tests to be obtained.</p>
<p>Both endogenous effects are positive and highly statistically significant. The estimated coefficient for reciprocity is 3.57 (<span class="math inline">\(SE = 0.15\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), indicating a strong tendency for characters to respond directly to those who have just spoken to them. Exponentiating the coefficient gives</p>
<p><span class="math display">\[
e^{3.57} \approx 35.6
\]</span></p>
<p>This means that a reciprocating interaction is estimated to be about 35 times more likely to occur next than it would be in the absence of this structural tendency, providing strong evidence of turn-taking dynamics in the <em>Frozen</em> dialogue network.</p>
<p>The estimated coefficient for repetition is 2.24 (<span class="math inline">\(SE = 0.13\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). Exponentiating this coefficient yields</p>
<p><span class="math display">\[
e^{2.24} \approx 9.4
\]</span></p>
<p>Thus, if the previous interaction was <span class="math inline">\(i \rightarrow j\)</span>, the same interaction occurring again immediately afterward is approximately nine times more likely than it would otherwise be. This suggests that once a conversational exchange begins between two characters, it often persists for multiple lines of dialogue.</p>
<p>Taken together, these results indicate that dialogue interactions in <em>Frozen</em> are strongly structured by basic conversational dynamics. Characters frequently respond directly to those who have just spoken to them, and conversations often continue between the same pair of characters across consecutive dialogue turns.</p>
</section>
</section>
<section id="model-2-gender-as-an-exogenous-covariate" class="level3" data-number="19.4.2">
<h3 data-number="19.4.2" class="anchored" data-anchor-id="model-2-gender-as-an-exogenous-covariate"><span class="header-section-number">19.4.2</span> Model 2: Gender as an Exogenous Covariate</h3>
<p>We now extend the previous model by incorporating gender as an exogenous actor-level covariate. The gender information is taken from the character data, where the variable <code>charfem</code> indicates whether a character is female (<code>1</code>) or not (<code>0</code>). This allows us to examine whether gender influences patterns of dialogue in the <em>Frozen</em> interaction network, while still accounting for the endogenous conversational dynamics captured in Model 1.</p>
<p>As before, the model includes reciprocity and repetition. In addition, it now allows the probability of an interaction to depend on the gender of the sender and the receiver.</p>
<p>The gender indicator is first constructed as an actor-level covariate aligned with the character IDs:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># female indicator by character ID</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>female <span class="ot">&lt;-</span> <span class="fu">matrix</span>(frozenchars<span class="sc">$</span>charfem[<span class="fu">order</span>(frozenchars<span class="sc">$</span>characterID)], <span class="at">ncol =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Formally, the event intensity for a potential interaction <span class="math inline">\(i \rightarrow j\)</span> at time <span class="math inline">\(t\)</span> is given by</p>
<p><span class="math display">\[
\begin{split}
\lambda_{ij}(t \mid H_t)  &amp; =
\lambda_0(t)\exp\Big(
\theta_1\,\text{Reciprocity}_{ij}(t) +
\theta_2\,\text{Repetition}_{ij}(t)   \\ &amp; \qquad \qquad \qquad
+\theta_3\,\text{SenderFemale}_{ij} +
\theta_4\,\text{ReceiverFemale}_{ij}
\Big)
\end{split}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\text{Reciprocity}_{ij}(t)\)</span> indicates whether the previous interaction was <span class="math inline">\(j \rightarrow i\)</span>,</li>
<li><span class="math inline">\(\text{Repetition}_{ij}(t)\)</span> indicates whether the previous interaction was <span class="math inline">\(i \rightarrow j\)</span>,</li>
<li><span class="math inline">\(\text{SenderFemale}_{ij}\)</span> equals 1 if the sender <span class="math inline">\(i\)</span> is female,</li>
<li><span class="math inline">\(\text{ReceiverFemale}_{ij}\)</span> equals 1 if the receiver <span class="math inline">\(j\)</span> is female.</li>
</ul>
<p>The parameters <span class="math inline">\(\theta_3\)</span> and <span class="math inline">\(\theta_4\)</span> therefore capture whether female characters are more or less likely to initiate dialogue or be addressed by others, respectively.</p>
<p>The sender gender effect (<code>CovSnd</code>) tests whether female characters are more likely to initiate interactions than male characters. A positive coefficient indicates that female characters speak more frequently to others, while a negative coefficient would suggest that male characters initiate dialogue more often.</p>
<p>The receiver gender effect (<code>CovRec</code>) tests whether female characters are more likely to be addressed by others. A positive coefficient indicates that interactions are more likely to target female characters.</p>
<p>Importantly, these effects are estimated while controlling for the conversational dynamics captured by reciprocity and repetition. This allows us to assess whether gender differences in dialogue persist after accounting for basic turn-taking behaviour and repeated exchanges between the same characters.</p>
<p>As in the previous model, the coefficients are expressed in log-relative rates, meaning that exponentiating a coefficient yields the multiplicative change in the event rate associated with a one-unit change in the corresponding statistic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># female indicator by character ID</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>female <span class="ot">&lt;-</span> <span class="fu">matrix</span>(frozenchars<span class="sc">$</span>charfem[<span class="fu">order</span>(frozenchars<span class="sc">$</span>characterID)], <span class="at">ncol =</span> <span class="dv">1</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">rem.dyad</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">edgelist =</span> edgelist,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_actors,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> <span class="fu">c</span>(<span class="st">"RRecSnd"</span>, <span class="st">"RSndSnd"</span>, <span class="st">"CovSnd"</span>, <span class="st">"CovRec"</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">covar =</span> <span class="fu">list</span>(</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">CovSnd =</span> female,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">CovRec =</span> female</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">ordinal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">hessian =</span> <span class="cn">TRUE</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Prepping edgelist.
Checking/prepping covariates.
Computing preliminary statistics
Fitting model
Obtaining goodness-of-fit statistics</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Relational Event Model (Ordinal Likelihood)

         Estimate  Std.Err Z value Pr(&gt;|z|)    
RRecSnd  3.669318 0.149300 24.5769   &lt;2e-16 ***
RSndSnd  2.171289 0.132459 16.3922   &lt;2e-16 ***
CovSnd.1 0.797349 0.082131  9.7083   &lt;2e-16 ***
CovRec.1 0.106776 0.085729  1.2455   0.2129    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Null deviance: 6879.697 on 661 degrees of freedom
Residual deviance: 3902.631 on 657 degrees of freedom
    Chi-square: 2977.066 on 4 degrees of freedom, asymptotic p-value 0 
AIC: 3910.631 AICC: 3910.692 BIC: 3928.606 </code></pre>
</div>
</div>
<section id="interpreting-the-coefficients-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="interpreting-the-coefficients-1">Interpreting the Coefficients</h4>
<p>The results of the relational event model including gender covariates can be summarized as follows.</p>
<p>The estimated coefficients again represent log-relative rates of events. As in the previous model, a positive coefficient indicates that the corresponding effect increases the likelihood that a particular interaction occurs next, while a negative coefficient indicates that it decreases that likelihood. Exponentiating a coefficient provides a multiplicative interpretation of the change in the event rate associated with a one-unit increase in the corresponding statistic.</p>
<p>The estimates indicate that the conversational dynamics identified in the previous model (reciprocity and repetition) remain strong and highly statistically significant even after accounting for gender effects.</p>
<p>The reciprocity coefficient is 3.67 (<span class="math inline">\(SE = 0.15\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), indicating a strong tendency for characters to respond directly to those who have just addressed them. Exponentiating the coefficient yields</p>
<p><span class="math display">\[
e^{3.67} \approx 39.3
\]</span></p>
<p>This implies that when a character <span class="math inline">\(i\)</span> speaks to character <span class="math inline">\(j\)</span>, the probability that the next interaction will be <span class="math inline">\(j \rightarrow i\)</span> is nearly forty times larger than it would otherwise be.</p>
<p>The repetition coefficient is 2.17 (<span class="math inline">\(SE = 0.13\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). Exponentiating this coefficient gives</p>
<p><span class="math display">\[
e^{2.17} \approx 8.8
\]</span></p>
<p>Thus, if the previous interaction was <span class="math inline">\(i \rightarrow j\)</span>, the same interaction occurring again immediately afterward is roughly nine times more likely than it would otherwise be. This indicates that conversations frequently continue between the same pair of characters across consecutive lines of dialogue.</p>
<p>Turning to the gender covariates, the sender gender coefficient is 0.80 (<span class="math inline">\(SE = 0.08\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), indicating that female characters are significantly more likely to initiate dialogue than male characters. Exponentiating the coefficient gives</p>
<p><span class="math display">\[
e^{0.80} \approx 2.22
\]</span></p>
<p>This suggests that, holding the conversational dynamics constant, interactions initiated by female characters occur at a rate that is approximately 2.2 times higher than those initiated by male characters.</p>
<p>The receiver gender coefficient is 0.11 (<span class="math inline">\(SE = 0.09\)</span>, <span class="math inline">\(p = 0.21\)</span>), which is not statistically significant. This indicates that there is no strong evidence that female characters are more or less likely to be addressed by others once conversational dynamics are taken into account.</p>
<p>Taken together, these results show that dialogue interactions in <em>Frozen</em> are shaped by both structural conversational dynamics and gender differences in speaking behavior. Turn-taking and repeated exchanges remain the dominant organizing mechanisms, while the gender covariate reveals that female characters are more likely to initiate dialogue within the interaction network.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Gender Dynamics in Dialogue Networks
</div>
</div>
<div class="callout-body-container callout-body">
<p>The finding that female characters are more likely to initiate dialogue is noteworthy in the context of film dialogue networks. In many films, speaking roles and conversational agency are disproportionately concentrated among male characters. A widely discussed indicator of this imbalance is the <a href="https://bechdeltest.com/"><strong>Bechdel Test</strong></a>, which evaluates whether a film contains at least two named female characters who speak to each other about something other than a man.</p>
<p>Many films fail to satisfy even this minimal criterion, highlighting the limited presence and interaction of female characters in cinematic narratives. Against this backdrop, the <em>Frozen</em> dialogue network presents a somewhat unusual pattern: female characters not only appear frequently but also play an active role in initiating interactions.</p>
<p>While this analysis does not directly test the Bechdel criterion, the strong sender gender effect suggests that female characters occupy central conversational roles within the narrative. This aligns with the broader narrative structure of <em>Frozen</em>, which centers on the relationship between its two main female protagonists.</p>
</div>
</div>
</section>
</section>
<section id="model-3-gender-interaction-effects" class="level3" data-number="19.4.3">
<h3 data-number="19.4.3" class="anchored" data-anchor-id="model-3-gender-interaction-effects"><span class="header-section-number">19.4.3</span> Model 3: Gender Interaction Effects</h3>
<p>We now extend the previous specification by allowing the gender of the sender and receiver to interact. While Model 2 examined whether female characters are more likely to initiate or receive dialogue, this model additionally tests whether interactions between female characters occur at a different rate than would be expected from the sender and receiver effects alone.</p>
<p>As before, the model includes the endogenous conversational dynamics captured by reciprocity and repetition. In addition, it now includes a gender interaction effect that captures whether interactions between two female characters are more or less likely than other interactions.</p>
<p>Formally, the event intensity for a potential interaction <span class="math inline">\(i \rightarrow j\)</span> at time <span class="math inline">\(t\)</span> is given by</p>
<p><span class="math display">\[
\begin{split}
\lambda_{ij}(t \mid H_t) &amp; =
\lambda_0(t)\exp\Big(
\theta_1\,\text{Reciprocity}_{ij}(t) +
\theta_2\,\text{Repetition}_{ij}(t)  \\ &amp; \qquad \qquad \qquad
+ \theta_3\,\text{SenderFemale}_{ij} +
\theta_4\,\text{ReceiverFemale}_{ij} +
\theta_5\,\text{FemaleInteraction}_{ij}
\Big)
\end{split}
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\text{Reciprocity}_{ij}(t)\)</span> indicates whether the previous interaction was <span class="math inline">\(j \rightarrow i\)</span>,</li>
<li><span class="math inline">\(\text{Repetition}_{ij}(t)\)</span> indicates whether the previous interaction was <span class="math inline">\(i \rightarrow j\)</span>,</li>
<li><span class="math inline">\(\text{SenderFemale}_{ij}\)</span> equals 1 if the sender <span class="math inline">\(i\)</span> is female,</li>
<li><span class="math inline">\(\text{ReceiverFemale}_{ij}\)</span> equals 1 if the receiver <span class="math inline">\(j\)</span> is female,</li>
<li><span class="math inline">\(\text{FemaleInteraction}_{ij}\)</span> equals 1 if both the sender and receiver are female.</li>
</ul>
<p>The interaction effect therefore captures whether conversations between female characters occur more or less frequently than would be expected based solely on sender and receiver gender effects.</p>
<p>The sender gender effect (<code>CovSnd</code>) continues to test whether female characters are more likely to initiate dialogue, while the receiver gender effect (<code>CovRec</code>) captures whether female characters are more likely to be addressed. The interaction effect (<code>CovInt</code>) captures whether interactions between female characters occur at a higher or lower rate than would be expected from these individual effects.</p>
<p>Importantly, these effects are estimated while controlling for the conversational dynamics captured by reciprocity and repetition. This allows us to examine whether gender-based interaction patterns persist once basic conversational mechanisms are taken into account.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">rem.dyad</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">edgelist =</span> edgelist,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_actors,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> <span class="fu">c</span>(<span class="st">"RRecSnd"</span>, <span class="st">"RSndSnd"</span>, <span class="st">"CovSnd"</span>, <span class="st">"CovRec"</span>, <span class="st">"CovInt"</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">covar =</span> <span class="fu">list</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">CovSnd =</span> female,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">CovRec =</span> female,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">CovInt =</span> female</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ordinal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">hessian =</span> <span class="cn">TRUE</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Prepping edgelist.
Checking/prepping covariates.
Computing preliminary statistics
Fitting model
Obtaining goodness-of-fit statistics</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Relational Event Model (Ordinal Likelihood)

         Estimate  Std.Err Z value Pr(&gt;|z|)    
RRecSnd   3.66899  0.14930 24.5739   &lt;2e-16 ***
RSndSnd   2.17218  0.13247 16.3972   &lt;2e-16 ***
CovSnd.1  0.49632 50.14947  0.0099   0.9921    
CovRec.1 -0.19450 50.14947 -0.0039   0.9969    
CovInt.1  0.30067 50.14945  0.0060   0.9952    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Null deviance: 6879.697 on 661 degrees of freedom
Residual deviance: 3902.631 on 656 degrees of freedom
    Chi-square: 2977.066 on 5 degrees of freedom, asymptotic p-value 0 
AIC: 3912.631 AICC: 3912.723 BIC: 3935.1 </code></pre>
</div>
</div>
<section id="interpreting-the-coefficients-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="interpreting-the-coefficients-2">Interpreting the Coefficients</h4>
<p>The interpretation of the coefficients follows the same logic as in the previous models. The estimated parameters represent log-relative rates of events. A positive coefficient indicates that the corresponding effect increases the likelihood that an interaction occurs next, while a negative coefficient indicates that it decreases that likelihood. Exponentiating a coefficient yields the multiplicative change in the event rate associated with a one-unit increase in the corresponding statistic.</p>
<p>The estimates show that the conversational dynamics identified in the previous models remain strong and highly statistically significant. The reciprocity coefficient is 3.67 (<span class="math inline">\(SE = 0.15\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), indicating a strong tendency for characters to respond directly to those who have just addressed them. Exponentiating the coefficient gives</p>
<p><span class="math display">\[
e^{3.67} \approx 39.3
\]</span></p>
<p>This implies that when a character <span class="math inline">\(i\)</span> speaks to character <span class="math inline">\(j\)</span>, the probability that the next interaction will be <span class="math inline">\(j \rightarrow i\)</span> is nearly forty times larger than it would otherwise be.</p>
<p>The repetition coefficient is 2.17 (<span class="math inline">\(SE = 0.13\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). Exponentiating this coefficient yields</p>
<p><span class="math display">\[
e^{2.17} \approx 8.8
\]</span></p>
<p>Thus, if the previous interaction was <span class="math inline">\(i \rightarrow j\)</span>, the same interaction occurring again immediately afterward is roughly nine times more likely than it would otherwise be. This again indicates that conversations frequently continue between the same pair of characters across consecutive dialogue turns.</p>
<p>Turning to the gender covariates, none of the gender-related effects are statistically significant in this specification. The estimated sender gender coefficient is 0.50 (<span class="math inline">\(SE = 51.83\)</span>, <span class="math inline">\(p = 0.99\)</span>), the receiver gender coefficient is <span class="math inline">\(-0.20\)</span> (<span class="math inline">\(SE = 51.83\)</span>, <span class="math inline">\(p = 0.997\)</span>), and the gender interaction coefficient is 0.30 (<span class="math inline">\(SE = 51.83\)</span>, <span class="math inline">\(p = 0.995\)</span>). The extremely large standard errors indicate that these parameters are estimated with very high uncertainty in this model.</p>
<p>Substantively, this suggests that once the interaction effect between sender and receiver gender is introduced, the model is unable to distinguish clear gender-based patterns in the dialogue sequence. In contrast to Model 2, where female characters appeared more likely to initiate dialogue, the additional interaction term absorbs much of the variation associated with gender and results in unstable estimates for the gender effects.</p>
<p>Taken together, these results reinforce the conclusion that the primary structure of the dialogue network is driven by conversational dynamics (specifically reciprocity and repetition) while gender-based interaction patterns are not strongly identified once interaction effects are included in the model.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Contextual Covariates in Relational Event Models
</div>
</div>
<div class="callout-body-container callout-body">
<p>In addition to endogenous network statistics and actor attributes, relational event models can also incorporate contextual covariates when such information is available. Contextual covariates capture features of the environment or situation in which interactions occur and allow researchers to examine how interaction patterns vary across different settings.</p>
<p>In the <code>relevent</code> package, such variables can be included using the <code>CovEvent</code> effect. Event-level covariates describe characteristics of the interaction context at a particular point in time rather than attributes of the actors involved.</p>
<p>For example, in studies of classroom interaction networks, contextual variables might include the structure of the lesson (e.g., lecture, group work, or discussion), the phase of an activity, or the seating arrangement of students. These contextual factors may influence who interacts with whom and how conversational dynamics unfold over time.</p>
<p>When included in the model, the event intensity can be written as</p>
<p><span class="math display">\[
\lambda_{ij}(t \mid H_t) =
\lambda_0(t)\exp\Big(
\theta_1\,\text{Reciprocity}_{ij}(t) +
\theta_2\,\text{Repetition}_{ij}(t) +
\theta_3\,\text{Context}_t
\Big)
\]</span></p>
<p>where <span class="math inline">\(\text{Context}_t\)</span> represents an event-level covariate capturing features of the situation at time <span class="math inline">\(t\)</span>.</p>
<p>In practice, such variables are included in <code>relevent</code> using the <code>CovEvent</code> term in the <code>effects</code> argument and supplying the corresponding event-level covariate through the <code>covar</code> list. For example:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rem.dyad</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">edgelist =</span> edgelist,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_actors,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> <span class="fu">c</span>(<span class="st">"RRecSnd"</span>, <span class="st">"RSndSnd"</span>, <span class="st">"CovEvent"</span>),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">covar =</span> <span class="fu">list</span>(<span class="at">CovEvent =</span> context_variable),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ordinal =</span> <span class="cn">TRUE</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Including contextual covariates (<code>context_variable</code> in above code) allows relational event models to move beyond purely structural explanations of interaction sequences and to account for how social behaviour is shaped by situational or institutional conditions.</p>
</div>
</div>
</section>
</section>
<section id="assessing-goodnes-of-fit" class="level3" data-number="19.4.4">
<h3 data-number="19.4.4" class="anchored" data-anchor-id="assessing-goodnes-of-fit"><span class="header-section-number">19.4.4</span> Assessing Goodnes of Fit</h3>
<p>After estimating the relational event models, it is useful to evaluate how well they reproduce the observed interaction sequence. Information criteria such as the Bayesian Information Criterion (BIC) can provide evidence about whether one model is preferred to another, but they do not directly indicate how well the model predicts the sequence of interaction events. To better understand model performance, we can examine both the predicted interactions and the residuals.</p>
<section id="actual-vs.-predicted" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="actual-vs.-predicted">Actual vs.&nbsp;Predicted</h4>
<p>For illustration, we focus on Model 3, the most complete specification including reciprocity, repetition, and gender effects. One useful component of the model output is the object <code>predicted.match</code>, which records whether the model correctly predicts the sender and receiver for each observed event.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(model3<span class="sc">$</span>predicted.match)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sender receiver
1   TRUE     TRUE
2  FALSE    FALSE
3   TRUE     TRUE
4   TRUE     TRUE
5  FALSE    FALSE
6   TRUE     TRUE</code></pre>
</div>
</div>
<p>Each row corresponds to an observed interaction in the dialogue sequence. The first column indicates whether the model correctly predicted the sender of the event, and the second column indicates whether it correctly predicted the receiver. Because the relational event model is trying to predict the exact sequence of interactions, this is a strict criterion: a prediction is fully correct only when both the sender and the receiver are correctly identified.</p>
<p>To summarize predictive accuracy, we can tabulate the sender and receiver matches.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>send_col <span class="ot">&lt;-</span> model3<span class="sc">$</span>predicted.match[, <span class="st">"sender"</span>]</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>receive_col <span class="ot">&lt;-</span> model3<span class="sc">$</span>predicted.match[, <span class="st">"receiver"</span>]</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(send_col, receive_col)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        receive_col
send_col FALSE TRUE
   FALSE   370  135
   TRUE     13  143</code></pre>
</div>
</div>
<p>This table indicates how often the model correctly predicts the sender, the receiver, both, or neither for each interaction event.</p>
<p>In 143 cases the model correctly predicts both the sender and the receiver, meaning that it successfully reproduces the exact interaction in the event sequence. In 370 cases the model fails to correctly identify either the sender or the receiver, indicating interactions that are poorly captured by the current specification. There are also cases where the model predicts only one component correctly: in 13 events the sender is predicted correctly but the receiver is not, while in 135 events the receiver is predicted correctly but the sender is not.</p>
<p>To better understand these proportions, we can convert the table into relative frequencies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(send_col, receive_col))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        receive_col
send_col      FALSE       TRUE
   FALSE 0.55975794 0.20423601
   TRUE  0.01966717 0.21633888</code></pre>
</div>
</div>
<p>These results show that the model exactly predicts both the sender and receiver in roughly 22% of the dialogue events, while in approximately 56% of cases it fails to predict either component correctly. In the remaining events, the model correctly identifies either the sender or the receiver but not both.</p>
<p>Overall, these results suggest that the model captures some important aspects of the interaction dynamics but still misses a substantial portion of the variation in the dialogue sequence. This is not surprising, as the model includes only a limited set of explanatory mechanisms—namely reciprocity, repetition, and gender effects. Additional factors, such as narrative context, scene structure, or character roles within the story, may influence the interaction sequence and could potentially improve predictive performance if incorporated into the model.</p>
</section>
<section id="residual-diagnostics" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="residual-diagnostics">Residual Diagnostics</h4>
<p>Another way to assess the goodness of fit of a relational event model is by examining the residuals. Residuals measure the discrepancy between the observed interaction and the interaction that the model would predict given the event history and the included covariates. Large residual values therefore indicate events that were substantially more or less likely than expected under the model.</p>
<p>A useful first step is to examine a summary of the residual distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3<span class="sc">$</span>residuals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.678   3.320   4.646   5.904   6.944  17.265 </code></pre>
</div>
</div>
<p>The summary provides an overview of the range and distribution of residuals across the event sequence. While many events will typically have residuals close to zero, larger values may indicate interactions that the model has difficulty explaining.</p>
<p>To identify potential outliers, we can locate events with particularly large residuals. For illustration, we define outlying cases as those with residuals greater than 10.</p>
<p>The summary provides an overview of the range and distribution of residuals across the event sequence. While many events will typically have residuals close to zero, larger values may indicate interactions that the model has difficulty explaining.</p>
<p>To identify potential outliers, we can locate events with particularly large residuals. For illustration, we define outlying cases as those with residuals greater than 12 (<span class="math inline">\(\approx  Q_3 + 1.5 \times IQR)\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>high_resids <span class="ot">&lt;-</span> <span class="fu">which</span>(model3<span class="sc">$</span>residuals <span class="sc">&gt;</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>These indices correspond to the positions of events in the event sequence where the observed interaction deviates strongly from the model’s predictions. We can inspect these events directly in the event list.</p>
<p>A visualization of the residual distribution and this threshold is shown below in <a href="#fig-rem-residuals" class="quarto-xref">Figure&nbsp;<span>19.2</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rem-residuals" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rem-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="rem_files/figure-html/fig-rem-residuals-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rem-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19.2: Distribution of residuals from Model 3 of the relational event model. The red vertical line indicates the threshold (residual = 12) used to identify unusually poorly predicted interaction events.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>edgelist[high_resids, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    time sender receiver
12    12      1        3
18    18      2        4
19    19      2        5
21    21      5        1
24    24      2        5
25    25      5        4
27    27      7        6
28    28      8        4
31    31      8        5
34    34      8        5
35    35      2        8
44    44      1        4
50    50      9        1
59    59     10        1
85    85      9        2
86    86     11        9
87    87     11        2
92    92     11        1
126  126     10        2
176  176     10       11
191  191     12        1
196  196     12        6
197  197      6        1
201  201     12        6
291  291      3        6
340  340     13       10
392  392      1        2
404  404      3        2
429  429      1       14
430  430      3       14
431  431     14        1
433  433     14        6
434  434      1        3
436  436      3        6
442  442      3        6
465  465      3        6
468  468     14        6
517  517      7        1
519  519      6        7
523  523      8        6
526  526      8        1
533  533      6        3
535  535     14       10
536  536     10        2
551  551     13        1
554  554      6        9
555  555      6       13
558  558      6       13
559  559      9       10
560  560     10        1
565  565     13       10
588  588     10       11
623  623     10        2
643  643      9       11
645  645      1        6
658  658      1        2</code></pre>
</div>
</div>
<p>Examining such cases can help identify systematic patterns that are not adequately captured by the model specification. For example, certain characters may appear disproportionately often in events with large residuals, suggesting that their interaction behavior differs from what would be expected based on the included effects.</p>
<p>Residual diagnostics can therefore be a useful tool for guiding further model development. If particular actors, dyads, or types of interactions repeatedly appear among the high-residual cases, this may indicate the need to include additional actor attributes, dyadic covariates, or contextual variables in the model. In narrative interaction networks such as film dialogue, for instance, conversational patterns may also be shaped by scene structure, narrative roles, or other contextual factors that are not currently included in the model.</p>
</section>
<section id="comparing-model-specifications" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="comparing-model-specifications">Comparing Model Specifications</h4>
<p>To compare the three model specifications, we examine their Bayesian Information Criterion (BIC) values. The BIC provides a measure of model fit that penalizes model complexity, meaning that lower values indicate a better balance between explanatory power and the number of estimated parameters.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model1_BIC =</span> model1<span class="sc">$</span>BIC,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model2_BIC =</span> model2<span class="sc">$</span>BIC,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model3_BIC =</span> model3<span class="sc">$</span>BIC</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model1_BIC Model2_BIC Model3_BIC 
  4008.732   3928.606   3935.100 </code></pre>
</div>
</div>
<p>The results show a substantial improvement in model fit when moving from Model 1 to Model 2. The BIC decreases from 4008.73 to 3928.61, indicating that including gender as an actor-level covariate significantly improves the model’s ability to explain the dialogue interactions.</p>
<p>By contrast, Model 3, which additionally includes the interaction between sender and receiver gender, produces a slightly higher BIC (3935.10) than Model 2. Because the BIC penalizes additional parameters,</p>
<p>Taken together, prediction accuracy, residual diagnostics, and information criteria provide a comprehensive picture of model performance. These tools help identify whether the model adequately captures the dynamics of the dialogue network and highlight potential directions for further model refinement.</p>


</section>
</section>
</section>
<section id="bibliography" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-butts2008" class="csl-entry" role="listitem">
Butts, Carter T. 2008. <span>“4. A Relational Event Framework for Social Action.”</span> <em>Sociological Methodology</em> 38 (1): 155–200.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/schochastics\.io\/R4SNA");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../inferential/saom.html" class="pagination-link" aria-label="Stochastic Actor Oriented Models (SAOMs)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Stochastic Actor Oriented Models (SAOMs)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../tidy/introduction.html" class="pagination-link" aria-label="Introduction">
        <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Introduction</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>R for Social Network Analysis was written by Termeh Shafie and David Schoch.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/schochastics/R4SNA/edit/main/inferential/rem.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/schochastics/R4SNA/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>