<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Termeh Shafie and David Schoch">

<title>18&nbsp; Stochastic Actor Oriented Models (SAOMs) – R for Social Network Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../inferential/rem.html" rel="next">
<link href="../inferential/ergm.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-87b7f55de2e0c9887283481eb31a794c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="18&nbsp; Stochastic Actor Oriented Models (SAOMs) – R for Social Network Analysis">
<meta property="og:description" content="">
<meta property="og:image" content="https://schochastics.io/R4SNA/inferential/img/‎‎saom-state-ex.png">
<meta property="og:site_name" content="R for Social Network Analysis">
<meta property="og:image:height" content="596">
<meta property="og:image:width" content="1869">
<meta name="twitter:title" content="18&nbsp; Stochastic Actor Oriented Models (SAOMs) – R for Social Network Analysis">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://schochastics.io/R4SNA/inferential/img/‎‎saom-state-ex.png">
<meta name="twitter:image-height" content="596">
<meta name="twitter:image-width" content="1869">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../inferential/introduction.html">Inferential Network Analysis</a></li><li class="breadcrumb-item"><a href="../inferential/saom.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Stochastic Actor Oriented Models (SAOMs)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">R for Social Network Analysis</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/schochastics/R4SNA" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../network-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Data and Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Descriptive Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/descriptives-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Basic Network Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/centrality-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Centrality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Cohesive Subgroups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/two-mode-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-Mode Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/signed-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Signed Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/ego-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ego Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/netropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Entropy Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Network Visualization</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/ggraph-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Basics of ggraph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/ggraph-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Advanced Layouts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/enhance-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Enhancing Visualizations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/interactive-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Interactive Visualization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Inferential Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/non-parametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Non-Parametric Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/rgm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Random Graph Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/ergm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Exponential Random Graph Models (ERGMs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/saom.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Stochastic Actor Oriented Models (SAOMs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/rem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Relational Event Models (REMs)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Tidy Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/tidygraph-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Basics of tidygraph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/tidygraph-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Descriptive Network Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/ucnets-egor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Creating the UCNets Ego Network Dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/cat-ex-saoms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">A Continuous-Time Markov Chain (Cat Behavior Model)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/rem-frozen-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Creating Relational Event Data for the Frozen Character Network</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#packages-needed-for-this-chapter" id="toc-packages-needed-for-this-chapter" class="nav-link active" data-scroll-target="#packages-needed-for-this-chapter"><span class="header-section-number">18.1</span> Packages Needed for this Chapter</a></li>
  <li><a href="#running-example-teenage-friends-and-lifestyle-study" id="toc-running-example-teenage-friends-and-lifestyle-study" class="nav-link" data-scroll-target="#running-example-teenage-friends-and-lifestyle-study"><span class="header-section-number">18.2</span> Running Example: Teenage Friends and Lifestyle Study</a></li>
  <li><a href="#saom-framework" id="toc-saom-framework" class="nav-link" data-scroll-target="#saom-framework"><span class="header-section-number">18.3</span> SAOM Framework</a></li>
  <li><a href="#extending-saoms-the-co-evolution-of-networks-and-behavior" id="toc-extending-saoms-the-co-evolution-of-networks-and-behavior" class="nav-link" data-scroll-target="#extending-saoms-the-co-evolution-of-networks-and-behavior"><span class="header-section-number">18.4</span> Extending SAOMs: The Co-Evolution of Networks and Behavior</a></li>
  <li><a href="#estimating-saoms-in-rsiena" id="toc-estimating-saoms-in-rsiena" class="nav-link" data-scroll-target="#estimating-saoms-in-rsiena"><span class="header-section-number">18.5</span> Estimating SAOMs in RSiena</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">References</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/schochastics/R4SNA/edit/main/inferential/saom.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/schochastics/R4SNA/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../inferential/introduction.html">Inferential Network Analysis</a></li><li class="breadcrumb-item"><a href="../inferential/saom.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Stochastic Actor Oriented Models (SAOMs)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-saom" class="quarto-section-identifier"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Stochastic Actor Oriented Models (SAOMs)</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Up to this point, we have focused on modeling social networks as <strong>cross-sectional data</strong>, that is, as static snapshots of tie patterns observed at a single point in time. Models such as Erdős–Rényi, preferential attachment, and Exponential Random Graph Models (ERGMs) allow us to account for structural dependencies, attribute effects, and network complexity within such static networks.</p>
<p>However, social networks are inherently dynamic. Ties are not fixed; they emerge, dissolve, and evolve through time as a result of decisions made by individual actors. Treating network data as static ignores this core aspect of social life. A more realistic modeling approach must account for the sequential, actor-driven nature of network evolution.</p>
<p>This brings us to <strong>Stochastic Actor-Oriented Models (SAOMs)</strong>, a class of models explicitly designed for <strong>longitudinal network data</strong>. Unlike cross-sectional models that treat the network as a single outcome, SAOMs treat the network as a continuous-time stochastic process driven by individual actor decisions. In this framework, changes to the network occur one tie at a time, reflecting micro-level decisions made by actors based on preferences, opportunities, and constraints.</p>
<p>SAOMs are particularly well-suited for panel data, i.e., multiple observations of the same network over time where both tie structures and actor attributes may co-evolve. This allows researchers to address questions such as:</p>
<ul>
<li>How often do actors initiate or terminate ties?</li>
<li>Do actors prefer to form ties based on similarity (selection) or become more similar after forming ties (influence)?</li>
<li>How do structural tendencies like reciprocity or transitivity manifest through sequential decision-making?</li>
<li>Can we simulate or predict how the network may evolve in future time points?</li>
</ul>
<p>SAOMs are one of two main frameworks for dynamic network modeling. The other is the <strong>Temporal Exponential Random Graph Model (TERGM)</strong>. While TERGMs extend ERGMs to panel data by conditioning on past networks, SAOMs take a process-based view that explicitly models <em>how</em> ties change over time due to actor decisions.</p>
<p><a href="#tbl-ergmsaom" class="quarto-xref">Table&nbsp;<span>18.1</span></a> shows the core differences between ERGMs. While ERGMs model the global structure of a network at a single point in time, SAOMs treat network evolution as a dynamic process driven by actors making sequential decisions. In other words, SAOMs extend the logic of ERGMs into the temporal domain, capturing the mechanisms of change rather than just the final structure.</p>
<div id="tbl-ergmsaom" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ergmsaom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.1: Comparison between Exponential Random Graph Models (ERGMs) and Stochastic Actor-Oriented Models (SAOMs). The two approaches differ in their treatment of time, unit of analysis, estimation, and interpretation.
</figcaption>
<div aria-describedby="tbl-ergmsaom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 36%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th>ERGMs</th>
<th>SAOMs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Data type</strong></td>
<td>Cross-sectional (static snapshot)</td>
<td>Longitudinal (panel data, repeated observations)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Unit of analysis</strong></td>
<td>The entire network</td>
<td>Individual actor decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Modeling approach</strong></td>
<td>Statistical dependence among ties</td>
<td>Actor-based tie change process</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Time modeling</strong></td>
<td>No time dimension</td>
<td>Continuous-time change process</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Common mechanisms</strong></td>
<td>Reciprocity, transitivity, nodal covariates</td>
<td>Same, but expressed as actor preferences over changes</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Estimation method</strong></td>
<td>MCMC Maximum Likelihood (MCMCMLE)</td>
<td>Simulation-based Method of Moments (MoM)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Outcome</strong></td>
<td>Probability of the observed network</td>
<td>Simulated network trajectories over time</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>In R</strong></td>
<td><code>ergm</code> (or <code>statnet</code>)</td>
<td><code>RSiena</code></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In what follows, we focus on the SAOM framework, its components, estimation process, and how it can be used to explain and simulate network evolution.</p>
<section id="packages-needed-for-this-chapter" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="packages-needed-for-this-chapter"><span class="header-section-number">18.1</span> Packages Needed for this Chapter</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(graphlayouts)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(networkdata)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(intergraph)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RSiena)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="running-example-teenage-friends-and-lifestyle-study" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="running-example-teenage-friends-and-lifestyle-study"><span class="header-section-number">18.2</span> Running Example: Teenage Friends and Lifestyle Study</h2>
<p>We use a running example with data from the “Teenage Friends and Lifestyle Study” <span class="citation" data-cites="west1996s50">(<a href="#ref-west1996s50" role="doc-biblioref">West and Sweeting 1996</a>)</span>, which was also used in the previous chapter on ERGMs. In contrast to the earlier example that focused on a single time point and only the subset of 50 pupils, we here model the dynamics of friendship ties across all three observed waves and with the 129 pupils over all three time points, and including relevant actor-level covariates such as gender and smoking behavior. The dataset is called <code>glasgow129</code> in the <code>networkdata</code> package, which includes the following:</p>
<ul>
<li>Networks: Binary, directed friendship ties measured at three time points.</li>
<li>Actors: 129 pupils measured at three time points.</li>
<li>Many covariates, but we focus on
<ul>
<li>Sex: 1 = Male, 2 = Female</li>
<li>Smoking: 1 = No, 2 = Occasional, 3 = Regular</li>
</ul></li>
</ul>
<p>We load the data from the <code>networkdata</code> package and extract an <code>igraph</code> object for each time period.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"glasgow129"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data as graph object from networkdata and extract all three wave networks</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>glasgow_g1 <span class="ot">&lt;-</span> glasgow129[[<span class="dv">1</span>]]</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>glasgow_g2 <span class="ot">&lt;-</span> glasgow129[[<span class="dv">2</span>]]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>glasgow_g3 <span class="ot">&lt;-</span> glasgow129[[<span class="dv">3</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>These <code>igraph</code> objects are our network snapshots and consider various SAOMs. We begin by converting each network snapshot into a binary adjacency matrix. These matrices represent the presence or absence of directed ties between actors at each time point.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to adjacency matrices</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>net1 <span class="ot">&lt;-</span> <span class="fu">as_adjacency_matrix</span>(glasgow_g1, <span class="at">sparse =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>net2 <span class="ot">&lt;-</span> <span class="fu">as_adjacency_matrix</span>(glasgow_g2, <span class="at">sparse =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>net3 <span class="ot">&lt;-</span> <span class="fu">as_adjacency_matrix</span>(glasgow_g3, <span class="at">sparse =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We then combine them into a 3-dimensional array with dimensions <code>[actor × actor × wave]</code>, which is the required format for longitudinal network data in <code>RSiena</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into 3D array [actor x actor x wave]</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>net_array <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="fu">c</span>(net1, net2, net3), <span class="at">dim =</span> <span class="fu">c</span>(<span class="dv">129</span>, <span class="dv">129</span>, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="saom-framework" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="saom-framework"><span class="header-section-number">18.3</span> SAOM Framework</h2>
<section id="modeling-network-evolution" class="level3" data-number="18.3.1">
<h3 data-number="18.3.1" class="anchored" data-anchor-id="modeling-network-evolution"><span class="header-section-number">18.3.1</span> Modeling Network Evolution</h3>
<p>Most real-world social networks are dynamic systems. Relationships between individuals form, dissolve, and evolve as a result of ongoing social interactions, personal decisions, and contextual factors. When we observe a single snapshot of a network, we can only speculate about the processes that produced it. By contrast, longitudinal network data, repeated observations of a network over time, allow us to move from static description to dynamic explanation.</p>
<p>Longitudinal network data consist of a set of actors <span class="math inline">\(N = \{1, 2, \dots, n\}\)</span> and a series of observed adjacency matrices: <span class="math display">\[
Y(t_0),\ Y(t_1),\ \dots,\ Y(t_M)
\]</span> where each matrix captures the presence or absence of ties between actors at a particular time point, that is <span class="math inline">\(y_{ij}(t) = 1\)</span> if actor <span class="math inline">\(i\)</span> has a tie to actor <span class="math inline">\(j\)</span> at time <span class="math inline">\(t\)</span>, and <span class="math inline">\(y_{ij}(t) = 0\)</span> otherwise.</p>
<p>These repeated measures make it possible to ask and answer key questions:</p>
<ul>
<li>How frequently do actors change their ties?</li>
<li>What drives the formation, maintenance, or dissolution of ties?</li>
<li>How do individual attributes (e.g., gender, age, group membership) shape network dynamics?</li>
<li>Can we predict how the network will evolve in the future?</li>
<li>How do both endogenous (network-based) and exogenous (attribute-based) factors jointly shape the network?</li>
</ul>
<p>Moreover, understanding <em>why</em> networks change requires distinguishing between competing explanations. For instance, if we observe that two similar actors are connected at time <span class="math inline">\(t_1\)</span>, this might reflect selection (they formed a tie because of their similarity) or influence (they became similar after forming a tie). Only a longitudinal framework allows us to tease apart these mechanisms.</p>
<p>Time also matters for structural tendencies. Consider transitivity: when we observe a triadic closure (i.e., if <span class="math inline">\(i\)</span> is tied to <span class="math inline">\(j\)</span> and <span class="math inline">\(j\)</span> to <span class="math inline">\(\ell\)</span>, then <span class="math inline">\(i\)</span> may become tied to <span class="math inline">\(\ell\)</span>), we cannot know whether it reflects an intentional closure or merely a residual pattern without knowing the order in which ties appeared.</p>
<p>Stochastic Actor-Oriented Models (SAOMs) offer a solution by treating network change as a <strong>continuous-time, actor-driven process</strong>. In this framework:</p>
<ul>
<li>The network evolves through a sequence of micro-steps where individual actors have opportunities to change their outgoing ties.</li>
<li>Each actor evaluates the current network and makes decisions based on preferences (e.g., for reciprocation, closure, or similarity).</li>
<li>The model simulates the timing and direction of these changes between observation moments (waves).</li>
</ul>
<p>This actor-oriented perspective aligns closely with how ties form in real life: individuals decide whom to connect with (or disconnect from), guided by structural cues and attribute-based tendencies.</p>
</section>
<section id="stochastic-processes-and-continuous-time-markov-chains" class="level3" data-number="18.3.2">
<h3 data-number="18.3.2" class="anchored" data-anchor-id="stochastic-processes-and-continuous-time-markov-chains"><span class="header-section-number">18.3.2</span> Stochastic Processes and Continuous-Time Markov Chains</h3>
<p>To understand the dynamics of network evolution in Stochastic Actor-Oriented Models (SAOMs), it is helpful to first grasp the concept of a <strong>stochastic process</strong>, a collection of random variables indexed by time:</p>
<p><span class="math display">\[
\{ X(t),\ t \in T \}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(T\)</span> is the index set (typically representing time),</li>
<li><span class="math inline">\(S\)</span> is the <strong>state space</strong>, the set of all possible values that <span class="math inline">\(X(t)\)</span> can take.</li>
</ul>
<p>In the context of longitudinal network analysis, the stochastic process represents the network evolving over time. That is, we can interpret the state as the network at time <span class="math inline">\(t\)</span>, so that</p>
<p><span class="math display">\[
X(t) \equiv Y(t),
\]</span></p>
<p>where <span class="math inline">\(Y(t)\)</span> is the adjacency matrix at time <span class="math inline">\(t\)</span>, with entries <span class="math inline">\(y_{ij}(t) \in \{0,1\}\)</span> indicating whether a tie from actor <span class="math inline">\(i\)</span> to actor <span class="math inline">\(j\)</span> is present at time <span class="math inline">\(t\)</span>.</p>
<p>SAOMs are based on a particular type of stochastic process: the <strong>continuous-time Markov chain (CTMC)</strong>. A CTMC is defined by:</p>
<ol type="1">
<li>A finite <strong>state space</strong> <span class="math inline">\(S\)</span> (e.g., all possible network configurations),</li>
<li>A <strong>continuous time domain</strong> <span class="math inline">\(t \in [0, \infty)\)</span>,</li>
<li>The <strong>Markov property</strong>, which states that the future state depends only on the present state, not on the past:</li>
</ol>
<p><span class="math display">\[
P\bigl(X(t_j) = s_j \mid \{X(t): t \le t_i\}\bigr)
=
P\bigl(X(t_j) = s_j \mid X(t_i) = s_i\bigr)
\]</span></p>
<p>This <strong>memoryless</strong> property implies that future network evolution depends only on the current configuration. In the context of SAOMs, actors make tie changes based solely on the present network structure (e.g., existing ties, shared partners, or attributes), without direct dependence on earlier configurations.</p>
<p>The CTMC evolves through a sequence of randomly timed transitions. Each state is held for a random duration, and transitions to the next state are governed by probability. More formally, a CTMC is characterized by:</p>
<ul>
<li>When a change occurs: governed by the holding time, typically modeled with an exponential distribution.</li>
<li>What the next state is: determined by the jump matrix, which specifies the transition probabilities between states.</li>
</ul>
<p>Together, <strong>holding time</strong> and <strong>jump probabilities</strong> define the full behavior of the CTMC.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A continuous-time Markov chain can be understood as a process that waits in a state for a random holding time and then jumps to a new state. The cat example in <a href="../appendix/cat-ex-saoms.html" class="quarto-xref"><span>Appendix B</span></a> illustrates this intuition.</p>
</div>
</div>
</section>
<section id="network-states-and-the-markov-property" class="level3" data-number="18.3.3">
<h3 data-number="18.3.3" class="anchored" data-anchor-id="network-states-and-the-markov-property"><span class="header-section-number">18.3.3</span> Network States and the Markov Property</h3>
<p>Stochastic Actor-Oriented Models (SAOMs), introduced by <span class="citation" data-cites="snijders1996stochastic">Snijders (<a href="#ref-snijders1996stochastic" role="doc-biblioref">1996</a>)</span>, provide a principled framework for analyzing how social networks evolve over time. Formally, network evolution is represented as a continuous-time Markov chain (CTMC) operating on a space of networks.</p>
<p>As previously introduced, a continuous-time Markov chain (CTMC) is characterized by three key components:</p>
<ul>
<li><strong>A finite state space</strong>: For SAOMs, this is the set <span class="math inline">\(\mathcal{Y}\)</span> of all possible directed networks on <span class="math inline">\(n\)</span> actors. Each state <span class="math inline">\(Y \in \mathcal{Y}\)</span> is an adjacency matrix with entries <span class="math inline">\(y_{ij} \in \{0,1\}\)</span> for <span class="math inline">\(i \neq j\)</span>.</li>
<li><strong>A continuous-time process</strong>: Network changes (such as the creation or dissolution of ties <span class="math inline">\(y_{ij}(t)\)</span>) occur at random points in continuous time.</li>
<li><strong>The Markov property</strong>: The probability of a transition depends only on the current network state <span class="math inline">\(Y(t)\)</span>, not on the sequence of past networks that preceded it.</li>
</ul>
<p>In the sections that follow, we explore how each of these components is specified in SAOMs, including how actors are selected to make changes and how tie updates are determined.</p>
<p>Let <span class="math inline">\(\mathcal{Y}\)</span> denote the set of all possible adjacency matrices (i.e., network configurations) defined on <span class="math inline">\(n\)</span> actors. Each matrix <span class="math inline">\(Y \in \mathcal{Y}\)</span> represents a possible state of the network.</p>
<p>For directed networks without self-ties, the size of this state space is:</p>
<p><span class="math display">\[
|\mathcal{Y}| = 2^{n(n-1)}
\]</span></p>
<p>This follows from the fact that each of the <span class="math inline">\(n(n-1)\)</span> possible directed ties between distinct actors <span class="math inline">\((i,j)\)</span> with <span class="math inline">\(i \neq j\)</span> can independently be either present (<span class="math inline">\(y_{ij} = 1\)</span>) or absent (<span class="math inline">\(y_{ij} = 0\)</span>).</p>
<p>In the SAOM framework, the stochastic process <span class="math inline">\(\{Y(t), t \geq 0\}\)</span> evolves over this state space, with each realization corresponding to a sequence of network configurations over time.</p>
<p>For instance, with a 4-node directed network shown in <a href="#fig-saomex" class="quarto-xref">Figure&nbsp;<span>18.1</span></a>, we can represent different adjacency matrices as the network evolves. The figure illustrates a step-by-step sequence of tie changes, starting from an empty network and progressing toward a more connected structure.</p>
<div id="fig-saomex" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-saomex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/‎‎saom-state-ex.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-saomex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.1: An example of network evolution as a sequence of micro-steps in continuous time. At each step, a single directed tie <span class="math inline">\(y_{ij}\)</span> is updated, producing a new network state and its corresponding adjacency matrix.
</figcaption>
</figure>
</div>
<p>Stochastic Actor-Oriented Models (SAOMs) assume that the network evolves as a continuous-time Markov process. Formally, the stochastic process <span class="math inline">\(\{Y(t), t \geq 0\}\)</span> changes over time through a sequence of small, actor-driven modifications, where individual ties <span class="math inline">\(y_{ij}(t)\)</span> may be created or dissolved.</p>
<p>In empirical applications, however, we do not observe the full trajectory of this process. Instead, we observe the network only at a finite set of discrete time points (e.g., survey waves): <span class="math display">\[
t_1,\ t_2,\ \ldots,\ t_M.
\]</span></p>
<p>At each observation moment, we record a network <span class="math inline">\(Y(t_m)\)</span>, but the intermediate tie changes (i.e., which actor changed which tie <span class="math inline">\((i,j)\)</span> and at what exact time) remain unobserved. These changes occur in a latent process between observation moments.</p>
<p>This distinction is fundamental:</p>
<ul>
<li><strong>Observed process</strong>: a sequence of network snapshots <span class="math inline">\(Y(t_1), Y(t_2), \ldots, Y(t_M)\)</span>.</li>
<li><strong>Latent process</strong>: the underlying continuous-time evolution, consisting of a sequence of micro-steps in which actors stochastically update individual ties <span class="math inline">\(y_{ij}(t)\)</span> based on the current network state <span class="math inline">\(Y(t)\)</span>.</li>
</ul>
<p>SAOMs aim to model and simulate this latent evolution process, allowing us to infer the actor-level mechanisms that most likely generated the observed changes between <span class="math inline">\(Y(t_1)\)</span> and <span class="math inline">\(Y(t_M)\)</span>.</p>
<p>A central assumption of Stochastic Actor-Oriented Models (SAOMs) is that the probability of moving to a new network state depends only on the current state, not on the path taken to get there. This is the Markov property and is formally defined as: <span class="math display">\[
P\bigl(Y(t_j) = y' \mid \{Y(t): t \leq t_i\}\bigr)
=
P\bigl(Y(t_j) = y' \mid Y(t_i) = y\bigr)
\]</span> where <span class="math inline">\(Y(t)\)</span> denotes the network state (i.e., adjacency matrix) at time <span class="math inline">\(t\)</span>, and <span class="math inline">\(y, y' \in \mathcal{Y}\)</span> are particular network configurations at times <span class="math inline">\(t_i\)</span> and <span class="math inline">\(t_j\)</span>, respectively.</p>
<p>In other words, the future evolution of the process depends solely on the current network state <span class="math inline">\(Y(t_i)\)</span> and not on the entire sequence of previous states. The model is memoryless: it “forgets” the past once the current state is known.</p>
<p>In the context of SAOMs, this means that when an actor is given the opportunity to make a change, such as forming or dissolving a tie <span class="math inline">\(y_{ij}(t)\)</span>, they do so based only on the current network structure and covariate information. There is no dependence on the path the network took to reach its current configuration.</p>
<p>This assumption significantly simplifies the modeling of network dynamics. It eliminates the need to track full network histories and allows for tractable simulation-based estimation. Conceptually, it also aligns with many social processes where actors respond to their current social environment rather than recalling a complete relational past.</p>
<p>Nonetheless, the Markov assumption is a modeling abstraction. While it facilitates analysis and interpretation, it may not capture certain behaviors where history matters, such as long-term reciprocity, reputation building, or delayed responses. Still, for many applications, it offers a powerful and flexible framework for understanding how networks evolve over time.</p>
</section>
<section id="actor-oriented-micro-steps" class="level3" data-number="18.3.4">
<h3 data-number="18.3.4" class="anchored" data-anchor-id="actor-oriented-micro-steps"><span class="header-section-number">18.3.4</span> Actor-Oriented Micro-Steps</h3>
<p>A central challenge in modeling network dynamics is the vast number of possible network configurations. For a directed network with <span class="math inline">\(n\)</span> actors, the state space <span class="math inline">\(\mathcal{Y}\)</span> contains <span class="math inline">\(2^{n(n-1)}\)</span> possible networks, making exhaustive evaluation of all potential transitions computationally infeasible.</p>
<p>SAOMs address this by adopting an <strong>actor-driven approach</strong>. Instead of modeling global changes to the network, SAOMs assume that individual actors make decisions about their outgoing ties through a series of small, sequential updates. This simplifies the modeling process while remaining grounded in a realistic representation of social behavior.</p>
<p>The SAOM framework relies on three core assumptions:</p>
<ol type="1">
<li><p><strong>One actor at a time</strong>: At each micro-step, a single actor <span class="math inline">\(i\)</span> is randomly selected and given the opportunity to revise their outgoing ties. This reflects individual, sequential decision-making.</p></li>
<li><p><strong>One tie at a time</strong>: The selected actor <span class="math inline">\(i\)</span> considers one outgoing tie <span class="math inline">\(y_{ij}(t)\)</span> for some <span class="math inline">\(j \neq i\)</span>, and may choose to create it (<span class="math inline">\(y_{ij}(t) = 1\)</span>), dissolve it (<span class="math inline">\(y_{ij}(t) = 0\)</span>), or leave it unchanged. Only one tie variable can change per step, which keeps the space of possible transitions manageable.</p></li>
<li><p><strong>Actor-controlled change</strong>: Each actor controls only their own outgoing ties. Tie changes arise solely from the actor’s individual evaluation of the current network state <span class="math inline">\(Y(t)\)</span> and are not the result of simultaneous or coordinated actions.</p></li>
</ol>
<p>Together, these assumptions define a process of sequential micro-steps, each involving:</p>
<ul>
<li>Selecting an actor <span class="math inline">\(i\)</span> at random,</li>
<li>Considering a possible change to one tie <span class="math inline">\(y_{ij}(t)\)</span>,</li>
<li>And waiting a randomly determined time before the next opportunity arises.</li>
</ul>
<p>This process unfolds in continuous time and follows the structure of a continuous-time Markov chain (CTMC). It consists of two key components: the <strong>holding time</strong>, which determines how long the current network state <span class="math inline">\(Y(t)\)</span> persists, and the <strong>jump chain</strong>, which defines the probability of transitioning to a new network state via a single tie update.</p>
</section>
<section id="rate-function-and-jump-chain" class="level3" data-number="18.3.5">
<h3 data-number="18.3.5" class="anchored" data-anchor-id="rate-function-and-jump-chain"><span class="header-section-number">18.3.5</span> Rate Function and Jump Chain</h3>
<p>The <strong>holding time</strong> in SAOMs refers to the waiting period before an actor is given the opportunity to change one of their outgoing ties. In accordance with the properties of a continuous-time Markov chain (CTMC), this waiting time is modeled as an exponentially distributed random variable.</p>
<p>For actor <span class="math inline">\(i\)</span>, the holding time <span class="math inline">\(T_i\)</span> has the following probability density function: <span class="math display">\[
f_{T_i}(t) = \lambda_i e^{-\lambda_i t}, \quad \lambda_i &gt; 0, \quad t &gt; 0
\]</span> Here, <span class="math inline">\(\lambda_i\)</span> is the rate parameter, determining how frequently actor <span class="math inline">\(i\)</span> receives opportunities to change their ties. The choice of <span class="math inline">\(\lambda_i\)</span> defines how the actor selection process unfolds:</p>
<ul>
<li><p><strong>Homogeneous specification</strong>: All actors have the same rate <span class="math inline">\(\lambda\)</span>, implying equal opportunity: <span class="math display">\[
\lambda_i = \lambda \quad \text{for all } i, \qquad
P(i \text{ is selected}) = \frac{1}{n}
\]</span></p></li>
<li><p><strong>Heterogeneous specification</strong>: The rate varies across actors based on covariates or network structure: <span class="math display">\[
\lambda_i = \lambda_i(\theta, Y(t), v)
\]</span> where <span class="math inline">\(\theta\)</span> is a parameter vector, <span class="math inline">\(Y(t)\)</span> is the current network configuration, and <span class="math inline">\(v\)</span> are actor-specific covariates. In this case: <span class="math display">\[
P(i \text{ is selected}) =
\frac{\lambda_i(\theta, Y(t), v)}{\sum_{r=1}^{n} \lambda_r(\theta, Y(t), v)}
\]</span> This flexibility allows the model to reflect actor-level heterogeneity in the speed of network change. In many applications, however, a homogeneous rate is assumed for simplicity and interpretability.</p></li>
</ul>
<p>This setup relies on the memoryless property of the exponential distribution: <span class="math display">\[
P(T_i &gt; s + t \mid T_i &gt; t) = P(T_i &gt; s)
\]</span> That is, the probability that actor <span class="math inline">\(i\)</span> will be selected in the next instant is unaffected by how long they have already been waiting. This property aligns naturally with the continuous-time Markov assumption and greatly simplifies simulation. In summary, the holding time determines <em>when</em> micro-steps occur.</p>
<p>Once an actor has been selected and the holding time has elapsed, the next question becomes: <em>what</em> change (if any) will this actor make to the network? This is governed by the <strong>jump chain</strong>, which determines the next network state.</p>
<p>At each micro-step, actor <span class="math inline">\(i\)</span> evaluates a set of feasible alternatives <span class="math inline">\(\{Y^{(a)}\}_{a=1}^{A}\)</span>, each differing from the current network <span class="math inline">\(Y(t)\)</span> by at most a change in one outgoing tie <span class="math inline">\(y_{ij}(t)\)</span> (i.e., forming, dissolving, or maintaining a tie).</p>
<p>Each alternative <span class="math inline">\(Y^{(a)}\)</span> is assigned a utility: <span class="math display">\[
U_{ia} = F_{ia} + \varepsilon_{ia}
\]</span></p>
<p>Here, <span class="math inline">\(F_{ia}\)</span> represents the deterministic component of the utility function, typically defined through an objective function that incorporates structural effects such as reciprocity, transitivity, or covariate similarity. The <span class="math inline">\(\varepsilon_{ia}\)</span> term introduces randomness via a Gumbel-distributed disturbance, reflecting unobserved preferences or decision noise.</p>
<p>This setup defines a <strong>random utility model</strong>, where actor <span class="math inline">\(i\)</span> selects among alternatives probabilistically. Under the Gumbel assumption, the choice probabilities follow a multinomial logit form:</p>
<p><span class="math display">\[
p_{ia} = \frac{\exp(F_{ia})}{\sum_{b=1}^{A} \exp(F_{ib})}
\]</span></p>
<p>where <span class="math inline">\(F_{ia}\)</span> is the deterministic utility that actor <span class="math inline">\(i\)</span> assigns to alternative <span class="math inline">\(a\)</span>, corresponding to the candidate network <span class="math inline">\(Y^{(a)}\)</span>.</p>
<p>These probabilities define the jump chain, describing the likelihood of moving from the current network state <span class="math inline">\(Y(t)\)</span> to a new state <span class="math inline">\(Y^{(a)}\)</span>. Because only one actor changes at most one tie at each micro-step, the set of feasible transitions is small, making the process computationally tractable.</p>
<p>We now make explicit how the deterministic component <span class="math inline">\(F_{ia}\)</span> is constructed. It is given by an <strong>objective function</strong>:</p>
<p><span class="math display">\[
F_{ia} = f_i(\theta, Y^{(a)}) = \sum_{k=1}^{K} \theta_k \cdot s_{ik}(Y^{(a)}, v)
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(Y^{(a)}\)</span> is the candidate network after a tie change,</li>
<li><span class="math inline">\(s_{ik}(Y^{(a)}, v)\)</span> is the contribution of effect <span class="math inline">\(k\)</span> for actor <span class="math inline">\(i\)</span>,</li>
<li><span class="math inline">\(\theta_k\)</span> is the parameter associated with that effect.</li>
</ul>
<p>This formulation makes clear that the utility of an alternative depends on how the resulting network configuration aligns with the actor’s preferences, as captured by the statistics <span class="math inline">\(s_{ik}(\cdot)\)</span>. The random utility formulation introduces stochasticity while allowing for interpretable parameter estimation.</p>
<p>In summary, the jump chain determines <em>which</em> network configuration the process moves to, conditional on actor selection. Combined with the holding time, which governs <em>when</em> actors are selected, it defines the dynamics of the SAOM as a continuous-time Markov process.</p>
</section>
<section id="endogenous-effects-in-the-objective-function" class="level3" data-number="18.3.6">
<h3 data-number="18.3.6" class="anchored" data-anchor-id="endogenous-effects-in-the-objective-function"><span class="header-section-number">18.3.6</span> Endogenous Effects in the Objective Function</h3>
<p>The objective function introduced above is a linear combination of effects, each capturing a specific structural pattern or social mechanism. These effects are conceptually similar to those used in Exponential Random Graph Models (ERGMs), although they differ in interpretation due to the dynamic and actor-oriented nature of SAOMs. They fall into two main categories:</p>
<ul>
<li><strong>Endogenous effects</strong>: derived from the structure of the network itself.</li>
<li><strong>Exogenous effects</strong>: related to external actor attributes.</li>
</ul>
<p>The objective function for actor <span class="math inline">\(i\)</span> evaluating a candidate network <span class="math inline">\(Y^{(a)}\)</span> is given by:</p>
<p><span class="math display">\[
f_i(\theta, Y^{(a)}) = \sum_{k=1}^{K} \theta_k \cdot s_{ik}(Y^{(a)})
\]</span></p>
<p>where <span class="math inline">\(\theta_k\)</span> is the parameter for effect <span class="math inline">\(k\)</span>, and <span class="math inline">\(s_{ik}(Y^{(a)})\)</span> is the value of effect <span class="math inline">\(k\)</span> evaluated for actor <span class="math inline">\(i\)</span> in the candidate network <span class="math inline">\(Y^{(a)}\)</span>. Each effect enters the objective function with an associated parameter to be estimated from data. The weighted sum of these effects (together with a stochastic component) determines the actor’s utility for each potential tie change, guiding the probabilistic decision-making process at the heart of the SAOM framework.</p>
<p>This section focuses on a set of commonly used endogenous effects, that is, effects based solely on the structure of the network (without using external covariates). Many other effects can be specified, depending on the theoretical focus and complexity of the network under study.</p>
<section id="outdegree-effect" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="outdegree-effect">1. Outdegree Effect</h5>
<p>Similar to the <code>edges</code> term in ERGM, this effect reflects the tendency (or cost) of maintaining ties. It counts the number of outgoing ties from actor <span class="math inline">\(i\)</span> in the candidate network configuration <span class="math inline">\(Y^{(a)}\)</span>:</p>
<p><span class="math display">\[
s_i^{\text{out}}(Y^{(a)}) = \sum_{j} y^{(a)}_{ij}
\]</span></p>
<p>This term typically has a negative coefficient, penalizing actors for having too many ties, and thus introducing a cost to maintaining social relationships.</p>
</section>
<section id="reciprocity-effect" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="reciprocity-effect">2. Reciprocity Effect</h5>
<p>The reciprocity effect captures the tendency for actors to form mutual ties (equivalent to the <code>mutual</code> term in ERGMs). It counts how many of actor <span class="math inline">\(i\)</span>’s outgoing ties are reciprocated:</p>
<p><span class="math display">\[
s_i^{\text{rec}}(Y^{(a)}) = \sum_{j} y^{(a)}_{ij} \, y^{(a)}_{ji}
\]</span></p>
<p>A positive coefficient for this effect reflects a preference for mutual connections, e.g., <em>“I send a tie to those who also send one to me.”</em></p>
</section>
<section id="transitive-triplets-effect" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="transitive-triplets-effect">3. Transitive Triplets Effect</h5>
<p>Closely related to the <code>triangles</code> or <code>GWESP</code> terms in ERGMs, this effect models triadic closure. The transitive effect reflects a tendency toward forming closed triads. If actor <span class="math inline">\(i\)</span> sends a tie to <span class="math inline">\(h\)</span>, and <span class="math inline">\(h\)</span> sends a tie to <span class="math inline">\(j\)</span>, then <span class="math inline">\(i\)</span> is more likely to send a tie to <span class="math inline">\(j\)</span>.</p>
<p><span class="math display">\[
s_i^{\text{trans}}(Y^{(a)}) = \sum_{j,h} y^{(a)}_{ij} \, y^{(a)}_{jh} \, y^{(a)}_{ih}
\]</span></p>
<p>This effect captures the formation of transitive triples (closed triads), where <span class="math inline">\(i \to j\)</span>, <span class="math inline">\(j \to h\)</span>, and <span class="math inline">\(i \to h\)</span>. It reflects processes such as social closure, hierarchy, and the formation of cohesive subgroups.</p>
</section>
<section id="three-cycle-effect" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="three-cycle-effect">4. Three-Cycle Effect</h5>
<p>The three-cycle effect (analogous to cyclic triads in ERGMs) captures the tendency of actors to form circular structures in the network. Specifically, it counts the number of directed cycles of length three involving actor <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[
s_i^{\text{cyc}}(Y^{(a)}) = \sum_{j,h} y^{(a)}_{ij} \, y^{(a)}_{jh} \, y^{(a)}_{hi}
\]</span></p>
<p>This effect captures patterns such as <span class="math inline">\(i \to j \to h \to i\)</span>, representing feedback loops or non-hierarchical structures in the network. It often receives a negative coefficient, discouraging cyclic patterns and favoring more hierarchical or transitive structures.</p>
<p>Next, we introduce exogenous effects, which link actor behavior to covariates such as attributes or group memberships.</p>
</section>
</section>
<section id="sec-exeffects" class="level3" data-number="18.3.7">
<h3 data-number="18.3.7" class="anchored" data-anchor-id="sec-exeffects"><span class="header-section-number">18.3.7</span> Exogenous Effects in the Objective Function</h3>
<p>In addition to modeling endogenous network tendencies (such as reciprocity or transitivity), SAOMs allow the inclusion of <strong>exogenous covariates</strong> that influence tie formation. These covariates capture observed attributes of actors or dyads that may shape network dynamics.</p>
<p>We denote covariate information by <span class="math inline">\(v\)</span>. Depending on the context, <span class="math inline">\(v\)</span> may include:</p>
<ul>
<li><strong>Actor-level covariates</strong>: <span class="math inline">\(v_i\)</span> (e.g., age, gender, smoking status),</li>
<li><strong>Dyadic covariates</strong>: <span class="math inline">\(v_{ij}\)</span> (e.g., geographic distance or similarity between actors <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>).</li>
</ul>
<p>As in ERGMs, these effects enter the <strong>objective function</strong>, which represents the utility that actor <span class="math inline">\(i\)</span> associates with a candidate network configuration <span class="math inline">\(Y^{(a)}\)</span>:</p>
<p><span class="math display">\[
f_i(\theta, Y^{(a)}) = \sum_{k=1}^{K} \theta_k \cdot s_{ik}(Y^{(a)}, v)
\]</span></p>
<p>Here, the statistics <span class="math inline">\(s_{ik}(Y^{(a)}, v)\)</span> may depend not only on the network structure <span class="math inline">\(Y^{(a)}\)</span> but also on the covariates <span class="math inline">\(v\)</span>. This allows actor <span class="math inline">\(i\)</span>’s evaluation of potential tie changes to incorporate both structural features of the network and observed attributes of actors or dyads.</p>
<p>Below are common types of exogenous effects.</p>
<section id="individual-level-covariate-effects" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="individual-level-covariate-effects">1. Individual-Level Covariate Effects</h5>
<p>These effects are based on <strong>actor-level covariates</strong> and can enter the objective function in two ways:</p>
<ol type="1">
<li><p><strong>Covariate-Ego Effect</strong><br>
This effect captures whether actors with a particular covariate value are more (or less) likely to form outgoing ties. <span class="math display">\[
s_i^{\text{ego}}(Y^{(a)}, v) = v_i \sum_j y^{(a)}_{ij}
\]</span> Here, <span class="math inline">\(v_i\)</span> is the covariate value for actor <span class="math inline">\(i\)</span> (the <em>ego</em>), and the statistic counts how many ties they initiate. If the covariate is binary, this can test whether having a trait (e.g., belonging to a particular group) is associated with being more active in sending ties.</p></li>
<li><p><strong>Covariate-Alter Effect</strong><br>
This effect reflects a preference for forming ties to others (<em>alters</em>) with certain attribute values. <span class="math display">\[
s_i^{\text{alter}}(Y^{(a)}, v) = \sum_j y^{(a)}_{ij} \, v_j
\]</span> Here, <span class="math inline">\(v_j\)</span> is the covariate value of the potential receiver. A positive parameter indicates that actors are more likely to send ties to alters with higher covariate values (and vice versa).</p></li>
</ol>
</section>
<section id="dyadic-covariate-effects" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="dyadic-covariate-effects">2. Dyadic Covariate Effects</h5>
<p>SAOMs also allow modeling based on <strong>dyadic similarity</strong>, capturing whether actors prefer to connect with others who are similar in some attribute.</p>
<p>A common specification is the similarity-based effect: <span class="math display">\[
s_i^{\text{sim}}(Y^{(a)}, v)
= \sum_j y^{(a)}_{ij}
\left( 1 - \frac{|v_i - v_j|}{\max(v) - \min(v)} \right)
\]</span></p>
<p>This statistic increases when actor <span class="math inline">\(i\)</span> sends ties to actors <span class="math inline">\(j\)</span> who are similar in their covariate values. The similarity term is normalized to the interval <span class="math inline">\([0,1]\)</span>, where 1 indicates perfect similarity and 0 indicates maximal difference.</p>
<p>For binary covariates, this simplifies to an indicator function: <span class="math display">\[
s_i^{\text{sim}}(Y^{(a)}, v) = \sum_j y^{(a)}_{ij} \cdot \mathbf{1}(v_i = v_j)
\]</span></p>
<p>This effect captures <strong>homophily</strong>, the tendency of actors to form ties with others who share the same attribute (e.g., same gender or group membership).</p>
</section>
</section>
<section id="choosing-effects-for-the-objective-function" class="level3" data-number="18.3.8">
<h3 data-number="18.3.8" class="anchored" data-anchor-id="choosing-effects-for-the-objective-function"><span class="header-section-number">18.3.8</span> Choosing Effects for the Objective Function</h3>
<p>When specifying a Stochastic Actor-Oriented Model (SAOM), the first step is to select which effects to include in the actor’s objective function <span class="math inline">\(f_i(\theta, Y^{(a)})\)</span>. At a minimum, models typically include an outdegree effect (capturing a baseline tendency to form ties) and a reciprocity effect (capturing the preference for mutual ties).</p>
<p>Beyond these baseline effects, additional terms should be guided by substantive theory or research hypotheses. For example, if theory suggests that individuals tend to befriend friends of their friends, a transitive triplet effect may be appropriate. If social similarity (homophily) based on covariates such as gender is expected, similarity-based covariate effects can be included.</p>
<p>These choices tailor the model to reflect specific structural patterns and attribute-driven mechanisms. While only a few examples are presented here, SAOMs provide a wide range of endogenous and exogenous effects that can be combined to test theoretically meaningful processes of network evolution.</p>
</section>
<section id="parameter-estimation-and-interpretation" class="level3" data-number="18.3.9">
<h3 data-number="18.3.9" class="anchored" data-anchor-id="parameter-estimation-and-interpretation"><span class="header-section-number">18.3.9</span> Parameter Estimation and Interpretation</h3>
<p>In Stochastic Actor-Oriented Models (SAOMs), each parameter <span class="math inline">\(\theta_k\)</span> quantifies the importance of a specific effect <span class="math inline">\(s_{ik}(Y^{(a)}, v)\)</span> in the actor’s decision-making process during network evolution. These parameters help us understand how structural features or covariates influence the likelihood of different tie changes.</p>
<p>The interpretation of <span class="math inline">\(\theta_k\)</span> is as follows:</p>
<ul>
<li>If <span class="math inline">\(\theta_k = 0\)</span>, the statistic <span class="math inline">\(s_{ik}(Y^{(a)}, v)\)</span> has no effect on the transition probabilities and does not influence network dynamics.</li>
<li>If <span class="math inline">\(\theta_k &gt; 0\)</span>, actor <span class="math inline">\(i\)</span> is more likely to move toward network states <span class="math inline">\(Y^{(a)}\)</span> that increase the value of <span class="math inline">\(s_{ik}(Y^{(a)}, v)\)</span>.</li>
<li>If <span class="math inline">\(\theta_k &lt; 0\)</span>, actor <span class="math inline">\(i\)</span> prefers changes that decrease the value of <span class="math inline">\(s_{ik}(Y^{(a)}, v)\)</span>.</li>
</ul>
<p>Importantly, these preferences are assumed to be stable over time. That is, the parameter vector <span class="math inline">\(\theta = (\theta_1, \dots, \theta_K)\)</span> is assumed to be constant throughout the observation period: <span class="math display">\[
\theta_1, \dots, \theta_K \text{ are constant over time.}
\]</span></p>
<p>Parameter estimation in SAOMs is performed using simulation-based methods, as implemented in the <code>RSiena</code> R package (SIENA: Simulation Investigation for Empirical Network Analysis).</p>
<p>The core idea is to simulate the network evolution process under the assumed model, compare the simulated outcomes with observed data, and iteratively adjust the parameters to improve the fit. This approach is based on the <strong>method of moments</strong>, where simulated network statistics are aligned with their empirical counterparts.</p>
<p>The estimation process typically involves:</p>
<ul>
<li>Defining the observed networks at multiple time points,</li>
<li>Specifying the effects (endogenous and exogenous) to include in the model,</li>
<li>Running simulations and updating parameters iteratively until convergence.</li>
</ul>
<p>To assess whether a particular effect significantly contributes to the network dynamics, we test each parameter <span class="math inline">\(\theta_k\)</span>:</p>
<ul>
<li><strong>Null Hypothesis (<span class="math inline">\(H_0\)</span>):</strong> The effect has no influence on tie changes, <span class="math display">\[
H_0 : \theta_k = 0
\]</span></li>
<li><strong>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>):</strong> The effect has a systematic influence, <span class="math display">\[
H_1 : \theta_k \ne 0
\]</span></li>
</ul>
<p>Under standard conditions, inference is based on the <strong>t-ratio</strong>, defined as the ratio of the parameter estimate to its standard error: <span class="math display">\[
\left| \frac{\theta_k}{\text{s.e.}(\theta_k)} \right| \ge 2
\;\Rightarrow\; \text{Reject } H_0
\]</span></p>
<p>If the absolute t-ratio exceeds 2, the parameter is considered significantly different from zero at approximately the 5% significance level.</p>
</section>
</section>
<section id="extending-saoms-the-co-evolution-of-networks-and-behavior" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="extending-saoms-the-co-evolution-of-networks-and-behavior"><span class="header-section-number">18.4</span> Extending SAOMs: The Co-Evolution of Networks and Behavior</h2>
<section id="basic-shape-effects" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="basic-shape-effects">1. Basic Shape Effects</h3>
<p>These effects govern the overall shape or distribution of the behavior.</p>
<ul>
<li><p><strong>Linear shape effect</strong><br>
This effect encourages an increase or decrease in behavior depending on the sign of the parameter:</p>
<p><span class="math display">\[
s^\text{beh}_{i,\text{linear}}(z) = z_i
\]</span></p>
<p>If <span class="math inline">\(\theta_{\text{lin}} &gt; 0\)</span>, higher behavior values are favored. If <span class="math inline">\(\theta_{\text{lin}} &lt; 0\)</span>, lower behavior values are favored.</p></li>
<li><p><strong>Quadratic shape effect</strong><br>
This effect penalizes extreme behavioral values (high or low), favoring moderation:</p>
<p><span class="math display">\[
s^\text{beh}_{i,\text{quadratic}}(z) = z_i^2
\]</span></p>
<p>A negative estimate for this effect leads to stabilization around the middle values of the behavioral scale, i.e., it favors moderate behavior (e.g., smoking occasionally rather than regularly).</p></li>
</ul>
<p>Note that the basic shape effects are typically included in the behavioral model specification.</p>
</section>
<section id="social-influence-effects" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="social-influence-effects">2. Social Influence Effects</h3>
<p>The behavioral similarity effects in SAOMs allow us to model how actors adjust their behavior to become more similar to their peers. These effects assume that individuals are influenced by the behavioral attributes of those they are connected to.</p>
<ul>
<li><p><strong>Average similarity</strong><br>
This effect captures how similar an actor’s behavior is to their alters’ behaviors, averaged across all outgoing ties. It reflects per-peer influence. The statistic is defined as:</p>
<p><span class="math display">\[
s^\text{beh}_{i,\text{avsim}}(Y, z) =
    \frac{1}{y_{i+}} \sum_{j=1}^n y_{ij}
    \left( \text{sim}_z(i,j) - \overline{\text{sim}_z} \right)
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(y_{ij}\)</span> is 1 if actor <span class="math inline">\(i\)</span> has a tie to actor <span class="math inline">\(j\)</span>, and 0 otherwise.</li>
<li><span class="math inline">\(y_{i+} = \sum_{j=1}^n y_{ij}\)</span> is the number of outgoing ties for actor <span class="math inline">\(i\)</span>.</li>
<li><span class="math inline">\(\text{sim}_z(i,j)\)</span> is the behavioral similarity between actor <span class="math inline">\(i\)</span> and actor <span class="math inline">\(j\)</span>, defined as: <span class="math display">\[
\text{sim}_z(i,j) = 1 - \frac{|z_i - z_j|}{R_z}
\]</span> where <span class="math inline">\(R_z\)</span> is the range of the behavior variable.</li>
<li><span class="math inline">\(\overline{\text{sim}_z}\)</span> is the average similarity across all dyads in the network and acts as a centering constant. This centering ensures that the statistic has an interpretable baseline, distinguishing whether actors are more or less similar to their peers compared to the overall average.</li>
</ul></li>
<li><p><strong>Total similarity</strong><br>
This variant captures the total amount of similarity, not normalized by the number of ties. It gives more weight to actors with more alters:</p>
<p><span class="math display">\[
s^\text{beh}_{i,\text{totsim}}(Y, z) =
    \sum_{j=1}^n y_{ij}
    \left( \text{sim}_z(i,j) - \overline{\text{sim}_z} \right)
\]</span></p></li>
</ul>
<p>Both versions reflect social influence. A positive parameter estimate means that actors are more likely to adjust their behavior to become more similar to those they are connected to. In other words, the model captures conformity or peer influence. The higher the similarity between ego and alters, the higher the objective function, making such changes more likely. A negative parameter estimate would indicate that actors tend to diverge from their peers, becoming less similar over time. This could suggest differentiation or opposition in behavior, although negative influence parameters are rare and often theoretically unexpected.</p>
<p>The difference between the two lies in how the influence is scaled: average similarity treats influence on a per-tie basis, while total similarity accumulates influence across all alters, potentially making actors with more peers more susceptible to conformity.</p>
</section>
<section id="network-position-effects" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="network-position-effects">3. Network Position Effects</h3>
<p>Network position effects model whether an actor’s behavior is associated with their position in the network. In this context, they are behavioral effects: they ask whether actors with more incoming or outgoing ties tend to have higher or lower behavioral values.</p>
<ul>
<li><p><strong>Outdegree effect</strong><br>
This effect investigates whether actors with more outgoing ties tend to have different behavioral values:</p>
<p><span class="math display">\[
s^\text{beh}_{i,\text{out}}(Y, z) =
    z_i \sum_{j=1}^n y_{ij}
\]</span></p></li>
<li><p><strong>Indegree effect</strong><br>
This effect models whether being popular (having many incoming ties) is related to behavior:</p>
<p><span class="math display">\[
s^\text{beh}_{i,\text{ind}}(Y, z) =
    z_i \sum_{j=1}^n y_{ji}
\]</span></p></li>
</ul>
<p>A positive parameter estimate for a position effect means that higher behavioral values are associated with the corresponding network position. For instance, if the behavior is smoking, a positive outdegree effect suggests that actors who smoke more tend to send more ties, while a positive indegree effect suggests that actors who smoke more tend to receive more ties.</p>
<p>A negative parameter estimate indicates that higher behavioral values are associated with fewer ties in that position. For example, actors with higher smoking values may be less active in sending ties or less popular as recipients, depending on whether the outdegree or indegree effect is negative.</p>
</section>
<section id="covariate-effects" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="covariate-effects">4. Covariate Effects</h3>
<p>Covariate effects capture how actor-level attributes, such as sex, age, or socioeconomic status, directly influence behavioral change. Unlike social influence effects, these effects do not depend on the network ties themselves; they test whether actors with certain attributes tend to have higher or lower behavioral values.</p>
<ul>
<li><p><strong>Covariate effect</strong><br>
Actor attributes can be included in the behavioral objective function as main effects. This indicates whether an attribute <span class="math inline">\(v_i\)</span> is associated with higher or lower behavior values:</p>
<p><span class="math display">\[
s^\text{beh}_{i,\text{covariate}}(v) = v_i
\]</span></p></li>
</ul>
<p>These effects capture how an actor’s covariate value influences their tendency to increase or decrease their behavioral score. For example, we might ask: Are boys or girls more likely to adopt a risky behavior? Do older students tend to reduce smoking over time?</p>
</section>
</section>
<section id="estimating-saoms-in-rsiena" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="estimating-saoms-in-rsiena"><span class="header-section-number">18.5</span> Estimating SAOMs in RSiena</h2>
<p>RSiena is an R package for estimating and simulating Stochastic Actor-Oriented Models (SAOMs) for network and behavioral dynamics. It is specifically designed to analyze longitudinal network data, where social ties and actor attributes evolve over time.</p>
<p>In RSiena, the distinction between modeling <strong>network evolution</strong> and the <strong>co-evolution of networks and behavior</strong> begins with how the dependent variables are specified.</p>
<p>If only the network is included as a dependent variable (i.e., a <code>sienaDependent</code> network object), the model focuses on network evolution. This framework captures how actors form, maintain, or dissolve ties over time. It can include covariates (such as gender or smoking status) to explain <strong>social selection</strong>, meaning that actor attributes influence the likelihood of tie formation or dissolution. In this case, individual attributes are treated as exogenous and remain fixed over time.</p>
<p>Alternatively, RSiena allows for <strong>co-evolution models</strong> by including both a network and a behavioral variable as dependent variables. This setup enables the simultaneous modeling of two processes: how networks evolve and how actors’ behaviors change over time. This makes it possible to study <strong>social influence</strong>, where individuals may adopt behaviors similar to those of their network peers. The model thus captures both the selection of network ties based on covariates and the influence of peers on individual behavior.</p>
<p>Below, we outline the typical steps involved in estimating SAOMs using RSiena:</p>
<ol type="1">
<li><p><strong>Preparing the data</strong><br>
Import and format the network and covariate data into the appropriate structure. This includes creating adjacency matrices for networks observed over time and vectors or matrices for actor-level covariates. These are then converted into RSiena objects such as <code>sienaDependent</code>, <code>coCovar</code>, or <code>varCovar</code>.</p></li>
<li><p><strong>Specifying the model</strong><br>
Define the model by selecting the effects to include. Use <code>getEffects()</code> to retrieve the default effects object and <code>includeEffects()</code> to add endogenous and covariate-related effects.</p></li>
<li><p><strong>Estimating the model</strong><br>
Set up the estimation procedure using <code>sienaAlgorithmCreate()</code> and estimate the model with <code>siena07()</code>. Evaluate convergence and diagnostic statistics to ensure reliable results.</p></li>
<li><p><strong>Interpreting the results</strong><br>
Analyze the estimated parameters to understand the underlying social processes. This involves examining the direction, magnitude, and statistical significance of effects to interpret mechanisms of network change or co-evolution.</p></li>
</ol>
<section id="model-1-structural-network-effects" class="level3" data-number="18.5.1">
<h3 data-number="18.5.1" class="anchored" data-anchor-id="model-1-structural-network-effects"><span class="header-section-number">18.5.1</span> Model 1: Structural Network Effects</h3>
<p>We begin by estimating a simple model specification that includes only two effects: an outdegree (density) effect and a reciprocity effect. These capture baseline tie propensity and the tendency toward mutual ties, without incorporating more complex structural or covariate-based influences. In other words, no covariates are included, and the model is specified purely in terms of endogenous network dynamics.</p>
<p>We first convert the 3D network array <code>net_array</code> into a <code>sienaDependent</code> object using the <code>sienaDependent()</code> function. This step tells <code>RSiena</code> that the array represents a dependent network variable observed over multiple waves. The resulting object is then used as input for model specification and estimation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert array into RSiena dependent object</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>siena_net <span class="ot">&lt;-</span> <span class="fu">sienaDependent</span>(net_array)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>After defining the network as a <code>sienaDependent</code> object, we now wrap it into a complete <code>RSiena</code> data object using <code>sienaDataCreate()</code>. This function prepares the data for model specification and estimation by bundling all input variables (here just the network) into a structure that the estimation algorithm can use.</p>
<p>Since we are modeling only the network (and no actor covariates yet), we simply pass <code>siena_net</code> as the argument.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a Siena data object</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>data_mod1 <span class="ot">&lt;-</span> <span class="fu">sienaDataCreate</span>(siena_net)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In RSiena, model specification is driven by the concept of “effects” which represent the structural features, covariate influences, and behavioral mechanisms that are hypothesized to drive network or behavioral change. By default, <code>getEffects()</code> lists all possible effects available for the data structure (e.g., network dynamics, covariates, behaviors). It doesn’t add any effects to the model yet though, it just initializes the structure that will hold them.</p>
<p>We begin by calling <code>getEffects()</code> on our <code>data_mod1</code> object to create a default effects object. This object holds all possible effects for the given data structure and is used as a base for customization. You can have a look at these effects directly by calling it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the effects: start with default effect object</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>my_effects <span class="ot">&lt;-</span> <span class="fu">getEffects</span>(data_mod1)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>my_effects</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>These are the exact effects included by default:</p>
<ul>
<li>Rate parameters for each wave transition (e.g., Period 1 and Period 2)</li>
<li>Outdegree (density): capturing the baseline propensity to send ties</li>
<li>Reciprocity: modeling the tendency to reciprocate received ties</li>
</ul>
<p>Since our simple model includes only these two structural effects, there is no need to add further effects using <code>includeEffects()</code> at this stage.</p>
<p>Before running the estimation, we need to define the estimation algorithm that RSiena will use. This is done with the function <code>sienaAlgorithmCreate()</code>, which sets up the computational parameters for the simulation-based estimation process.</p>
<p>In the example below, we assign the algorithm to the object <code>my_algorithm</code>. The <code>projname</code> argument specifies a name for the project; RSiena will use this name to organize temporary output files and logs related to the estimation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the estimation algorithm</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>my_algorithm <span class="ot">&lt;-</span> <span class="fu">sienaAlgorithmCreate</span>(<span class="at">projname =</span> <span class="st">"saom_1"</span>, <span class="at">seed =</span> <span class="dv">1108</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Setting a seed as argument ensures reproducible results across runs given same R setup. Due to the stochastic nature of the algorithm and differences in computational environments, minor variations may still occur across:</p>
<ul>
<li>different versions of R or RSiena,</li>
<li>different operating systems,</li>
<li>or when using parallel processing.</li>
</ul>
</div>
</div>
<p>This algorithm object is later passed into the <code>siena07()</code> function to control how the estimation is performed. You can customize various settings like number of iterations, convergence thresholds, or use defaults (as we do here) for a basic estimation.</p>
<p>Now that we’ve set up the data, specified the effects, and defined the estimation algorithm, we can estimate the Stochastic Actor-Oriented Model using the <code>siena07()</code> function. This function runs the RSiena estimation procedure. It takes the following inputs:</p>
<ul>
<li><code>my_algorithm</code>: the algorithm settings we defined earlier.</li>
<li><code>data = data_mod1</code>: the network data in RSiena format.</li>
<li><code>effects = my_effects</code>: the specified model effects (in this case, outdegree and reciprocity).</li>
<li><code>batch = TRUE</code>: suppresses user prompts during the estimation, making it suitable for scripted or automated runs.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate the SAOM</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>saom_1 <span class="ot">&lt;-</span> <span class="fu">siena07</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  my_algorithm,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_mod1,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> my_effects,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">batch =</span> <span class="cn">TRUE</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>To print a summary of the estimation results:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View results</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>saom_1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimates, standard errors and convergence t-ratios

                                   Estimate   Standard   Convergence 
                                                Error      t-ratio   

Rate parameters: 
  0.1      Rate parameter period 1  8.5913  ( 0.7025   )             
  0.2      Rate parameter period 2  7.2618  ( 0.5713   )             

Other parameters: 
  1.  eval outdegree (density)     -2.4128  ( 0.0372   )   -0.0075   
  2.  eval reciprocity              2.7079  ( 0.0849   )   -0.0206   

Overall maximum convergence ratio:    0.0254 


Total of 2067 iteration steps.</code></pre>
</div>
</div>
<p>A nicer summary of the model is obtained by running the following, which renders the table of results inline (including significance stars for easy interpretation).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">siena_table</span>(saom_1, <span class="at">type =</span> <span class="st">"html"</span>, <span class="at">sig =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="{=html}">
<table border="1" rules="none" frame="hsides">
<tbody><tr>
<td>
Effect
</td>
<td>
&nbsp;&nbsp;&nbsp;par.
</td>
<td>
</td>
<td>
&nbsp;&nbsp;&nbsp; (s.e.)
</td>
</tr>
<tr>
<td>
Rate 1
</td>
<td align="right">
8.591
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.703)
</td>
</tr>
<tr>
<td>
Rate 2
</td>
<td align="right">
7.262
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.571)
</td>
</tr>
<tr>
<td>
outdegree-(density)
</td>
<td align="right">
&nbsp;–2.413
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.037)
</td>
</tr>
<tr>
<td>
reciprocity
</td>
<td align="right">
2.708
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.085)
</td>
</tr>
<tr>
<td colspan="9">
<hr>
</td>
</tr>
</tbody></table>
<table border="1" rules="none" frame="below">
<tbody><tr>
<td colspan="4" align="left">
† p &lt; 0.1; * p &lt; 0.05; ** p &lt; 0.01; *** p &lt; 0.001;
</td>
</tr>
<tr>
</tr>
<tr>
<td colspan="9" align="left">
all convergence t ratios &lt; 0.03.
</td>
</tr>
<tr>
</tr>
<tr>
<td colspan="9" align="left">
Overall maximum convergence ratio 0.03.
</td>
</tr>
<tr>
</tr>
</tbody></table>
</div>
<p>We now interpret the results from Model 1, beginning with an assessment of convergence, followed by the interpretation of the estimated parameters.</p>
<section id="convergence-assessment" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="convergence-assessment">Convergence Assessment</h5>
<p>Before interpreting parameter estimates, it’s essential to assess whether the estimation has converged adequately. In RSiena, convergence is assessed using two main criteria:</p>
<ol type="1">
<li><p>Overall maximum convergence ratio:&nbsp; This value summarizes how far the simulated statistics deviate from the observed ones. A value below 0.25 is generally considered acceptable, with values below 0.15 indicating very good convergence.</p></li>
<li><p>Individual convergence t-ratios:<br>
For each effect, the t-ratio compares the observed statistic to the average from the simulated networks. If the estimation has converged, these t-ratios should be close to zero. Values below 0.10 are ideal, and below 0.20 is generally acceptable.</p></li>
</ol>
<p>All convergence t-ratios in our Model 1 ouput are below 0.03, which suggests that the simulated statistics align closely with the observed network statistics for each parameter. This implies that the estimated model reproduces the key structural features of the observed data with high precision. Additionally, the overall maximum convergence ratio is 0.04, which is well below the commonly used threshold of 0.10, and even under the more conservative cutoff of 0.05. This means that none of the parameters are associated with poor convergence behavior. Taken together, these diagnostics confirm that the SAOM estimation process has stabilized, and the parameter estimates can be interpreted with confidence.</p>
</section>
<section id="rate-parameters" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="rate-parameters">Rate Parameters</h5>
<p>The rate parameters capture how frequently actors are given the opportunity to change their outgoing ties between two consecutive observation moments. These are modeled as intensities in a continuous-time Markov framework.</p>
<p>The estimates can be interpreted as follows:</p>
<ul>
<li><p><strong>Rate 1</strong>: Estimate = 8.580 (SE = 0.698)<br>
On average, each actor had about 9 opportunities to change a tie between waves 1 and 2.</p></li>
<li><p><strong>Rate 2</strong>: Estimate = 7.238 (SE = 0.605)<br>
On average, each actor had about 7 opportunities to change a tie between waves 2 and 3.</p></li>
</ul>
<p>These values do not indicate how many changes were actually made, but how often actors <em>could have</em> made a change. Since actors may choose not to modify a tie (i.e., retain the current state), the actual number of observed changes is typically lower than the number of opportunities.</p>
</section>
<section id="network-dynamics" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="network-dynamics">Network Dynamics</h5>
<p>Once an actor is given an opportunity to change a tie, their decision is guided by an objective function that evaluates alternative network states. Each effect included in the model represents a social mechanism influencing this decision.</p>
<p>The main effects in this model are:</p>
<ul>
<li><p><strong>Outdegree (density)</strong>: Estimate = –2.411 (SE = 0.041)<br>
Strong negative effect: actors are generally reluctant to form many ties.</p></li>
<li><p><strong>Reciprocity</strong>: Estimate = 2.705 (SE = 0.086)<br>
Strong positive effect: actors strongly prefer to reciprocate existing ties.</p></li>
</ul>
<p>Both estimates are statistically significant, as their t-ratios exceed 2.</p>
<blockquote class="blockquote">
<p><em>So, how do we interpret the parameter estimates?</em></p>
</blockquote>
<p><strong>Outdegree (density):</strong> <span class="math inline">\(\theta_{\text{out}} = -2.411\)</span><br>
A strong negative value indicates that actors prefer <em>sparser networks</em>. Forming new ties carries a cost, so additional ties are less likely unless offset by other favorable effects.</p>
<p><strong>Reciprocity:</strong> <span class="math inline">\(\theta_{\text{rec}} = 2.705\)</span><br>
A strong positive value reflects a preference for reciprocating existing ties. If another actor sends a tie to ego, ego is much more likely to return it.</p>
<p>These effects jointly determine how actors evaluate potential tie changes. The objective function for actor <span class="math inline">\(i\)</span> can be written as:</p>
<p><span class="math display">\[
f_i(\theta, Y^{(a)}) =
\theta_{\text{out}} \sum_{j} y^{(a)}_{ij}
+
\theta_{\text{rec}} \sum_{j} y^{(a)}_{ij} \, y^{(a)}_{ji}
\]</span></p>
<p>To understand this, consider two scenarios:</p>
<ol type="1">
<li><p><strong>Adding a reciprocated tie</strong><br>
Suppose <span class="math inline">\(y_{ji}(t) = 1\)</span> (the other actor has already sent a tie), and actor <span class="math inline">\(i\)</span> considers forming <span class="math inline">\(y_{ij} = 1\)</span>. The change in utility is:</p>
<p><span class="math display">\[
-2.411 + 2.705 = 0.294
\]</span></p>
<p>This yields a <strong>positive utility change</strong>, making the move likely.</p></li>
<li><p><strong>Adding a non-reciprocated tie</strong><br>
If <span class="math inline">\(y_{ji}(t) = 0\)</span>, the tie is not reciprocated. The utility change is:</p>
<p><span class="math display">\[
-2.411
\]</span></p>
<p>This is <strong>negative</strong>, making the change unlikely.</p></li>
</ol>
<p>Overall, the results indicate that actors strongly prefer reciprocated ties and are cautious about forming many new ties. Reciprocated ties generate positive utility, while unreciprocated ties are penalized. These patterns reflect well-known social mechanisms: a preference for mutual relationships and an aversion to the costs of maintaining many ties.</p>
</section>
</section>
<section id="model-2-structural-and-covariate-effects" class="level3" data-number="18.5.2">
<h3 data-number="18.5.2" class="anchored" data-anchor-id="model-2-structural-and-covariate-effects"><span class="header-section-number">18.5.2</span> Model 2: Structural and Covariate Effects</h3>
<p>Sociological theory suggests that, beyond general tendencies such as reciprocity and transitivity, actors are influenced by individual characteristics when forming or maintaining ties. In adolescent friendship networks, one of the most important predictors of tie formation is behavioral similarity, such as shared lifestyle choices or habits.</p>
<p>Having established a baseline SAOM using only endogenous structural effects (e.g., outdegree and reciprocity), we now extend the model to incorporate actor-level covariates. By including exogenous attributes such as sex and smoking behavior, we can investigate how individual characteristics shape tie formation in addition to structural patterns. This richer specification allows us to test more nuanced hypotheses about social selection and influence mechanisms within the network.</p>
<p>As discussed in <a href="#sec-exeffects" class="quarto-xref"><span>Section 18.3.7</span></a>, incorporating covariates into the objective function requires distinguishing between different types of effects:</p>
<ul>
<li><strong>Ego effects</strong>: How an actor’s own covariate value influences their tendency to form or maintain ties (e.g., do smokers send more ties?).</li>
<li><strong>Alter effects</strong>: How the recipient’s covariate value affects the likelihood of receiving a tie (e.g., are smokers more likely to be chosen as friends?).</li>
<li><strong>Similarity effects</strong>: Whether actors prefer to form ties with others who are similar to themselves (e.g., are adolescents more likely to befriend others with similar smoking behavior?).</li>
</ul>
<p>This extended specification remains actor-oriented and stochastic but adds an important layer of covariate-based preference. It allows us to distinguish between purely structural mechanisms and individual-level traits influencing network evolution, aligning more closely with theoretical insights from social psychology and adolescent health research.</p>
<p>Building on Model 1, which included only outdegree (density) and reciprocity, we now incorporate exogenous covariate information to obtain a more nuanced model of friendship dynamics.</p>
<p>In Model 2, we treat sex as a fixed covariate and smoking behavior as a changing covariate observed at each wave. We include the following additional effects:</p>
<ul>
<li><strong>Ego effect of smoking</strong>: Does an adolescent’s smoking status influence how many ties they send?</li>
<li><strong>Alter effect of smoking</strong>: Are smokers more likely to receive ties?</li>
<li><strong>Similarity in smoking</strong>: Are adolescents more likely to form ties with others who have similar smoking behavior?</li>
<li><strong>Sex effects</strong>: Do patterns of tie formation differ by sex?</li>
</ul>
<p>In sum, Model 2 captures not only structural tendencies in friendship formation but also how individual traits shape social dynamics, resulting in a more realistic and theoretically grounded model of network evolution.</p>
<p>We begin by converting the 3D network array into a <code>sienaDependent</code> object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert array into RSiena dependent object</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>siena_net <span class="ot">&lt;-</span> <span class="fu">sienaDependent</span>(net_array)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Like before, this object represents the longitudinal network that serves as the dependent variable in the SAOM. Different from before, we extract covariate values from the network’s node attributes. Sex (<code>sex.F</code>) is treated as a time-invariant covariate, while smoking behavior (<code>familysmoking</code>) is treated as time-varying across the three network waves.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract sex and recode to numeric: 1 = Female, 0 = Male</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>sex_char <span class="ot">&lt;-</span> <span class="fu">V</span>(glasgow_g2)<span class="sc">$</span>sex.F</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>sex_num <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sex_char <span class="sc">==</span> <span class="st">"F"</span>, <span class="dv">1</span>, <span class="fu">ifelse</span>(sex_char <span class="sc">==</span> <span class="st">"M"</span>, <span class="dv">0</span>, <span class="cn">NA</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to fixed covariate object</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>sex_cov <span class="ot">&lt;-</span> <span class="fu">coCovar</span>(sex_num)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract smoking behavior (assumed changing)</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>smoke1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">V</span>(glasgow_g1)<span class="sc">$</span>tobacco)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>smoke2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">V</span>(glasgow_g2)<span class="sc">$</span>tobacco)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>smoke3 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">V</span>(glasgow_g3)<span class="sc">$</span>tobacco)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>smoking_array <span class="ot">&lt;-</span> <span class="fu">cbind</span>(smoke1, smoke2, smoke3)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to changing covariate object</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>smoking_cov <span class="ot">&lt;-</span> <span class="fu">varCovar</span>(smoking_array)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Next we combine the network and covariates into a single Siena data object that will be used for estimation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data_mod2 <span class="ot">&lt;-</span> <span class="fu">sienaDataCreate</span>(siena_net, sex_cov, smoking_cov)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We define the effects to be included in the model. This includes structural effects (like outdegree, reciprocity, and transitive triplets) as well as ego, alter, and similarity effects for both sex and smoking covariates.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Start with the default effect set</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>my_effects <span class="ot">&lt;-</span> <span class="fu">getEffects</span>(data_mod2)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add structural effects</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>my_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(my_effects, outdegree, recip, transTrip)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add effects for sex</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>my_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  my_effects,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  egoX,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  altX,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  simX,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">interaction1 =</span> <span class="st">"sex_cov"</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Add effects for smoking</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>my_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  my_effects,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  egoX,</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>  altX,</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>  simX,</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">interaction1 =</span> <span class="st">"smoking_cov"</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We define the estimation settings using <code>sienaAlgorithmCreate()</code>. A seed is included to support reproducibility of the results.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>my_algorithm <span class="ot">&lt;-</span> <span class="fu">sienaAlgorithmCreate</span>(<span class="at">projname =</span> <span class="st">"saom_2"</span>, <span class="at">seed =</span> <span class="dv">1108</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We now estimate the model using the <code>siena07()</code> function, which runs the simulation-based estimation procedure.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>saom_2 <span class="ot">&lt;-</span> <span class="fu">siena07</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  my_algorithm,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_mod2,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> my_effects,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">batch =</span> <span class="cn">TRUE</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Finally, as before, we display the model results inline.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">siena_table</span>(saom_2, <span class="at">type =</span> <span class="st">"html"</span>, <span class="at">sig =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="{=html}">
<table border="1" rules="none" frame="hsides">
<tbody><tr>
<td>
Effect
</td>
<td>
&nbsp;&nbsp;&nbsp;par.
</td>
<td>
</td>
<td>
&nbsp;&nbsp;&nbsp; (s.e.)
</td>
</tr>
<tr>
<td>
Rate 1
</td>
<td align="right">
10.710
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(1.029)
</td>
</tr>
<tr>
<td>
Rate 2
</td>
<td align="right">
8.999
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.821)
</td>
</tr>
<tr>
<td>
outdegree-(density)
</td>
<td align="right">
&nbsp;–2.864
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.057)
</td>
</tr>
<tr>
<td>
reciprocity
</td>
<td align="right">
1.988
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.087)
</td>
</tr>
<tr>
<td>
transitive-triplets
</td>
<td align="right">
0.450
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.026)
</td>
</tr>
<tr>
<td>
sex-cov-alter
</td>
<td align="right">
&nbsp;–0.150
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.102)
</td>
</tr>
<tr>
<td>
sex-cov-ego
</td>
<td align="right">
0.152
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.113)
</td>
</tr>
<tr>
<td>
sex-cov-similarity
</td>
<td align="right">
0.919
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.096)
</td>
</tr>
<tr>
<td>
smoking-cov-alter
</td>
<td align="right">
0.112
</td>
<td align="left">
†
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.058)
</td>
</tr>
<tr>
<td>
smoking-cov-ego
</td>
<td align="right">
0.073
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.064)
</td>
</tr>
<tr>
<td>
smoking-cov-similarity
</td>
<td align="right">
0.381
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.115)
</td>
</tr>
<tr>
<td colspan="9">
<hr>
</td>
</tr>
</tbody></table>
<table border="1" rules="none" frame="below">
<tbody><tr>
<td colspan="4" align="left">
† p &lt; 0.1; * p &lt; 0.05; ** p &lt; 0.01; *** p &lt; 0.001;
</td>
</tr>
<tr>
</tr>
<tr>
<td colspan="9" align="left">
all convergence t ratios &lt; 0.09.
</td>
</tr>
<tr>
</tr>
<tr>
<td colspan="9" align="left">
Overall maximum convergence ratio 0.14.
</td>
</tr>
<tr>
</tr>
</tbody></table>
</div>
<section id="convergence-assessment-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="convergence-assessment-1">Convergence Assessment</h5>
<p>In Model 2, all convergence t-ratios are below 0.07, and the overall maximum convergence ratio is 0.11. This indicates good convergence, and the parameter estimates can be interpreted with confidence.</p>
</section>
<section id="rate-parameters-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="rate-parameters-1">Rate Parameters</h5>
<p>Rate parameters determine how frequently actors are given the opportunity to change their outgoing ties between observation moments. The estimated rates are:</p>
<ul>
<li><strong>Period 1</strong>: 10.761 (SE = 1.054)</li>
<li><strong>Period 2</strong>: 8.981 (SE = 0.850)</li>
</ul>
<p>These values suggest that, on average, each actor had approximately 11 opportunities to change a tie between waves 1 and 2, and about 9 opportunities between waves 2 and 3. Importantly, these values reflect the <em>rate of opportunities</em> for change, not the number of actual tie changes.</p>
</section>
<section id="network-dynamics-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="network-dynamics-1">Network Dynamics</h5>
<ul>
<li><p><strong>Outdegree (density)</strong>: <span class="math inline">\(-2.859\)</span> (SE = 0.053)<br>
This strong negative effect indicates that actors are generally reluctant to form many ties, leading to relatively sparse networks.</p></li>
<li><p><strong>Reciprocity</strong>: <span class="math inline">\(1.991\)</span> (SE = 0.089)<br>
This positive effect reflects a strong tendency for actors to reciprocate incoming ties.</p></li>
<li><p><strong>Transitive triplets</strong>: <span class="math inline">\(0.448\)</span> (SE = 0.026)<br>
This positive effect indicates a preference for triadic closure: if actor <span class="math inline">\(i\)</span> is tied to <span class="math inline">\(j\)</span>, and <span class="math inline">\(j\)</span> is tied to <span class="math inline">\(k\)</span>, then <span class="math inline">\(i\)</span> is more likely to form a tie to <span class="math inline">\(k\)</span>.</p></li>
</ul>
<p>Together, these effects capture key structural features of the network dynamics: sparsity, reciprocity, and local clustering.</p>
<p>We now turn to covariate-related effects, starting with sex:</p>
<ul>
<li><p><strong>Sex alter</strong>: <span class="math inline">\(-0.154\)</span> (SE = 0.097, not significant)<br>
There is no evidence that actors systematically prefer or avoid alters based on their sex.</p></li>
<li><p><strong>Sex ego</strong>: <span class="math inline">\(0.159\)</span> (SE = 0.103, not significant)<br>
This suggests no significant difference in tie-sending activity between male and female actors.</p></li>
<li><p><strong>Sex similarity</strong>: <span class="math inline">\(0.912\)</span> (SE = 0.093)<br>
This strong and statistically significant effect indicates a clear tendency toward same-sex friendships, i.e., sex-based homophily.</p></li>
</ul>
<p>The SAOM specification includes three effects based on the covariate <code>sex</code>, which is coded as <code>0</code> for boys and <code>1</code> for girls and is centered around its mean value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sex_cov)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4341085</code></pre>
</div>
</div>
<p>i.e., <span class="math inline">\(\bar{v} = 0.434\)</span>. Thus, approximately 43.4% of actors in this dataset are girls. In <code>RSiena</code>, covariates are mean-centered by default, ensuring that estimated effects are interpreted relative to the average actor.</p>
<p>After centering, the covariate values become: <span class="math display">\[
v_i - \bar{v} =
\begin{cases}
-0.434 &amp; \text{if actor } i \text{ is a boy} \\
\;\;0.566 &amp; \text{if actor } i \text{ is a girl}
\end{cases}
\]</span></p>
<p>Because covariates are mean-centered, the contribution of a potential tie <span class="math inline">\(y_{ij}\)</span> to the objective function depends on these centered values. The covariate-related part of the objective function for actor <span class="math inline">\(i\)</span>, when evaluating a candidate network <span class="math inline">\(Y^{(a)}\)</span>, can be written as:</p>
<p><span class="math display">\[
f_i(\theta, Y^{(a)}) =
\theta_{\text{ego}} (v_i - \bar{v}) \sum_{j} y^{(a)}_{ij}
\;+\;
\theta_{\text{alter}} \sum_{j} y^{(a)}_{ij} (v_j - \bar{v})
\;+\;
\theta_{\text{sim}} \sum_{j} y^{(a)}_{ij} \, I(v_i = v_j)
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(v_i\)</span> and <span class="math inline">\(v_j\)</span> are the covariate values (sex) for actors <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>, respectively (coded as 0 = boy, 1 = girl),</li>
<li><span class="math inline">\(\bar{v} = 0.434\)</span> is the sample mean of the covariate,</li>
<li><span class="math inline">\(y^{(a)}_{ij}\)</span> indicates the presence of a tie from <span class="math inline">\(i\)</span> to <span class="math inline">\(j\)</span> in the candidate network <span class="math inline">\(Y^{(a)}\)</span>,</li>
<li><span class="math inline">\(I(v_i = v_j)\)</span> is an indicator function equal to 1 if actors <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> share the same sex, and 0 otherwise.</li>
</ul>
<p><a href="#tbl-sexeff" class="quarto-xref">Table&nbsp;<span>18.2</span></a> below lists some example contributions to the objective function</p>
<div id="tbl-sexeff" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sexeff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.2: Sex-based contributions to the objective function under different ego-alter combinations.
</figcaption>
<div aria-describedby="tbl-sexeff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 29%">
<col style="width: 30%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Ego</th>
<th>Alter</th>
<th>Ego Term</th>
<th>Alter Term</th>
<th>Similarity Term</th>
<th>Total Contribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Male</td>
<td>Male</td>
<td><span class="math inline">\(0.159 \times (-0.434) = -0.069\)</span></td>
<td><span class="math inline">\(-0.154 \times (-0.434) = +0.067\)</span></td>
<td><span class="math inline">\(+0.912\)</span></td>
<td><span class="math inline">\(0.910\)</span></td>
</tr>
<tr class="even">
<td>Male</td>
<td>Female</td>
<td><span class="math inline">\(-0.069\)</span></td>
<td><span class="math inline">\(-0.154 \times 0.566 = -0.087\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(-0.156\)</span></td>
</tr>
<tr class="odd">
<td>Female</td>
<td>Male</td>
<td><span class="math inline">\(0.159 \times 0.566 = +0.090\)</span></td>
<td><span class="math inline">\(+0.067\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(0.157\)</span></td>
</tr>
<tr class="even">
<td>Female</td>
<td>Female</td>
<td><span class="math inline">\(+0.090\)</span></td>
<td><span class="math inline">\(-0.087\)</span></td>
<td><span class="math inline">\(+0.912\)</span></td>
<td><span class="math inline">\(0.915\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>These values show that same-sex ties, especially between girls, are more likely due to the strong similarity effect. Cross-sex ties are less likely, receiving lower utility in the objective function.</p>
<p>Next, we look at the behavioral covariate smoking. From the above output we note the following:</p>
<ul>
<li><p><strong>Smoking Alter</strong>: <span class="math inline">\(0.109\)</span> (SE = 0.061, not significant)<br>
Suggests no evidence that smoking status affects how attractive an actor is as a tie recipient.</p></li>
<li><p><strong>Smoking Ego</strong>: <span class="math inline">\(0.077\)</span> (SE = 0.063, not significant)<br>
No effect of smoking behavior on how active an actor is in sending ties.</p></li>
<li><p><strong>Smoking Similarity</strong>: <span class="math inline">\(0.380\)</span> (SE = 0.117)<br>
This positive and significant parameter indicates a clear tendency toward homophily with respect to smoking behavior: actors are more likely to form or maintain friendships with others who share a similar smoking status.</p></li>
</ul>
<p>Based on the model output and the centered smoking covariate, we interpret the smoking-related effects in the SAOM model. The smoking variable is ordinal with three categories: 1 = no smoking, 2 = occasional smoking, and 3 = regular smoking. The covariate is centered by subtracting its mean. In this case, the mean value is computed in R as:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(smoking_cov)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.377261</code></pre>
</div>
</div>
<p>We now interpret the covariate effects related to smoking behavior. In this model, smoking is treated as a three-level categorical covariate: 1 = Non-smoker, 2 = Occasional, 3 = Regular. The mean of the covariate, computed via <code>mean(smoke_cov)</code>, is approximately <span class="math inline">\(\bar{v} = 1.377\)</span>.</p>
<p>After mean-centering (as done by default in RSiena), the transformed values are:</p>
<p><span class="math display">\[
v_i - \bar{v} =
\begin{cases}
-0.377 &amp; \text{if } v_i = 1 \quad \text{(Non-smoker)} \\
0.623  &amp; \text{if } v_i = 2 \quad \text{(Occasional smoker)} \\
1.623  &amp; \text{if } v_i = 3 \quad \text{(Regular smoker)}
\end{cases}
\]</span></p>
<p>The contribution of a potential tie <span class="math inline">\(y_{ij}(t)\)</span> (from actor <span class="math inline">\(i\)</span> to actor <span class="math inline">\(j\)</span>) to the objective function is given by:</p>
<p><span class="math display">\[
\theta_{\text{ego}}(v_i - \bar{v})
+ \theta_{\text{alter}}(v_j - \bar{v})
+ \theta_{\text{sim}} \left(1 - \frac{|v_i - v_j|}{R_v}\right)
\]</span></p>
<p>where <span class="math inline">\(R_v\)</span> denotes the range of the covariate <span class="math inline">\(v\)</span> (here, <span class="math inline">\(R_v = 3 - 1 = 2\)</span>). Substituting the estimated parameter values from the model:</p>
<p><span class="math display">\[
0.077(v_i - 1.377) + 0.109(v_j - 1.377)
+ 0.380 \left(1 - \frac{|v_i - v_j|}{2} \right)
\]</span></p>
<p>This expression combines:</p>
<ul>
<li>an <strong>ego effect</strong>, capturing how smoking behavior influences how many ties actor <span class="math inline">\(i\)</span> tends to send,</li>
<li>an <strong>alter effect</strong>, capturing how smoking behavior affects how attractive actor <span class="math inline">\(j\)</span> is as a recipient of ties,</li>
<li>and a <strong>similarity effect</strong>, which rewards ties between actors with similar smoking levels.</li>
</ul>
<p><a href="#tbl-smokeeff" class="quarto-xref">Table&nbsp;<span>18.3</span></a> illustrates how these smoking-related covariate effects contribute to the objective function. Each cell reports the total contribution associated with a potential tie from ego <span class="math inline">\(i\)</span> to alter <span class="math inline">\(j\)</span>, given their respective smoking levels.</p>
<div id="tbl-smokeeff" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-smokeeff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.3: Smoking-related contributions to the objective function under different ego-alter combinations.
</figcaption>
<div aria-describedby="tbl-smokeeff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Ego</th>
<th>Alter</th>
<th>Ego Term</th>
<th>Alter Term</th>
<th>Similarity Term</th>
<th>Total Contribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Non-smoker</td>
<td>Non-smoker</td>
<td><span class="math inline">\(0.077 \cdot (-0.377) = -0.029\)</span></td>
<td><span class="math inline">\(0.109 \cdot (-0.377) = -0.041\)</span></td>
<td><span class="math inline">\(0.380 \cdot 1 = 0.380\)</span></td>
<td><span class="math inline">\(0.310\)</span></td>
</tr>
<tr class="even">
<td>Non-smoker</td>
<td>Occasional</td>
<td><span class="math inline">\(-0.029\)</span></td>
<td><span class="math inline">\(0.109 \cdot 0.623 = 0.068\)</span></td>
<td><span class="math inline">\(0.380 \cdot (1 - 0.5) = 0.190\)</span></td>
<td><span class="math inline">\(0.229\)</span></td>
</tr>
<tr class="odd">
<td>Non-smoker</td>
<td>Regular</td>
<td><span class="math inline">\(-0.029\)</span></td>
<td><span class="math inline">\(0.109 \cdot 1.623 = 0.177\)</span></td>
<td><span class="math inline">\(0.380 \cdot (1 - 1) = 0\)</span></td>
<td><span class="math inline">\(0.148\)</span></td>
</tr>
<tr class="even">
<td>Occasional</td>
<td>Non-smoker</td>
<td><span class="math inline">\(0.077 \cdot 0.623 = 0.048\)</span></td>
<td><span class="math inline">\(-0.041\)</span></td>
<td><span class="math inline">\(0.190\)</span></td>
<td><span class="math inline">\(0.197\)</span></td>
</tr>
<tr class="odd">
<td>Occasional</td>
<td>Occasional</td>
<td><span class="math inline">\(0.048\)</span></td>
<td><span class="math inline">\(0.068\)</span></td>
<td><span class="math inline">\(0.380\)</span></td>
<td><span class="math inline">\(0.496\)</span></td>
</tr>
<tr class="even">
<td>Occasional</td>
<td>Regular</td>
<td><span class="math inline">\(0.048\)</span></td>
<td><span class="math inline">\(0.177\)</span></td>
<td><span class="math inline">\(0.190\)</span></td>
<td><span class="math inline">\(0.415\)</span></td>
</tr>
<tr class="odd">
<td>Regular</td>
<td>Non-smoker</td>
<td><span class="math inline">\(0.077 \cdot 1.623 = 0.125\)</span></td>
<td><span class="math inline">\(-0.041\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(0.084\)</span></td>
</tr>
<tr class="even">
<td>Regular</td>
<td>Occasional</td>
<td><span class="math inline">\(0.125\)</span></td>
<td><span class="math inline">\(0.068\)</span></td>
<td><span class="math inline">\(0.190\)</span></td>
<td><span class="math inline">\(0.383\)</span></td>
</tr>
<tr class="odd">
<td>Regular</td>
<td>Regular</td>
<td><span class="math inline">\(0.125\)</span></td>
<td><span class="math inline">\(0.177\)</span></td>
<td><span class="math inline">\(0.380\)</span></td>
<td><span class="math inline">\(0.682\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We see from <a href="#tbl-smokeeff" class="quarto-xref">Table&nbsp;<span>18.3</span></a> that actors with similar smoking behavior are more likely to form ties, especially regular-to-regular smokers, indicating a strong homophily pattern. The ego and alter terms slightly amplify or reduce this tendency depending on individual smoking levels.</p>
</section>
</section>
<section id="model-3-network-and-behavioral-co-evolution" class="level3" data-number="18.5.3">
<h3 data-number="18.5.3" class="anchored" data-anchor-id="model-3-network-and-behavioral-co-evolution"><span class="header-section-number">18.5.3</span> Model 3: Network and Behavioral Co-Evolution</h3>
<p>We now estimate a co-evolution model in which the friendship network and smoking behavior are treated as jointly dependent processes. The network process models changes in friendship ties, while the behavioral process models changes in actors’ smoking behavior over time.</p>
<p>In this specification, smoking enters the model in two ways. First, smoking is used in the network objective function to test <strong>selection</strong> effects: whether actors form or maintain ties based on smoking behavior. Second, smoking is modeled as a behavioral dependent variable to test <strong>influence</strong> effects: whether actors adjust their smoking behavior in response to their friends.</p>
<blockquote class="blockquote">
<p><em>Key point: <code>smoking_beh</code> is no longer only a covariate. It is a behavioral dependent variable, while also being used to explain network selection.</em></p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Dependent variables ---</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>siena_net <span class="ot">&lt;-</span> <span class="fu">sienaDependent</span>(net_array)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>smoking_beh <span class="ot">&lt;-</span> <span class="fu">sienaDependent</span>(smoking_array, <span class="at">type =</span> <span class="st">"behavior"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Covariate ---</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>sex_cov <span class="ot">&lt;-</span> <span class="fu">coCovar</span>(sex_num)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Data object ---</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>data_coev <span class="ot">&lt;-</span> <span class="fu">sienaDataCreate</span>(</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  siena_net,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  smoking_beh,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  sex_cov</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Effects ---</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>eff <span class="ot">&lt;-</span> <span class="fu">getEffects</span>(data_coev)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="co"># NETWORK DYNAMICS</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>eff <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>  eff,</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  outdegree,</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>  recip,</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>  transTrip,</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> <span class="st">"siena_net"</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a><span class="co"># sex effects</span></span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>eff <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>  eff,</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>  egoX,</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>  altX,</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>  simX,</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> <span class="st">"siena_net"</span>,</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">interaction1 =</span> <span class="st">"sex_cov"</span></span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a><span class="co"># smoking selection effects</span></span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>eff <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>  eff,</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>  egoX,</span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>  altX,</span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>  simX,</span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> <span class="st">"siena_net"</span>,</span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">interaction1 =</span> <span class="st">"smoking_beh"</span></span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------</span></span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a><span class="co"># BEHAVIOR DYNAMICS</span></span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------</span></span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-53"><a href="#cb24-53" aria-hidden="true" tabindex="-1"></a><span class="co"># shape effects</span></span>
<span id="cb24-54"><a href="#cb24-54" aria-hidden="true" tabindex="-1"></a>eff <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(eff, linear, quad, <span class="at">name =</span> <span class="st">"smoking_beh"</span>)</span>
<span id="cb24-55"><a href="#cb24-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-56"><a href="#cb24-56" aria-hidden="true" tabindex="-1"></a><span class="co"># network position effects</span></span>
<span id="cb24-57"><a href="#cb24-57" aria-hidden="true" tabindex="-1"></a>eff <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(</span>
<span id="cb24-58"><a href="#cb24-58" aria-hidden="true" tabindex="-1"></a>  eff,</span>
<span id="cb24-59"><a href="#cb24-59" aria-hidden="true" tabindex="-1"></a>  indeg,</span>
<span id="cb24-60"><a href="#cb24-60" aria-hidden="true" tabindex="-1"></a>  outdeg,</span>
<span id="cb24-61"><a href="#cb24-61" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> <span class="st">"smoking_beh"</span>,</span>
<span id="cb24-62"><a href="#cb24-62" aria-hidden="true" tabindex="-1"></a>  <span class="at">interaction1 =</span> <span class="st">"siena_net"</span></span>
<span id="cb24-63"><a href="#cb24-63" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-64"><a href="#cb24-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-65"><a href="#cb24-65" aria-hidden="true" tabindex="-1"></a><span class="co"># social influence</span></span>
<span id="cb24-66"><a href="#cb24-66" aria-hidden="true" tabindex="-1"></a>eff <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(</span>
<span id="cb24-67"><a href="#cb24-67" aria-hidden="true" tabindex="-1"></a>  eff,</span>
<span id="cb24-68"><a href="#cb24-68" aria-hidden="true" tabindex="-1"></a>  avAlt,</span>
<span id="cb24-69"><a href="#cb24-69" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> <span class="st">"smoking_beh"</span>,</span>
<span id="cb24-70"><a href="#cb24-70" aria-hidden="true" tabindex="-1"></a>  <span class="at">interaction1 =</span> <span class="st">"siena_net"</span></span>
<span id="cb24-71"><a href="#cb24-71" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We define the estimation settings using <code>sienaAlgorithmCreate()</code> and estimate the co-evolution model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>alg <span class="ot">&lt;-</span> <span class="fu">sienaAlgorithmCreate</span>(<span class="at">projname =</span> <span class="st">"saom_coev"</span>, <span class="at">seed =</span> <span class="dv">1108</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>saom_coev <span class="ot">&lt;-</span> <span class="fu">siena07</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  alg,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_coev,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> eff,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">batch =</span> <span class="cn">TRUE</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Finally, we display the model results.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">siena_table</span>(saom_coev, <span class="at">type =</span> <span class="st">"html"</span>, <span class="at">sig =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="{=html}">
<table border="1" rules="none" frame="hsides">
<tbody><tr>
<td>
Effect
</td>
<td>
&nbsp;&nbsp;&nbsp;par.
</td>
<td>
</td>
<td>
&nbsp;&nbsp;&nbsp; (s.e.)
</td>
</tr>
<tr>
<td colspan="4" align="left">
Network Dynamics
</td>
</tr>
<tr>
</tr>
<tr>
<td>
constant-siena-net-rate-(period-1)
</td>
<td align="right">
10.639
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(1.084)
</td>
</tr>
<tr>
<td>
constant-siena-net-rate-(period-2)
</td>
<td align="right">
8.916
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.921)
</td>
</tr>
<tr>
<td>
outdegree-(density)
</td>
<td align="right">
&nbsp;–2.870
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.068)
</td>
</tr>
<tr>
<td>
reciprocity
</td>
<td align="right">
1.987
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.092)
</td>
</tr>
<tr>
<td>
transitive-triplets
</td>
<td align="right">
0.446
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.030)
</td>
</tr>
<tr>
<td>
sex-cov-alter
</td>
<td align="right">
&nbsp;–0.179
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.116)
</td>
</tr>
<tr>
<td>
sex-cov-ego
</td>
<td align="right">
0.196
</td>
<td align="left">
†
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.117)
</td>
</tr>
<tr>
<td>
sex-cov-similarity
</td>
<td align="right">
0.942
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.111)
</td>
</tr>
<tr>
<td>
smoking-beh-alter
</td>
<td align="right">
0.125
</td>
<td align="left">
†
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.070)
</td>
</tr>
<tr>
<td>
smoking-beh-ego
</td>
<td align="right">
0.051
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.070)
</td>
</tr>
<tr>
<td>
smoking-beh-similarity
</td>
<td align="right">
0.513
</td>
<td align="left">
**
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.174)
</td>
</tr>
<tr>
<td colspan="9">
<hr>
</td>
</tr>
<tr>
<td colspan="4" align="left">
Behaviour Dynamics
</td>
</tr>
<tr>
</tr>
<tr>
<td>
rate-smoking-beh-(period-1)
</td>
<td align="right">
4.664
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(3.202)
</td>
</tr>
<tr>
<td>
rate-smoking-beh-(period-2)
</td>
<td align="right">
4.441
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(1.539)
</td>
</tr>
<tr>
<td>
smoking-beh-linear-shape
</td>
<td align="right">
&nbsp;–4.529
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.791)
</td>
</tr>
<tr>
<td>
smoking-beh-quadratic-shape
</td>
<td align="right">
3.142
</td>
<td align="left">
***
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.431)
</td>
</tr>
<tr>
<td>
smoking-beh-indegree
</td>
<td align="right">
0.196
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.205)
</td>
</tr>
<tr>
<td>
smoking-beh-outdegree
</td>
<td align="right">
&nbsp;–0.045
</td>
<td align="left">
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.233)
</td>
</tr>
<tr>
<td>
smoking-beh-average-alter
</td>
<td align="right">
1.908
</td>
<td align="left">
*
</td>
<td align="right">
&nbsp;&nbsp;&nbsp;(0.798)
</td>
</tr>
<tr>
<td colspan="9">
<hr>
</td>
</tr>
</tbody></table>
<table border="1" rules="none" frame="below">
<tbody><tr>
<td colspan="4" align="left">
† p &lt; 0.1; * p &lt; 0.05; ** p &lt; 0.01; *** p &lt; 0.001;
</td>
</tr>
<tr>
</tr>
<tr>
<td colspan="9" align="left">
all convergence t ratios &lt; 0.43.
</td>
</tr>
<tr>
</tr>
<tr>
<td colspan="9" align="left">
Overall maximum convergence ratio 1.53.
</td>
</tr>
<tr>
</tr>
</tbody></table>
</div>
<p>The co-evolution model shows the following key patterns:</p>
<ul>
<li><strong>Network structure</strong>
<ul>
<li>Strong negative outdegree <span class="math inline">\(\Rightarrow\)</span> sparse network</li>
<li>Strong positive reciprocity <span class="math inline">\(\Rightarrow\)</span> mutual ties are strongly favored</li>
<li>Positive transitivity <span class="math inline">\(\Rightarrow\)</span> evidence of triadic closure</li>
</ul></li>
<li><strong>Sex effects</strong>
<ul>
<li>Strong positive similarity <span class="math inline">\(\Rightarrow\)</span> clear same-sex homophily</li>
<li>Ego and alter effects not significant <span class="math inline">\(\Rightarrow\)</span> no strong differences in tie activity by sex</li>
</ul></li>
<li><strong>Smoking and network selection</strong>
<ul>
<li>Positive similarity effect <span class="math inline">\(\Rightarrow\)</span> friendships are formed between actors with similar smoking behavior (selection)</li>
<li>Ego and alter effects not significant <span class="math inline">\(\Rightarrow\)</span> smoking does not affect sending/receiving ties overall</li>
</ul></li>
<li><strong>Behavioral dynamics (smoking)</strong>
<ul>
<li>Negative linear + positive quadratic shape <span class="math inline">\(\Rightarrow\)</span> tendency toward moderate smoking levels</li>
<li>Average alter effect positive and significant <span class="math inline">\(\Rightarrow\)</span> evidence of social influence (actors adjust smoking toward friends)</li>
<li>Indegree and outdegree effects not significant <span class="math inline">\(\Rightarrow\)</span> network position not strongly related to smoking</li>
</ul></li>
</ul>
<p>Overall, the results suggest that network evolution is primarily driven by reciprocity, triadic closure, and homophily. In addition, there is evidence for both selection and influence processes in the co-evolution of networks and behavior: actors tend to form ties with others who have similar smoking behavior, and they also adjust their behavior over time to become more similar to their friends.</p>
<p>Given that the overall maximum convergence ratio exceeds the recommended threshold, the model has not fully converged. Therefore, the parameter estimates should be interpreted with caution, as they may not reliably reflect the underlying data-generating process.</p>
<p>To improve convergence, one can adjust the estimation settings (e.g., increase the number of simulation iterations via <code>n3</code>, modify phase lengths, or tune other algorithm parameters). Details on these options can be found in the RSiena Manual <span class="citation" data-cites="ripley2011manual">(<a href="#ref-ripley2011manual" role="doc-biblioref">Ripley et al. 2011</a>)</span>, particularly in the sections on:</p>
<ul>
<li><code>sienaAlgorithmCreate()</code> (algorithm settings and iteration control)</li>
<li>Convergence diagnostics and troubleshooting guidelines</li>
</ul>
<p>See also the RSiena help pages in R: <code>?sienaAlgorithmCreate</code> and <code>?siena07</code>.</p>


</section>
</section>
<section id="bibliography" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-ripley2011manual" class="csl-entry" role="listitem">
Ripley, Ruth M, Tom AB Snijders, Zsófia Boda, András Vörös, and Paulina Preciado. 2011. <span>“Manual for RSIENA.”</span> <em>University of Oxford, Department of Statistics, Nuffield College</em> 1: 2011.
</div>
<div id="ref-snijders1996stochastic" class="csl-entry" role="listitem">
Snijders, Tom AB. 1996. <span>“Stochastic Actor-Oriented Models for Network Change.”</span> <em>Journal of Mathematical Sociology</em> 21 (1-2): 149–72.
</div>
<div id="ref-west1996s50" class="csl-entry" role="listitem">
West, P, and H Sweeting. 1996. <span>“Background, Rationale and Design of the West of Scotland 11 to 16 Study.”</span> <em>MRC Medical Sociology Unit Working Paper</em>, no. 52: 1.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/schochastics\.io\/R4SNA");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../inferential/ergm.html" class="pagination-link" aria-label="Exponential Random Graph Models (ERGMs)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Exponential Random Graph Models (ERGMs)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../inferential/rem.html" class="pagination-link" aria-label="Relational Event Models (REMs)">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Relational Event Models (REMs)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>R for Social Network Analysis was written by Termeh Shafie and David Schoch.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/schochastics/R4SNA/edit/main/inferential/saom.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/schochastics/R4SNA/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>