project:
  type: book

book:
  title: "R4SNA - R for Social Network Analysis"
  author: 
    - name: "David Schoch"
    - name: "Termeh Shafie"
  date: "26/02/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - network-data.qmd
    - part: "Descriptive Network Analysis"
      chapters:
        - descriptives-intro.qmd
        - descriptives-basic.qmd
        - centrality-basic.qmd
        - centrality-advanced.qmd
        - clustering.qmd
        - two-mode-networks.qmd
        - signed-networks.qmd
        - ego-networks.qmd
    - part: "Network Visualization"
      chapters: 
        - visualization-intro.qmd
        - ggraph-basics.qmd
        - example-viz.qmd
        - enhance-viz.qmd
        - advanced-viz.qmd
        - further-viz.qmd
    - part: "Inferential Network Analysis"
    - part: "Tidy Network Analysis"
      chapters:
        - tidygraph-intro.qmd
        - tidygraph-basics.qmd
        - tidygraph-descriptive.qmd
        - tidygraph-summary.qmd
    - summary.qmd
    - references.qmd
    


bibliography: references.bib

format:
  html:
    theme: cosmo
    
execute: 
  freeze: auto
