project:
  type: book

book:
  title: "R4SNA - R for Social Network Analysis"
  author: 
    - name: "David Schoch"
    - name: "Termeh Shafie"
  date: "26/02/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - network-data.qmd
    - part: descriptives.qmd
      chapters:
        - descriptives-basic.qmd
        - centrality-basic.qmd
        - centrality-advanced.qmd
        - clustering.qmd
        - two-mode-networks.qmd
        - signed-networks.qmd
        - ego-networks.qmd
    - part: visualization.qmd
      chapters: 
        - ggraph-basics.qmd
        - ggraph-advanced.qmd
        - enhance-viz.qmd
        - interactive-viz.qmd
    - part: inferential.qmd
    - part: tidygraph.qmd
      chapters:
        - tidygraph-basics.qmd
        - tidygraph-descriptive.qmd
        - tidygraph-summary.qmd
    - summary.qmd
    - references.qmd
    


bibliography: references.bib

format:
  html:
    theme: cosmo
    
execute: 
  freeze: auto
