lang: en

project:
  type: book

book:
  title: "R for Social Network Analysis"
  page-footer:
    left: |
      R for Social Network Analysis was written by Termeh Shafie and David Schoch.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  # cover-image: cover.png
  # favicon: cover.png
  site-url: https://schochastics.io/R4SNA
  repo-url: https://github.com/schochastics/R4SNA
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - network-data.qmd
    - part: "Descriptive Network Analysis"
      chapters:
        - descriptive/introduction.qmd
        - descriptive/descriptives-basic.qmd
        - descriptive/centrality-basic.qmd
        - descriptive/clustering.qmd
        - descriptive/two-mode-networks.qmd
        - descriptive/signed-networks.qmd
        - descriptive/ego-networks.qmd
        - descriptive/netropy.qmd
    - part: "Network Visualization"
      chapters: 
        - visualization/introduction.qmd
        - visualization/ggraph-basics.qmd
        - visualization/ggraph-advanced.qmd
        - visualization/enhance-viz.qmd
        - visualization/interactive-viz.qmd
    - part: "Inferential Network Analysis"
      chapters: 
        - inferential/introduction.qmd
        - inferential/non-parametric.qmd
        - inferential/rgm.qmd
        - inferential/ergm.qmd
        - inferential/saom.qmd
        - inferential/rem.qmd
    - part: "Tidy Network Analysis"
      chapters:
        - tidy/introduction.qmd
        - tidy/tidygraph-basics.qmd
        - tidy/tidygraph-descriptive.qmd
  appendices:
  - appendix/ucnets-egor.qmd
  - appendix/rem-frozen-data.qmd
  
bibliography: references.bib
reference-section-title: References


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 5
    code-link: true
    author-meta: "Termeh Shafie and David Schoch"
    open-graph: true
    twitter-card: true
  # pdf:
  #   documentclass: scrbook
  #   papersize: a4
  #   geometry:
  #     - top=25mm
  #     - bottom=25mm
  #     - left=25mm
  #     - right=25mm
  #   toc: true
  #   toc-depth: 2
  #   number-sections: true
  #   colorlinks: true
  #   code-block-bg: true
  #   fig-pos: "H"
  #   fig-format: png
  #   fig-dpi: 300
  #   keep-tex: false

execute:
  freeze: auto
