project:
  type: book

book:
  title: "R for Social Network Analysis"
  page-footer:
    left: |
      R for Social Network Analysis was written by David Schoch, and Termeh Shafie.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  site-url: https://schochastics.io/R4SNA
  repo-url: https://github.com/schochastics/R4sna
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - network-data.qmd
    - part: "Descriptive Network Analysis"
      chapters:
        - descriptive/introduction.qmd
        - descriptive/descriptives-basic.qmd
        - descriptive/centrality-basic.qmd
        - descriptive/centrality-advanced.qmd
        - descriptive/clustering.qmd
        - descriptive/two-mode-networks.qmd
        - descriptive/signed-networks.qmd
        - descriptive/ego-networks.qmd
    - part: "Network Visualization"
      chapters: 
        - visualization/introduction.qmd
        - visualization/ggraph-basics.qmd
        - visualization/ggraph-advanced.qmd
        - visualization/enhance-viz.qmd
        - visualization/interactive-viz.qmd
    - part: "Inferential Network Analysis"
      chapters: 
        - inferential/introduction.qmd
        - inferential/non-parametric.qmd
        - inferential/rgm.qmd
        - inferential/ergm.qmd
        - inferential/saom.qmd
        - inferential/rem.qmd
    - part: "Tidy Network Analysis"
      chapters:
        - tidy/introduction.qmd
        - tidy/tidygraph-basics.qmd
        - tidy/tidygraph-descriptive.qmd
        - tidy/tidygraph-summary.qmd
    - part: "Additional Tools"
      chapters:
        - additional/introduction.qmd
        - additional/netropy.qmd
        - additional/multigraphr.qmd
    - summary.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "David Schoch, and Termeh Shafie"
    
execute: 
  freeze: auto
