project:
  type: book

book:
  title: "R4SNA - R for Social Network Analysis"
  author: 
    - name: "David Schoch"
    - name: "Termeh Shafie"
  date: "26/02/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Descriptive Network Analysis"
    - part: "Network Visualization"
    - part: "Inferential Network Analysis"
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute: 
  freeze: auto

