{
  "hash": "67d783e5b2f0f02aa4ad01d344c46475",
  "result": {
    "engine": "knitr",
    "markdown": "# Relational Event Models (REMs)\n\nImagine you are watching a group of people at a party. At any moment, someone\nmight start a conversation with someone else. The question is: *who will start\ntalking to whom next?*\n\nMany different interactions are possible, but only one actually happens.\nUnderstanding why that particular interaction occurs rather than any of the\nothers is the kind of problem that event-based statistical models are designed\nto address.\n\nOne approach to studying such processes is Cox regression, a statistical method\nused to analyze events that unfold over time. Instead of focusing only on\nwhether something happens, Cox regression models the rate at which events occur,\nand how different factors make an event more or less likely to happen sooner\nrather than later. In intuitive terms, it helps us understand which possible\nevents are \"more likely to happen next\" given the current situation and the\ncharacteristics of the actors involved.\n\n**Relational Event Models (REMs)** build on this logic to study social\ninteractions as they occur in sequence. Rather than treating relationships as\nstatic connections between individuals, REMs conceptualize networks as streams\nof actions (such as messages, conversations, or interactions) unfolding over\ntime.\n\nTraditional approaches in social network analysis have typically relied on two\ndominant perspectives. On the one hand, **static network models**, such as\nExponential Random Graph Models (@sec-ergm), focus on long-term equilibrium\npatterns in aggregated networks. On the other hand, **longitudinal network\nmodels**, such as Stochastic Actor Oriented Models (@sec-saom), examine how\nrelatively stable ties evolve across discrete time periods. Both approaches\nemphasize relationships as relatively enduring structures observed over bounded\nintervals.\n\nIn contrast, Relational Event Models shift attention to the fine-grained\nsequence and timing of discrete behavioral events. Rather than treating ties as\nfixed or slowly evolving entities, REM conceptualizes networks as streams of\ninteraction. Social structure is not simply observed, it is continuously\nproduced and reproduced through temporally ordered actions.\n\nA key distinction between ERGMs and REM lies in the question each approach seeks\nto answer. ERGMs ask whether a particular *network structure* is likely to\nemerge within a defined time window. REM, by contrast, asks:\n\n> Given the history of prior interactions, how likely is it that actor *a* will\n> direct an event toward actor *b* at a specific moment?\n\nThis represents a conceptual shift from modeling cumulative structures to\nmodeling event rates. In REM, the fundamental unit of analysis is not the tie,\nbut the event. Each event is understood as occurring within a dynamic system\nshaped by prior interactions. The probability (or rate) of a new event depends\non the evolving history of the network.\n\nRelational Event Models pursue two central analytic objectives:\n\n1. **Prediction**: Accurately predict who will send a message to whom, given the\n   prior sequence of events.\n2. **Explanation**: Identify the factors that influence the propensity for\n   interaction between two actors.\n\nThese factors may include:\n\n- **Node attributes** (e.g., status, role, demographic characteristics)\n- **Dyadic attributes** (e.g., similarity, shared group membership)\n- **Historical patterns of communication** (e.g., reciprocity, repetition,\n  transitive closure)\n- **Environmental or contextual factors** (e.g., time constraints, institutional\n  settings)\n\nBy incorporating these elements, REM enables researchers to test hypotheses\nabout the mechanisms that generate interaction sequences.\n\nThis chapter introduces the theoretical foundations and methodological tools of\nRelational Event Models. It begins by situating REM within the broader landscape\nof network analysis and clarifying its event-centered logic. It then develops\nthe core components of the model (event histories, risk sets, and rate\nfunctions) before examining how structural, attribute-based, and contextual\neffects are specified and interpreted.\n\nThrough this approach, we will see how REM provides a rigorous and flexible\nframework for modeling dynamic interaction processes, illuminating the\nmicro-level mechanisms through which social structure emerges over time.\n\n## Packages Needed for this Chapter\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(relevent)\n```\n:::\n\n\n::: {.callout-note}\n\n\n# Note on Alternative Software for Relational Event Models\n\nIn this chapter we use the `relevent` package to estimate relational event\nmodels. The package implements the framework introduced by @butts2008 and\nprovides a straightforward and widely used approach for estimating REMs from\nsequences of dyadic interactions.\n\nSeveral alternative implementations are also available. The `goldfish` package\nprovides a more modern and flexible framework for relational event modeling. In\ncontrast to `relevent`, which requires users to manually construct event\nstatistics and covariates, `goldfish` offers a formula-based interface that\nallows endogenous effects and actor attributes to be specified directly within\nthe model. The package also supports a broader range of structural effects and\nis designed to scale more efficiently to larger event datasets.\n\nAnother option is the `rem` package, which provides a simplified implementation\nof relational event models with a more modern interface than `relevent`. In\nparticular, `rem` integrates more naturally with tidyverse-style workflows,\nmaking it convenient for researchers who prefer a tidy data structure and\nformula-based model specification. While it supports many core REM features, it\nis currently less widely used in applied research than `relevent` or `goldfish`.\n\nDespite these differences in implementation, the underlying statistical logic\nremains the same across packages: relational event models estimate the intensity\nof possible interactions and compare competing events within a risk set. For\nintroductory applications and teaching purposes, `relevent` remains a convenient\nand transparent tool, while `goldfish` or `rem` may be preferable in more\ncomplex or larger-scale analyses.\n\n:::\n\n## Model Specification\n\nWhen relational event data contain information about the *order* of events (but\nnot their precise timestamps), the modeling problem can be framed in terms of\nrelative event hazards. This situation is mathematically equivalent to\nestimating a Cox proportional hazards model (or Cox regression) over a sequence\nof discrete event opportunities [@butts2008]. Rather than modeling the exact\ntiming of events, we instead model the relative rate (or intensity) at which a\nparticular interaction occurs next, given the prior history of events.\n\n### Formal Specification of the Relational Event Model\n\nFollowing @butts2008, relational event models are formulated in terms of a\n**conditional event intensity function**, which represents the instantaneous\nrate at which a specific interaction occurs given the past event history.\n\nLet $\\lambda_{ab}(t)$ denote the intensity of an event from actor $a$ to actor\n$b$ at time $t$, given the history of past events $H_t$. The model is specified\nas\n\n$$\n\\lambda_{ab}(t \\mid H_t) = \\lambda_0(t)\\exp(\\theta^\\top s_{ab}(t))\n$$\n\nwhere:\n\n- $\\lambda_{ab}(t)$ is the **event intensity** for interaction $a \\rightarrow b$\n  at time $t$,\n- $\\lambda_0(t)$ is the **baseline rate** of events,\n- $s_{ab}(t)$ is a vector of **statistics** describing the event (e.g., actor\n  attributes, dyadic covariates, or history-based structural effects),\n- $\\theta$ is a vector of **model parameters**.\n\nThe statistics $s_{ab}(t)$ are typically functions of the event history, meaning\nthey evolve as new interactions occur.\n\nWhen only the *order* of events is observed (rather than exact timestamps),\ninference can proceed using the partial likelihood, which compares the intensity\nof the observed event with the intensities of all other possible events in the\nrisk set $R_t$. The probability that a specific event $a \\rightarrow b$ occurs\nnext is therefore\n\n$$\nP(a \\rightarrow b \\text{ occurs next}) =\n\\frac{\\exp(\\theta^\\top s_{ab}(t))}\n{\\sum_{(i,j)\\in R_t}\\exp(\\theta^\\top s_{ij}(t))}\n$$\n\nwhere $R_t$ denotes the set of all interactions that could occur at time $t$.\n\nThis formulation shows that relational event models explain which interaction\noccurs next by comparing the relative intensities of all competing events in the\nrisk set.\n\nAlthough REMs are typically written using event intensities, estimation for\nordered event data relies on the same likelihood logic as Cox proportional\nhazards models.\n\n### Relational Event Data Structure\n\nTo apply the event-based hazard logic to social interactions, we need a specific\ntype of data structure known as relational event data. Rather than representing\nrelationships as static ties between actors, relational event data record\nindividual interactions as they occur over time.\n\nEach observation typically includes:\n\n- a **sender** (the actor initiating the interaction),\n- a **receiver** (the actor targeted by the interaction),\n- and a **time or order** indicating when the interaction occurred.\n\nFor example, a relational event dataset describing communication might look like\nthis:\n\n  | time | sender | receiver |\n  | ---- | ------ | -------- |\n  | 1    | Alice  | Bob      |\n  | 2    | Bob    | Alice    |\n  | 3    | Carol  | Alice    |\n\nIn this format, the network is not represented as a fixed structure but as a\nchronological sequence of actions. The history of past events becomes crucial,\nbecause earlier interactions influence the likelihood of future ones. For\ninstance, a reply may be more likely after receiving a message, or individuals\nwho communicate frequently may continue interacting.\n\nRelational event data therefore allow researchers to study *how interaction\nprocesses unfold moment by moment*, rather than only observing the final network\nstructure.\n\n### Intuition: Competing Events\n\nOne intuitive way to think about Cox regression is as a race. Suppose several\nrunners are lined up at the starting line. Each runner represents a possible\nevent (for example, a person sending a message to another person). Each runner\nruns at a different speed depending on certain characteristics:\n\n- Some runners have better shoes (a helpful covariate).\n- Some runners are tired (a negative covariate).\n- Some runners have run this race before and know the route (history effects).\n\nThe runner who reaches the finish line first is the event that occurs. Cox\nregression does not try to predict the exact finishing time. Instead, it focuses\non who is most likely to win the race, given their characteristics.\n\nAt the core of Cox regression is the idea of a **hazard**. The hazard represents\nthe instantaneous chance that an event happens right now, given that it has not\nyet occurred. A helpful analogy is popcorn in a microwave. Imagine many popcorn\nkernels heating up at the same time. At any moment, each kernel has some chance\nof popping. Some kernels pop early, others later. Cox regression models what\nmakes certain kernels more likely to pop sooner. In social science terms, we\nmight ask questions such as:\n\n- Does previous interaction make a new message more likely?\n- Are people more likely to communicate with similar others?\n- Does status increase the chance that someone initiates contact?\n\nEach of these factors changes the hazard rate, increasing or decreasing the\nlikelihood that a particular event occurs next.\n\nOne of the most elegant features of Cox regression is that it does not require\nspecifying the overall timing pattern of events. Events might occur very quickly\nat the beginning and slow down later, or slowly at first and accelerate over\ntime. Cox regression essentially says:\n\n> *That's fine. We will ignore the overall clock and focus on comparing the\n> competitors.*\n\nInstead of modeling absolute time, the model compares relative chances:\n\n> *At this moment, which event is most likely to happen?*\n\nThis is achieved through the **partial likelihood**, which evaluates the\nrelative hazards of all possible events at each moment in time.\n\nSo why does this work so well for social interactions? In many datasets,\nespecially relational event data, the exact timing of events is often less\nimportant than the order in which events occur.\n\nConsider the following sequence:\n\n1. Alice messages Bob\\\n2. Bob replies to Alice\\\n3. Carol messages Alice\\\n\nAt step 3, several interactions were possible, including:\n\n- Alice → Bob\\\n- Alice → Carol\\\n- Bob → Alice\\\n- Bob → Carol\\\n- Carol → Alice\\\n- Carol → Bob\\\n\nThis set of possible interactions is called the risk set (which we return to\nmore formally in the next section).\n\nCox regression allows us to ask:\n\n> *Given the situation and the history of interactions, why did Carol message\n> Alice rather than another interaction occurring?*\n\nThe model compares the rate (or intensity) of the observed event with those of\nall other possible events in the same situation.\n\n## Modeling Procedure\n\nEstimation of relational event models proceeds in three main steps. These steps\ntransform the sequence of observed interactions into a dataset that can be\nestimated using a Cox-type likelihood.\n\n#### Step 1: Constructing the Risk Sets {.unnumbered}\n\nAt each point in the event sequence, one interaction is observed, but many other\ninteractions were possible and did not occur. All dyads that could potentially\ninteract at that moment form the risk set.\n\nEach event time can therefore be understood as a discrete choice situation, in\nwhich one event is selected from among several competing alternatives. The Cox\npartial likelihood compares the covariates of the observed event with those of\nall other possible events in the same risk set.\n\nFor each observed interaction, we identify all dyads that were eligible to\ninteract at that time. We then augment the dataset by adding all unobserved but\npossible events corresponding to that risk set. This transforms the event\nhistory into a series of choice sets consisting of one observed event and\nmultiple non-events at each step in the sequence.\n\n#### Step 2: Computing Event Statistics {.unnumbered}\n\nFor both observed and unobserved events, we compute a set of statistics that\ncapture factors influencing the likelihood of interaction. These statistics\nserve as explanatory variables in the relational event model.\n\nThe statistics can capture several types of mechanisms, including:\n\n- **Endogenous structural effects**, derived from the history of previous\n  interactions,\n- **Node-level attributes**, describing characteristics of the actors involved,\n- **Dyadic covariates**, capturing properties of the sender--receiver pair,\n- **Contextual variables**, describing features of the environment in which\n  interactions occur.\n\nAll statistics are evaluated **dynamically**, meaning they are recalculated at\neach event step to reflect the evolving interaction history.\n\nThe specific statistics included in our model are described in the following\nsection.\n\n#### Step 3: Estimating the Model {.unnumbered}\n\nFinally, we estimate the relational event model using a Cox proportional hazards\nframework. Event occurrence is treated as the dependent variable, while the\ncomputed statistics serve as explanatory variables.\n\nEstimation relies on the partial likelihood, which compares the intensity of the\nobserved event with the intensities of all other possible events within the same\nrisk set.\n\n### Endogenous Statistics\n\nRelational event models allow us to incorporate **endogenous statistics**, which\ncapture patterns that arise from the history of interactions itself. These\nstatistics represent mechanisms through which past events influence the\nlikelihood of future events. Some of these endogenous statistics are summarized\nin the following and in @tbl-endstats.\n\nLet $V=\\{1,\\dots,n\\}$ denote the set of actors. An event at time $t$ is\nrepresented as $e_t=(i,j,t)$, where actor $i$ sends an interaction to actor $j$.\nLet $Y_{ij}(t)$ be an indicator variable that equals 1 if the event\n$i \\rightarrow j$ occurs at time $t$ and 0 otherwise. Further, let $N_{ij}(t)$\ndenote the total number of interactions from $i$ to $j$ that have occurred up to\ntime $t$.\n\n#### Reciprocity {.unnumbered}\n\nReciprocity captures the tendency for actors to immediately respond to\ninteractions they have received. If the previous event was $i \\rightarrow j$,\nthe statistic equals 1 when the next event is $j \\rightarrow i$.\n\n$$\ns_{\\text{reciprocity}}(i,j,t) = Y_{ij}(t-1) \\cdot Y_{ji}(t)\n$$\n\n#### Repetition {.unnumbered}\n\nRepetition captures the continuation of a dyadic interaction, meaning the same\nsender repeats an interaction with the same receiver.\n\n$$\ns_{\\text{repetition}}(i,j,t) = Y_{ij}(t-1) \\cdot Y_{ij}(t)\n$$\n\n#### Past Interaction {.unnumbered}\n\nThis statistic measures the strength of the historical relationship between the\nsender and receiver. It is defined as the proportion of the sender's previous\ninteractions that were directed toward the receiver.\n\n$$\ns_{\\text{past}}(i,j,t) =\n\\frac{N_{ij}(t-1)}\n{\\sum_{k=1}^{n} N_{ik}(t-1) + \\sum_{k=1}^{n} N_{ki}(t-1)}\n$$\n\n#### Sender Activity {.unnumbered}\n\nSender activity captures how frequently the sender has initiated interactions in\nthe past. It is defined as the proportion of all previous events that were sent\nby the current sender.\n\n$$\ns_{\\text{sender activity}}(i,j,t) =\n\\frac{\\sum_{k=1}^{n} N_{ik}(t-1)}\n{\\sum_{p \\neq q} N_{pq}(t-1)}\n$$\n\n#### Sender Popularity {.unnumbered}\n\nSender popularity measures how often the sender has previously received\ninteractions from others.\n\n$$\ns_{\\text{sender popularity}}(i,j,t) =\n\\frac{\\sum_{k=1}^{n} N_{ki}(t-1)}\n{\\sum_{p \\neq q} N_{pq}(t-1)}\n$$\n\n#### Receiver Activity {.unnumbered}\n\nReceiver activity captures how frequently the receiver has initiated\ninteractions in the past.\n\n$$\ns_{\\text{receiver activity}}(i,j,t) =\n\\frac{\\sum_{k=1}^{n} N_{jk}(t-1)}\n{\\sum_{p \\neq q} N_{pq}(t-1)}\n$$\n\n#### Receiver Popularity {.unnumbered}\n\nReceiver popularity measures how frequently the receiver has previously been the\ntarget of interactions.\n\n$$\ns_{\\text{receiver popularity}}(i,j,t) =\n\\frac{\\sum_{k=1}^{n} N_{kj}(t-1)}\n{\\sum_{p \\neq q} N_{pq}(t-1)}\n$$\n\n::: {#tbl-endstats}\n\n  | Statistic           | Description                                                       | Formula                                                     |\n  | ------------------- | ----------------------------------------------------------------- | ----------------------------------------------------------- |\n  | Reciprocity         | Immediate response to previous interaction                        | $Y_{ij}(t-1)Y_{ji}(t)$                                      |\n  | Repetition          | Same sender repeats interaction                                   | $Y_{ij}(t-1)Y_{ij}(t)$                                      |\n  | Past interaction    | Proportion of sender’s past interactions directed toward receiver | $\\frac{N_{ij}(t-1)}{\\sum_k N_{ik}(t-1)+\\sum_k N_{ki}(t-1)}$ |\n  | Sender activity     | Proportion of past events sent by the sender                      | $\\frac{\\sum_k N_{ik}(t-1)}{\\sum_{p\\ne q}N_{pq}(t-1)}$       |\n  | Sender popularity   | Proportion of past events received by the sender                  | $\\frac{\\sum_k N_{ki}(t-1)}{\\sum_{p\\ne q}N_{pq}(t-1)}$       |\n  | Receiver activity   | Proportion of past events sent by the receiver                    | $\\frac{\\sum_k N_{jk}(t-1)}{\\sum_{p\\ne q}N_{pq}(t-1)}$       |\n  | Receiver popularity | Proportion of past events received by the receiver                | $\\frac{\\sum_k N_{kj}(t-1)}{\\sum_{p\\ne q}N_{pq}(t-1)}$       |\n\nSummary of some endogenous statistics used in relational event models.\n{.striped}\n:::\n\n### Exogenous Covariates\n\nIn addition to endogenous statistics derived from the event history, relational\nevent models can also incorporate **exogenous covariates**. These variables\ncapture attributes of actors or dyads that may influence the likelihood of\ninteractions but are not themselves determined by the evolving sequence of\nevents.\n\nExogenous covariates may include **actor-level attributes** (e.g., demographic\ncharacteristics, roles, or status), **dyadic attributes** (e.g., similarity or\nshared group membership), or other contextual variables describing the\nenvironment in which interactions occur.\n\nLet $c_k$ denote an attribute associated with actor $k$. For binary attributes,\nthis can be represented as\n\n$$\nc_k =\n\\begin{cases}\n1 & \\text{if actor } k \\text{ possesses the attribute} \\\\\n0 & \\text{otherwise}\n\\end{cases}\n$$\n\nUsing this attribute, several covariates can be constructed for a potential\nevent $i \\rightarrow j$. For example:\n\n- **Sender attribute**: indicates whether the sender possesses the attribute\\\n- **Receiver attribute**: indicates whether the receiver possesses the attribute\n  \\\n- **Sender--receiver interaction**: indicates whether both sender and receiver\n  possess the attribute\\\n\nThese covariates allow the model to test whether actor characteristics influence\ninteraction patterns, such as whether certain actors are more likely to initiate\ncommunication, receive interactions, or interact preferentially with others\nsharing the same attribute.\n\nThe exogenous covariates included in the model are summarized in @tbl-exstats.\n\n::: {#tbl-exstats}\n  | Covariate                   | Description                                            | Formula   |\n  | --------------------------- | ------------------------------------------------------ | --------- |\n  | Sender attribute            | Indicates whether the sender possesses the attribute   | $c_i$     |\n  | Receiver attribute          | Indicates whether the receiver possesses the attribute | $c_j$     |\n  | Sender–receiver interaction | Indicates whether both actors possess the attribute    | $c_i c_j$ |\n\nSummary of exogenous covariates used in relational event models. {.striped}\n:::\n\n## REMs in R\n\nHere we estimate a relational event model for the dialogue interactions among\ncharacters in *Frozen*. In the `relevent` package, relational event models are\nestimated using the function `rem.dyad()`, which fits a dyadic relational event\nmodel based on the observed sequence of interactions.\n\nThe main arguments of the `rem.dyad()` function are:\n\n- **`edgelist`**: the event sequence, provided as a matrix or data frame\n  containing the time (or order) of each event, the sender, and the receiver.\n- **`n`**: the number of actors in the network.\n- **`effects`**: a vector specifying the endogenous effects to include in the\n  model (e.g., reciprocity, repetition, or activity effects).\n- **`covar`**: a list of covariate matrices corresponding to the exogenous\n  effects specified in `effects`.\n- **`ordinal`**: a logical argument indicating whether the event data are\n  ordinal. Set `TRUE` if the data only record the order of events (without exact\n  timestamps), and `FALSE` if precise event times are available.\n\nIn our case, the dataset consists of a sequence of dialogue interactions between\ncharacters in *Frozen*, where each event records which character speaks to\nanother and the order in which the interaction occurs (see @sec-apx-remfrozen\nfor details on how the data are created). To get a sense of the structure, we\nlook at the first 10 rows of the data.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Preview of the relational event data created from the *Frozen* character network as described in @sec-apx-remfrozen\n\n| time| sender| receiver|\n|----:|------:|--------:|\n|    1|      1|        2|\n|    2|      1|        2|\n|    3|      2|        1|\n|    4|      1|        2|\n|    5|      2|        1|\n|    6|      1|        2|\n|    7|      1|        2|\n|    8|      1|        2|\n|    9|      1|        2|\n|   10|      2|        1|\n\n\n:::\n:::\n\n\nNote that because the data contain only the ordering of events rather than\nprecise timestamps, we specify `ordinal = TRUE` when estimating the model.\nHpwever, before estimating the relational event models, we visualize the\naggregated dialogue network. Figure @fig-frozen shows the *Frozen* character\ninteraction network, with node color indicating gender and edge width reflects\ninteraction frequency.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Aggregated dialogue network of Frozen characters. Node colour indicates gender, node size reflects the number of dialogue lines spoken, and edge width reflects interaction frequency.](rem_files/figure-html/fig-frozen-1.png){#fig-frozen width=672}\n:::\n:::\n\n\n### Model 1: Reciprocity and Repetition\n\nWe begin by estimating a relational event model that includes two endogenous\nstructural effects: reciprocity and repetition. These effects capture two basic\nconversational dynamics: turn-taking behaviour and the persistence of\ninteractions between the same pair of characters. Including these mechanisms\nallows the model to account for simple structural patterns in the dialogue\nsequence before introducing additional explanatory variables, such as actor\nattributes or contextual factors, in later models.\n\nBecause the dialogue data record only the order of interactions rather than\nprecise timestamps, the model is estimated with `ordinal = TRUE`. In this\nsetting, the relational event model compares the intensity of the observed\ninteraction to the intensities of all other possible interactions in the risk\nset, which consists of all possible sender--receiver pairs at that moment.\n\nFormally, the event intensity for a potential interaction $i \\rightarrow j$ at\ntime $t$ is given by\n\n$$\n\\lambda_{ij}(t \\mid H_t) =\n\\lambda_0(t)\\exp\\Big(\n\\theta_1\\,\\text{Reciprocity}_{ij}(t) +\n\\theta_2\\,\\text{Repetition}_{ij}(t)\n\\Big)\n$$\n\nwhere $\\lambda_{ij}(t \\mid H_t)$ denotes the rate at which actor $i$ directs an\ninteraction to actor $j$ at time $t$, given the event history $H_t$. The\nstatistics capture the following mechanisms:\n\n- $\\text{Reciprocity}_{ij}(t)$ indicates whether the previous interaction was\n  $j \\rightarrow i$.\n- $\\text{Repetition}_{ij}(t)$ indicates whether the previous interaction was\n  $i \\rightarrow j$.\n\n#### Reciprocity (`RRecSnd`) {.unnumbered}\n\nThis effect captures whether characters tend to respond to someone who has just\naddressed them. In conversational settings, reciprocity reflects a basic\nturn-taking mechanism. If the previous interaction was $i \\rightarrow j$, a\npositive reciprocity effect indicates that the event $j \\rightarrow i$ becomes\nmore likely to occur next.\n\nIn the context of the *Frozen* dialogue network, a positive reciprocity\ncoefficient implies that when one character speaks to another, the addressed\ncharacter is more likely to respond directly.\n\n#### Repetition (`RSndSnd`) {.unnumbered}\n\nThis effect captures the tendency for the same sender--receiver interaction to\noccur repeatedly. If the previous event was $i \\rightarrow j$, this statistic\nmeasures whether the same interaction $i \\rightarrow j$ occurs again immediately\nafterward.\n\nIn conversational terms, repetition indicates that a speaker may continue\naddressing the same character across consecutive lines of dialogue.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- rem.dyad(\n  edgelist = edgelist,\n  n = n_actors,\n  effects = c(\"RRecSnd\", \"RSndSnd\"),\n  ordinal = TRUE,\n  hessian = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrepping edgelist.\nChecking/prepping covariates.\nComputing preliminary statistics\nFitting model\nObtaining goodness-of-fit statistics\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRelational Event Model (Ordinal Likelihood)\n\n        Estimate Std.Err Z value  Pr(>|z|)    \nRRecSnd  3.57036 0.14991  23.816 < 2.2e-16 ***\nRSndSnd  2.24439 0.13296  16.881 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nNull deviance: 6879.697 on 661 degrees of freedom\nResidual deviance: 3995.745 on 659 degrees of freedom\n\tChi-square: 2883.952 on 2 degrees of freedom, asymptotic p-value 0 \nAIC: 3999.745 AICC: 3999.763 BIC: 4008.732 \n```\n\n\n:::\n:::\n\n\n#### Interpreting the Coefficients {.unnumbered}\n\nThe estimated coefficients reported in `summary(model1)` represent log-relative\nrates of events. A positive coefficient indicates that the corresponding\ninteraction pattern increases the likelihood that a given event occurs next,\nwhile a negative coefficient indicates that it decreases that likelihood.\nBecause the model uses a log-linear intensity formulation, coefficients can be\ninterpreted multiplicatively: if a coefficient is $\\theta$, the corresponding\nevent rate is multiplied by $e^{\\theta}$ when the associated statistic increases\nby one unit. The argument `hessian = TRUE` instructs the model to compute the\nHessian matrix, allowing standard errors and statistical tests to be obtained.\n\nBoth endogenous effects are positive and highly statistically significant. The\nestimated coefficient for reciprocity is 3.57 ($SE = 0.15$, $p < 0.001$),\nindicating a strong tendency for characters to respond directly to those who\nhave just spoken to them. Exponentiating the coefficient gives\n\n$$\ne^{3.57} \\approx 35.6\n$$\n\nThis means that a reciprocating interaction is estimated to be about 35 times\nmore likely to occur next than it would be in the absence of this structural\ntendency, providing strong evidence of turn-taking dynamics in the *Frozen*\ndialogue network.\n\nThe estimated coefficient for repetition is 2.24 ($SE = 0.13$, $p < 0.001$).\nExponentiating this coefficient yields\n\n$$\ne^{2.24} \\approx 9.4\n$$\n\nThus, if the previous interaction was $i \\rightarrow j$, the same interaction\noccurring again immediately afterward is approximately nine times more likely\nthan it would otherwise be. This suggests that once a conversational exchange\nbegins between two characters, it often persists for multiple lines of dialogue.\n\nTaken together, these results indicate that dialogue interactions in *Frozen*\nare strongly structured by basic conversational dynamics. Characters frequently\nrespond directly to those who have just spoken to them, and conversations often\ncontinue between the same pair of characters across consecutive dialogue turns.\n\n### Model 2: Gender as an Exogenous Covariate\n\nWe now extend the previous model by incorporating gender as an exogenous\nactor-level covariate. The gender information is taken from the character data,\nwhere the variable `charfem` indicates whether a character is female (`1`) or\nnot (`0`). This allows us to examine whether gender influences patterns of\ndialogue in the *Frozen* interaction network, while still accounting for the\nendogenous conversational dynamics captured in Model 1.\n\nAs before, the model includes reciprocity and repetition. In addition, it now\nallows the probability of an interaction to depend on the gender of the sender\nand the receiver.\n\nThe gender indicator is first constructed as an actor-level covariate aligned\nwith the character IDs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# female indicator by character ID\nfemale <- matrix(frozenchars$charfem[order(frozenchars$characterID)], ncol = 1)\n```\n:::\n\n\nFormally, the event intensity for a potential interaction $i \\rightarrow j$ at\ntime $t$ is given by\n\n$$\n\\begin{split}\n\\lambda_{ij}(t \\mid H_t)  & =\n\\lambda_0(t)\\exp\\Big(\n\\theta_1\\,\\text{Reciprocity}_{ij}(t) +\n\\theta_2\\,\\text{Repetition}_{ij}(t)   \\\\ & \\qquad \\qquad \\qquad \n+\\theta_3\\,\\text{SenderFemale}_{ij} +\n\\theta_4\\,\\text{ReceiverFemale}_{ij}\n\\Big)\n\\end{split}\n$$\n\nwhere:\n\n- $\\text{Reciprocity}_{ij}(t)$ indicates whether the previous interaction was\n  $j \\rightarrow i$,\n- $\\text{Repetition}_{ij}(t)$ indicates whether the previous interaction was\n  $i \\rightarrow j$,\n- $\\text{SenderFemale}_{ij}$ equals 1 if the sender $i$ is female,\n- $\\text{ReceiverFemale}_{ij}$ equals 1 if the receiver $j$ is female.\n\nThe parameters $\\theta_3$ and $\\theta_4$ therefore capture whether female\ncharacters are more or less likely to initiate dialogue or be addressed by\nothers, respectively.\n\nThe sender gender effect (`CovSnd`) tests whether female characters are more\nlikely to initiate interactions than male characters. A positive coefficient\nindicates that female characters speak more frequently to others, while a\nnegative coefficient would suggest that male characters initiate dialogue more\noften.\n\nThe receiver gender effect (`CovRec`) tests whether female characters are more\nlikely to be addressed by others. A positive coefficient indicates that\ninteractions are more likely to target female characters.\n\nImportantly, these effects are estimated while controlling for the\nconversational dynamics captured by reciprocity and repetition. This allows us\nto assess whether gender differences in dialogue persist after accounting for\nbasic turn-taking behaviour and repeated exchanges between the same characters.\n\nAs in the previous model, the coefficients are expressed in log-relative rates,\nmeaning that exponentiating a coefficient yields the multiplicative change in\nthe event rate associated with a one-unit change in the corresponding statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# female indicator by character ID\nfemale <- matrix(frozenchars$charfem[order(frozenchars$characterID)], ncol = 1)\n\nmodel2 <- rem.dyad(\n  edgelist = edgelist,\n  n = n_actors,\n  effects = c(\"RRecSnd\", \"RSndSnd\", \"CovSnd\", \"CovRec\"),\n  covar = list(\n    CovSnd = female,\n    CovRec = female\n  ),\n  ordinal = TRUE,\n  hessian = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrepping edgelist.\nChecking/prepping covariates.\nComputing preliminary statistics\nFitting model\nObtaining goodness-of-fit statistics\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRelational Event Model (Ordinal Likelihood)\n\n         Estimate  Std.Err Z value Pr(>|z|)    \nRRecSnd  3.669318 0.149300 24.5769   <2e-16 ***\nRSndSnd  2.171289 0.132459 16.3922   <2e-16 ***\nCovSnd.1 0.797349 0.082131  9.7083   <2e-16 ***\nCovRec.1 0.106776 0.085729  1.2455   0.2129    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nNull deviance: 6879.697 on 661 degrees of freedom\nResidual deviance: 3902.631 on 657 degrees of freedom\n\tChi-square: 2977.066 on 4 degrees of freedom, asymptotic p-value 0 \nAIC: 3910.631 AICC: 3910.692 BIC: 3928.606 \n```\n\n\n:::\n:::\n\n\n#### Interpreting the Coefficients {.unnumbered}\n\nThe results of the relational event model including gender covariates can be\nsummarized as follows.\n\nThe estimated coefficients again represent log-relative rates of events. As in\nthe previous model, a positive coefficient indicates that the corresponding\neffect increases the likelihood that a particular interaction occurs next, while\na negative coefficient indicates that it decreases that likelihood.\nExponentiating a coefficient provides a multiplicative interpretation of the\nchange in the event rate associated with a one-unit increase in the\ncorresponding statistic.\n\nThe estimates indicate that the conversational dynamics identified in the\nprevious model (reciprocity and repetition) remain strong and highly\nstatistically significant even after accounting for gender effects.\n\nThe reciprocity coefficient is 3.67 ($SE = 0.15$, $p < 0.001$), indicating a\nstrong tendency for characters to respond directly to those who have just\naddressed them. Exponentiating the coefficient yields\n\n$$\ne^{3.67} \\approx 39.3\n$$\n\nThis implies that when a character $i$ speaks to character $j$, the probability\nthat the next interaction will be $j \\rightarrow i$ is nearly forty times larger\nthan it would otherwise be.\n\nThe repetition coefficient is 2.17 ($SE = 0.13$, $p < 0.001$). Exponentiating\nthis coefficient gives\n\n$$\ne^{2.17} \\approx 8.8\n$$\n\nThus, if the previous interaction was $i \\rightarrow j$, the same interaction\noccurring again immediately afterward is roughly nine times more likely than it\nwould otherwise be. This indicates that conversations frequently continue\nbetween the same pair of characters across consecutive lines of dialogue.\n\nTurning to the gender covariates, the sender gender coefficient is 0.80\n($SE = 0.08$, $p < 0.001$), indicating that female characters are significantly\nmore likely to initiate dialogue than male characters. Exponentiating the\ncoefficient gives\n\n$$\ne^{0.80} \\approx 2.22\n$$\n\nThis suggests that, holding the conversational dynamics constant, interactions\ninitiated by female characters occur at a rate that is approximately 2.2 times\nhigher than those initiated by male characters.\n\nThe receiver gender coefficient is 0.11 ($SE = 0.09$, $p = 0.21$), which is not\nstatistically significant. This indicates that there is no strong evidence that\nfemale characters are more or less likely to be addressed by others once\nconversational dynamics are taken into account.\n\nTaken together, these results show that dialogue interactions in *Frozen* are\nshaped by both structural conversational dynamics and gender differences in\nspeaking behavior. Turn-taking and repeated exchanges remain the dominant\norganizing mechanisms, while the gender covariate reveals that female characters\nare more likely to initiate dialogue within the interaction network.\n\n::: {.callout-note}\n\n# Gender Dynamics in Dialogue Networks\n\nThe finding that female characters are more likely to initiate dialogue is\nnoteworthy in the context of film dialogue networks. In many films, speaking\nroles and conversational agency are disproportionately concentrated among male\ncharacters. A widely discussed indicator of this imbalance is the [**Bechdel\nTest**](https://bechdeltest.com/), which evaluates whether a film contains at\nleast two named female characters who speak to each other about something other\nthan a man.\n\nMany films fail to satisfy even this minimal criterion, highlighting the limited\npresence and interaction of female characters in cinematic narratives. Against\nthis backdrop, the *Frozen* dialogue network presents a somewhat unusual\npattern: female characters not only appear frequently but also play an active\nrole in initiating interactions.\n\nWhile this analysis does not directly test the Bechdel criterion, the strong\nsender gender effect suggests that female characters occupy central\nconversational roles within the narrative. This aligns with the broader\nnarrative structure of *Frozen*, which centers on the relationship between its\ntwo main female protagonists.\n\n:::\n\n### Model 3: Gender Interaction Effects\n\nWe now extend the previous specification by allowing the gender of the sender\nand receiver to interact. While Model 2 examined whether female characters are\nmore likely to initiate or receive dialogue, this model additionally tests\nwhether interactions between female characters occur at a different rate than\nwould be expected from the sender and receiver effects alone.\n\nAs before, the model includes the endogenous conversational dynamics captured by\nreciprocity and repetition. In addition, it now includes a gender interaction\neffect that captures whether interactions between two female characters are more\nor less likely than other interactions.\n\nFormally, the event intensity for a potential interaction $i \\rightarrow j$ at\ntime $t$ is given by\n\n$$\n\\begin{split}\n\\lambda_{ij}(t \\mid H_t) & =\n\\lambda_0(t)\\exp\\Big(\n\\theta_1\\,\\text{Reciprocity}_{ij}(t) +\n\\theta_2\\,\\text{Repetition}_{ij}(t)  \\\\ & \\qquad \\qquad \\qquad \n+ \\theta_3\\,\\text{SenderFemale}_{ij} +\n\\theta_4\\,\\text{ReceiverFemale}_{ij} +\n\\theta_5\\,\\text{FemaleInteraction}_{ij}\n\\Big)\n\\end{split}\n$$\n\nwhere\n\n- $\\text{Reciprocity}_{ij}(t)$ indicates whether the previous interaction was\n  $j \\rightarrow i$,\n- $\\text{Repetition}_{ij}(t)$ indicates whether the previous interaction was\n  $i \\rightarrow j$,\n- $\\text{SenderFemale}_{ij}$ equals 1 if the sender $i$ is female,\n- $\\text{ReceiverFemale}_{ij}$ equals 1 if the receiver $j$ is female,\n- $\\text{FemaleInteraction}_{ij}$ equals 1 if both the sender and receiver are\n  female.\n\nThe interaction effect therefore captures whether conversations between female\ncharacters occur more or less frequently than would be expected based solely on\nsender and receiver gender effects.\n\nThe sender gender effect (`CovSnd`) continues to test whether female characters\nare more likely to initiate dialogue, while the receiver gender effect\n(`CovRec`) captures whether female characters are more likely to be addressed.\nThe interaction effect (`CovInt`) captures whether interactions between female\ncharacters occur at a higher or lower rate than would be expected from these\nindividual effects.\n\nImportantly, these effects are estimated while controlling for the\nconversational dynamics captured by reciprocity and repetition. This allows us\nto examine whether gender-based interaction patterns persist once basic\nconversational mechanisms are taken into account.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- rem.dyad(\n  edgelist = edgelist,\n  n = n_actors,\n  effects = c(\"RRecSnd\", \"RSndSnd\", \"CovSnd\", \"CovRec\", \"CovInt\"),\n  covar = list(\n    CovSnd = female,\n    CovRec = female,\n    CovInt = female\n  ),\n  ordinal = TRUE,\n  hessian = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrepping edgelist.\nChecking/prepping covariates.\nComputing preliminary statistics\nFitting model\nObtaining goodness-of-fit statistics\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRelational Event Model (Ordinal Likelihood)\n\n         Estimate  Std.Err Z value Pr(>|z|)    \nRRecSnd   3.66897  0.14930 24.5738   <2e-16 ***\nRSndSnd   2.17218  0.13247 16.3972   <2e-16 ***\nCovSnd.1  0.49512 51.48811  0.0096   0.9923    \nCovRec.1 -0.19570 51.48812 -0.0038   0.9970    \nCovInt.1  0.30187 51.48810  0.0059   0.9953    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nNull deviance: 6879.697 on 661 degrees of freedom\nResidual deviance: 3902.631 on 656 degrees of freedom\n\tChi-square: 2977.066 on 5 degrees of freedom, asymptotic p-value 0 \nAIC: 3912.631 AICC: 3912.723 BIC: 3935.1 \n```\n\n\n:::\n:::\n\n\n#### Interpreting the Coefficients {.unnumbered}\n\nThe interpretation of the coefficients follows the same logic as in the previous\nmodels. The estimated parameters represent log-relative rates of events. A\npositive coefficient indicates that the corresponding effect increases the\nlikelihood that an interaction occurs next, while a negative coefficient\nindicates that it decreases that likelihood. Exponentiating a coefficient yields\nthe multiplicative change in the event rate associated with a one-unit increase\nin the corresponding statistic.\n\nThe estimates show that the conversational dynamics identified in the previous\nmodels remain strong and highly statistically significant. The reciprocity\ncoefficient is 3.67 ($SE = 0.15$, $p < 0.001$), indicating a strong tendency for\ncharacters to respond directly to those who have just addressed them.\nExponentiating the coefficient gives\n\n$$\ne^{3.67} \\approx 39.3\n$$\n\nThis implies that when a character $i$ speaks to character $j$, the probability\nthat the next interaction will be $j \\rightarrow i$ is nearly forty times larger\nthan it would otherwise be.\n\nThe repetition coefficient is 2.17 ($SE = 0.13$, $p < 0.001$). Exponentiating\nthis coefficient yields\n\n$$\ne^{2.17} \\approx 8.8\n$$\n\nThus, if the previous interaction was $i \\rightarrow j$, the same interaction\noccurring again immediately afterward is roughly nine times more likely than it\nwould otherwise be. This again indicates that conversations frequently continue\nbetween the same pair of characters across consecutive dialogue turns.\n\nTurning to the gender covariates, none of the gender-related effects are\nstatistically significant in this specification. The estimated sender gender\ncoefficient is 0.50 ($SE = 51.83$, $p = 0.99$), the receiver gender coefficient\nis $-0.20$ ($SE = 51.83$, $p = 0.997$), and the gender interaction coefficient\nis 0.30 ($SE = 51.83$, $p = 0.995$). The extremely large standard errors\nindicate that these parameters are estimated with very high uncertainty in this\nmodel.\n\nSubstantively, this suggests that once the interaction effect between sender and\nreceiver gender is introduced, the model is unable to distinguish clear\ngender-based patterns in the dialogue sequence. In contrast to Model 2, where\nfemale characters appeared more likely to initiate dialogue, the additional\ninteraction term absorbs much of the variation associated with gender and\nresults in unstable estimates for the gender effects.\n\nTaken together, these results reinforce the conclusion that the primary\nstructure of the dialogue network is driven by conversational dynamics\n(specifically reciprocity and repetition) while gender-based interaction\npatterns are not strongly identified once interaction effects are included in\nthe model.\n\n::: {.callout-note}\n\n# Contextual Covariates in Relational Event Models\n\nIn addition to endogenous network statistics and actor attributes, relational\nevent models can also incorporate contextual covariates when such information is\navailable. Contextual covariates capture features of the environment or\nsituation in which interactions occur and allow researchers to examine how\ninteraction patterns vary across different settings.\n\nIn the `relevent` package, such variables can be included using the `CovEvent`\neffect. Event-level covariates describe characteristics of the interaction\ncontext at a particular point in time rather than attributes of the actors\ninvolved.\n\nFor example, in studies of classroom interaction networks, contextual variables\nmight include the structure of the lesson (e.g., lecture, group work, or\ndiscussion), the phase of an activity, or the seating arrangement of students.\nThese contextual factors may influence who interacts with whom and how\nconversational dynamics unfold over time.\n\nWhen included in the model, the event intensity can be written as\n\n$$\n\\lambda_{ij}(t \\mid H_t) =\n\\lambda_0(t)\\exp\\Big(\n\\theta_1\\,\\text{Reciprocity}_{ij}(t) +\n\\theta_2\\,\\text{Repetition}_{ij}(t) +\n\\theta_3\\,\\text{Context}_t\n\\Big)\n$$\n\nwhere $\\text{Context}_t$ represents an event-level covariate capturing features\nof the situation at time $t$.\n\nIn practice, such variables are included in `relevent` using the `CovEvent` term\nin the `effects` argument and supplying the corresponding event-level covariate\nthrough the `covar` list. For example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrem.dyad(\n  edgelist = edgelist,\n  n = n_actors,\n  effects = c(\"RRecSnd\", \"RSndSnd\", \"CovEvent\"),\n  covar = list(CovEvent = context_variable),\n  ordinal = TRUE\n)\n```\n:::\n\n\nIncluding contextual covariates (`context_variable` in above code) allows\nrelational event models to move beyond purely structural explanations of\ninteraction sequences and to account for how social behaviour is shaped by\nsituational or institutional conditions.\n\n:::\n\n### Assessing Goodnes of Fit\n\nAfter estimating the relational event models, it is useful to evaluate how well\nthey reproduce the observed interaction sequence. Information criteria such as\nthe Bayesian Information Criterion (BIC) can provide evidence about whether one\nmodel is preferred to another, but they do not directly indicate how well the\nmodel predicts the sequence of interaction events. To better understand model\nperformance, we can examine both the predicted interactions and the residuals.\n\n#### Actual vs. Predicted {.unnumbered}\n\nFor illustration, we focus on Model 3, the most complete specification including\nreciprocity, repetition, and gender effects. One useful component of the model\noutput is the object `predicted.match`, which records whether the model\ncorrectly predicts the sender and receiver for each observed event.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(model3$predicted.match)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sender receiver\n1   TRUE     TRUE\n2  FALSE    FALSE\n3   TRUE     TRUE\n4   TRUE     TRUE\n5  FALSE    FALSE\n6   TRUE     TRUE\n```\n\n\n:::\n:::\n\nEach row corresponds to an observed interaction in the dialogue sequence. The\nfirst column indicates whether the model correctly predicted the sender of the\nevent, and the second column indicates whether it correctly predicted the\nreceiver. Because the relational event model is trying to predict the exact\nsequence of interactions, this is a strict criterion: a prediction is fully\ncorrect only when both the sender and the receiver are correctly identified.\n\nTo summarize predictive accuracy, we can tabulate the sender and receiver\nmatches.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsend_col <- model3$predicted.match[, \"sender\"]\nreceive_col <- model3$predicted.match[, \"receiver\"]\n\ntable(send_col, receive_col)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        receive_col\nsend_col FALSE TRUE\n   FALSE   370  135\n   TRUE     13  143\n```\n\n\n:::\n:::\n\n\nThis table indicates how often the model correctly predicts the sender, the\nreceiver, both, or neither for each interaction event.\n\nIn 143 cases the model correctly predicts both the sender and the receiver,\nmeaning that it successfully reproduces the exact interaction in the event\nsequence. In 370 cases the model fails to correctly identify either the sender\nor the receiver, indicating interactions that are poorly captured by the current\nspecification. There are also cases where the model predicts only one component\ncorrectly: in 13 events the sender is predicted correctly but the receiver is\nnot, while in 135 events the receiver is predicted correctly but the sender is\nnot.\n\nTo better understand these proportions, we can convert the table into relative\nfrequencies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(send_col, receive_col))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        receive_col\nsend_col      FALSE       TRUE\n   FALSE 0.55975794 0.20423601\n   TRUE  0.01966717 0.21633888\n```\n\n\n:::\n:::\n\n\nThese results show that the model exactly predicts both the sender and receiver\nin roughly 22% of the dialogue events, while in approximately 56% of cases it\nfails to predict either component correctly. In the remaining events, the model\ncorrectly identifies either the sender or the receiver but not both.\n\nOverall, these results suggest that the model captures some important aspects of\nthe interaction dynamics but still misses a substantial portion of the variation\nin the dialogue sequence. This is not surprising, as the model includes only a\nlimited set of explanatory mechanisms---namely reciprocity, repetition, and\ngender effects. Additional factors, such as narrative context, scene structure,\nor character roles within the story, may influence the interaction sequence and\ncould potentially improve predictive performance if incorporated into the model.\n\n#### Residual Diagnostics {.unnumbered}\n\nAnother way to assess the goodness of fit of a relational event model is by\nexamining the residuals. Residuals measure the discrepancy between the observed\ninteraction and the interaction that the model would predict given the event\nhistory and the included covariates. Large residual values therefore indicate\nevents that were substantially more or less likely than expected under the\nmodel.\n\nA useful first step is to examine a summary of the residual distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model3$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.678   3.320   4.646   5.904   6.944  17.265 \n```\n\n\n:::\n:::\n\n\nThe summary provides an overview of the range and distribution of residuals\nacross the event sequence. While many events will typically have residuals close\nto zero, larger values may indicate interactions that the model has difficulty\nexplaining.\n\nTo identify potential outliers, we can locate events with particularly large\nresiduals. For illustration, we define outlying cases as those with residuals\ngreater than 10.\n\nThe summary provides an overview of the range and distribution of residuals\nacross the event sequence. While many events will typically have residuals close\nto zero, larger values may indicate interactions that the model has difficulty\nexplaining.\n\nTo identify potential outliers, we can locate events with particularly large\nresiduals. For illustration, we define outlying cases as those with residuals\ngreater than 12 ($\\approx  Q_3 + 1.5 \\times IQR)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhigh_resids <- which(model3$residuals > 12)\n```\n:::\n\n\nThese indices correspond to the positions of events in the event sequence where\nthe observed interaction deviates strongly from the model's predictions. We can\ninspect these events directly in the event list.\n\nA visualization of the residual distribution and this threshold is shown below\nin @fig-rem-residuals.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of residuals from Model 3 of the relational event model. The red vertical line indicates the threshold (residual = 12) used to identify unusually poorly predicted interaction events.](rem_files/figure-html/fig-rem-residuals-1.png){#fig-rem-residuals width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedgelist[high_resids, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    time sender receiver\n12    12      1        3\n18    18      2        4\n19    19      2        5\n21    21      5        1\n24    24      2        5\n25    25      5        4\n27    27      7        6\n28    28      8        4\n31    31      8        5\n34    34      8        5\n35    35      2        8\n44    44      1        4\n50    50      9        1\n59    59     10        1\n85    85      9        2\n86    86     11        9\n87    87     11        2\n92    92     11        1\n126  126     10        2\n176  176     10       11\n191  191     12        1\n196  196     12        6\n197  197      6        1\n201  201     12        6\n291  291      3        6\n340  340     13       10\n392  392      1        2\n404  404      3        2\n429  429      1       14\n430  430      3       14\n431  431     14        1\n433  433     14        6\n434  434      1        3\n436  436      3        6\n442  442      3        6\n465  465      3        6\n468  468     14        6\n517  517      7        1\n519  519      6        7\n523  523      8        6\n526  526      8        1\n533  533      6        3\n535  535     14       10\n536  536     10        2\n551  551     13        1\n554  554      6        9\n555  555      6       13\n558  558      6       13\n559  559      9       10\n560  560     10        1\n565  565     13       10\n588  588     10       11\n623  623     10        2\n643  643      9       11\n645  645      1        6\n658  658      1        2\n```\n\n\n:::\n:::\n\n\nExamining such cases can help identify systematic patterns that are not\nadequately captured by the model specification. For example, certain characters\nmay appear disproportionately often in events with large residuals, suggesting\nthat their interaction behavior differs from what would be expected based on the\nincluded effects.\n\nResidual diagnostics can therefore be a useful tool for guiding further model\ndevelopment. If particular actors, dyads, or types of interactions repeatedly\nappear among the high-residual cases, this may indicate the need to include\nadditional actor attributes, dyadic covariates, or contextual variables in the\nmodel. In narrative interaction networks such as film dialogue, for instance,\nconversational patterns may also be shaped by scene structure, narrative roles,\nor other contextual factors that are not currently included in the model.\n\n#### Comparing Model Specifications {.unnumbered}\n\nTo compare the three model specifications, we examine their Bayesian Information\nCriterion (BIC) values. The BIC provides a measure of model fit that penalizes\nmodel complexity, meaning that lower values indicate a better balance between\nexplanatory power and the number of estimated parameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  Model1_BIC = model1$BIC,\n  Model2_BIC = model2$BIC,\n  Model3_BIC = model3$BIC\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel1_BIC Model2_BIC Model3_BIC \n  4008.732   3928.606   3935.100 \n```\n\n\n:::\n:::\n\n\nThe results show a substantial improvement in model fit when moving from Model 1\nto Model 2. The BIC decreases from 4008.73 to 3928.61, indicating that including\ngender as an actor-level covariate significantly improves the model's ability to\nexplain the dialogue interactions.\n\nBy contrast, Model 3, which additionally includes the interaction between sender\nand receiver gender, produces a slightly higher BIC (3935.10) than Model 2.\nBecause the BIC penalizes additional parameters,\n\nTaken together, prediction accuracy, residual diagnostics, and information\ncriteria provide a comprehensive picture of model performance. These tools help\nidentify whether the model adequately captures the dynamics of the dialogue\nnetwork and highlight potential directions for further model refinement.\n",
    "supporting": [
      "rem_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}