{
  "hash": "038b1cde2daf1f103286bfd0ac6f7e7f",
  "result": {
    "engine": "knitr",
    "markdown": "# Stochastic Actor Oriented Models (SAOMs) {#sec-saom}\n\nUp to this point, we have focused on modeling social networks as\n**cross-sectional data**, that is, as static snapshots of tie patterns observed\nat a single point in time. Models such as Erdős--Rényi, preferential attachment,\nand Exponential Random Graph Models (ERGMs) allow us to account for structural\ndependencies, attribute effects, and network complexity within such static\nnetworks.\n\nHowever, social networks are inherently dynamic. Ties are not fixed; they\nemerge, dissolve, and evolve through time as a result of decisions made by\nindividual actors. Treating network data as static ignores this core aspect of\nsocial life. A more realistic modeling approach must account for the sequential,\nactor-driven nature of network evolution.\n\nThis brings us to **Stochastic Actor-Oriented Models (SAOMs)**, a class of\nmodels explicitly designed for **longitudinal network data**. Unlike\ncross-sectional models that treat the network as a single outcome, SAOMs treat\nthe network as a continuous-time stochastic process driven by individual actor\ndecisions. In this framework, changes to the network occur one tie at a time,\nreflecting micro-level decisions made by actors based on preferences,\nopportunities, and constraints.\n\nSAOMs are particularly well-suited for panel data, i.e., multiple observations\nof the same network over time where both tie structures and actor attributes may\nco-evolve. This allows researchers to address questions such as:\n\n- How often do actors initiate or terminate ties?\n- Do actors prefer to form ties based on similarity (selection) or become more\n  similar after forming ties (influence)?\n- How do structural tendencies like reciprocity or transitivity manifest through\n  sequential decision-making?\n- Can we simulate or predict how the network may evolve in future time points?\n\nSAOMs are one of two main frameworks for dynamic network modeling. The other is\nthe **Temporal Exponential Random Graph Model (TERGM)**. While TERGMs extend\nERGMs to panel data by conditioning on past networks, SAOMs take a process-based\nview that explicitly models *how* ties change over time due to actor decisions.\n\n@tbl-ergmsaom shows the core differences between ERGMs. While ERGMs model the\nglobal structure of a network at a single point in time, SAOMs treat network\nevolution as a dynamic process driven by actors making sequential decisions. In\nother words, SAOMs extend the logic of ERGMs into the temporal domain, capturing\nthe mechanisms of change rather than just the final structure.\n\n::: {#tbl-ergmsaom}\n  |                       | ERGMs                                       | SAOMs                                                 |\n  | :-------------------- | ------------------------------------------- | ----------------------------------------------------- |\n  | **Data type**         | Cross-sectional (static snapshot)           | Longitudinal (panel data, repeated observations)      |\n  | **Unit of analysis**  | The entire network                          | Individual actor decisions                            |\n  | **Modeling approach** | Statistical dependence among ties           | Actor-based tie change process                        |\n  | **Time modeling**     | No time dimension                           | Continuous-time change process                        |\n  | **Common mechanisms** | Reciprocity, transitivity, nodal covariates | Same, but expressed as actor preferences over changes |\n  | **Estimation method** | MCMC Maximum Likelihood (MCMCMLE)           | Simulation-based Method of Moments (MoM)              |\n  | **Outcome**           | Probability of the observed network         | Simulated network trajectories over time              |\n  | **In R**              | `ergm` (or `statnet`)                       | `RSiena`                                              |\n\nComparison between Exponential Random Graph Models (ERGMs) and Stochastic\nActor-Oriented Models (SAOMs). The two approaches differ in their treatment of\ntime, unit of analysis, estimation, and interpretation.\n:::\n\nIn what follows, we focus on the SAOM framework, its components, estimation\nprocess, and how it can be used to explain and simulate network evolution.\n\n## Packages Needed for this Chapter\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\nlibrary(ggraph)\nlibrary(graphlayouts)\nlibrary(networkdata)\nlibrary(intergraph)\nlibrary(RSiena)\n```\n:::\n\n\n### Example: Teenage Friends and Lifestyle Study\n\nWe use a running example with data from the \"Teenage Friends and Lifestyle\nStudy\" [@west1996s50], which was also used in the previous chapter on ERGMs. In\ncontrast to the earlier example that focused on a single time point and only the\nsubset of 50 pupils, we here model the dynamics of friendship ties across all\nthree observed waves and with the 129 pupils over all three time points, and\nincluding relevant actor-level covariates such as gender and smoking behavior.\nThe dataset is called `glasgow129` in the `networkdata` package, which includes\nthe following:\n\n- Networks: Binary, directed friendship ties measured at three time points.\n- Actors: 129 pupils measured at three time points.\n- Many covariates, but we focus on\n  - Sex: 1 = Male, 2 = Female\n  - Smoking: 1 = No, 2 = Occasional, 3 = Regular\n\nWe load the data from the `networkdata` package and extract a graph object for\neach time period:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data as graph object from networkdata and extract all three wave networks\nglasgow_g1 <- glasgow129[[1]]\nglasgow_g2 <- glasgow129[[2]]\nglasgow_g3 <- glasgow129[[3]]\n```\n:::\n\nThese `igraph` objects are our network snapshots and consider various SAOMs. We\nbegin by converting each network snapshot into a binary adjacency matrix. These\nmatrices represent the presence or absence of directed ties between actors at\neach time point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert to adjacency matrices\nnet1 <- as_adjacency_matrix(glasgow_g1, sparse = FALSE)\nnet2 <- as_adjacency_matrix(glasgow_g2, sparse = FALSE)\nnet3 <- as_adjacency_matrix(glasgow_g3, sparse = FALSE)\n```\n:::\n\n\nWe then combine them into a 3-dimensional array with dimensions\n`[actor × actor × wave]`, which is the required format for longitudinal network\ndata in `RSiena`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine into 3D array [actor x actor x wave]\nnet_array <- array(c(net1, net2, net3), dim = c(129, 129, 3))\n```\n:::\n\n\n## Modeling Network Evolution\n\nMost real-world social networks are dynamic systems. Relationships between\nindividuals form, dissolve, and evolve as a result of ongoing social\ninteractions, personal decisions, and contextual factors. When we observe a\nsingle snapshot of a network, we can only speculate about the processes that\nproduced it. By contrast, longitudinal network data, repeated observations of a\nnetwork over time, allow us to move from static description to dynamic\nexplanation.\n\nLongitudinal network data consist of a set of actors $N = \\{1, 2, \\dots, n\\}$\nand a series of observed adjacency matrices:\n$$\nY(t_0),\\ Y(t_1),\\ \\dots,\\ Y(t_M)\n$$\nwhere each matrix captures the presence or absence of ties between actors at a\nparticular time point, that is $y_{ij}(t) = 1$ if actor $i$ has a tie to actor $j$ at time $t$, and\n$y_{ij}(t) = 0$ otherwise.\n\nThese repeated measures make it possible to ask and answer key questions:\n\n- How frequently do actors change their ties?\n- What drives the formation, maintenance, or dissolution of ties?\n- How do individual attributes (e.g., gender, age, group membership) shape\n  network dynamics?\n- Can we predict how the network will evolve in the future?\n- How do both endogenous (network-based) and exogenous (attribute-based) factors\n  jointly shape the network?\n\nMoreover, understanding *why* networks change requires distinguishing between\ncompeting explanations. For instance, if we observe that two similar actors are\nconnected at time $t_1$, this might reflect selection (they formed a tie because\nof their similarity) or influence (they became similar after forming a tie).\nOnly a longitudinal framework allows us to tease apart these mechanisms.\n\nTime also matters for structural tendencies. Consider transitivity: when we\nobserve a triadic closure (i.e., if $i$ is tied to $j$ and $j$ to $\\ell$, then $i$\nmay become tied to $\\ell$), we cannot know whether it reflects an intentional\nclosure or merely a residual pattern without knowing the order in which ties\nappeared.\n\nStochastic Actor-Oriented Models (SAOMs) offer a solution by treating network\nchange as a **continuous-time, actor-driven process**. In this framework:\n\n- The network evolves through a sequence of micro-steps where individual actors\n  have opportunities to change their outgoing ties.\n- Each actor evaluates the current network and makes decisions based on\n  preferences (e.g., for reciprocation, closure, or similarity).\n- The model simulates the timing and direction of these changes between\n  observation moments (waves).\n\nThis actor-oriented perspective aligns closely with how ties form in real life:\nindividuals decide whom to connect with (or disconnect from), guided by\nstructural cues and attribute-based tendencies.\n\nIn the next section, we will formalize this logic, introduce the core components\nof SAOMs, and show how the `RSiena` package implements these models for\nempirical analysis.\n\n### Stochastic Processes and Continuous-Time Markov Chains\n\nTo understand the dynamics of network evolution in Stochastic Actor-Oriented\nModels (SAOMs), it is helpful to first grasp the concept of a **stochastic\nprocess**, a collection of random variables indexed by time:\n\n$$\n\\{ X(t),\\ t \\in T \\}\n$$\n\nwhere:\n\n- $T$ is the index set (typically representing time),\n- $S$ is the **state space**, the set of all possible values that $X(t)$ can take.\n\nIn the context of longitudinal network analysis, the stochastic process\nrepresents the network evolving over time. That is, we can interpret the state\nas the network at time $t$, so that\n\n$$\nX(t) \\equiv Y(t),\n$$\n\nwhere $Y(t)$ is the adjacency matrix at time $t$, with entries\n$y_{ij}(t) \\in \\{0,1\\}$ indicating whether a tie from actor $i$ to actor $j$\nis present at time $t$.\n\n\nSAOMs are based on a particular type of stochastic process: the\n**continuous-time Markov chain (CTMC)**. A CTMC is defined by:\n\n1. A finite **state space** $S$ (e.g., all possible network configurations),\n2. A **continuous time domain** $t \\in [0, \\infty)$,\n3. The **Markov property**, which states that the future state depends only on\n   the present state, not on the past:\n\n$$\nP\\bigl(X(t_j) = s_j \\mid \\{X(t): t \\le t_i\\}\\bigr)\n=\nP\\bigl(X(t_j) = s_j \\mid X(t_i) = s_i\\bigr)\n$$\n\nThis **memoryless** property implies that future network evolution depends only\non the current configuration. In the context of SAOMs, actors make tie changes\nbased solely on the present network structure (e.g., existing ties, shared\npartners, or attributes), without direct dependence on earlier configurations.\n\nThe CTMC evolves through a sequence of randomly timed transitions. Each state is\nheld for a random duration, and transitions to the next state are governed by\nprobability. More formally, a CTMC is characterized by:\n\n- When a change occurs: governed by the holding time, typically modeled with an\n  exponential distribution.\n- What the next state is: determined by the jump matrix, which specifies the\n  transition probabilities between states.\n\nTogether, **holding time** and **jump probabilities** define the full behavior\nof the CTMC.\n\n#### Example: A Cat’s Daily Activities {.unnumbered}\n\nTo bring the concept of a continuous-time Markov chain (CTMC) to life (or to all\nnine lives of our cat), consider a model of a house cat's daily activities. At\nany given moment, the cat is in one of the following behavioral states:\n\n- $0$: Sleeping\n- $1$: Eating\n- $2$: Playing\n- $3$: Plotting chaos (e.g., knocking things off shelves)\n\nWe define $X(t)$ as the cat's current activity at time $t$. The process\n$\\{X(t), t \\in [0, \\infty)\\}$ satisfies:\n\n- A finite state space $S = \\{0, 1, 2, 3\\}$\\\n- Continuous transitions over time\\\n- The Markov property: next state depends only on the current state\\\n\nThe cat transitions between states at random times. Each stay in a state lasts\nfor a random holding time, and transitions to the next state occur\nprobabilistically based on a transition (jump) matrix.\n\nThe holding time $T_r$ in state $r$ is modeled using an exponential\ndistribution:\n$$\nf_{T_r}(t) = \\lambda_r e^{-\\lambda_r t}, \\quad t > 0\n$$\n\n- $\\lambda_r$ is the rate of leaving state $r$.\n- $\\mathbb{E}[T_r] = \\frac{1}{\\lambda_r}$ is the expected duration in state $r$.\n\nThe exponential distribution's **memoryless property** means that the\nprobability of remaining in a state is independent of how long the cat has\nalready been in it:\n$$\nP(T_r > s + t \\mid T_r > t) = P(T_r > s)\n$$\nSo, even after two hours of napping, the chance that the cat naps another 30\nminutes is the same as if it had just started.\n\nOnce the holding time ends, the cat jumps to a new state. The **transition\n(jump) matrix** $P = (p_{rs})$ governs this:\n$$\np_{rs} = P(X(t^+) = s \\mid X(t) = r)\n$$\nFor each state $r$, the row of probabilities $p_{rs}$ must sum to 1:\n$$\n\\sum_{s \\in S} p_{rs} = 1\n$$\n\n@fig-catex illustrates a single realization of such a process. This visual shows\nhow a process starting in state 0 might stay there for some time, then jump to\nstate 2, then state 3, and so on, with irregular intervals between jumps.\n\n::: {#fig-catex}\n\n::: {.cell}\n::: {.cell-output-display}\n![](saom_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nA realization of a continuous-time Markov chain (CTMC) showing the cat\ntransitioning through behavioral states (Sleep → Play → Chaos → Sleep → Eat).\nHorizontal segments show how long each activity lasts (holding time), while\nvertical arrows show transitions (jumps) between states.\n\n:::\n\nBelow is a hypothetical transition matrix $P$ for the cat's behavioral states.\nEach row corresponds to the current state, and each column to the next state:\n\n  |           | Sleep | Eat  | Play | Chaos |\n  | --------- | :---: | :--: | :--: | :---: |\n  | **Sleep** | 0.00  | 0.70 | 0.83 | 0.56  |\n  | **Eat**   | 0.71  | 0.00 | 0.81 | 0.20  |\n  | **Play**  | 0.05  | 0.82 | 0.00 | 0.45  |\n  | **Chaos** | 0.91  | 0.46 | 0.61 | 0.00  |\n\n> *Note: Diagonal entries (e.g., Sleep → Sleep) are set to zero for\n> interpretability. They can be included to model the probability of no state\n> change.*\n\nNext, we can combine the states and transitions into a directed graph showing\nwhich states can be reached from one another, and with what likelihood. This is\nshown in @fig-catex2.\n\n::: {#fig-catex2}\n\n::: {.cell}\n::: {.cell-output-display}\n![](saom_files/figure-html/unnamed-chunk-6-1.png){width=384}\n:::\n:::\n\nDirected graph representation of the CTMC jump chain. Each node is a state\n(e.g., Sleep, Eat), and arrows represent possible transitions with associated\nprobabilities.\n:::\n\n@fig-catex2 is a visual representation of this matrix. Each arrow in the graph\ncorresponds to a non-zero entry $p_{rs}$ in the matrix. The curved edges\nindicate transitions between pairs of states, and the labels on the arrows match\nthe values in the matrix. Together, the matrix and the graph describe a **jump\nchain** over the set of behavioral states. These transitions are stochastic\n(i.e., random), and their dynamics unfold in continuous time, which is what\ndifferentiates CTMCs from discrete-time Markov models.\n\nIn summary, a Continuous-Time Markov Chain (CTMC):\n\n- Determines how long the system remains in a state using the holding time,\n  typically modeled as exponentially distributed.\n- Uses a transition (jump) matrix to govern which state is entered next.\n- Is memoryless and evolves in continuous time, meaning the future depends only\n  on the present state and not the past.\n\nThese principles underpin Stochastic Actor-Oriented Models (SAOMs), where actors\nmake sequential and probabilistic changes to their network ties or attributes,\ndriven solely by the current network state.\n\n### Definition of SAOMs\n\nStochastic Actor-Oriented Models (SAOMs), introduced by @snijders1996stochastic,\nprovide a principled framework for analyzing how social networks evolve over\ntime. Formally, network evolution is represented as a continuous-time Markov\nchain (CTMC) operating on a space of networks.\n\nAs previously introduced, a continuous-time Markov chain (CTMC) is characterized\nby three key components:\n\n- **A finite state space**: For SAOMs, this is the set $\\mathcal{Y}$ of all\n  possible directed networks on $n$ actors. Each state $Y \\in \\mathcal{Y}$ is an\n  adjacency matrix with entries $y_{ij} \\in \\{0,1\\}$ for $i \\neq j$.\n- **A continuous-time process**: Network changes (such as the creation or\n  dissolution of ties $y_{ij}(t)$) occur at random points in continuous time.\n- **The Markov property**: The probability of a transition depends only on the\n  current network state $Y(t)$, not on the sequence of past networks that\n  preceded it.\n\nIn the sections that follow, we explore how each of these components is specified\nin SAOMs, including how actors are selected to make changes and how tie updates\nare determined.\n\n#### State Space of Networks\n\nLet $\\mathcal{Y}$ denote the set of all possible adjacency matrices (i.e.,\nnetwork configurations) defined on $n$ actors. Each matrix $Y \\in \\mathcal{Y}$\nrepresents a possible state of the network.\n\nFor directed networks without self-ties, the size of this state space is:\n\n$$\n|\\mathcal{Y}| = 2^{n(n-1)}\n$$\n\nThis follows from the fact that each of the $n(n-1)$ possible directed ties\nbetween distinct actors $(i,j)$ with $i \\neq j$ can independently be either\npresent ($y_{ij} = 1$) or absent ($y_{ij} = 0$).\n\nIn the SAOM framework, the stochastic process $\\{Y(t), t \\geq 0\\}$ evolves over\nthis state space, with each realization corresponding to a sequence of network\nconfigurations over time.\n\nFor instance, with a 4-node directed network shown in @fig-saomex, we can\nrepresent different adjacency matrices as the network evolves. The figure\nillustrates a step-by-step sequence of tie changes, starting from an empty\nnetwork and progressing toward a more connected structure.\n\n::: {#fig-saomex .center}\n![](img/‎‎saom-state-ex.png){width=\"100%\"}\n\nAn example of network evolution as a sequence of micro-steps in continuous time.\nAt each step, a single directed tie $y_{ij}$ is updated, producing a new network\nstate and its corresponding adjacency matrix.\n:::\n\n#### Continuous-time process\n\nStochastic Actor-Oriented Models (SAOMs) assume that the network evolves as a\ncontinuous-time Markov process. Formally, the stochastic process\n$\\{Y(t), t \\geq 0\\}$ changes over time through a sequence of small,\nactor-driven modifications, where individual ties $y_{ij}(t)$ may be created or\ndissolved.\n\nIn empirical applications, however, we do not observe the full trajectory of\nthis process. Instead, we observe the network only at a finite set of discrete\ntime points (e.g., survey waves):\n$$\nt_1,\\ t_2,\\ \\ldots,\\ t_M.\n$$\n\nAt each observation moment, we record a network $Y(t_m)$, but the intermediate\ntie changes (i.e., which actor changed which tie $(i,j)$ and at what exact time)\nremain unobserved. These changes occur in a latent process between observation\nmoments.\n\nThis distinction is fundamental:\n\n- **Observed process**: a sequence of network snapshots\n  $Y(t_1), Y(t_2), \\ldots, Y(t_M)$.\n- **Latent process**: the underlying continuous-time evolution, consisting of\n  a sequence of micro-steps in which actors stochastically update individual\n  ties $y_{ij}(t)$ based on the current network state $Y(t)$.\n\nSAOMs aim to model and simulate this latent evolution process, allowing us to\ninfer the actor-level mechanisms that most likely generated the observed changes\nbetween $Y(t_1)$ and $Y(t_M)$.\n\n#### The Markov Property\n\nA central assumption of Stochastic Actor-Oriented Models (SAOMs) is that the\nprobability of moving to a new network state depends only on the current state,\nnot on the path taken to get there. This is the Markov property and is formally\ndefined as:\n$$\nP\\bigl(Y(t_j) = y' \\mid \\{Y(t): t \\leq t_i\\}\\bigr)\n=\nP\\bigl(Y(t_j) = y' \\mid Y(t_i) = y\\bigr)\n$$\nwhere $Y(t)$ denotes the network state (i.e., adjacency matrix) at time $t$,\nand $y, y' \\in \\mathcal{Y}$ are particular network configurations at times\n$t_i$ and $t_j$, respectively.\n\nIn other words, the future evolution of the process depends solely on the\ncurrent network state $Y(t_i)$ and not on the entire sequence of previous\nstates. The model is memoryless: it \"forgets\" the past once the current state is\nknown.\n\nIn the context of SAOMs, this means that when an actor is given the opportunity\nto make a change, such as forming or dissolving a tie $y_{ij}(t)$, they do so\nbased only on the current network structure and covariate information. There is\nno dependence on the path the network took to reach its current configuration.\n\nThis assumption significantly simplifies the modeling of network dynamics. It\neliminates the need to track full network histories and allows for tractable\nsimulation-based estimation. Conceptually, it also aligns with many social\nprocesses where actors respond to their current social environment rather than\nrecalling a complete relational past.\n\nNonetheless, the Markov assumption is a modeling abstraction. While it\nfacilitates analysis and interpretation, it may not capture certain behaviors\nwhere history matters, such as long-term reciprocity, reputation building, or\ndelayed responses. Still, for many applications, it offers a powerful and\nflexible framework for understanding how networks evolve over time.\n\n#### Actor-Oriented Modeling Assumptions\n\nA central challenge in modeling network dynamics is the vast number of possible\nnetwork configurations. For a directed network with $n$ actors, the state space\n$\\mathcal{Y}$ contains $2^{n(n-1)}$ possible networks, making exhaustive\nevaluation of all potential transitions computationally infeasible.\n\nSAOMs address this by adopting an **actor-driven approach**. Instead of modeling\nglobal changes to the network, SAOMs assume that individual actors make\ndecisions about their outgoing ties through a series of small, sequential\nupdates. This simplifies the modeling process while remaining grounded in a\nrealistic representation of social behavior.\n\nThe SAOM framework relies on three core assumptions:\n\n1. **One actor at a time**: At each micro-step, a single actor $i$ is randomly\n   selected and given the opportunity to revise their outgoing ties. This\n   reflects individual, sequential decision-making.\n\n2. **One tie at a time**: The selected actor $i$ considers one outgoing tie\n   $y_{ij}(t)$ for some $j \\neq i$, and may choose to create it\n   ($y_{ij}(t) = 1$), dissolve it ($y_{ij}(t) = 0$), or leave it unchanged.\n   Only one tie variable can change per step, which keeps the space of possible\n   transitions manageable.\n\n3. **Actor-controlled change**: Each actor controls only their own outgoing\n   ties. Tie changes arise solely from the actor's individual evaluation of the\n   current network state $Y(t)$ and are not the result of simultaneous or\n   coordinated actions.\n\nTogether, these assumptions define a process of sequential micro-steps, each\ninvolving:\n\n- Selecting an actor $i$ at random,\n- Considering a possible change to one tie $y_{ij}(t)$,\n- And waiting a randomly determined time before the next opportunity arises.\n\nThis process unfolds in continuous time and follows the structure of a\ncontinuous-time Markov chain (CTMC). It consists of two key components: the\n**holding time**, which determines how long the current network state $Y(t)$\npersists, and the **jump chain**, which defines the probability of transitioning\nto a new network state via a single tie update.\n\n\n#### The Holding Time and the Jump Chain\n\nThe **holding time** in SAOMs refers to the waiting period before an actor is\ngiven the opportunity to change one of their outgoing ties. In accordance with\nthe properties of a continuous-time Markov chain (CTMC), this waiting time is\nmodeled as an exponentially distributed random variable.\n\nFor actor $i$, the holding time $T_i$ has the following probability density\nfunction:\n$$\nf_{T_i}(t) = \\lambda_i e^{-\\lambda_i t}, \\quad \\lambda_i > 0, \\quad t > 0\n$$\nHere, $\\lambda_i$ is the rate parameter, determining how frequently actor $i$\nreceives opportunities to change their ties. The choice of $\\lambda_i$ defines\nhow the actor selection process unfolds:\n\n- **Homogeneous specification**: All actors have the same rate $\\lambda$,\n  implying equal opportunity:\n  $$\n  \\lambda_i = \\lambda \\quad \\text{for all } i, \\qquad \n  P(i \\text{ is selected}) = \\frac{1}{n}\n  $$\n\n- **Heterogeneous specification**: The rate varies across actors based on\n  covariates or network structure:\n  $$\n  \\lambda_i = \\lambda_i(\\theta, Y(t), v)\n  $$\n  where $\\theta$ is a parameter vector, $Y(t)$ is the current network\n  configuration, and $v$ are actor-specific covariates. In this case:\n  $$\n  P(i \\text{ is selected}) = \n  \\frac{\\lambda_i(\\theta, Y(t), v)}{\\sum_{r=1}^{n} \\lambda_r(\\theta, Y(t), v)}\n  $$\n  This flexibility allows the model to reflect actor-level heterogeneity in the\n  speed of network change. In many applications, however, a homogeneous rate is\n  assumed for simplicity and interpretability.\n\nThis setup relies on the memoryless property of the exponential distribution:\n$$\nP(T_i > s + t \\mid T_i > t) = P(T_i > s)\n$$\nThat is, the probability that actor $i$ will be selected in the next instant is\nunaffected by how long they have already been waiting. This property aligns\nnaturally with the continuous-time Markov assumption and greatly simplifies\nsimulation. In summary, the holding time determines *when* micro-steps occur.\n\nOnce an actor has been selected and the holding time has elapsed, the next\nquestion becomes: *what* change (if any) will this actor make to the network?\nThis is governed by the **jump chain**, which determines the next network state.\n\nAt each micro-step, actor $i$ evaluates a set of feasible alternatives\n$\\{Y^{(a)}\\}_{a=1}^{A}$, each differing from the current network $Y(t)$ by at\nmost a change in one outgoing tie $y_{ij}(t)$ (i.e., forming, dissolving, or\nmaintaining a tie).\n\nEach alternative $Y^{(a)}$ is assigned a utility:\n$$\nU_{ia} = F_{ia} + \\varepsilon_{ia}\n$$\n\nHere, $F_{ia}$ represents the deterministic component of the utility function,\ntypically defined through an objective function that incorporates structural\neffects such as reciprocity, transitivity, or covariate similarity. The\n$\\varepsilon_{ia}$ term introduces randomness via a Gumbel-distributed\ndisturbance, reflecting unobserved preferences or decision noise.\n\nThis setup defines a **random utility model**, where actor $i$ selects among\nalternatives probabilistically. Under the Gumbel assumption, the choice\nprobabilities follow a multinomial logit form:\n\n$$\np_{ia} = \\frac{\\exp(F_{ia})}{\\sum_{b=1}^{A} \\exp(F_{ib})}\n$$\n\nwhere $F_{ia}$ is the deterministic utility that actor $i$ assigns to\nalternative $a$, corresponding to the candidate network $Y^{(a)}$.\n\nThese probabilities define the jump chain, describing the likelihood of moving\nfrom the current network state $Y(t)$ to a new state $Y^{(a)}$. Because only one\nactor changes at most one tie at each micro-step, the set of feasible\ntransitions is small, making the process computationally tractable.\n\nWe now make explicit how the deterministic component $F_{ia}$ is constructed.\nIt is given by an **objective function**:\n\n$$\nF_{ia} = f_i(\\theta, Y^{(a)}) = \\sum_{k=1}^{K} \\theta_k \\cdot s_{ik}(Y^{(a)}, v)\n$$\n\nwhere:\n\n- $Y^{(a)}$ is the candidate network after a tie change,\n- $s_{ik}(Y^{(a)}, v)$ is the contribution of effect $k$ for actor $i$,\n- $\\theta_k$ is the parameter associated with that effect.\n\nThis formulation makes clear that the utility of an alternative depends on how\nthe resulting network configuration aligns with the actor's preferences, as\ncaptured by the statistics $s_{ik}(\\cdot)$. The random utility formulation\nintroduces stochasticity while allowing for interpretable parameter estimation.\n\nIn summary, the jump chain determines *which* network configuration the process\nmoves to, conditional on actor selection. Combined with the holding time, which\ngoverns *when* actors are selected, it defines the dynamics of the SAOM as a\ncontinuous-time Markov process.\n\n#### Endogenous Effects in the Objective Function\n\nThe objective function introduced above is a linear combination of effects, each\ncapturing a specific structural pattern or social mechanism. These effects are\nconceptually similar to those used in Exponential Random Graph Models (ERGMs),\nalthough they differ in interpretation due to the dynamic and actor-oriented\nnature of SAOMs. They fall into two main categories:\n\n- **Endogenous effects**: derived from the structure of the network itself.\n- **Exogenous effects**: related to external actor attributes.\n\nThe objective function for actor $i$ evaluating a candidate network $Y^{(a)}$\nis given by:\n\n$$\nf_i(\\theta, Y^{(a)}) = \\sum_{k=1}^{K} \\theta_k \\cdot s_{ik}(Y^{(a)})\n$$\n\nwhere $\\theta_k$ is the parameter for effect $k$, and s_{ik}(Y^{(a)}) is\nthe value of effect $k$ evaluated for actor $i$ in the candidate network\n$Y^{(a)}$. Each effect enters the objective function with an associated\nparameter to be estimated from data. The weighted sum of these effects (together\nwith a stochastic component) determines the actor's utility for each potential\ntie change, guiding the probabilistic decision-making process at the heart of\nthe SAOM framework.\n\nThis section focuses on a set of commonly used endogenous effects, that is,\neffects based solely on the structure of the network (without using external\ncovariates). Many other effects can be specified, depending on the theoretical\nfocus and complexity of the network under study.\n\n##### 1. Outdegree Effect {.unnumbered}\n\nSimilar to the `edges` term in ERGM, this effect reflects the tendency (or cost)\nof maintaining ties. It counts the number of outgoing ties from actor $i$ in the\ncandidate network configuration $Y^{(a)}$:\n\n$$\ns_i^{\\text{out}}(Y^{(a)}) = \\sum_{j} y^{(a)}_{ij}\n$$\n\nThis term typically has a negative coefficient, penalizing actors for having too\nmany ties, and thus introducing a cost to maintaining social relationships.\n\n##### 2. Reciprocity Effect {.unnumbered}\n\nThe reciprocity effect captures the tendency for actors to form mutual ties\n(equivalent to the `mutual` term in ERGMs). It counts how many of actor $i$'s\noutgoing ties are reciprocated:\n\n$$\ns_i^{\\text{rec}}(Y^{(a)}) = \\sum_{j} y^{(a)}_{ij} \\, y^{(a)}_{ji}\n$$\n\nA positive coefficient for this effect reflects a preference for mutual\nconnections, e.g., *\"I send a tie to those who also send one to me.\"*\n\n##### 3. Transitive Triplets Effect {.unnumbered}\n\nClosely related to the `triangles` or `GWESP` terms in ERGMs, this effect models\ntriadic closure. The transitive effect reflects a tendency toward forming\nclosed triads. If actor $i$ sends a tie to $h$, and $h$ sends a tie to $j$, then\n$i$ is more likely to send a tie to $j$.\n\n$$\ns_i^{\\text{trans}}(Y^{(a)}) = \\sum_{j,h} y^{(a)}_{ij} \\, y^{(a)}_{jh} \\, y^{(a)}_{ih}\n$$\n\nThis effect captures the formation of transitive triples (closed triads), where\n$i \\to j$, $j \\to h$, and $i \\to h$. It reflects processes such as social\nclosure, hierarchy, and the formation of cohesive subgroups.\n\n##### 4. Three-Cycle Effect {.unnumbered}\n\nThe three-cycle effect (analogous to cyclic triads in ERGMs) captures the\ntendency of actors to form circular structures in the network. Specifically,\nit counts the number of directed cycles of length three involving actor $i$:\n\n$$\ns_i^{\\text{cyc}}(Y^{(a)}) = \\sum_{j,h} y^{(a)}_{ij} \\, y^{(a)}_{jh} \\, y^{(a)}_{hi}\n$$\n\nThis effect captures patterns such as $i \\to j \\to h \\to i$, representing\nfeedback loops or non-hierarchical structures in the network. It often receives\na negative coefficient, discouraging cyclic patterns and favoring more\nhierarchical or transitive structures.\n\nNext, we introduce exogenous effects, which link actor behavior to covariates\nsuch as attributes or group memberships.\n\n#### Exogenous Effects in the Objective Function {#sec-exeffects}\nIn addition to modeling endogenous network tendencies (such as reciprocity or\ntransitivity), SAOMs allow the inclusion of **exogenous covariates** that\ninfluence tie formation. These covariates capture observed attributes of actors\nor dyads that may shape network dynamics.\n\nWe denote covariate information by $v$. Depending on the context, $v$ may include:\n\n- **Actor-level covariates**: $v_i$ (e.g., age, gender, smoking status),\n- **Dyadic covariates**: $v_{ij}$ (e.g., geographic distance or similarity between actors $i$ and $j$).\n\nAs in ERGMs, these effects enter the **objective function**, which represents\nthe utility that actor $i$ associates with a candidate network configuration\n$Y^{(a)}$:\n\n$$\nf_i(\\theta, Y^{(a)}) = \\sum_{k=1}^{K} \\theta_k \\cdot s_{ik}(Y^{(a)}, v)\n$$\n\nHere, the statistics $s_{ik}(Y^{(a)}, v)$ may depend not only on the network\nstructure $Y^{(a)}$ but also on the covariates $v$. This allows actor $i$’s\nevaluation of potential tie changes to incorporate both structural features of\nthe network and observed attributes of actors or dyads.\n\nBelow are common types of exogenous effects.\n\n##### 1. Individual-Level Covariate Effects {.unnumbered} \n\nThese effects are based on **actor-level covariates** and can enter the\nobjective function in two ways:\n\n1. **Covariate-Ego Effect**\\\n   This effect captures whether actors with a particular covariate value are\n   more (or less) likely to form outgoing ties.\n   $$\n   s_i^{\\text{ego}}(Y^{(a)}, v) = v_i \\sum_j y^{(a)}_{ij}\n   $$\n   Here, $v_i$ is the covariate value for actor $i$ (the *ego*), and the\n   statistic counts how many ties they initiate. If the covariate is binary,\n   this can test whether having a trait (e.g., belonging to a particular group)\n   is associated with being more active in sending ties.\n\n2. **Covariate-Alter Effect**\\\n   This effect reflects a preference for forming ties to others (*alters*) with\n   certain attribute values.\n   $$\n   s_i^{\\text{alter}}(Y^{(a)}, v) = \\sum_j y^{(a)}_{ij} \\, v_j\n   $$\n   Here, $v_j$ is the covariate value of the potential receiver. A positive\n   parameter indicates that actors are more likely to send ties to alters with\n   higher covariate values (and vice versa).\n\n##### 2. Dyadic Covariate Effects {.unnumbered}\n\nSAOMs also allow modeling based on **dyadic similarity**, capturing whether\nactors prefer to connect with others who are similar in some attribute.\n\nA common specification is the similarity-based effect:\n$$\ns_i^{\\text{sim}}(Y^{(a)}, v) \n= \\sum_j y^{(a)}_{ij} \n\\left( 1 - \\frac{|v_i - v_j|}{\\max(v) - \\min(v)} \\right)\n$$\n\nThis statistic increases when actor $i$ sends ties to actors $j$ who are similar\nin their covariate values. The similarity term is normalized to the interval\n$[0,1]$, where 1 indicates perfect similarity and 0 indicates maximal\ndifference.\n\nFor binary covariates, this simplifies to an indicator function:\n$$\ns_i^{\\text{sim}}(Y^{(a)}, v) = \\sum_j y^{(a)}_{ij} \\cdot \\mathbf{1}(v_i = v_j)\n$$\n\nThis effect captures **homophily**, the tendency of actors to form ties with\nothers who share the same attribute (e.g., same gender or group membership).\n\n#### Choosing Effects for the Objective Function\n\nWhen specifying a Stochastic Actor-Oriented Model (SAOM), the first step is to\nselect which effects to include in the actor's objective function\n$f_i(\\theta, Y^{(a)})$. At a minimum, models typically include an outdegree\neffect (capturing a baseline tendency to form ties) and a reciprocity effect\n(capturing the preference for mutual ties). \n\nBeyond these baseline effects, additional terms should be guided by substantive\ntheory or research hypotheses. For example, if theory suggests that individuals\ntend to befriend friends of their friends, a transitive triplet effect may be\nappropriate. If social similarity (homophily) based on covariates such as gender\nis expected, similarity-based covariate effects can be included.\n\nThese choices tailor the model to reflect specific structural patterns and\nattribute-driven mechanisms. While only a few examples are presented here,\nSAOMs provide a wide range of endogenous and exogenous effects that can be\ncombined to test theoretically meaningful processes of network evolution.\n\n### Parameter Estimation and Interpretation\n\nIn Stochastic Actor-Oriented Models (SAOMs), each parameter $\\theta_k$\nquantifies the importance of a specific effect $s_{ik}(Y^{(a)}, v)$ in the\nactor's decision-making process during network evolution. These parameters help\nus understand how structural features or covariates influence the likelihood of\ndifferent tie changes.\n\nThe interpretation of $\\theta_k$ is as follows:\n\n- If $\\theta_k = 0$, the statistic $s_{ik}(Y^{(a)}, v)$ has no effect on the\n  transition probabilities and does not influence network dynamics.\n- If $\\theta_k > 0$, actor $i$ is more likely to move toward network states\n  $Y^{(a)}$ that increase the value of $s_{ik}(Y^{(a)}, v)$.\n- If $\\theta_k < 0$, actor $i$ prefers changes that decrease the value of\n  $s_{ik}(Y^{(a)}, v)$.\n\nImportantly, these preferences are assumed to be stable over time. That is, the\nparameter vector $\\theta = (\\theta_1, \\dots, \\theta_K)$ is assumed to be constant\nthroughout the observation period:\n$$\n\\theta_1, \\dots, \\theta_K \\text{ are constant over time.}\n$$\n\nParameter estimation in SAOMs is performed using simulation-based methods, as\nimplemented in the `RSiena` R package (SIENA: Simulation Investigation for\nEmpirical Network Analysis).\n\nThe core idea is to simulate the network evolution process under the assumed\nmodel, compare the simulated outcomes with observed data, and iteratively adjust\nthe parameters to improve the fit. This approach is based on the **method of\nmoments**, where simulated network statistics are aligned with their empirical\ncounterparts.\n\nThe estimation process typically involves:\n\n- Defining the observed networks at multiple time points,\n- Specifying the effects (endogenous and exogenous) to include in the model,\n- Running simulations and updating parameters iteratively until convergence.\n\nTo assess whether a particular effect significantly contributes to the network\ndynamics, we test each parameter $\\theta_k$:\n\n- **Null Hypothesis ($H_0$):** The effect has no influence on tie changes,\n  $$\n  H_0 : \\theta_k = 0\n  $$\n- **Alternative Hypothesis ($H_1$):** The effect has a systematic influence,\n  $$\n  H_1 : \\theta_k \\ne 0\n  $$\n\nUnder standard conditions, inference is based on the **t-ratio**, defined as the\nratio of the parameter estimate to its standard error:\n$$\n\\left| \\frac{\\theta_k}{\\text{s.e.}(\\theta_k)} \\right| \\ge 2 \n\\;\\Rightarrow\\; \\text{Reject } H_0\n$$\n\nIf the absolute t-ratio exceeds 2, the parameter is considered significantly\ndifferent from zero at approximately the 5% significance level.\n\n### RSiena\nRSiena is an R package for estimating and simulating Stochastic Actor-Oriented\nModels (SAOMs) for network and behavioral dynamics. It is specifically designed\nto analyze longitudinal network data, where social ties and actor attributes\nevolve over time.\n\nIn RSiena, the distinction between modeling **network evolution** and the\n**co-evolution of networks and behavior** begins with how the dependent\nvariables are specified.\n\nIf only the network is included as a dependent variable (i.e., a\n`sienaDependent` network object), the model focuses on network evolution. This\nframework captures how actors form, maintain, or dissolve ties over time. It\ncan include covariates (such as gender or smoking status) to explain **social\nselection**, meaning that actor attributes influence the likelihood of tie\nformation or dissolution. In this case, individual attributes are treated as\nexogenous and remain fixed over time.\n\nAlternatively, RSiena allows for **co-evolution models** by including both a\nnetwork and a behavioral variable as dependent variables. This setup enables the\nsimultaneous modeling of two processes: how networks evolve and how actors'\nbehaviors change over time. This makes it possible to study **social influence**,\nwhere individuals may adopt behaviors similar to those of their network peers.\nThe model thus captures both the selection of network ties based on covariates\nand the influence of peers on individual behavior.\n\nBelow, we outline the typical steps involved in estimating SAOMs using RSiena:\n\n1. **Preparing the data**\\\n   Import and format the network and covariate data into the appropriate\n   structure. This includes creating adjacency matrices for networks observed\n   over time and vectors or matrices for actor-level covariates. These are then\n   converted into RSiena objects such as `sienaDependent`, `coCovar`, or\n   `varCovar`.\n\n2. **Specifying the model**\\\n   Define the model by selecting the effects to include. Use `getEffects()` to\n   retrieve the default effects object and `includeEffects()` to add endogenous\n   and covariate-related effects.\n\n3. **Estimating the model**\\\n   Set up the estimation procedure using `sienaAlgorithmCreate()` and estimate\n   the model with `siena07()`. Evaluate convergence and diagnostic statistics to\n   ensure reliable results.\n\n4. **Interpreting the results**\\\n   Analyze the estimated parameters to understand the underlying social\n   processes. This involves examining the direction, magnitude, and statistical\n   significance of effects to interpret mechanisms of network change or\n   co-evolution.\n\n\n#### Model 1: Structural Effects\nWe begin by estimating a simple model specification that includes only two\neffects: an outdegree (density) effect and a reciprocity effect. These capture\nbaseline tie propensity and the tendency toward mutual ties, without\nincorporating more complex structural or covariate-based influences. In other\nwords, no covariates are included, and the model is specified purely in terms of\nendogenous network dynamics.\n\nWe first convert the 3D network array `net_array` into a `sienaDependent`\nobject using the `sienaDependent()` function. This step tells `RSiena` that the\narray represents a dependent network variable observed over multiple waves. The\nresulting object is then used as input for model specification and estimation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert array into RSiena dependent object\nsiena_net <- sienaDependent(net_array)\n```\n:::\n\n\nAfter defining the network as a `sienaDependent` object, we now wrap it into a\ncomplete `RSiena` data object using `sienaDataCreate()`. This function prepares\nthe data for model specification and estimation by bundling all input variables\n(here just the network) into a structure that the estimation algorithm can use.\n\nSince we are modeling only the network (and no actor covariates yet), we simply\npass `siena_net` as the argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a Siena data object\ndata_mod1 <- sienaDataCreate(siena_net)\n```\n:::\n\n\nIn RSiena, model specification is driven by the concept of \"effects\" which\nrepresent the structural features, covariate influences, and behavioral\nmechanisms that are hypothesized to drive network or behavioral change. By\ndefault, `getEffects()` lists all possible effects available for the data\nstructure (e.g., network dynamics, covariates, behaviors). It doesn't add any\neffects to the model yet though, it just initializes the structure that will\nhold them.\n\nWe begin by calling `getEffects()` on our `data_mod1` object to create a\ndefault effects object. This object holds all possible effects for the given\ndata structure and is used as a base for customization. You can have a look at\nthese effects directly by calling it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the effects: start with default effect object\nmy_effects <- getEffects(data_mod1)\nmy_effects\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  effectName                         include fix   test  initialValue parm\n1 constant siena_net rate (period 1) TRUE    FALSE FALSE    7.45424   0   \n2 constant siena_net rate (period 2) TRUE    FALSE FALSE    6.82927   0   \n3 outdegree (density)                TRUE    FALSE FALSE   -1.61299   0   \n4 reciprocity                        TRUE    FALSE FALSE    0.00000   0   \n```\n\n\n:::\n:::\n\n\nThese are the exact effects included by default:\n\n- Rate parameters for each wave transition (e.g., Period 1 and Period 2)\n- Outdegree (density): capturing the baseline propensity to send ties\n- Reciprocity: modeling the tendency to reciprocate received ties\n\nSince our simple model includes only these two structural effects, there is no\nneed to add further effects using `includeEffects()` at this stage.\n\nBefore running the estimation, we need to define the estimation algorithm that\nRSiena will use. This is done with the function `sienaAlgorithmCreate()`, which\nsets up the computational parameters for the simulation-based estimation\nprocess.\n\nIn the example below, we assign the algorithm to the object `my_algorithm`. The\n`projname` argument specifies a name for the project; RSiena will use this name\nto organize temporary output files and logs related to the estimation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the estimation algorithm\nmy_algorithm <- sienaAlgorithmCreate(projname = \"saom_1\", seed = 123)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIf you use this algorithm object, siena07 will create/use an output file saom_1.txt .\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\nSetting a seed as argument ensures reproducible results across runs given same R\nsetup. Due to the stochastic nature of the algorithm and differences in\ncomputational environments, minor variations may still occur across:\n\n- different versions of R or RSiena,\n- different operating systems,\n- or when using parallel processing.\n:::\n\nThis algorithm object is later passed into the `siena07()` function to control\nhow the estimation is performed. You can customize various settings like number\nof iterations, convergence thresholds, or use defaults (as we do here) for a\nbasic estimation.\n\nNow that we've set up the data, specified the effects, and defined the\nestimation algorithm, we can estimate the Stochastic Actor-Oriented Model using\nthe `siena07()` function. This function runs the RSiena estimation procedure. It\ntakes the following inputs:\n\n- `my_algorithm`: the algorithm settings we defined earlier.\n- `data = data_mod1`: the network data in RSiena format.\n- `effects = my_effects`: the specified model effects (in this case, outdegree\n  and reciprocity).\n- `batch = TRUE`: suppresses user prompts during the estimation, making it\n  suitable for scripted or automated runs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimate the SAOM\nsaom_1 <- siena07(\n  my_algorithm,\n  data = data_mod1,\n  effects = my_effects,\n  batch = TRUE\n)\n```\n:::\n\n\nTo print a summary of the estimation results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# View results\nsaom_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimates, standard errors and convergence t-ratios\n\n                                   Estimate   Standard   Convergence \n                                                Error      t-ratio   \n\nRate parameters: \n  0.1      Rate parameter period 1  8.5797  ( 0.6983   )             \n  0.2      Rate parameter period 2  7.2383  ( 0.6048   )             \n\nOther parameters: \n  1.  eval outdegree (density)     -2.4114  ( 0.0407   )   -0.0013   \n  2.  eval reciprocity              2.7049  ( 0.0858   )   -0.0252   \n\nOverall maximum convergence ratio:    0.0396 \n\n\nTotal of 2412 iteration steps.\n```\n\n\n:::\n:::\n\n\nA nicer summary of the model is obtained by running the following, which\nrenders the table of results inline (including significance stars for easy\ninterpretation):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsiena.table(saom_1, type = \"html\", sig = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n<TABLE border=1  rules=none frame = hsides>\n<TR><TD>Effect</TD><TD>&nbsp;&nbsp;&nbsp;par.</TD><TD></TD>\n\t\t\t\t\t<TD>&nbsp;&nbsp;&nbsp; (s.e.) </TD>  </TR>\n\n<TR><TD>Rate 1</TD><TD align=\"right\">8.580</TD><TD align=\"left\"></TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.698)</TD></TR>\n<TR><TD>Rate 2</TD><TD align=\"right\">7.238</TD><TD align=\"left\"></TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.605)</TD></TR>\n\n\n<TR><TD>outdegree (density) </TD><TD align=\"right\">&nbsp;&ndash;2.411</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.041)</TD></TR>\n<TR><TD>reciprocity         </TD><TD align=\"right\">  2.705</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.086)</TD></TR>\n<TR> <TD colspan='9'><HR/></TD> </TR>\n</TABLE>\n<TABLE border=1  rules=none frame = below>\n<TR> <TD colspan=4 align=left> &#134 p < 0.1;\n\t\t\t\t\t\t\t* p < 0.05; ** p < 0.01; *** p < 0.001;  </TD> </TR> <TR> </TR> \n <TR> <TD colspan=9 align=left>\n\t\t\t\t\t\t\tall convergence t ratios < 0.03.</TD> </TR> <TR> </TR> <TR> <TD colspan=9 align=left>\n\t\t\t\t\t\t\tOverall maximum convergence ratio 0.04.</TD> </TR> <TR> </TR>\n</TABLE>\n\n**So, how do we interpret the parameter estimates?**\n\nBefore interpreting parameter estimates, it's essential to assess whether the\nestimation has converged adequately. In RSiena, convergence is assessed using\ntwo main criteria:\n\n1. Overall maximum convergence ratio:\\  This value summarizes how far the\n   simulated statistics deviate from the observed ones. A value below 0.25 is\n   generally considered acceptable, with values below 0.15 indicating very good\n   convergence.\n\n2. Individual convergence t-ratios:\\\n   For each effect, the t-ratio compares the observed statistic to the average\n   from the simulated networks. If the estimation has converged, these t-ratios\n   should be close to zero. Values below 0.10 are ideal, and below 0.20 is\n   generally acceptable.\n\n##### Convergence Assessment {.unnumbered}\n\nAll convergence t-ratios in our Model 1 ouput are below 0.03, which suggests\nthat the simulated statistics align closely with the observed network statistics\nfor each parameter. This implies that the estimated model reproduces the key\nstructural features of the observed data with high precision. Additionally, the\noverall maximum convergence ratio is 0.04, which is well below the commonly used\nthreshold of 0.10, and even under the more conservative cutoff of 0.05. This\nmeans that none of the parameters are associated with poor convergence behavior.\nTaken together, these diagnostics confirm that the SAOM estimation process has\nstabilized, and the parameter estimates can be interpreted with confidence.\n\n##### Rate Parameters {.unnumbered}\n\nThe rate parameters capture how frequently actors are given the opportunity to\nchange their outgoing ties between two consecutive observation moments. These\nare modeled as intensities in a continuous-time Markov framework.\n\nThe estimates can be interpreted as follows:\n\n- **Rate 1**: Estimate = 8.580 (SE = 0.698)  \n  On average, each actor had about 9 opportunities to change a tie between\n  waves 1 and 2.\n\n- **Rate 2**: Estimate = 7.238 (SE = 0.605)  \n  On average, each actor had about 7 opportunities to change a tie between\n  waves 2 and 3.\n\nThese values do not indicate how many changes were actually made, but how often\nactors *could have* made a change. Since actors may choose not to modify a tie\n(i.e., retain the current state), the actual number of observed changes is\ntypically lower than the number of opportunities.\n\n\n##### Network Dynamics {.unnumbered}\n\nOnce an actor is given an opportunity to change a tie, their decision is guided\nby an objective function that evaluates alternative network states. Each effect\nincluded in the model represents a social mechanism influencing this decision.\n\nThe main effects in this model are:\n\n- **Outdegree (density)**: Estimate = –2.411 (SE = 0.041)  \n  Strong negative effect: actors are generally reluctant to form many ties.\n\n- **Reciprocity**: Estimate = 2.705 (SE = 0.086)  \n  Strong positive effect: actors strongly prefer to reciprocate existing ties.\n\nBoth estimates are statistically significant, as their t-ratios exceed 2.\n\n\n##### Interpretation of Parameters\n\n**Outdegree (density):** $\\theta_{\\text{out}} = -2.411$  \nA strong negative value indicates that actors prefer *sparser networks*. Forming\nnew ties carries a cost, so additional ties are less likely unless offset by\nother favorable effects.\n\n**Reciprocity:** $\\theta_{\\text{rec}} = 2.705$  \nA strong positive value reflects a preference for reciprocating existing ties.\nIf another actor sends a tie to ego, ego is much more likely to return it.\n\n\n##### Interpreting Utility Changes\n\nThese effects jointly determine how actors evaluate potential tie changes. The\nobjective function for actor $i$ can be written as:\n\n$$\nf_i(\\theta, Y^{(a)}) =\n\\theta_{\\text{out}} \\sum_{j} y^{(a)}_{ij}\n+\n\\theta_{\\text{rec}} \\sum_{j} y^{(a)}_{ij} \\, y^{(a)}_{ji}\n$$\n\nTo understand this, consider two scenarios:\n\n1. **Adding a reciprocated tie**  \n   Suppose $y_{ji}(t) = 1$ (the other actor has already sent a tie), and actor\n   $i$ considers forming $y_{ij} = 1$. The change in utility is:\n\n   $$\n   -2.411 + 2.705 = 0.294\n   $$\n\n   This yields a **positive utility change**, making the move likely.\n\n2. **Adding a non-reciprocated tie**  \n   If $y_{ji}(t) = 0$, the tie is not reciprocated. The utility change is:\n\n   $$\n   -2.411\n   $$\n\n   This is **negative**, making the change unlikely.\n\n\nOverall, the results indicate that actors strongly prefer reciprocated ties and\nare cautious about forming many new ties. Reciprocated ties generate positive\nutility, while unreciprocated ties are penalized. These patterns reflect\nwell-known social mechanisms: a preference for mutual relationships and an\naversion to the costs of maintaining many ties.\n\n#### Model 2: Structural + Covariate Effects\n\nSociological theory suggests that, beyond general tendencies such as reciprocity\nand transitivity, actors are influenced by individual characteristics when\nforming or maintaining ties. In adolescent friendship networks, one of the most\nimportant predictors of tie formation is behavioral similarity, such as shared\nlifestyle choices or habits.\n\nHaving established a baseline SAOM using only endogenous structural effects\n(e.g., outdegree and reciprocity), we now extend the model to incorporate\nactor-level covariates. By including exogenous attributes such as sex and\nsmoking behavior, we can investigate how individual characteristics shape tie\nformation in addition to structural patterns. This richer specification allows\nus to test more nuanced hypotheses about social selection and influence\nmechanisms within the network.\n\nAs discussed in @sec-exeffects, incorporating covariates into the objective\nfunction requires distinguishing between different types of effects:\n\n- **Ego effects**: How an actor's own covariate value influences their tendency\n  to form or maintain ties (e.g., do smokers send more ties?).\n- **Alter effects**: How the recipient's covariate value affects the likelihood\n  of receiving a tie (e.g., are smokers more likely to be chosen as friends?).\n- **Similarity effects**: Whether actors prefer to form ties with others who are\n  similar to themselves (e.g., are adolescents more likely to befriend others\n  with similar smoking behavior?).\n\nThis extended specification remains actor-oriented and stochastic but adds an\nimportant layer of covariate-based preference. It allows us to distinguish\nbetween purely structural mechanisms and individual-level traits influencing\nnetwork evolution, aligning more closely with theoretical insights from social\npsychology and adolescent health research.\n\nBuilding on Model 1, which included only outdegree (density) and reciprocity, we\nnow incorporate exogenous covariate information to obtain a more nuanced model\nof friendship dynamics.\n\nIn Model 2, we treat sex as a fixed covariate and smoking behavior as a changing\ncovariate observed at each wave. We include the following additional effects:\n\n- **Ego effect of smoking**: Does an adolescent's smoking status influence how\n  many ties they send?\n- **Alter effect of smoking**: Are smokers more likely to receive ties?\n- **Similarity in smoking**: Are adolescents more likely to form ties with\n  others who have similar smoking behavior?\n- **Sex effects**: Do patterns of tie formation differ by sex?\n\nIn sum, Model 2 captures not only structural tendencies in friendship formation\nbut also how individual traits shape social dynamics, resulting in a more\nrealistic and theoretically grounded model of network evolution.\n\nWe begin by converting the 3D network array into a `sienaDependent` object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert array into RSiena dependent object\nsiena_net <- sienaDependent(net_array)\n```\n:::\n\n\nLike before, this object represents the longitudinal network that serves as the\ndependent variable in the SAOM. Different from before, we extract covariate\nvalues from the network's node attributes. Sex (`sex.F`) is treated as a\ntime-invariant covariate, while smoking behavior (`familysmoking`) is treated as\ntime-varying across the three network waves.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract sex (constant over all waves) and recode to numeric: 1 = Female, 0 = Male\nsex_char <- V(glasgow_g2)$sex.F\nsex_num <- ifelse(sex_char == \"F\", 1,\n                  ifelse(sex_char == \"M\", 0, NA))\n# convert to fixed covariate object                  \nsex_cov <- coCovar(sex_num)\n\n# Extract smoking behavior (assumed changing)\nsmoke1 <- as.numeric(V(glasgow_g1)$tobacco)\nsmoke2 <- as.numeric(V(glasgow_g2)$tobacco)\nsmoke3 <- as.numeric(V(glasgow_g3)$tobacco)\nsmoking_array <- cbind(smoke1, smoke2, smoke3)\n# convert to changing covariate object\nsmoking_cov <- varCovar(smoking_array)\n```\n:::\n\n\nNext we combine the network and covariates into a single Siena data object that\nwill be used for estimation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_mod2 <- sienaDataCreate(siena_net, sex_cov, smoking_cov)\n```\n:::\n\n\nWe define the effects to be included in the model. This includes structural\neffects (like outdegree, reciprocity, and transitive triplets) as well as ego,\nalter, and similarity effects for both sex and smoking covariates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Start with the default effect set\nmy_effects <- getEffects(data_mod2)\n\n# Add structural effects\nmy_effects <- includeEffects(my_effects, outdegree, recip, transTrip)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  effectName          include fix   test  initialValue parm\n1 reciprocity         TRUE    FALSE FALSE          0   0   \n2 transitive triplets TRUE    FALSE FALSE          0   0   \n```\n\n\n:::\n\n```{.r .cell-code}\n# Add effects for sex\nmy_effects <- includeEffects(my_effects, egoX, altX, simX, interaction1 = \"sex_cov\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  effectName         include fix   test  initialValue parm\n1 sex_cov alter      TRUE    FALSE FALSE          0   0   \n2 sex_cov ego        TRUE    FALSE FALSE          0   0   \n3 sex_cov similarity TRUE    FALSE FALSE          0   0   \n```\n\n\n:::\n\n```{.r .cell-code}\n# Add effects for smoking\nmy_effects <- includeEffects(my_effects, egoX, altX, simX, interaction1 = \"smoking_cov\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  effectName             include fix   test  initialValue parm\n1 smoking_cov alter      TRUE    FALSE FALSE          0   0   \n2 smoking_cov ego        TRUE    FALSE FALSE          0   0   \n3 smoking_cov similarity TRUE    FALSE FALSE          0   0   \n```\n\n\n:::\n:::\n\n\nWe define the estimation settings using `sienaAlgorithmCreate()`. A seed is\nincluded to support reproducibility of the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_algorithm <-  sienaAlgorithmCreate(projname = \"saom_2\", seed = 123)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIf you use this algorithm object, siena07 will create/use an output file saom_2.txt .\n```\n\n\n:::\n:::\n\n\nWe now estimate the model using the `siena07()` function, which runs the\nsimulation-based estimation procedure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaom_2 <- siena07(\n  my_algorithm,\n  data = data_mod2,\n  effects = my_effects,\n  batch = TRUE\n)\n```\n:::\n\n\nFinally, as before, we display the model results inline:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsiena.table(saom_2, type = \"html\", sig = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n<TABLE border=1  rules=none frame = hsides>\n<TR><TD>Effect</TD><TD>&nbsp;&nbsp;&nbsp;par.</TD><TD></TD>\n\t\t\t\t\t<TD>&nbsp;&nbsp;&nbsp; (s.e.) </TD>  </TR>\n\n<TR><TD>Rate 1</TD><TD align=\"right\">10.753</TD><TD align=\"left\"></TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(1.033)</TD></TR>\n<TR><TD>Rate 2</TD><TD align=\"right\"> 9.062</TD><TD align=\"left\"></TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.829)</TD></TR>\n\n\n<TR><TD>outdegree (density)    </TD><TD align=\"right\">&nbsp;&ndash;2.862</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.056)</TD></TR>\n<TR><TD>reciprocity            </TD><TD align=\"right\">  1.990</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.092)</TD></TR>\n<TR><TD>transitive triplets    </TD><TD align=\"right\">  0.447</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.031)</TD></TR>\n<TR><TD>sex-cov alter          </TD><TD align=\"right\">&nbsp;&ndash;0.158</TD><TD align=\"left\">                 </TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.108)</TD></TR>\n<TR><TD>sex-cov ego            </TD><TD align=\"right\">  0.160</TD><TD align=\"left\">                 </TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.112)</TD></TR>\n<TR><TD>sex-cov similarity     </TD><TD align=\"right\">  0.918</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.094)</TD></TR>\n<TR><TD>smoking-cov alter      </TD><TD align=\"right\">  0.110</TD><TD align=\"left\">&#134</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.066)</TD></TR>\n<TR><TD>smoking-cov ego        </TD><TD align=\"right\">  0.072</TD><TD align=\"left\">                 </TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.063)</TD></TR>\n<TR><TD>smoking-cov similarity </TD><TD align=\"right\">  0.380</TD><TD align=\"left\">**</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(0.126)</TD></TR>\n<TR> <TD colspan='9'><HR/></TD> </TR>\n</TABLE>\n<TABLE border=1  rules=none frame = below>\n<TR> <TD colspan=4 align=left> &#134 p < 0.1;\n\t\t\t\t\t\t\t* p < 0.05; ** p < 0.01; *** p < 0.001;  </TD> </TR> <TR> </TR> \n <TR> <TD colspan=9 align=left>\n\t\t\t\t\t\t\tall convergence t ratios < 0.09.</TD> </TR> <TR> </TR> <TR> <TD colspan=9 align=left>\n\t\t\t\t\t\t\tOverall maximum convergence ratio 0.18.</TD> </TR> <TR> </TR>\n</TABLE>\n\nWe now interpret the results from Model 2, beginning with an assessment of\nconvergence, followed by the interpretation of the estimated parameters.\n\n##### Convergence Assessment {.unnumbered}\n\nIn Model 2, all convergence t-ratios are below 0.07, and the overall maximum\nconvergence ratio is 0.11. This indicates good convergence, and the parameter\nestimates can be interpreted with confidence.\n\n##### Rate Parameters {.unnumbered}\n\nRate parameters determine how frequently actors are given the opportunity to\nchange their outgoing ties between observation moments. The estimated rates are:\n\n- **Period 1**: 10.761 (SE = 1.054)\n- **Period 2**: 8.981 (SE = 0.850)\n\nThese values suggest that, on average, each actor had approximately 11\nopportunities to change a tie between waves 1 and 2, and about 9 opportunities\nbetween waves 2 and 3. Importantly, these values reflect the *rate of\nopportunities* for change, not the number of actual tie changes.\n\n##### Network Dynamics {.unnumbered}\n\n- **Outdegree (density)**: $-2.859$ (SE = 0.053)\\\n  This strong negative effect indicates that actors are generally reluctant to\n  form many ties, leading to relatively sparse networks.\n\n- **Reciprocity**: $1.991$ (SE = 0.089)\\\n  This positive effect reflects a strong tendency for actors to reciprocate\n  incoming ties.\n\n- **Transitive triplets**: $0.448$ (SE = 0.026)\\\n  This positive effect indicates a preference for triadic closure: if actor $i$\n  is tied to $j$, and $j$ is tied to $k$, then $i$ is more likely to form a tie\n  to $k$.\n\nTogether, these effects capture key structural features of the network dynamics:\nsparsity, reciprocity, and local clustering.\n\nWe now turn to covariate-related effects, starting with sex:\n\n- **Sex alter**: $-0.154$ (SE = 0.097, not significant)\\\n  There is no evidence that actors systematically prefer or avoid alters based\n  on their sex.\n\n- **Sex ego**: $0.159$ (SE = 0.103, not significant)\\\n  This suggests no significant difference in tie-sending activity between male\n  and female actors.\n\n- **Sex similarity**: $0.912$ (SE = 0.093)\\\n  This strong and statistically significant effect indicates a clear tendency\n  toward same-sex friendships, i.e., sex-based homophily.\n\nThe SAOM specification includes three effects based on the covariate `sex`,\nwhich is coded as `0` for boys and `1` for girls and is centered around its\nmean value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(sex_cov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4341085\n```\n\n\n:::\n:::\n\ni.e., $\\bar{v} = 0.434$. Thus, approximately 43.4% of actors in this dataset\nare girls. In `RSiena`, covariates are mean-centered by default, ensuring that\nestimated effects are interpreted relative to the average actor.\n\nAfter centering, the covariate values become:\n$$\nv_i - \\bar{v} =\n\\begin{cases}\n-0.434 & \\text{if actor } i \\text{ is a boy} \\\\\n\\;\\;0.566 & \\text{if actor } i \\text{ is a girl}\n\\end{cases}\n$$\n\nBecause covariates are mean-centered, the contribution of a potential tie\n$y_{ij}$ to the objective function depends on these centered values. The\ncovariate-related part of the objective function for actor $i$, when evaluating\na candidate network $Y^{(a)}$, can be written as:\n\n$$\nf_i(\\theta, Y^{(a)}) =\n\\theta_{\\text{ego}} (v_i - \\bar{v}) \\sum_{j} y^{(a)}_{ij}\n\\;+\\;\n\\theta_{\\text{alter}} \\sum_{j} y^{(a)}_{ij} (v_j - \\bar{v})\n\\;+\\;\n\\theta_{\\text{sim}} \\sum_{j} y^{(a)}_{ij} \\, I(v_i = v_j)\n$$\n\nwhere:\n\n- $v_i$ and $v_j$ are the covariate values (sex) for actors $i$ and $j$,\n  respectively (coded as 0 = boy, 1 = girl),\n- $\\bar{v} = 0.434$ is the sample mean of the covariate,\n- $y^{(a)}_{ij}$ indicates the presence of a tie from $i$ to $j$ in the\n  candidate network $Y^{(a)}$,\n- $I(v_i = v_j)$ is an indicator function equal to 1 if actors $i$ and $j$\n  share the same sex, and 0 otherwise.\n\n@tbl-sexeff below lists some example contributions to the objective function\n\n::: {#tbl-sexeff}\n  | Ego    | Alter  | Ego Term                         | Alter Term                        | Similarity Term | Total Contribution |\n  | ------ | ------ | -------------------------------- | --------------------------------- | --------------- | ------------------ |\n  | Male   | Male   | $0.159 \\times (-0.434) = -0.069$ | $-0.154 \\times (-0.434) = +0.067$ | $+0.912$        | $0.910$            |\n  | Male   | Female | $-0.069$                         | $-0.154 \\times 0.566 = -0.087$    | $0$             | $-0.156$           |\n  | Female | Male   | $0.159 \\times 0.566 = +0.090$    | $+0.067$                          | $0$             | $0.157$            |\n  | Female | Female | $+0.090$                         | $-0.087$                          | $+0.912$        | $0.915$            |\n\nSex-based contributions to the objective function under different ego-alter\ncombinations. {.striped}\n:::\n\nThese values show that same-sex ties, especially between girls, are more likely\ndue to the strong similarity effect. Cross-sex ties are less likely, receiving\nlower utility in the objective function.\n\nNext, we look at the behavioral covariate smoking. From the above output we note\nthe following:\n\n- **Smoking Alter**: $0.109$ (SE = 0.061, not significant)\\\n  Suggests no evidence that smoking status affects how attractive an actor is as\n  a tie recipient.\n\n- **Smoking Ego**: $0.077$ (SE = 0.063, not significant)\\\n  No effect of smoking behavior on how active an actor is in sending ties.\n\n- **Smoking Similarity**: $0.380$ (SE = 0.117)\\\n  This positive and significant parameter indicates a clear tendency toward\n  homophily with respect to smoking behavior: actors are more likely to form or\n  maintain friendships with others who share a similar smoking status.\n\nBased on the model output and the centered smoking covariate, we interpret the\nsmoking-related effects in the SAOM model. The smoking variable is ordinal with\nthree categories: 1 = no smoking, 2 = occasional smoking, and 3 = regular\nsmoking. The covariate is centered by subtracting its mean. In this case, the\nmean value is computed in R as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(smoking_cov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.377261\n```\n\n\n:::\n:::\n\n\nWe now interpret the covariate effects related to smoking behavior. In this\nmodel, smoking is treated as a three-level categorical covariate:\n1 = Non-smoker, 2 = Occasional, 3 = Regular. The mean of the covariate,\ncomputed via `mean(smoke_cov)`, is approximately $\\bar{v} = 1.377$.\n\nAfter mean-centering (as done by default in RSiena), the transformed values are:\n\n$$\nv_i - \\bar{v} =\n\\begin{cases}\n-0.377 & \\text{if } v_i = 1 \\quad \\text{(Non-smoker)} \\\\\n0.623  & \\text{if } v_i = 2 \\quad \\text{(Occasional smoker)} \\\\\n1.623  & \\text{if } v_i = 3 \\quad \\text{(Regular smoker)}\n\\end{cases}\n$$\n\nThe contribution of a potential tie $y_{ij}(t)$ (from actor $i$ to actor $j$)\nto the objective function is given by:\n\n$$\n\\theta_{\\text{ego}}(v_i - \\bar{v}) \n+ \\theta_{\\text{alter}}(v_j - \\bar{v}) \n+ \\theta_{\\text{sim}} \\left(1 - \\frac{|v_i - v_j|}{R_v}\\right)\n$$\n\nwhere $R_v$ denotes the range of the covariate $v$ (here, $R_v = 3 - 1 = 2$).\nSubstituting the estimated parameter values from the model:\n\n$$\n0.077(v_i - 1.377) + 0.109(v_j - 1.377) \n+ 0.380 \\left(1 - \\frac{|v_i - v_j|}{2} \\right)\n$$\n\nThis expression combines:\n\n- an **ego effect**, capturing how smoking behavior influences how many ties\n  actor $i$ tends to send,\n- an **alter effect**, capturing how smoking behavior affects how attractive\n  actor $j$ is as a recipient of ties,\n- and a **similarity effect**, which rewards ties between actors with similar\n  smoking levels.\n\n@tbl-smokeeff illustrates how these smoking-related covariate effects contribute\nto the objective function. Each cell reports the total contribution associated\nwith a potential tie from ego $i$ to alter $j$, given their respective smoking\nlevels.\n\n::: {#tbl-smokeeff}\n\n  | Ego        | Alter      | Ego Term                        | Alter Term                      | Similarity Term                 | Total Contribution |\n  | ---------- | ---------- | ------------------------------- | ------------------------------- | ------------------------------- | ------------------ |\n  | Non-smoker | Non-smoker | $0.077 \\cdot (-0.377) = -0.029$ | $0.109 \\cdot (-0.377) = -0.041$ | $0.380 \\cdot 1 = 0.380$         | $0.310$            |\n  | Non-smoker | Occasional | $-0.029$                        | $0.109 \\cdot 0.623 = 0.068$     | $0.380 \\cdot (1 - 0.5) = 0.190$ | $0.229$            |\n  | Non-smoker | Regular    | $-0.029$                        | $0.109 \\cdot 1.623 = 0.177$     | $0.380 \\cdot (1 - 1) = 0$       | $0.148$            |\n  | Occasional | Non-smoker | $0.077 \\cdot 0.623 = 0.048$     | $-0.041$                        | $0.190$                         | $0.197$            |\n  | Occasional | Occasional | $0.048$                         | $0.068$                         | $0.380$                         | $0.496$            |\n  | Occasional | Regular    | $0.048$                         | $0.177$                         | $0.190$                         | $0.415$            |\n  | Regular    | Non-smoker | $0.077 \\cdot 1.623 = 0.125$     | $-0.041$                        | $0$                             | $0.084$            |\n  | Regular    | Occasional | $0.125$                         | $0.068$                         | $0.190$                         | $0.383$            |\n  | Regular    | Regular    | $0.125$                         | $0.177$                         | $0.380$                         | $0.682$            |\n\nSmoking-related contributions to the objective function under different\nego-alter combinations. {.striped}\n:::\n\nWe see from @tbl-smokeeff that actors with similar smoking behavior are more\nlikely to form ties, especially regular-to-regular smokers, indicating a strong\nhomophily pattern. The ego and alter terms slightly amplify or reduce this\ntendency depending on individual smoking levels.\n\n## Modeling the Co-Evolution of Networks and Behaviors\n\n#### 1. Basic Shape Effects {.unnumbered}\n\nThese effects govern the overall shape or distribution of the behavior.\n\n- **Linear shape effect**  \n  This effect encourages an increase or decrease in behavior depending on the\n  sign of the parameter:\n\n  $$\n  s^\\text{beh}_{i,\\text{linear}}(z) = z_i\n  $$\n\n  If $\\theta_{\\text{lin}} > 0$, higher behavior values are favored. If\n  $\\theta_{\\text{lin}} < 0$, lower behavior values are favored.\n\n- **Quadratic shape effect**  \n  This effect penalizes extreme behavioral values (high or low), favoring\n  moderation:\n\n  $$\n  s^\\text{beh}_{i,\\text{quadratic}}(z) = z_i^2\n  $$\n\n  A negative estimate for this effect leads to stabilization around the middle\n  values of the behavioral scale, i.e., it favors moderate behavior (e.g.,\n  smoking occasionally rather than regularly).\n\nNote that the basic shape effects are typically included in the behavioral model\nspecification.\n\n#### 2. Social Influence Effects {.unnumbered}\n\nThe behavioral similarity effects in SAOMs allow us to model how actors adjust\ntheir behavior to become more similar to their peers. These effects assume that\nindividuals are influenced by the behavioral attributes of those they are\nconnected to.\n\n- **Average similarity**  \n  This effect captures how similar an actor's behavior is to their alters'\n  behaviors, averaged across all outgoing ties. It reflects per-peer influence.\n  The statistic is defined as:\n\n  $$\n  s^\\text{beh}_{i,\\text{avsim}}(Y, z) =\n  \\frac{1}{y_{i+}} \\sum_{j=1}^n y_{ij}\n  \\left( \\text{sim}_z(i,j) - \\overline{\\text{sim}_z} \\right)\n  $$\n\n  where:\n\n  - $y_{ij}$ is 1 if actor $i$ has a tie to actor $j$, and 0 otherwise.\n  - $y_{i+} = \\sum_{j=1}^n y_{ij}$ is the number of outgoing ties for actor $i$.\n  - $\\text{sim}_z(i,j)$ is the behavioral similarity between actor $i$ and actor\n    $j$, defined as:\n    $$\n    \\text{sim}_z(i,j) = 1 - \\frac{|z_i - z_j|}{R_z}\n    $$\n    where $R_z$ is the range of the behavior variable.\n  - $\\overline{\\text{sim}_z}$ is the average similarity across all dyads in the\n    network and acts as a centering constant. This centering ensures that the\n    statistic has an interpretable baseline, distinguishing whether actors are\n    more or less similar to their peers compared to the overall average.\n\n- **Total similarity**  \n  This variant captures the total amount of similarity, not normalized by the\n  number of ties. It gives more weight to actors with more alters:\n\n  $$\n  s^\\text{beh}_{i,\\text{totsim}}(Y, z) =\n  \\sum_{j=1}^n y_{ij}\n  \\left( \\text{sim}_z(i,j) - \\overline{\\text{sim}_z} \\right)\n  $$\n\nBoth versions reflect social influence. A positive parameter estimate means that\nactors are more likely to adjust their behavior to become more similar to those\nthey are connected to. In other words, the model captures conformity or peer\ninfluence. The higher the similarity between ego and alters, the higher the\nobjective function, making such changes more likely. A negative parameter\nestimate would indicate that actors tend to diverge from their peers, becoming\nless similar over time. This could suggest differentiation or opposition in\nbehavior, although negative influence parameters are rare and often\ntheoretically unexpected.\n\nThe difference between the two lies in how the influence is scaled: average\nsimilarity treats influence on a per-tie basis, while total similarity\naccumulates influence across all alters, potentially making actors with more\npeers more susceptible to conformity.\n\n#### 3. Network Position Effects {.unnumbered}\n\nNetwork position effects model whether an actor's behavior is associated with\ntheir position in the network. In this context, they are behavioral effects:\nthey ask whether actors with more incoming or outgoing ties tend to have higher\nor lower behavioral values.\n\n- **Outdegree effect**  \n  This effect investigates whether actors with more outgoing ties tend to have\n  different behavioral values:\n\n  $$\n  s^\\text{beh}_{i,\\text{out}}(Y, z) =\n  z_i \\sum_{j=1}^n y_{ij}\n  $$\n\n- **Indegree effect**  \n  This effect models whether being popular (having many incoming ties) is\n  related to behavior:\n\n  $$\n  s^\\text{beh}_{i,\\text{ind}}(Y, z) =\n  z_i \\sum_{j=1}^n y_{ji}\n  $$\n\nA positive parameter estimate for a position effect means that higher behavioral\nvalues are associated with the corresponding network position. For instance, if\nthe behavior is smoking, a positive outdegree effect suggests that actors who\nsmoke more tend to send more ties, while a positive indegree effect suggests\nthat actors who smoke more tend to receive more ties.\n\nA negative parameter estimate indicates that higher behavioral values are\nassociated with fewer ties in that position. For example, actors with higher\nsmoking values may be less active in sending ties or less popular as recipients,\ndepending on whether the outdegree or indegree effect is negative.\n\n#### 4. Covariate Effects {.unnumbered}\n\nCovariate effects capture how actor-level attributes, such as sex, age, or\nsocioeconomic status, directly influence behavioral change. Unlike social\ninfluence effects, these effects do not depend on the network ties themselves;\nthey test whether actors with certain attributes tend to have higher or lower\nbehavioral values.\n\n- **Covariate effect**  \n  Actor attributes can be included in the behavioral objective function as main\n  effects. This indicates whether an attribute $v_i$ is associated with higher\n  or lower behavior values:\n\n  $$\n  s^\\text{beh}_{i,\\text{covariate}}(v) = v_i\n  $$\n\nThese effects capture how an actor's covariate value influences their tendency\nto increase or decrease their behavioral score. For example, we might ask: Are\nboys or girls more likely to adopt a risky behavior? Do older students tend to\nreduce smoking over time?\n\n\n#### Model 3: Network and Behavioral Co-Evolution\n\nWe now estimate a co-evolution model in which the friendship network and smoking\nbehavior are both treated as dependent processes. The network evolves through\nchanges in ties, while smoking behavior evolves through changes in actors'\nbehavioral states.\n\n> Key point: here `smoking_beh` is no longer only a covariate. It is a **behavioral dependent variable**, so the model estimates both **selection** effects and **influence** effects.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Network dependent variable\nsiena_net <- sienaDependent(net_array)\n\n# Behavioral dependent variable: smoking over waves\nsmoking_beh <- sienaDependent(smoking_array, type = \"behavior\")\n\n# Time-constant covariate: sex\nsex_cov <- coCovar(sex_num)\n\n# Create RSiena data object\ndata_coev <- sienaDataCreate(\n  siena_net,\n  smoking_beh,\n  sex_cov\n)\n```\n:::\n\n\nWe now specify both network and behavioral effects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Start with default effects\nmy_effects <- getEffects(data_coev)\n\n# Network structural effects\nmy_effects <- includeEffects(\n  my_effects,\n  outdegree, recip, transTrip,\n  name = \"siena_net\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  effectName          include fix   test  initialValue parm\n1 reciprocity         TRUE    FALSE FALSE          0   0   \n2 transitive triplets TRUE    FALSE FALSE          0   0   \n```\n\n\n:::\n\n```{.r .cell-code}\n# Sex effects on network evolution\nmy_effects <- includeEffects(\n  my_effects,\n  egoX, altX, simX,\n  name = \"siena_net\",\n  interaction1 = \"sex_cov\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  effectName         include fix   test  initialValue parm\n1 sex_cov alter      TRUE    FALSE FALSE          0   0   \n2 sex_cov ego        TRUE    FALSE FALSE          0   0   \n3 sex_cov similarity TRUE    FALSE FALSE          0   0   \n```\n\n\n:::\n\n```{.r .cell-code}\n# Smoking-based selection effects on network evolution\nmy_effects <- includeEffects(\n  my_effects,\n  egoX, altX, simX,\n  name = \"siena_net\",\n  interaction1 = \"smoking_beh\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  effectName             include fix   test  initialValue parm\n1 smoking_beh alter      TRUE    FALSE FALSE          0   0   \n2 smoking_beh ego        TRUE    FALSE FALSE          0   0   \n3 smoking_beh similarity TRUE    FALSE FALSE          0   0   \n```\n\n\n:::\n\n```{.r .cell-code}\n# Behavioral dynamics: shape effects are typically included by default,\n# but we explicitly include peer influence via average alter behavior\nmy_effects <- includeEffects(\n  my_effects,\n  avAlt,\n  name = \"smoking_beh\",\n  interaction1 = \"siena_net\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  effectName                include fix   test  initialValue parm\n1 smoking_beh average alter TRUE    FALSE FALSE          0   0   \n```\n\n\n:::\n\n```{.r .cell-code}\nmy_effects\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   name        effectName                         include fix   test \n1  siena_net   constant siena_net rate (period 1) TRUE    FALSE FALSE\n2  siena_net   constant siena_net rate (period 2) TRUE    FALSE FALSE\n3  siena_net   outdegree (density)                TRUE    FALSE FALSE\n4  siena_net   reciprocity                        TRUE    FALSE FALSE\n5  siena_net   transitive triplets                TRUE    FALSE FALSE\n6  siena_net   sex_cov alter                      TRUE    FALSE FALSE\n7  siena_net   sex_cov ego                        TRUE    FALSE FALSE\n8  siena_net   sex_cov similarity                 TRUE    FALSE FALSE\n9  siena_net   smoking_beh alter                  TRUE    FALSE FALSE\n10 siena_net   smoking_beh ego                    TRUE    FALSE FALSE\n11 siena_net   smoking_beh similarity             TRUE    FALSE FALSE\n12 smoking_beh rate smoking_beh (period 1)        TRUE    FALSE FALSE\n13 smoking_beh rate smoking_beh (period 2)        TRUE    FALSE FALSE\n14 smoking_beh smoking_beh linear shape           TRUE    FALSE FALSE\n15 smoking_beh smoking_beh quadratic shape        TRUE    FALSE FALSE\n16 smoking_beh smoking_beh average alter          TRUE    FALSE FALSE\n   initialValue parm\n1     7.45424   0   \n2     6.82927   0   \n3    -1.61299   0   \n4     0.00000   0   \n5     0.00000   0   \n6     0.00000   0   \n7     0.00000   0   \n8     0.00000   0   \n9     0.00000   0   \n10    0.00000   0   \n11    0.00000   0   \n12    0.47181   0   \n13    0.42288   0   \n14   -0.58955   0   \n15    0.00000   0   \n16    0.00000   0   \n```\n\n\n:::\n:::\n\n\nWe define the estimation settings using `sienaAlgorithmCreate()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_algorithm <- sienaAlgorithmCreate(\n  projname = \"saom_coev\",\n  seed = 123\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIf you use this algorithm object, siena07 will create/use an output file saom_coev.txt .\n```\n\n\n:::\n:::\n\n\nWe now estimate the co-evolution model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaom_coev <- siena07(\n  my_algorithm,\n  data = data_coev,\n  effects = my_effects,\n  batch = TRUE\n)\n```\n:::\n\nFinally, we display the model results inline.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsiena.table(saom_coev, type = \"html\", sig = TRUE)\n```\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n<TABLE border=1  rules=none frame = hsides>\n<TR><TD>Effect</TD><TD>&nbsp;&nbsp;&nbsp;par.</TD><TD></TD>\n\t\t\t\t\t<TD>&nbsp;&nbsp;&nbsp; (s.e.) </TD>  </TR>\n<TR> <TD colspan=4 align=left> Network Dynamics   </TD> </TR> <TR> </TR>\n\n<TR><TD>constant siena-net rate (period 1) </TD><TD align=\"right\">   9.577</TD><TD align=\"left\"></TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 1.169)</TD></TR>\n<TR><TD>constant siena-net rate (period 2) </TD><TD align=\"right\">   8.259</TD><TD align=\"left\"></TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 1.835)</TD></TR>\n\n\n<TR><TD>outdegree (density)                </TD><TD align=\"right\">&nbsp;&ndash;2.975</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 0.087)</TD></TR>\n<TR><TD>reciprocity                        </TD><TD align=\"right\">   2.073</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 0.195)</TD></TR>\n<TR><TD>transitive triplets                </TD><TD align=\"right\">   0.457</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 0.035)</TD></TR>\n<TR><TD>sex-cov alter                      </TD><TD align=\"right\">&nbsp;&ndash;0.321</TD><TD align=\"left\">**</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 0.123)</TD></TR>\n<TR><TD>sex-cov ego                        </TD><TD align=\"right\">   0.364</TD><TD align=\"left\">**</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 0.129)</TD></TR>\n<TR><TD>sex-cov similarity                 </TD><TD align=\"right\">   1.063</TD><TD align=\"left\">***</TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 0.152)</TD></TR>\n<TR><TD>smoking-beh alter                  </TD><TD align=\"right\">   0.055</TD><TD align=\"left\">                 </TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 0.130)</TD></TR>\n<TR><TD>smoking-beh ego                    </TD><TD align=\"right\">   0.023</TD><TD align=\"left\">                 </TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 0.095)</TD></TR>\n<TR><TD>smoking-beh similarity             </TD><TD align=\"right\">   0.302</TD><TD align=\"left\">                 </TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;( 0.205)</TD></TR>\n<TR> <TD colspan='9'><HR/></TD> </TR>\n<TR> <TD colspan=4 align=left> Behaviour Dynamics   </TD> </TR> <TR> </TR>\n\n<TR><TD>rate smoking-beh (period 1)        </TD><TD align=\"right\">  36.351</TD><TD align=\"left\"></TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(11.732)</TD></TR>\n<TR><TD>rate smoking-beh (period 2)        </TD><TD align=\"right\">  37.029</TD><TD align=\"left\"></TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(24.368)</TD></TR>\n\n\n<TR><TD>smoking-beh linear shape           </TD><TD align=\"right\">&nbsp;&ndash;18.003</TD><TD align=\"left\">                 </TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(59.048)</TD></TR>\n<TR><TD>smoking-beh quadratic shape        </TD><TD align=\"right\">  16.650</TD><TD align=\"left\">                 </TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(55.703)</TD></TR>\n<TR><TD>smoking-beh average alter          </TD><TD align=\"right\">   7.399</TD><TD align=\"left\">                 </TD><TD align=\"right\">&nbsp;&nbsp;&nbsp;(28.541)</TD></TR>\n<TR> <TD colspan='9'><HR/></TD> </TR>\n</TABLE>\n<TABLE border=1  rules=none frame = below>\n<TR> <TD colspan=4 align=left> &#134 p < 0.1;\n\t\t\t\t\t\t\t* p < 0.05; ** p < 0.01; *** p < 0.001;  </TD> </TR> <TR> </TR> \n <TR> <TD colspan=9 align=left>\n\t\t\t\t\t\t\tall convergence t ratios < 3.39.</TD> </TR> <TR> </TR> <TR> <TD colspan=9 align=left>\n\t\t\t\t\t\t\tOverall maximum convergence ratio 28.47.</TD> </TR> <TR> </TR>\n</TABLE>\n\n\n\nIn summary, we note the following:\n\n- **Network structure**  \n  - Strong negative outdegree (density) effect $\\implies$ actors are selective; the network is sparse.  \n  - Strong positive reciprocity $\\implies$ actors tend to return ties.  \n  - Positive transitive triplets $\\implies$ evidence of triadic closure and clustering.  \n\n- **Sex effects (covariates)**  \n  - Significant ego effect $\\implies$ sex influences tie-sending activity.  \n  - Significant alter effect $\\implies$ sex affects likelihood of receiving ties.  \n  - Strong positive similarity effect $\\implies$ clear sex-based homophily.  \n\n- **Smoking and network selection**  \n  - No significant ego, alter, or similarity effects for smoking  \n  - $\\implies$ no evidence that friendships are formed based on smoking behavior.  \n\n- **Behavioral dynamics (smoking)**  \n  - High rate parameters $\\implies$ many opportunities for behavior change.  \n  - Linear and quadratic shape effects not significant $\\implies$ no clear baseline behavioral tendency.  \n  - Average alter effect not significant $\\implies$ no evidence of social influence.  \n\n- **Overall conclusion**  \n  - Network evolution is strongly structured (reciprocity, closure, homophily).\n  - $\\implies$ no evidence for selection or influence based on smoking behavior in this model.  \n  \n  \n::: {.callout-note}\n**Convergence assessment**\nIn this model, although individual convergence t-ratios are all below 3.39,\nthe overall maximum convergence ratio is **28.47**, which is far above acceptable\nthresholds. This indicates that the estimation has **not converged properly**.\n\nAs a result, the parameter estimates should be interpreted with caution.\nAdditional iterations, improved model specification, or adjustments to the\nestimation settings are required before drawing substantive conclusions.\n:::\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}