<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Termeh Shafie and David Schoch">

<title>7&nbsp; Ego Networks – R for Social Network Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../descriptive/netropy.html" rel="next">
<link href="../descriptive/signed-networks.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-36bf55b16c7cb4b1420f41495cb5446a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="7&nbsp; Ego Networks – R for Social Network Analysis">
<meta property="og:description" content="">
<meta property="og:image" content="https://schochastics.io/R4SNA/descriptive/ego-networks_files/figure-html/fig-egos-1.png">
<meta property="og:site_name" content="R for Social Network Analysis">
<meta property="og:image:height" content="1728">
<meta property="og:image:width" content="1728">
<meta name="twitter:title" content="7&nbsp; Ego Networks – R for Social Network Analysis">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://schochastics.io/R4SNA/descriptive/ego-networks_files/figure-html/fig-egos-1.png">
<meta name="twitter:image-height" content="1728">
<meta name="twitter:image-width" content="1728">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../descriptive/introduction.html">Descriptive Network Analysis</a></li><li class="breadcrumb-item"><a href="../descriptive/ego-networks.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ego Networks</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">R for Social Network Analysis</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/schochastics/R4SNA" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../network-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Data and Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Descriptive Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/descriptives-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Basic Network Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/centrality-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Centrality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Cohesive Subgroups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/two-mode-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-Mode Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/signed-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Signed Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/ego-networks.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ego Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive/netropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Entropy Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Network Visualization</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/ggraph-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Basics of ggraph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/ggraph-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Advanced Layouts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/enhance-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Enhancing Visualizations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization/interactive-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Interactive Visualization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Inferential Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/non-parametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Non-Parametric Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/rgm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Random Graph Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/ergm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Exponential Random Graph Models (ERGMs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/saom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Stochastic Actor Oriented Models (SAOMs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/rem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Relational Event Models (REMs)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Tidy Network Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/tidygraph-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Basics of tidygraph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tidy/tidygraph-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Descriptive Network Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/ucnets-egor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Constructing the UCNets Ego Network Dataset</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#packages-needed-for-this-chapter" id="toc-packages-needed-for-this-chapter" class="nav-link active" data-scroll-target="#packages-needed-for-this-chapter"><span class="header-section-number">7.1</span> Packages Needed for this Chapter</a></li>
  <li><a href="#ego-network-data-structure" id="toc-ego-network-data-structure" class="nav-link" data-scroll-target="#ego-network-data-structure"><span class="header-section-number">7.2</span> Ego Network Data Structure</a>
  <ul>
  <li><a href="#constructing-an-ego-network-with-egor" id="toc-constructing-an-ego-network-with-egor" class="nav-link" data-scroll-target="#constructing-an-ego-network-with-egor"><span class="header-section-number">7.2.1</span> Constructing an Ego Network with <code>egor</code></a></li>
  </ul></li>
  <li><a href="#plotting-ego-nets" id="toc-plotting-ego-nets" class="nav-link" data-scroll-target="#plotting-ego-nets"><span class="header-section-number">7.3</span> Plotting Ego Nets</a></li>
  <li><a href="#descriptive-statistics-for-ego-networks" id="toc-descriptive-statistics-for-ego-networks" class="nav-link" data-scroll-target="#descriptive-statistics-for-ego-networks"><span class="header-section-number">7.4</span> Descriptive Statistics for Ego Networks</a>
  <ul>
  <li><a href="#network-composition-based-on-alter-attributes" id="toc-network-composition-based-on-alter-attributes" class="nav-link" data-scroll-target="#network-composition-based-on-alter-attributes"><span class="header-section-number">7.4.1</span> Network Composition Based on Alter Attributes</a>
  <ul>
  <li><a href="#proportion-of-family-members" id="toc-proportion-of-family-members" class="nav-link" data-scroll-target="#proportion-of-family-members">Proportion of Family Members</a></li>
  <li><a href="#gender-composition-of-the-network" id="toc-gender-composition-of-the-network" class="nav-link" data-scroll-target="#gender-composition-of-the-network">Gender Composition of the Network</a></li>
  <li><a href="#racial-homophily" id="toc-racial-homophily" class="nav-link" data-scroll-target="#racial-homophily">Racial Homophily</a></li>
  </ul></li>
  <li><a href="#diversity-of-alters-within-ego-networks" id="toc-diversity-of-alters-within-ego-networks" class="nav-link" data-scroll-target="#diversity-of-alters-within-ego-networks"><span class="header-section-number">7.4.2</span> Diversity of Alters Within Ego Networks</a></li>
  </ul></li>
  <li><a href="#predicting-individual-outcomes-using-ego-network-measures" id="toc-predicting-individual-outcomes-using-ego-network-measures" class="nav-link" data-scroll-target="#predicting-individual-outcomes-using-ego-network-measures"><span class="header-section-number">7.5</span> Predicting Individual Outcomes Using Ego Network Measures</a>
  <ul>
  <li><a href="#predicting-self-reported-health" id="toc-predicting-self-reported-health" class="nav-link" data-scroll-target="#predicting-self-reported-health"><span class="header-section-number">7.5.1</span> Predicting Self-Reported Health</a>
  <ul>
  <li><a href="#outcome-variable" id="toc-outcome-variable" class="nav-link" data-scroll-target="#outcome-variable"><span class="header-section-number">7.5.1.1</span> Outcome Variable</a></li>
  <li><a href="#predictors" id="toc-predictors" class="nav-link" data-scroll-target="#predictors"><span class="header-section-number">7.5.1.2</span> Predictors</a></li>
  <li><a href="#preparing-the-analysis-data" id="toc-preparing-the-analysis-data" class="nav-link" data-scroll-target="#preparing-the-analysis-data"><span class="header-section-number">7.5.1.3</span> Preparing the Analysis Data</a></li>
  <li><a href="#estimating-the-model" id="toc-estimating-the-model" class="nav-link" data-scroll-target="#estimating-the-model"><span class="header-section-number">7.5.1.4</span> Estimating the Model</a></li>
  <li><a href="#interpretation-of-model-output" id="toc-interpretation-of-model-output" class="nav-link" data-scroll-target="#interpretation-of-model-output"><span class="header-section-number">7.5.1.5</span> Interpretation of Model Output</a></li>
  <li><a href="#predicted-probabilities" id="toc-predicted-probabilities" class="nav-link" data-scroll-target="#predicted-probabilities"><span class="header-section-number">7.5.1.6</span> Predicted Probabilities</a></li>
  </ul></li>
  <li><a href="#predicting-smoking-behavior" id="toc-predicting-smoking-behavior" class="nav-link" data-scroll-target="#predicting-smoking-behavior"><span class="header-section-number">7.5.2</span> Predicting Smoking Behavior</a>
  <ul>
  <li><a href="#outcome-variable-1" id="toc-outcome-variable-1" class="nav-link" data-scroll-target="#outcome-variable-1"><span class="header-section-number">7.5.2.1</span> Outcome Variable</a></li>
  <li><a href="#predictors-1" id="toc-predictors-1" class="nav-link" data-scroll-target="#predictors-1"><span class="header-section-number">7.5.2.2</span> Predictors</a></li>
  <li><a href="#estimating-the-model-1" id="toc-estimating-the-model-1" class="nav-link" data-scroll-target="#estimating-the-model-1"><span class="header-section-number">7.5.2.3</span> Estimating the Model</a></li>
  <li><a href="#interpretation-of-model-output-1" id="toc-interpretation-of-model-output-1" class="nav-link" data-scroll-target="#interpretation-of-model-output-1"><span class="header-section-number">7.5.2.4</span> Interpretation of Model Output</a></li>
  <li><a href="#predicted-probabilities-1" id="toc-predicted-probabilities-1" class="nav-link" data-scroll-target="#predicted-probabilities-1"><span class="header-section-number">7.5.2.5</span> Predicted Probabilities</a></li>
  </ul></li>
  <li><a href="#predicting-drinking-frequency" id="toc-predicting-drinking-frequency" class="nav-link" data-scroll-target="#predicting-drinking-frequency"><span class="header-section-number">7.5.3</span> Predicting Drinking Frequency</a>
  <ul>
  <li><a href="#outcome-variable-2" id="toc-outcome-variable-2" class="nav-link" data-scroll-target="#outcome-variable-2"><span class="header-section-number">7.5.3.1</span> Outcome Variable</a></li>
  <li><a href="#predictors-2" id="toc-predictors-2" class="nav-link" data-scroll-target="#predictors-2"><span class="header-section-number">7.5.3.2</span> Predictors</a></li>
  <li><a href="#estimating-the-model-2" id="toc-estimating-the-model-2" class="nav-link" data-scroll-target="#estimating-the-model-2"><span class="header-section-number">7.5.3.3</span> Estimating the Model</a></li>
  <li><a href="#interpretation-of-model-output-2" id="toc-interpretation-of-model-output-2" class="nav-link" data-scroll-target="#interpretation-of-model-output-2"><span class="header-section-number">7.5.3.4</span> Interpretation of Model Output</a></li>
  </ul></li>
  <li><a href="#interpretation-of-model-output-3" id="toc-interpretation-of-model-output-3" class="nav-link" data-scroll-target="#interpretation-of-model-output-3"><span class="header-section-number">7.5.4</span> Interpretation of Model Output</a>
  <ul>
  <li><a href="#predicted-counts" id="toc-predicted-counts" class="nav-link" data-scroll-target="#predicted-counts"><span class="header-section-number">7.5.4.1</span> Predicted Counts</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/schochastics/R4SNA/edit/main/descriptive/ego-networks.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/schochastics/R4SNA/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../descriptive/introduction.html">Descriptive Network Analysis</a></li><li class="breadcrumb-item"><a href="../descriptive/ego-networks.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ego Networks</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-ego" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ego Networks</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Ego networks refer to the personal network surrounding a single focal individual, known as the <strong>ego</strong>. An ego network includes the ego, the people directly connected to them, so called <strong>alters</strong>, and the relationships among those alters.</p>
<p>Rather than examining an entire community or organization, ego network analysis focuses on the immediate social environment of one person, allowing researchers to understand how information, resources, influence, or support flow through that individual’s connections.</p>
<p>By analyzing the size of the network, the strength of ties, the diversity of contacts, and the level of interconnectedness among alters, scholars can assess factors such as social capital, access to opportunities, and resilience. Ego networks are especially useful in studying phenomena like job searching, knowledge sharing, health behaviors, and online social interaction, where an individual’s direct relationships play a critical role in shaping outcomes.</p>
<p>In this chapter, we will begin by introducing the fundamentals of ego network data and learning how to use the <code>egor</code> package to manipulate, construct, and visualize ego networks. We will then examine substantive research questions related to homophily; the tendency for similar individuals to associate with one another more frequently than with dissimilar others, across various demographic dimensions. Finally, we will explore an applied example in which properties of ego networks are used to predict important outcomes of interest.</p>
<section id="packages-needed-for-this-chapter" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="packages-needed-for-this-chapter"><span class="header-section-number">7.1</span> Packages Needed for this Chapter</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(egor)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(networkdata)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>egor</code> package works with ego network data in <em>tidy</em> format, meaning it follows tidy data principles. In tidy data, each row represents one observation and each column represents one variable. Instead of storing everything in a single large matrix, ego network data are separated into three linked tables: one containing information about egos, one containing information about alters, and one containing the ties among alters. These tables are connected through ID variables that indicate which alters belong to which ego and which alters are tied to one another. This structure makes the data easier to understand, manipulate, and analyze using tools from the tidyverse, while still preserving the relational nature of network data.</p>
</div>
</div>
</section>
<section id="ego-network-data-structure" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="ego-network-data-structure"><span class="header-section-number">7.2</span> Ego Network Data Structure</h2>
<p>Ego network data are typically generated through survey-based approaches that capture information about individuals and their immediate social surroundings. In one common design, respondents (<strong>egos</strong>) are asked to name the people with whom they have specific types of relationships and to describe the connections among those named individuals (<strong>alters</strong>), thereby providing both node-level and tie-level information from a single informant. A more elaborate strategy uses a two-stage snowball approach: after the initial respondent identifies their contacts, those contacts are subsequently surveyed about their relationships with one another, allowing for more detailed mapping of ties within the ego’s local network. Although data collected in these ways do not reveal how these personal networks are embedded within the broader population structure, they enable researchers to estimate the distribution and characteristics of ego network forms across even very large populations.</p>
<p>An important methodological implication of this design is that survey-based ego network data typically produce independent observations: each ego network is centered on a different respondent and represents a separate local structure. As a result, ego networks can often be treated as independent units of analysis, which allows researchers to apply standard statistical models (such as regression models) to explain variation in network characteristics (e.g., density, composition, or diversity) across egos.</p>
<p>Methodologically, such data consist of multiple distinct networks, each centered on a different ego and typically composed of different actors. This means that each ego network should be stored and analyzed as a separate actor-by-actor matrix rather than combined into a single stacked dataset, since the matrices do not represent multiple relations among the same set of individuals.</p>
<p>A second common source of ego network data involves deriving them from complete network datasets that already contain information about all actors and ties within a bounded population. In this case, researchers can extract the local network surrounding a focal actor directly from the larger structure. Simple extraction procedures allow analysts to isolate an ego and their direct ties, though these methods may omit information about relationships among the alters themselves. More comprehensive approaches rely on identifying a defined neighborhood—such as through a previously constructed attribute or partition that marks members of a particular ego’s local environment—and then generating a subgraph that preserves both ego–alter and alter–alter ties. Unlike survey-generated ego networks, these extracted ego networks remain embedded within a known global structure, enabling comparisons between local and whole-network properties.</p>
<section id="constructing-an-ego-network-with-egor" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="constructing-an-ego-network-with-egor"><span class="header-section-number">7.2.1</span> Constructing an Ego Network with <code>egor</code></h3>
<p>An <code>egor</code> object stores the multiple data levels required for ego-centered network analysis. These levels include <strong>ego-level data</strong> (attributes of respondents), <strong>alter-level data</strong> (attributes of the individuals named by the respondent), and <strong>alter–alter ties</strong> (relationships among those alters).</p>
<p>In this chapter, we draw on ego network data from the <strong>UC Berkeley Social Networks Study (UCNets)</strong> <span class="citation" data-cites="fischer2020uc">(<a href="#ref-fischer2020uc" role="doc-biblioref">Fischer 2020</a>)</span>, a longitudinal study of personal networks in the San Francisco Bay Area conducted between 2015 and 2018. Specifically, we use data from the <em>first wave</em> and select only a subset of variables relevant for the examples presented here. Several of these variables are also recoded to create analytically useful ego-, alter-, and alter–alter-level measures. The full code used to construct the dataset is provided in the <a href="../appendix/ucnets-egor.html" class="quarto-xref"><span>Appendix A</span></a>. This code already processes the raw survey files and combines them into an <code>egor</code> object, the data structure used by the <code>egor</code> package for ego-centered network analysis. An <code>egor</code> object contains three linked levels of data: ego-level attributes (characteristics of the respondents), alter-level attributes (characteristics of the individuals named in each respondent’s personal network), and alter–alter ties (relationships among those alters within each ego network). Because the UCNets data are restricted-access, readers must register and obtain access themselves in order to reproduce the dataset from the original files. Further information about the study is available at the <a href="https://ucnets.berkeley.edu/">UCNets project website</a>.</p>
<p>We begin by exploring each of the three components of the <code>egor</code> object (ego attributes, alter attributes, and alter–alter ties), in order to understand how the ego network data are structured before proceeding to the analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ego_net_w1<span class="sc">$</span>ego) <span class="co"># ego level</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 19
  .egoID gender year_birth   age married  pets home_owner informal_groups health
  &lt;chr&gt;   &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;           &lt;dbl&gt; &lt;ord&gt; 
1 30000…      1       1961  53.8       0     0          0               1 fair  
2 30000…      0       1964  51.3       0     0          0               1 good  
3 30000…      1       1951  63.7       0     1          0               0 good  
4 30000…      1       1959  55.9       1     1          1               1 very_…
5 30000…      1       1952  63.1       1     0          1               0 excel…
6 30000…      1       1949  66.3       0     0          0               0 fair  
# ℹ 10 more variables: lose_weight_advice &lt;dbl&gt;, smoker &lt;dbl&gt;,
#   drinking_days &lt;dbl&gt;, marijuana_use &lt;dbl&gt;, extraversion &lt;dbl&gt;,
#   education &lt;ord&gt;, race &lt;fct&gt;, birth_continent &lt;fct&gt;, religion &lt;fct&gt;,
#   income &lt;ord&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ego_net_w1<span class="sc">$</span>alter) <span class="co"># alter level</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  .altID .egoID        gender family same_race same_age
  &lt;chr&gt;  &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 1      3000000000036      1      1         1        1
2 2      3000000000036      0      0         1        1
3 3      3000000000036      1      0         1       NA
4 4      3000000000036      1      0         1       NA
5 5      3000000000036      0      0         1        1
6 6      3000000000036      1      0         1       NA</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ego_net_w1<span class="sc">$</span>aatie) <span class="co"># alter-alter ties</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  .egoID        .srcID .tgtID weight
  &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;   &lt;dbl&gt;
1 3000000000036 2      5           1
2 3000000000036 2      5           1
3 3000000000156 2      3           1
4 3000000000156 3      5           1
5 3000000000156 2      3           1
6 3000000000156 2      5           1</code></pre>
</div>
</div>
<p>Each of the three tables is linked through identifier variables that ensure the different levels of information correspond to the correct ego networks. The variable <code>.egoID</code> appears in all three tables and serves as the key that connects respondent-level attributes in the <strong>ego table</strong> to the individuals they named in their personal networks in the <strong>alter table</strong>, and to the relationships among those alters recorded in the <strong>alter–alter tie table</strong>.</p>
<p>In the alter-level table, each network member receives an identifier <code>.altID</code>, which uniquely identifies alters within a given ego network. Additional variables describe characteristics of the alter, including gender, whether the alter is a family member (<code>family</code>), whether the alter shares the same race as the ego (<code>same_race</code>), and whether the alter is approximately the same age as the ego (<code>same_age</code>).</p>
<p>The alter–alter tie table records the relationships among alters within each ego network. These ties are based on survey questions asking respondents how well pairs of alters know each other (e.g., “How well does name 1 know name 2?”), with response options such as <em>very well</em>, <em>know a little</em>, or <em>do not know/something else</em>. For the purposes of constructing the network, responses indicating that alters know each other “very well” or “a little” were coded as a tie. The pairwise variables were reshaped into long format, and the identifiers <code>.srcID</code> and <code>.tgtID</code> indicate which two alters are connected. Because only positive ties were retained, the resulting <code>weight</code> variable is constant and equal to 1 for all alter–alter ties in the final dataset.</p>
<p>Before proceeding with the analysis, we remove respondents for whom the variable <code>numgiven</code> is missing in the ego-level data. This variable records how many alters each respondent named and is required for several of the descriptive measures used later in the chapter. Because <code>numgiven</code> records how many alters a respondent named, a missing value at the ego level implies that no alter information is recorded for that respondent. Consequently, it is sufficient to remove missing values only from the ego table, since the alter and alter–alter tie tables contain entries only for egos who actually reported network members.</p>
<p>Examining the dimensions of the three components after removing missing values (<code>dim(ego_net_w1$ego)</code>, <code>dim(ego_net_w1$alter)</code>, and <code>dim(ego_net_w1$aatie)</code>) provides a quick overview of the dataset. The ego table now contains 1159 respondents. Across these respondents, a total of 12209 alters were named, each linked to a specific ego via <code>.egoID</code> and uniquely identified within each ego network by <code>.altID</code>. The alter–alter tie table contains 6696 rows, with each row representing a relationship between two alters within the same ego network. These ties are identified by the <code>.egoID</code> of the corresponding ego and the <code>.srcID</code> and <code>.tgtID</code> variables that indicate the two alters involved.</p>
</section>
</section>
<section id="plotting-ego-nets" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="plotting-ego-nets"><span class="header-section-number">7.3</span> Plotting Ego Nets</h2>
<p>We now plot the networks using <code>igraph</code>. The first step is to convert the <code>egor</code> object into a list of <code>igraph</code> objects using <code>as_igraph()</code> from the <code>egor</code> package. Below, we create the list and inspect the first three ego networks.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert egor object to a list of igraph ego networks</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">as.igraph</span>(ego_net_w1)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect the first three ego networks</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>g[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
IGRAPH b508638 DNW- 6 2 -- 
+ attr: .egoID (g/c), name (v/c), .egoID (v/c), gender (v/n), family
| (v/n), same_race (v/n), same_age (v/n), .egoID (e/c), weight (e/n)
+ edges from b508638 (vertex names):
[1] 2-&gt;5 2-&gt;5

[[2]]
IGRAPH df1009c DNW- 15 8 -- 
+ attr: .egoID (g/c), name (v/c), .egoID (v/c), gender (v/n), family
| (v/n), same_race (v/n), same_age (v/n), .egoID (e/c), weight (e/n)
+ edges from df1009c (vertex names):
[1] 2-&gt;3 3-&gt;5 2-&gt;3 2-&gt;5 1-&gt;4 2-&gt;5 3-&gt;5 1-&gt;4

[[3]]
IGRAPH 16f3028 DNW- 5 6 -- 
+ attr: .egoID (g/c), name (v/c), .egoID (v/c), gender (v/n), family
| (v/n), same_race (v/n), same_age (v/n), .egoID (e/c), weight (e/n)
+ edges from 16f3028 (vertex names):
[1] 1-&gt;2 1-&gt;3 1-&gt;2 2-&gt;3 1-&gt;3 2-&gt;3</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If we instead wanted to work within the <code>statnet</code> framework, we could use <code>as_network()</code> to convert the data into objects of class <code>network</code>.</p>
</div>
</div>
<p>After running <code>as_igraph()</code>, we obtain a list of ego networks in igraph format, where each element of the list corresponds to one ego’s personal network. The attributes stored at the alter level are automatically transferred as vertex attributes, and the alter–alter tie information (including edge weights) is preserved as edge attributes. By default, the ego node itself is not included in these igraph representations. This is common practice because ego is, by definition, connected to all alters, and therefore contributes little additional structural variation in many visualizations or structural measures. In later sections, we will examine statistics that explicitly incorporate both ego and alter information.</p>
<p>We now visualize a subset of the data by plotting the first 9 ego networks in the list using <code>ggraph</code>. This is shown in <a href="#fig-egos" class="quarto-xref">Figure&nbsp;<span>7.1</span></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>plots <span class="ot">&lt;-</span> <span class="fu">lapply</span>(g[<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>], <span class="cf">function</span>(g) {</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># rebuild a clean graph using only structure + names</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  el <span class="ot">&lt;-</span> <span class="fu">as_edgelist</span>(g, <span class="at">names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  vn <span class="ot">&lt;-</span> <span class="fu">V</span>(g)<span class="sc">$</span>name</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(el) <span class="sc">==</span> <span class="dv">0</span> <span class="sc">||</span> <span class="fu">nrow</span>(el) <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    g_clean <span class="ot">&lt;-</span> <span class="fu">make_empty_graph</span>(<span class="at">n =</span> <span class="fu">length</span>(vn), <span class="at">directed =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">V</span>(g_clean)<span class="sc">$</span>name <span class="ot">&lt;-</span> vn</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    g_clean <span class="ot">&lt;-</span> <span class="fu">graph_from_edgelist</span>(el, <span class="at">directed =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># add back isolated vertices, if any</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    missing_v <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(vn, <span class="fu">V</span>(g_clean)<span class="sc">$</span>name)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(missing_v) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>      g_clean <span class="ot">&lt;-</span> <span class="fu">add_vertices</span>(g_clean, <span class="at">nv =</span> <span class="fu">length</span>(missing_v), <span class="at">name =</span> missing_v)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggraph</span>(g_clean, <span class="at">layout =</span> <span class="st">"kk"</span>) <span class="sc">+</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_edge_link</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_node_point</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_node_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> name), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_graph</span>()</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="fu">wrap_plots</span>(plots, <span class="at">ncol =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-egos" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-egos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ego-networks_files/figure-html/fig-egos-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-egos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: The first nine ego networks derived from the egor object based on the example dataset. Each panel represents the alter–alter structure of a single ego’s personal network, where nodes correspond to alters and edges represent ties among them. The ego node itself is not shown, as it is by definition connected to all alters. Differences across panels illustrate variation in density, clustering, and overall structural configuration across ego networks.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="descriptive-statistics-for-ego-networks" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="descriptive-statistics-for-ego-networks"><span class="header-section-number">7.4</span> Descriptive Statistics for Ego Networks</h2>
<p>One of the most commonly used structural measures in ego network analysis is <strong>density</strong>. Density captures the proportion of all possible alter–alter ties that are actually present in an ego network. In other words, it tells us how interconnected an ego’s alters are with one another. For example, if an ego has 5 alters, there are <span class="math display">\[
\frac{5 \times (5 - 1)}{2} = 10
\]</span> possible undirected ties among those alters. If all 10 ties are present, density equals 1 (a fully connected clique). If only 8 of the 10 possible ties are present, density equals 0.8.</p>
<p>Density is often of substantive interest because it reflects the level of cohesion within a personal network. Highly dense ego networks (values close to 1) indicate tightly knit groups in which most alters are connected to one another. Such cohesive structures can facilitate trust, norm enforcement, and social support, as information circulates quickly and reputational mechanisms are strong. However, according to <strong>structural hole theory</strong> <span class="citation" data-cites="burt1992structural">(<a href="#ref-burt1992structural" role="doc-biblioref">Burt 1992</a>)</span>, dense networks tend to generate redundant information because alters are connected to many of the same people and share overlapping perspectives. The key advantages of social capital derive not primarily from the attributes of one’s alters, but from the <em>structure</em> of the ego network itself. Individuals benefit when they bridge gaps, so-called structural holes, between otherwise disconnected groups. In low-density networks, ego may occupy a brokerage position linking clusters that are not directly connected to each other, thereby gaining access to diverse, non-redundant information and potential strategic advantages (such as faster promotion within organizations). Density therefore captures an important theoretical trade-off between cohesion and brokerage in ego network structure.</p>
<p>We can calculate density for each ego network using the <code>ego_density()</code> function applied to our <code>egor</code> object. Note that ego networks with 0 or 1 alters will have density equal to <code>NaN</code>, because density is undefined when no alter–alter ties are possible. There are 10 such values and they are removed from the plot below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dens <span class="ot">&lt;-</span> <span class="fu">ego_density</span>(ego_net_w1)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dens)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  .egoID        density
  &lt;chr&gt;           &lt;dbl&gt;
1 3000000000036  0.133 
2 3000000000156  0.0762
3 3000000000271  0.6   
4 3000000000317  0.171 
5 3000000000346  0.152 
6 3000000000349  0.0549</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.nan</span>(dens<span class="sc">$</span>density)) <span class="co"># number of NaN's</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dens, <span class="fu">aes</span>(<span class="at">x =</span> density)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.05</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Ego network density"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of ego networks"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of ego network densities"</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ego-networks_files/figure-html/ego-dens-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="network-composition-based-on-alter-attributes" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="network-composition-based-on-alter-attributes"><span class="header-section-number">7.4.1</span> Network Composition Based on Alter Attributes</h3>
<p>A useful way to describe ego networks is to examine the <strong>composition of alters</strong> within each network. Rather than focusing on the structure of ties among alters, compositional measures summarize <em>who is present in the ego’s personal network</em>. These measures are obtained by aggregating alter attributes within each ego network.</p>
<p>The <code>comp_ply()</code> function from the <code>egor</code> package provides a convenient way to compute such summaries. It applies a function to an alter attribute within each ego network and returns one value per ego. In our dataset, the alter-level data include several characteristics, such as <code>gender</code>, whether the alter is a <code>family</code> member, and whether the alter shares the same race as the ego (<code>same_race</code>). Using these variables, we can construct several interpretable measures of network composition.</p>
<section id="proportion-of-family-members" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="proportion-of-family-members">Proportion of Family Members</h4>
<p>A simple but informative compositional measure is the <strong>proportion of family members</strong> within an ego network. This captures the extent to which a respondent’s personal network is centered around kin relationships rather than non-kin ties such as friends, coworkers, or acquaintances. Networks with a high proportion of family members may indicate stronger reliance on kin-based support systems, whereas networks with fewer family members may reflect more diverse social connections outside the household or extended family.</p>
<p>In our alter-level data, the variable <code>family</code> indicates whether an alter is a relative (including spouse/partner, parent, child, sibling, or another relative). Using <code>comp_ply()</code>, we can compute the proportion of alters who are family members for each ego network.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>prop_family <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(ego_net_w1, <span class="st">"family"</span>, mean)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(prop_family)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  .egoID        result
  &lt;chr&gt;          &lt;dbl&gt;
1 3000000000036 0.167 
2 3000000000156 0.0667
3 3000000000271 0     
4 3000000000317 0.467 
5 3000000000346 0.533 
6 3000000000349 0.714 </code></pre>
</div>
</div>
</section>
<section id="gender-composition-of-the-network" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="gender-composition-of-the-network">Gender Composition of the Network</h4>
<p>Another compositional measure describes the gender composition of ego networks. This measure captures the share of alters who are female within each respondent’s personal network. Examining gender composition can reveal patterns of gender-based social organization and potential gender homophily, where individuals tend to form ties with others of the same gender.</p>
<p>In our alter-level data, gender is coded as <code>0 = male</code> and <code>1 = female</code>. By taking the mean of this binary variable across alters within each ego network, we obtain the proportion of female alters in each network. Values close to 0 indicate networks composed mostly of men, values close to 1 indicate networks composed mostly of women, and values around 0.5 suggest a more gender-balanced network.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>prop_female <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(ego_net_w1, <span class="st">"gender"</span>, mean)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(prop_female)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  .egoID        result
  &lt;chr&gt;          &lt;dbl&gt;
1 3000000000036  0.667
2 3000000000156  0.2  
3 3000000000271  1    
4 3000000000317  0.6  
5 3000000000346  0.467
6 3000000000349  0.5  </code></pre>
</div>
</div>
</section>
<section id="racial-homophily" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="racial-homophily">Racial Homophily</h4>
<p>A third compositional measure captures racial homophily within ego networks. Homophily refers to the tendency for individuals to form social ties with others who share similar characteristics. Here we examine whether alters share the same race as the ego.</p>
<p>The alter-level variable same_race indicates whether the respondent reported that the alter is of the same race as themselves (<code>1 = same race</code>, <code>0 = different race</code>). By averaging this binary variable across alters within each ego network, we obtain the proportion of alters who share the ego’s race. Higher values indicate more racially homogeneous networks, while lower values suggest greater racial diversity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>prop_same_race <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(ego_net_w1, <span class="st">"same_race"</span>, mean)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(prop_same_race)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  .egoID        result
  &lt;chr&gt;          &lt;dbl&gt;
1 3000000000036  1    
2 3000000000156  0.133
3 3000000000271 NA    
4 3000000000317  1    
5 3000000000346  1    
6 3000000000349 NA    </code></pre>
</div>
</div>
<p>To obtain a compact overview of these compositional measures, we combine them into a single summary table.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>prop_family <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(ego_net_w1, <span class="st">"family"</span>, mean)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>prop_female <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(ego_net_w1, <span class="st">"gender"</span>, mean)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>prop_same_race <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(ego_net_w1, <span class="st">"same_race"</span>, mean)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>comp_summary <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">egoID =</span> prop_family<span class="sc">$</span>.egoID,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_family =</span> prop_family<span class="sc">$</span>result,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_female =</span> prop_female<span class="sc">$</span>result,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_same_race =</span> prop_same_race<span class="sc">$</span>result</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(comp_summary) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(comp_summary, <span class="dv">10</span>),</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Summary of compositional measures for ego networks."</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary of compositional measures for ego networks.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">egoID</th>
<th style="text-align: right;">prop_family</th>
<th style="text-align: right;">prop_female</th>
<th style="text-align: right;">prop_same_race</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3000000000036</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">3000000000156</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3000000000271</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">3000000000317</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3000000000346</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">3000000000349</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3000000000490</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">3000000000552</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3000000000560</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">3000000000601</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Several entries may appear as <code>NA</code>. These occur when the compositional measure cannot be computed because the relevant alter attribute is missing or undefined for all alters in that ego network, or when a network contains too few alters to compute a meaningful proportion.</p>
</section>
</section>
<section id="diversity-of-alters-within-ego-networks" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="diversity-of-alters-within-ego-networks"><span class="header-section-number">7.4.2</span> Diversity of Alters Within Ego Networks</h3>
<p>While the previous measures summarize the presence of specific alter characteristics, another perspective focuses on the overall diversity of alters within an ego network. Instead of examining whether alters resemble the ego, diversity measures capture how heterogeneous the set of alters is with respect to a given attribute.</p>
<p>One commonly used diversity measure is Shannon entropy, defined as</p>
<p><span class="math display">\[
H = - \sum_i p_i \log(p_i)
\]</span></p>
<p>where (<span class="math inline">\(p_i\)</span>) represents the proportion of alters belonging to category (<span class="math inline">\(i\)</span>). Entropy increases when alters are more evenly distributed across categories and decreases when most alters belong to the same category. Networks with entropy close to zero therefore contain alters who are largely similar to one another, while higher values indicate more heterogeneous networks.</p>
<p>In the <code>egor</code> package, entropy-based diversity measures can be computed directly using the function <code>alts_diversity_entropy()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>gender_entropy <span class="ot">&lt;-</span> <span class="fu">alts_diversity_entropy</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  ego_net_w1,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">alt.attr =</span> <span class="st">"gender"</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">base =</span> <span class="fu">exp</span>(<span class="dv">1</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gender_entropy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  .egoID        entropy
  &lt;chr&gt;           &lt;dbl&gt;
1 3000000000036   0.637
2 3000000000156   0.500
3 3000000000271   0    
4 3000000000317   0.673
5 3000000000346   0.691
6 3000000000349   0.693</code></pre>
</div>
</div>
<p>This measure captures the gender diversity of each ego network. Networks in which alters are evenly split between men and women have higher entropy values, whereas networks composed mostly of alters of the same gender have lower values.</p>
<p>We can combine the diversity measure with the compositional measures above and visualize their distributions to better understand how ego networks vary across respondents.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add entropy to summary table</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>comp_summary<span class="sc">$</span>gender_entropy <span class="ot">&lt;-</span> gender_entropy<span class="sc">$</span>entropy</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># reshape for plotting</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>comp_long <span class="ot">&lt;-</span> comp_summary <span class="sc">|&gt;</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">-</span>egoID,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"measure"</span>,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"value"</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(comp_long, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> measure, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Value"</span>,</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frequency"</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ego-networks_files/figure-html/plot-comp-summary-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distributions reveal several interesting patterns in the composition of ego networks. The proportion of family members varies widely across respondents, indicating substantial heterogeneity in the extent to which personal networks are centered around kin. The gender composition measure is broadly distributed around intermediate values, suggesting that many respondents’ networks contain a mixture of male and female alters rather than being strongly gender-segregated. The gender diversity measure is concentrated toward higher values, indicating that many ego networks contain a relatively balanced mix of male and female alters. Finally, the distribution of racial homophily is highly skewed toward 1, suggesting that most respondents name alters who share their racial background.</p>
<p>These patterns are consistent with well-known findings on homophily in social networks, that is, the tendency for individuals to form ties with others who are similar to themselves <span class="citation" data-cites="mcpherson2001birds">(<a href="#ref-mcpherson2001birds" role="doc-biblioref">McPherson et al. 2001</a>)</span>. In particular, the concentration of prop_same_race near one indicates strong racial homophily in personal networks. At the same time, the distributions of prop_female and gender_entropy suggest that many networks remain gender-mixed rather than fully gender-segregated. Together, these measures show that ego networks are shaped by both similarity and diversity in the social contexts from which alters are drawn.</p>
</section>
</section>
<section id="predicting-individual-outcomes-using-ego-network-measures" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="predicting-individual-outcomes-using-ego-network-measures"><span class="header-section-number">7.5</span> Predicting Individual Outcomes Using Ego Network Measures</h2>
<p>In the previous sections we examined the structure and composition of ego networks, focusing on characteristics such as family ties, gender composition, and racial homophily. These measures describe how individuals’ personal networks are organized. However, ego network properties can also be used as explanatory variables in statistical models.</p>
<p>As discussed in the introduction, ego network data are typically collected through surveys in which each respondent reports information about their personal contacts. Because each ego corresponds to a distinct survey respondent, the resulting observations can reasonably be treated as independent. This differs from whole-network data, where observations are inherently interdependent. The survey-based structure of ego network data therefore allows us to apply familiar statistical tools such as regression models to examine how network characteristics relate to individual outcomes.</p>
<section id="predicting-self-reported-health" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="predicting-self-reported-health"><span class="header-section-number">7.5.1</span> Predicting Self-Reported Health</h3>
<p>Here we illustrate this approach by examining whether features of respondents’ ego networks are associated with their <strong>self-reported health</strong>. Substantively, this is a plausible question: individuals embedded in larger, more diverse, or more supportive personal networks may report better health. At the same time, kin-centered or highly homogeneous networks may provide different forms of support and constraint, so the direction of association is not obvious a priori.</p>
<section id="outcome-variable" class="level4" data-number="7.5.1.1">
<h4 data-number="7.5.1.1" class="anchored" data-anchor-id="outcome-variable"><span class="header-section-number">7.5.1.1</span> Outcome Variable</h4>
<blockquote class="blockquote">
<p><em>Are respondents with larger, more diverse, or more kin-centered personal networks more likely to report better health?</em></p>
</blockquote>
<p>So we are basically checking whether individuals embedded in larger, more diverse, or more supportive personal networks may report better health.</p>
<p>Our outcome is the ego-level variable <code>health</code>, which records respondents’ self-rated health. In the data preparation step, this variable was retained as an ordered factor with the categories:</p>
<ul>
<li><code>excellent</code></li>
<li><code>very_good</code></li>
<li><code>good</code></li>
<li><code>fair</code></li>
<li><code>poor</code></li>
</ul>
<p>Because these categories are ordered but not measured on an interval scale, an ordinal regression model is an appropriate choice.</p>
</section>
<section id="predictors" class="level4" data-number="7.5.1.2">
<h4 data-number="7.5.1.2" class="anchored" data-anchor-id="predictors"><span class="header-section-number">7.5.1.2</span> Predictors</h4>
<p>We include four ego-network measures as predictors:</p>
<ul>
<li><strong><code>ego_size</code></strong>: the number of alters in the ego network</li>
<li><strong><code>prop_family</code></strong>: the proportion of alters who are family members</li>
<li><strong><code>gender_entropy</code></strong>: a measure of gender diversity among alters</li>
</ul>
<p>Note that we do not use <code>prop_same_race</code> due to its high number of missing observations.</p>
<p>To account for basic respondent characteristics, we also include three ego-level controls:</p>
<ul>
<li><strong><code>age</code></strong></li>
<li><strong><code>gender</code></strong></li>
<li><strong><code>education</code></strong></li>
</ul>
<p>Together, this model combines network size, network composition, homophily, and diversity, along with standard demographic controls.</p>
</section>
<section id="preparing-the-analysis-data" class="level4" data-number="7.5.1.3">
<h4 data-number="7.5.1.3" class="anchored" data-anchor-id="preparing-the-analysis-data"><span class="header-section-number">7.5.1.3</span> Preparing the Analysis Data</h4>
<p>We first compute ego network size and combine all predictors into a single analysis dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># network size = number of alters per ego</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>net_size <span class="ot">&lt;-</span> ego_net_w1<span class="sc">$</span>alter <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(.egoID, <span class="at">name =</span> <span class="st">"ego_size"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compositional measures</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>prop_family <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(ego_net_w1, <span class="st">"family"</span>, mean)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>prop_same_race <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(ego_net_w1, <span class="st">"same_race"</span>, mean)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>gender_entropy <span class="ot">&lt;-</span> <span class="fu">alts_diversity_entropy</span>(</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  ego_net_w1,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">alt.attr =</span> <span class="st">"gender"</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">base =</span> <span class="fu">exp</span>(<span class="dv">1</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co"># rename columns to merge cleanly</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>prop_family_df <span class="ot">&lt;-</span> prop_family <span class="sc">|&gt;</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">prop_family =</span> result)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>prop_same_race_df <span class="ot">&lt;-</span> prop_same_race <span class="sc">|&gt;</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">prop_same_race =</span> result)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>gender_entropy_df <span class="ot">&lt;-</span> gender_entropy <span class="sc">|&gt;</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gender_entropy =</span> entropy)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a><span class="co"># combine into one analysis dataset</span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>analysis_dat <span class="ot">&lt;-</span> egos <span class="sc">|&gt;</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(net_size, <span class="at">by =</span> <span class="st">".egoID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(prop_family_df, <span class="at">by =</span> <span class="st">".egoID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(prop_same_race_df, <span class="at">by =</span> <span class="st">".egoID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(gender_entropy_df, <span class="at">by =</span> <span class="st">".egoID"</span>)</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(analysis_dat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         .egoID gender year_birth      age married pets home_owner
1 3000000000036      1       1961 53.83333       0    0          0
2 3000000000156      0       1964 51.33333       0    0          0
3 3000000000271      1       1951 63.66667       0    1          0
4 3000000000317      1       1959 55.91667       1    1          1
5 3000000000346      1       1952 63.08333       1    0          1
6 3000000000349      1       1949 66.33333       0    0          0
  informal_groups    health lose_weight_advice smoker drinking_days
1               1      fair                  0      1             9
2               1      good                  0      1             9
3               0      good                  0      0             6
4               1 very_good                  0      0             8
5               0 excellent                  0      0             1
6               0      fair                  0      0             1
  marijuana_use extraversion           education             race
1             0          4.0        some_college            white
2             1          2.0        some_college pacific_islander
3             0          4.0        some_college            white
4             0          2.0              master            white
5             0          1.0 professional_degree            white
6             0          3.5 professional_degree            asian
  birth_continent    religion    income ego_size prop_family prop_same_race
1   north_america  protestant   35k_45k        6  0.16666667      1.0000000
2   north_america no_religion under_15k       15  0.06666667      0.1333333
3   north_america no_religion   25k_35k        5  0.00000000             NA
4   north_america no_religion under_15k       15  0.46666667      1.0000000
5   north_america    catholic under_15k       15  0.53333333      1.0000000
6   north_america    buddhist   60k_75k       14  0.71428571             NA
  gender_entropy
1      0.6365142
2      0.5004024
3      0.0000000
4      0.6730117
5      0.6909233
6      0.6931472</code></pre>
</div>
</div>
<p>Before estimating the model, it is useful to reorder the health outcome so that higher categories correspond to better health. This makes the interpretation of coefficients more intuitive.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>analysis_dat<span class="sc">$</span>health_ord <span class="ot">&lt;-</span> <span class="fu">ordered</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  analysis_dat<span class="sc">$</span>health,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"poor"</span>, <span class="st">"fair"</span>, <span class="st">"good"</span>, <span class="st">"very_good"</span>, <span class="st">"excellent"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(analysis_dat<span class="sc">$</span>health_ord, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     poor      fair      good very_good excellent      &lt;NA&gt; 
       29       137       287       448       256         2 </code></pre>
</div>
</div>
</section>
<section id="estimating-the-model" class="level4" data-number="7.5.1.4">
<h4 data-number="7.5.1.4" class="anchored" data-anchor-id="estimating-the-model"><span class="header-section-number">7.5.1.4</span> Estimating the Model</h4>
<p>We now estimate an ordinal logistic regression model using the <code>polr()</code> function from the MASS package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># treat education as categorical</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>analysis_dat<span class="sc">$</span>education <span class="ot">&lt;-</span> <span class="fu">factor</span>(analysis_dat<span class="sc">$</span>education)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>health_model <span class="ot">&lt;-</span> <span class="fu">polr</span>(</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  health_ord <span class="sc">~</span> ego_size <span class="sc">+</span> prop_family <span class="sc">+</span> gender_entropy <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    age <span class="sc">+</span> gender <span class="sc">+</span> education,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> analysis_dat,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Hess =</span> <span class="cn">TRUE</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> na.omit</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(health_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = health_ord ~ ego_size + prop_family + gender_entropy + 
    age + gender + education, data = analysis_dat, na.action = na.omit, 
    Hess = TRUE)

Coefficients:
                   Value Std. Error t value
ego_size        0.036763   0.013619  2.6993
prop_family    -0.141296   0.259089 -0.5454
gender_entropy -0.156403   0.369930 -0.4228
age            -0.004227   0.003141 -1.3457
gender         -0.066838   0.116978 -0.5714
education.L     1.099295   0.417016  2.6361
education.Q     0.277373   0.392132  0.7073
education.C    -0.642736   0.401649 -1.6002
education^4    -0.399798   0.319163 -1.2526
education^5    -0.194744   0.256395 -0.7595
education^6    -0.209106   0.334843 -0.6245
education^7     0.327806   0.298822  1.0970
education^8    -0.619628   0.206942 -2.9942

Intercepts:
                    Value   Std. Error t value
poor|fair           -3.5890  0.3666    -9.7888
fair|good           -1.6261  0.3222    -5.0475
good|very_good      -0.2238  0.3180    -0.7037
very_good|excellent  1.5334  0.3215     4.7698

Residual Deviance: 3124.629 
AIC: 3158.629 
(14 observations deleted due to missingness)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Because the education variable was originally stored as an ordered factor, R expanded it into polynomial contrasts when estimating the model. These contrasts can sometimes introduce linear dependencies in the design matrix, especially in the presence of missing data. To simplify interpretation and avoid this issue, we treat education as a categorical factor in the regression model.</p>
</div>
</div>
</section>
<section id="interpretation-of-model-output" class="level4" data-number="7.5.1.5">
<h4 data-number="7.5.1.5" class="anchored" data-anchor-id="interpretation-of-model-output"><span class="header-section-number">7.5.1.5</span> Interpretation of Model Output</h4>
<p>The ordinal logistic regression results suggest that ego network size is positively associated with better self-reported health. The coefficient for ego_size is positive (<span class="math inline">\(0.037\)</span>) and its corresponding test statistic (<span class="math inline">\(t = 2.70\)</span>) indicates that the effect is statistically significant at conventional levels. In ordinal logistic regression estimated with <code>polr()</code>, statistical significance can be assessed by examining the ratio of the coefficient to its standard error (the <span class="math inline">\(t\)</span> value). As a rule of thumb, absolute values larger than about 1.96 correspond to significance at the 5% level under the normal approximation. Applying this criterion, the effect of network size is statistically significant, suggesting that respondents with larger personal networks are more likely to report better health categories.</p>
<p>In contrast, the compositional characteristics of the network do not show strong associations with health in this model. The proportion of family members in the network (<code>prop_family</code>) and the gender diversity of alters (<code>gender_entropy</code>) both have coefficients with <span class="math inline">\(t\)</span> values well below this threshold, indicating that their effects are not statistically distinguishable from zero in this sample. This suggests that, in this example, the size of the personal network appears to matter more for self-reported health than the specific composition of the network.</p>
<p>Among the control variables, <code>education</code> shows a statistically significant association with health, as indicated by the large <span class="math inline">\(t\)</span> value for the linear education contrast. This pattern is consistent with a large body of research linking higher educational attainment to better health outcomes. Age and gender, by contrast, do not show statistically significant associations in this model.</p>
<p>Overall, the results illustrate how ego network measures can be incorporated into standard regression frameworks. In this example, network size emerges as the most important network characteristic associated with health, whereas compositional aspects of the network appear less strongly related to the outcome once demographic characteristics are taken into account.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In an ordinal logistic regression, the values listed under <em>“Intercepts”</em> are <em>threshold parameters</em>, not traditional regression intercepts. They define the boundaries between adjacent categories of the ordered outcome (e.g., <code>poor|fair</code>, <code>fair|good</code>). The model assumes an underlying continuous health propensity, and these thresholds determine where respondents transition between the observed health categories. Because they simply partition this latent scale, the thresholds are typically <em>not interpreted substantively</em>; the main quantities of interest are the coefficients of the predictors, which indicate how variables such as ego network size shift respondents along the latent health scale.</p>
</div>
</div>
</section>
<section id="predicted-probabilities" class="level4" data-number="7.5.1.6">
<h4 data-number="7.5.1.6" class="anchored" data-anchor-id="predicted-probabilities"><span class="header-section-number">7.5.1.6</span> Predicted Probabilities</h4>
<p>Although the coefficients from an ordinal logistic regression indicate how predictors shift respondents along the underlying latent scale of the outcome, they can be difficult to interpret substantively. A more intuitive way to understand the model is to examine predicted probabilities for each category of the outcome variable.</p>
<p>Predicted probabilities translate the regression results into the probability that a respondent falls into each health category (e.g., <em>poor</em>, <em>fair</em>, <em>good</em>, <em>very good</em>, or <em>excellent</em>) given specific values of the predictors. These probabilities make it easier to see how changes in ego network characteristics are associated with differences in expected health outcomes.</p>
<p>For example, we can examine how the predicted probability of reporting different health levels changes as ego network size increases, while holding the other variables constant.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted probabilities for each observation</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>pred_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(health_model, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pred_probs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        poor       fair      good very_good excellent
1 0.03121252 0.15537749 0.2959123 0.3613524 0.1561453
2 0.02025457 0.10805282 0.2460178 0.4018487 0.2238261
3 0.02988656 0.15000244 0.2914431 0.3665312 0.1621367
4 0.01573578 0.08646079 0.2141202 0.4120718 0.2716114
5 0.01022860 0.05830848 0.1616812 0.4039483 0.3658334
6 0.01103190 0.06254727 0.1704593 0.4076679 0.3482936</code></pre>
</div>
</div>
<p>Each row now contains the estimated probability that a respondent falls into each of the five health categories according to the fitted model.</p>
<p>To visualize the relationship between network size and health, we can generate predicted probabilities across a range of ego network sizes while holding the other predictors at typical values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a sequence of network sizes</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>size_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">min</span>(analysis_dat<span class="sc">$</span>ego_size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(analysis_dat<span class="sc">$</span>ego_size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">length.out =</span> <span class="dv">50</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># create prediction dataset</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>pred_dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ego_size =</span> size_seq,</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_family =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>prop_family, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender_entropy =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>gender_entropy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender =</span> <span class="dv">0</span>,</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">education =</span> <span class="fu">levels</span>(analysis_dat<span class="sc">$</span>education)[<span class="dv">1</span>]</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a><span class="co"># compute predicted probabilities</span></span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>pred_dat <span class="ot">&lt;-</span> <span class="fu">cbind</span>(</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>  pred_dat,</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(health_model, <span class="at">newdata =</span> pred_dat, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a><span class="co"># reshape for plotting</span></span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>pred_long <span class="ot">&lt;-</span> pred_dat <span class="sc">|&gt;</span></span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(poor, fair, good, very_good, excellent),</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"health_category"</span>,</span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"probability"</span></span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred_long, <span class="fu">aes</span>(<span class="at">x =</span> ego_size, <span class="at">y =</span> probability, <span class="at">color =</span> health_category)) <span class="sc">+</span></span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb35-34"><a href="#cb35-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-35"><a href="#cb35-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Ego Network Size"</span>,</span>
<span id="cb35-36"><a href="#cb35-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Probability"</span>,</span>
<span id="cb35-37"><a href="#cb35-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Health Category"</span></span>
<span id="cb35-38"><a href="#cb35-38" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb35-39"><a href="#cb35-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ego-networks_files/figure-html/predicted-probs-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure displays the predicted probabilities of reporting each health category as ego network size increases, while holding the other predictors constant at typical values. Overall, the results show a clear pattern: as the number of alters in a respondent’s personal network increases, the probability of reporting better health categories increases, while the probability of reporting poorer health categories declines.</p>
<p>In particular, the predicted probability of reporting excellent health rises steadily with ego network size, and the probability of reporting very good health also increases. At the same time, the probabilities of reporting fair or poor health decrease as networks become larger. This pattern indicates that larger ego networks are associated with a greater likelihood of reporting better health outcomes.</p>
<p>The probability of reporting good health declines slightly as network size increases. This occurs because good is a middle category on the health scale. In ordinal models, probability does not move directly from one category to a single adjacent category. Instead, probability mass is redistributed across all categories when a predictor changes. The probability of reporting good health declines slightly as network size increases. This occurs because “good” is a middle category on the health scale. As network size increases, the predicted probabilities of lower categories such as fair and poor decline, while the probabilities of higher categories such as very good and excellent increase. The reduction in the middle category therefore reflects a redistribution of probability toward the higher end of the health scale..</p>
<p>Taken together, the pattern of increasing probabilities for higher health categories and decreasing probabilities for lower categories suggests that larger ego networks are associated with better self-reported health. This interpretation is consistent with the regression results presented earlier, which indicated a positive association between ego network size and the latent health scale. Substantively, this finding aligns with the idea that individuals embedded in larger personal networks may benefit from greater social support, access to information, and other resources that can contribute to improved health and well-being.</p>
</section>
</section>
<section id="predicting-smoking-behavior" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="predicting-smoking-behavior"><span class="header-section-number">7.5.2</span> Predicting Smoking Behavior</h3>
<p>In the previous example, we examined how ego network characteristics are associated with respondents’ self-reported health. We now illustrate a second application by examining whether features of respondents’ ego networks are associated with a <strong>binary health behavior outcome: cigarette smoking</strong>.</p>
<p>Smoking behavior is a natural outcome to consider in a network context. Social networks often shape health behaviors through mechanisms such as social norms, peer influence, and access to support. Individuals embedded in larger or more diverse networks may experience different pressures or resources that affect their likelihood of smoking. For example, networks with strong family presence may discourage smoking, while more diverse networks may expose individuals to different behavioral norms.</p>
<section id="outcome-variable-1" class="level4" data-number="7.5.2.1">
<h4 data-number="7.5.2.1" class="anchored" data-anchor-id="outcome-variable-1"><span class="header-section-number">7.5.2.1</span> Outcome Variable</h4>
<blockquote class="blockquote">
<p><em>Are respondents with larger, more diverse, or more kin-centered personal networks more or less likely to smoke cigarettes?</em></p>
</blockquote>
<p>Our outcome variable is the ego-level indicator <code>smoker</code>, which records whether the respondent reports currently smoking cigarettes.</p>
<p>The variable is coded as:</p>
<ul>
<li><code>1</code> = respondent smokes</li>
<li><code>0</code> = respondent does not smoke</li>
</ul>
<p>Because this outcome is binary, we estimate a <strong>logistic regression model</strong>.</p>
</section>
<section id="predictors-1" class="level4" data-number="7.5.2.2">
<h4 data-number="7.5.2.2" class="anchored" data-anchor-id="predictors-1"><span class="header-section-number">7.5.2.2</span> Predictors</h4>
<p>We include the same ego-network measures as predictors:</p>
<ul>
<li><strong><code>ego_size</code></strong>: the number of alters in the ego network<br>
</li>
<li><strong><code>prop_family</code></strong>: the proportion of alters who are family members<br>
</li>
<li><strong><code>gender_entropy</code></strong>: a measure of gender diversity among alters</li>
</ul>
<p>As before, we exclude <code>prop_same_race</code> due to the large number of missing observations.</p>
<p>We also include the same ego-level control variables:</p>
<ul>
<li><strong><code>age</code></strong></li>
<li><strong><code>gender</code></strong></li>
<li><strong><code>education</code></strong></li>
</ul>
<p>This specification allows us to examine whether network size, network composition, and diversity are associated with smoking behavior while accounting for basic demographic characteristics.</p>
</section>
<section id="estimating-the-model-1" class="level4" data-number="7.5.2.3">
<h4 data-number="7.5.2.3" class="anchored" data-anchor-id="estimating-the-model-1"><span class="header-section-number">7.5.2.3</span> Estimating the Model</h4>
<p>We estimate a logistic regression model using the <code>glm()</code> function with a binomial link.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>smoke_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  smoker <span class="sc">~</span> ego_size <span class="sc">+</span> prop_family <span class="sc">+</span> gender_entropy <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    age <span class="sc">+</span> gender <span class="sc">+</span> education,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> analysis_dat,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> na.omit</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(smoke_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = smoker ~ ego_size + prop_family + gender_entropy + 
    age + gender + education, family = binomial, data = analysis_dat, 
    na.action = na.omit)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)    -0.834686   0.684750  -1.219   0.2229  
ego_size       -0.060849   0.035252  -1.726   0.0843 .
prop_family    -0.988552   0.608703  -1.624   0.1044  
gender_entropy  0.174328   0.809086   0.215   0.8294  
age            -0.011351   0.007343  -1.546   0.1221  
gender         -0.505703   0.269515  -1.876   0.0606 .
education.L    -2.169284   0.874946  -2.479   0.0132 *
education.Q    -0.327076   0.830557  -0.394   0.6937  
education.C     1.560839   0.781781   1.997   0.0459 *
education^4     0.034602   0.660243   0.052   0.9582  
education^5    -0.256551   0.550060  -0.466   0.6409  
education^6     0.015995   0.563957   0.028   0.9774  
education^7    -0.669260   0.471493  -1.419   0.1558  
education^8     0.520699   0.352631   1.477   0.1398  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 510.60  on 1146  degrees of freedom
Residual deviance: 462.89  on 1133  degrees of freedom
  (12 observations deleted due to missingness)
AIC: 490.89

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
</section>
<section id="interpretation-of-model-output-1" class="level4" data-number="7.5.2.4">
<h4 data-number="7.5.2.4" class="anchored" data-anchor-id="interpretation-of-model-output-1"><span class="header-section-number">7.5.2.4</span> Interpretation of Model Output</h4>
<p>The logistic regression results examine whether characteristics of respondents’ ego networks are associated with the likelihood of smoking. In logistic regression, coefficients represent the effect of predictors on the log-odds of the outcome. A positive coefficient indicates that higher values of the predictor increase the likelihood of smoking, while a negative coefficient indicates a decrease in the likelihood of smoking. Statistical significance can be assessed using the ratio of the coefficient to its standard error (the <span class="math inline">\(z\)</span>-statistic). As a rule of thumb, absolute values larger than approximately 1.96 correspond to statistical significance at the 5% level.</p>
<p>Among the network predictors, ego network size (<code>ego_size</code>) shows a negative association with smoking. The coefficient is −0.061, corresponding to an odds ratio of approximately 0.94. This suggests that each additional alter in a respondent’s ego network is associated with roughly a 6% decrease in the odds of smoking, although the effect is only marginally significant. Substantively, this pattern is consistent with the idea that individuals embedded in larger personal networks may experience stronger social norms or social support that discourage smoking.</p>
<p>The proportion of family members in the network (<code>prop_family</code>) also has a negative coefficient, indicating that more kin-centered networks may be associated with lower odds of smoking. However, the effect is not statistically significant in this model. Similarly, gender diversity in the network (<code>gender_entropy</code>) does not show a clear association with smoking behavior, suggesting that variation in the gender composition of alters is not strongly related to smoking in this sample.</p>
<p>Among the demographic controls, gender shows a marginally significant association with smoking. The negative coefficient indicates that respondents coded as female have lower odds of smoking than males. Age does not appear to have a statistically significant effect in this model.</p>
<p>Finally, the results indicate that education is associated with smoking behavior, as reflected in the statistically significant polynomial contrasts for the education variable. These contrasts capture systematic variation in smoking across levels of educational attainment. Substantively, this pattern is consistent with well-established findings that smoking prevalence tends to be lower among individuals with higher levels of education.</p>
<p>Overall, the results demonstrate how ego network measures can be incorporated into standard logistic regression models to study behavioral outcomes. In this example, there is some evidence that individuals with larger personal networks are less likely to smoke, while compositional aspects of the network appear less strongly related to smoking behavior once demographic characteristics are taken into account.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For ease of interpretation, it is often useful to transform the coefficients into odds ratios, which indicate the multiplicative change in the odds of smoking associated with a one-unit increase in the predictor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(smoke_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)       ego_size    prop_family gender_entropy            age 
     0.4340106      0.9409650      0.3721150      1.1904458      0.9887130 
        gender    education.L    education.Q    education.C    education^4 
     0.6030812      0.1142593      0.7210287      4.7628151      1.0352075 
   education^5    education^6    education^7    education^8 
     0.7737154      1.0161236      0.5120876      1.6832035 </code></pre>
</div>
</div>
<p>Odds ratios greater than 1 indicate that the predictor is associated with higher odds of smoking, while values below 1 indicate lower odds of smoking.</p>
</div>
</div>
</section>
<section id="predicted-probabilities-1" class="level4" data-number="7.5.2.5">
<h4 data-number="7.5.2.5" class="anchored" data-anchor-id="predicted-probabilities-1"><span class="header-section-number">7.5.2.5</span> Predicted Probabilities</h4>
<p>As with the ordinal model above, predicted probabilities often provide a more intuitive way to interpret logistic regression results.</p>
<p>We can examine how the probability of smoking changes as ego network size increases, while holding the other predictors constant.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>size_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">min</span>(analysis_dat<span class="sc">$</span>ego_size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(analysis_dat<span class="sc">$</span>ego_size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">length.out =</span> <span class="dv">50</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>pred_dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">ego_size =</span> size_seq,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_family =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>prop_family, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender_entropy =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>gender_entropy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender =</span> <span class="dv">0</span>,</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">education =</span> <span class="fu">levels</span>(analysis_dat<span class="sc">$</span>education)[<span class="dv">1</span>]</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>pred_dat<span class="sc">$</span>prob_smoke <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>  smoke_model,</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> pred_dat,</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"response"</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred_dat, <span class="fu">aes</span>(<span class="at">x =</span> ego_size, <span class="at">y =</span> prob_smoke)) <span class="sc">+</span></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Ego Network Size"</span>,</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Probability of Smoking"</span></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ego-networks_files/figure-html/predicted-smoking-probs-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure shows how the predicted probability of smoking changes as ego network size increases, while holding the other predictors in the model constant at typical values. The relationship is clearly negative: respondents with larger personal networks are predicted to have a lower probability of smoking.</p>
<p>For individuals with very small ego networks, the predicted probability of smoking is relatively high, at roughly 20 percent. As network size increases, this probability steadily declines. For respondents with very large ego networks, the predicted probability of smoking falls to below 5 percent.</p>
<p>This pattern suggests that individuals embedded in larger personal networks may be less likely to smoke. One possible interpretation is that larger networks provide stronger social norms, greater social support, or more opportunities for social monitoring that discourage smoking behavior.</p>
<p>Of course, whether networks influence smoking behavior also depends on the behaviors of the alters themselves. For example, if many alters smoke, peer influence could increase the likelihood that the ego smokes as well. However, the dataset used here does not contain information about the smoking behavior of alters, so we cannot directly examine such influence processes in this analysis.</p>
</section>
</section>
<section id="predicting-drinking-frequency" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="predicting-drinking-frequency"><span class="header-section-number">7.5.3</span> Predicting Drinking Frequency</h3>
<p>In addition to examining health outcomes and smoking behavior, we can also use ego network characteristics to study patterns of alcohol consumption. Drinking behavior is a natural outcome to consider in a network context because social interactions often occur in settings where alcohol is present. Individuals embedded in larger or more socially active networks may encounter more opportunities to drink, while networks centered around family members may involve different social norms around alcohol use.</p>
<p>Here we examine whether characteristics of respondents’ ego networks are associated with <strong>how frequently they drink alcohol</strong>.</p>
<section id="outcome-variable-2" class="level4" data-number="7.5.3.1">
<h4 data-number="7.5.3.1" class="anchored" data-anchor-id="outcome-variable-2"><span class="header-section-number">7.5.3.1</span> Outcome Variable</h4>
<blockquote class="blockquote">
<p><em>Are respondents with larger, more diverse, or more kin-centered personal networks more likely to drink alcohol more frequently?</em></p>
</blockquote>
<p>Our outcome variable is the ego-level variable <code>drinking_days</code>, which records how many days per week the respondent reports having an alcoholic drink.</p>
<p>In the original survey data, this variable is coded as:</p>
<ul>
<li><code>0</code> = less than once a week<br>
</li>
<li><code>1</code> = one day a week<br>
</li>
<li><code>2</code> = two days a week<br>
</li>
<li><code>3</code> = three days a week<br>
</li>
<li><code>4</code> = four days a week<br>
</li>
<li><code>5</code> = five days a week<br>
</li>
<li><code>6</code> = six days a week<br>
</li>
<li><code>7</code> = every day<br>
</li>
<li><code>8</code> = less than one drink per week<br>
</li>
<li><code>9</code> = does not drink at all</li>
</ul>
<p>For the analysis, we recode the variable so that it represents a count of drinking days per week. Respondents who report not drinking at all (<code>9</code>) are coded as <code>0</code>, and respondents reporting less than one drink per week (<code>8</code>) are also coded as <code>0</code>. The remaining values already correspond to the number of drinking days per week.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>analysis_dat<span class="sc">$</span>drinking_days_rec <span class="ot">&lt;-</span> analysis_dat<span class="sc">$</span>drinking_days</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>analysis_dat<span class="sc">$</span>drinking_days_rec[</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  analysis_dat<span class="sc">$</span>drinking_days <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">9</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(analysis_dat<span class="sc">$</span>drinking_days_rec, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1    2    3    4    5    6    7 &lt;NA&gt; 
 340  301  110  128  113   62   69   35    1 </code></pre>
</div>
</div>
<p>Because the outcome variable represents a count of events (drinking days per week), a Poisson regression model is appropriate.</p>
</section>
<section id="predictors-2" class="level4" data-number="7.5.3.2">
<h4 data-number="7.5.3.2" class="anchored" data-anchor-id="predictors-2"><span class="header-section-number">7.5.3.2</span> Predictors</h4>
<p>We include the same ego-network measures used in the previous examples:</p>
<ul>
<li><code>ego_size</code>: the number of alters in the ego network<br>
</li>
<li><code>prop_family</code>: the proportion of alters who are family members<br>
</li>
<li><code>gender_entropy</code>: a measure of gender diversity among alters</li>
</ul>
<p>As before, we exclude <code>prop_same_race</code> due to the large number of missing observations.</p>
<p>We also include three demographic control variables:</p>
<ul>
<li><code>age</code><br>
</li>
<li><code>gender</code><br>
</li>
<li><code>education</code></li>
</ul>
<p>Together, these predictors allow us to examine whether network size, network composition, and diversity are associated with alcohol consumption while accounting for basic demographic characteristics.</p>
</section>
<section id="estimating-the-model-2" class="level4" data-number="7.5.3.3">
<h4 data-number="7.5.3.3" class="anchored" data-anchor-id="estimating-the-model-2"><span class="header-section-number">7.5.3.3</span> Estimating the Model</h4>
<p>We estimate a Poisson regression model using the <code>glm()</code> function with a Poisson link.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>drink_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  drinking_days_rec <span class="sc">~</span> ego_size <span class="sc">+</span> prop_family <span class="sc">+</span> gender_entropy <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    age <span class="sc">+</span> gender <span class="sc">+</span> education,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> analysis_dat,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> poisson,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> na.omit</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(drink_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = drinking_days_rec ~ ego_size + prop_family + gender_entropy + 
    age + gender + education, family = poisson, data = analysis_dat, 
    na.action = na.omit)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     0.4810541  0.1310035   3.672 0.000241 ***
ego_size        0.0134878  0.0050336   2.680 0.007372 ** 
prop_family    -0.2819585  0.1035761  -2.722 0.006484 ** 
gender_entropy  0.0437564  0.1477433   0.296 0.767104    
age             0.0007412  0.0012170   0.609 0.542500    
gender         -0.1123705  0.0447703  -2.510 0.012075 *  
education.L     0.3736343  0.2430547   1.537 0.124234    
education.Q    -0.6962611  0.2406259  -2.894 0.003809 ** 
education.C     0.0506934  0.2237053   0.227 0.820729    
education^4    -0.4743386  0.1673270  -2.835 0.004585 ** 
education^5     0.0700040  0.1203433   0.582 0.560767    
education^6    -0.1346388  0.1432642  -0.940 0.347324    
education^7    -0.0578159  0.1264793  -0.457 0.647587    
education^8    -0.0404278  0.0866799  -0.466 0.640927    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 2553.3  on 1145  degrees of freedom
Residual deviance: 2492.2  on 1132  degrees of freedom
  (13 observations deleted due to missingness)
AIC: 4747.7

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
</section>
<section id="interpretation-of-model-output-2" class="level4" data-number="7.5.3.4">
<h4 data-number="7.5.3.4" class="anchored" data-anchor-id="interpretation-of-model-output-2"><span class="header-section-number">7.5.3.4</span> Interpretation of Model Output</h4>
</section>
</section>
<section id="interpretation-of-model-output-3" class="level3" data-number="7.5.4">
<h3 data-number="7.5.4" class="anchored" data-anchor-id="interpretation-of-model-output-3"><span class="header-section-number">7.5.4</span> Interpretation of Model Output</h3>
<p>The Poisson regression results examine whether characteristics of respondents’ ego networks are associated with the number of days per week they report drinking alcohol. In a Poisson regression model, coefficients represent the effect of predictors on the log of the expected count of the outcome. A positive coefficient indicates that higher values of the predictor are associated with more drinking days per week, while a negative coefficient indicates fewer drinking days.</p>
<p>Statistical significance can be evaluated using the ratio of the coefficient to its standard error (the <span class="math inline">\(z\)</span>-statistic). As in the previous models, absolute values larger than approximately 1.96 correspond to statistical significance at the 5% level under the normal approximation.</p>
<p>Among the network predictors, ego network size (<code>ego_size</code>) shows a positive and statistically significant association with drinking frequency. The coefficient is approximately 0.013 (<span class="math inline">\(z\)</span> = 2.68, <span class="math inline">\(p\)</span> &lt; 0.01). Because Poisson regression models the log of the expected count, it is useful to exponentiate the coefficient to interpret the effect multiplicatively. The value exp(0.013) ≈ 1.014 suggests that each additional alter in a respondent’s ego network is associated with roughly a 1.4 percent increase in the expected number of drinking days per week. Substantively, this pattern is consistent with the idea that individuals embedded in larger personal networks may have more opportunities for social activities where alcohol consumption occurs.</p>
<p>The proportion of family members in the network (<code>prop_family</code>) shows a negative and statistically significant association with drinking frequency (<span class="math inline">\(z\)</span> = −2.72, <span class="math inline">\(p\)</span> &lt; 0.01). This suggests that respondents whose networks contain a larger share of family members tend to report fewer drinking days per week. One possible interpretation is that kin-centered networks may involve different social norms or contexts that discourage frequent alcohol consumption compared to networks composed primarily of friends or acquaintances.</p>
<p>By contrast, gender diversity in the network (<code>gender_entropy</code>) does not appear to be strongly related to drinking frequency in this model. The coefficient is small and statistically insignificant, indicating that variation in the gender composition of alters is not associated with meaningful differences in drinking behavior.</p>
<p>Among the demographic controls, respondent gender shows a statistically significant association with drinking frequency (<span class="math inline">\(z\)</span> = −2.51, <span class="math inline">\(p\)</span> &lt; 0.05). The negative coefficient indicates that respondents coded as female report fewer drinking days per week than males. Age does not show a statistically significant relationship with drinking behavior in this model.</p>
<p>Finally, the education variable shows some evidence of association with drinking behavior, as reflected in several statistically significant polynomial contrasts. These contrasts indicate that drinking frequency varies systematically across levels of educational attainment, although the interpretation of individual contrast terms is less straightforward than standard regression coefficients.</p>
<p>Overall, the results illustrate how ego network measures can be incorporated into regression models for count outcomes. In this example, larger ego networks are associated with slightly more frequent drinking, while networks with a higher proportion of family members are associated with less frequent drinking. These patterns suggest that both the size and composition of personal networks may shape opportunities and social contexts for alcohol consumption.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For ease of interpretation, it is often useful to transform the coefficients into incidence rate ratios, which indicate the multiplicative change in the expected number of drinking days associated with a one-unit increase in the predictor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(drink_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)       ego_size    prop_family gender_entropy            age 
     1.6177788      1.0135791      0.7543050      1.0447279      1.0007415 
        gender    education.L    education.Q    education.C    education^4 
     0.8937130      1.4530057      0.4984455      1.0520003      0.6222965 
   education^5    education^6    education^7    education^8 
     1.0725124      0.8740316      0.9438237      0.9603785 </code></pre>
</div>
</div>
<p>Values greater than 1 indicate that the predictor is associated with more frequent drinking, while values below 1 indicate less frequent drinking.</p>
</div>
</div>
<section id="predicted-counts" class="level4" data-number="7.5.4.1">
<h4 data-number="7.5.4.1" class="anchored" data-anchor-id="predicted-counts"><span class="header-section-number">7.5.4.1</span> Predicted Counts</h4>
<p>As in the previous examples, predicted values provide a more intuitive way to interpret the model than the raw regression coefficients alone. In a Poisson regression, the fitted values correspond to the expected number of events—in this case, the expected number of drinking days per week.</p>
<p>To visualize the effects of the substantively important predictors, we generate predicted counts while varying one predictor at a time and holding the remaining variables constant at typical values. Here, we focus on the three predictors that showed the clearest associations with drinking frequency in the model: <code>ego_size</code>, <code>prop_family</code>, and <code>gender</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sequences for predictors</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>size_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(analysis_dat<span class="sc">$</span>ego_size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                <span class="fu">max</span>(analysis_dat<span class="sc">$</span>ego_size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">length.out =</span> <span class="dv">50</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>family_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">50</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction data for ego_size</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>pred_size <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ego_size =</span> size_seq,</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_family =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>prop_family, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender_entropy =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>gender_entropy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender =</span> <span class="dv">0</span>,</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">education =</span> <span class="fu">levels</span>(analysis_dat<span class="sc">$</span>education)[<span class="dv">1</span>]</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>pred_size<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(drink_model, <span class="at">newdata =</span> pred_size, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>pred_size<span class="sc">$</span>variable <span class="ot">&lt;-</span> <span class="st">"ego_size"</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>pred_size<span class="sc">$</span>x <span class="ot">&lt;-</span> pred_size<span class="sc">$</span>ego_size</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction data for prop_family</span></span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>pred_family <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">ego_size =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>ego_size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_family =</span> family_seq,</span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender_entropy =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>gender_entropy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender =</span> <span class="dv">0</span>,</span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">education =</span> <span class="fu">levels</span>(analysis_dat<span class="sc">$</span>education)[<span class="dv">1</span>]</span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a>pred_family<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(drink_model, <span class="at">newdata =</span> pred_family, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>pred_family<span class="sc">$</span>variable <span class="ot">&lt;-</span> <span class="st">"prop_family"</span></span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a>pred_family<span class="sc">$</span>x <span class="ot">&lt;-</span> pred_family<span class="sc">$</span>prop_family</span>
<span id="cb47-35"><a href="#cb47-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-36"><a href="#cb47-36" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction data for gender</span></span>
<span id="cb47-37"><a href="#cb47-37" aria-hidden="true" tabindex="-1"></a>pred_gender <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-38"><a href="#cb47-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">ego_size =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>ego_size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-39"><a href="#cb47-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_family =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>prop_family, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-40"><a href="#cb47-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender_entropy =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>gender_entropy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-41"><a href="#cb47-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">mean</span>(analysis_dat<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-42"><a href="#cb47-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">gender =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb47-43"><a href="#cb47-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">education =</span> <span class="fu">levels</span>(analysis_dat<span class="sc">$</span>education)[<span class="dv">1</span>]</span>
<span id="cb47-44"><a href="#cb47-44" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-45"><a href="#cb47-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-46"><a href="#cb47-46" aria-hidden="true" tabindex="-1"></a>pred_gender<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(drink_model, <span class="at">newdata =</span> pred_gender, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb47-47"><a href="#cb47-47" aria-hidden="true" tabindex="-1"></a>pred_gender<span class="sc">$</span>variable <span class="ot">&lt;-</span> <span class="st">"gender"</span></span>
<span id="cb47-48"><a href="#cb47-48" aria-hidden="true" tabindex="-1"></a>pred_gender<span class="sc">$</span>x <span class="ot">&lt;-</span> pred_gender<span class="sc">$</span>gender</span>
<span id="cb47-49"><a href="#cb47-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-50"><a href="#cb47-50" aria-hidden="true" tabindex="-1"></a><span class="co"># combine predictions</span></span>
<span id="cb47-51"><a href="#cb47-51" aria-hidden="true" tabindex="-1"></a>pred_all <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(pred_size, pred_family, pred_gender)</span>
<span id="cb47-52"><a href="#cb47-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-53"><a href="#cb47-53" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb47-54"><a href="#cb47-54" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred_all, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> pred)) <span class="sc">+</span></span>
<span id="cb47-55"><a href="#cb47-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb47-56"><a href="#cb47-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>variable, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb47-57"><a href="#cb47-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb47-58"><a href="#cb47-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Predictor value"</span>,</span>
<span id="cb47-59"><a href="#cb47-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Expected drinking days per week"</span></span>
<span id="cb47-60"><a href="#cb47-60" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb47-61"><a href="#cb47-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ego-networks_files/figure-html/predicted-drinking-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure summarizes how the expected number of drinking days per week changes across the three predictors. The left panel shows a clear positive relationship between <code>ego_size</code> and expected drinking frequency. Holding the other variables constant, respondents with larger ego networks are predicted to drink on more days per week. Although the absolute increase is modest, the pattern is consistent with the positive coefficient for network size in the Poisson model.</p>
<p>The middle panel shows the predicted effect of <code>gender</code>. Because <code>gender</code> is coded <code>0 = male</code> and <code>1 = female</code>, the downward slope indicates that respondents coded as female are predicted to drink less frequently than those coded as male, all else equal. This matches the negative regression coefficient for <code>gender</code>.</p>
<p>The right panel displays the predicted effect of <code>prop_family</code>. Here the relationship is negative: as the share of family members in the ego network increases, the expected number of drinking days per week declines. Substantively, this suggests that respondents embedded in more kin-centered networks tend to drink less frequently than those whose networks contain fewer family members.</p>
<p>Taken together, the predicted counts reinforce the main results of the Poisson model. Larger ego networks are associated with somewhat more frequent drinking, whereas networks with a higher proportion of family members are associated with less frequent drinking. At the same time, women are predicted to drink less frequently than men. As in the previous examples, these predictions are model-based associations rather than causal effects. In particular, whether alters themselves drink alcohol would likely matter for understanding social influence more directly, but the present dataset does not include alter-level information on drinking behavior.</p>


</section>
</section>
</section>
<section id="bibliography" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-burt1992structural" class="csl-entry" role="listitem">
Burt, Ronald. 1992. <em>Structural Holes: The Social Structure of Competition</em>. Harvard University Press.
</div>
<div id="ref-fischer2020uc" class="csl-entry" role="listitem">
Fischer, Claude S. 2020. <em>UC Berkeley Social Networks Study (UCNets), San Francisco Bay Area, 2015-2018</em>.
</div>
<div id="ref-mcpherson2001birds" class="csl-entry" role="listitem">
McPherson, Miller, Lynn Smith-Lovin, and James M Cook. 2001. <span>“Birds of a Feather: Homophily in Social Networks.”</span> <em>Annual Review of Sociology</em> 27 (1): 415–44.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/schochastics\.io\/R4SNA");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../descriptive/signed-networks.html" class="pagination-link" aria-label="Signed Networks">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Signed Networks</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../descriptive/netropy.html" class="pagination-link" aria-label="Entropy Analysis">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Entropy Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>R for Social Network Analysis was written by Termeh Shafie and David Schoch.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/schochastics/R4SNA/edit/main/descriptive/ego-networks.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/schochastics/R4SNA/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>